### ISSUE TITLE
Re-implement let

### ISSUE THREAD

**Issue by paultag** [hylang/hy#1000]
Feedback on the following:

``` hy
(defmacro let [forms &rest body]
  (setv closure-name (gensym "CLOSURE"))
  (setv closure `(do (setv ~closure-name {})))

  (defn generic-visit [visit node]
    (if (coll? node)
        (setv (cut node) (list-comp (visit x) [x node]))
        node))

  (defn name-mangle [forms]
    (setv names (list-comp (get x 0) [x forms]))
    (defn visit [node]
      (if (in node names)
          `(get ~closure-name (quote ~node))
          (generic-visit visit node))))

  `(do ~closure  ; assign {} to something like ':CLOSURE_35151
       ; Now, let's assign all the bindings to the closure we know about
       ~@(list-comp `(assoc ~closure-name (quote ~name) ~value) [(, name value) forms])
       ; And, now, let's change any names to ref the dict.
       ~@(map (name-mangle forms) body)))
```

This fucks up locals when using gdb, but it might work for trying to actually write a LoL

**Comment by paultag** [comment]
@hylang/core RFR

**Comment by kirbyfan64** [comment]
Not core...but I have a feeling this may break with `nonlocal` and `global`...

**Comment by algernon** [comment]
I will try adderall and hydiomatic with this `let`, over the holidays.

**Comment by paultag** [comment]
@kirbyfan64 why *aren't* you core?

**Comment by farhaven** [comment]
Looks nice. I'm currently playing around with the old `let` renamed to `let*` so we don't need things like `gensym` in bootstrap and this in `hy/core/macros.hy`. There is a bit of fallout in tests where some test expects the `let` to call a function, and when running the tests with Python 2, during `yield-from`, but I think those are expected and can be fixed.

I've also added

```
(setv forms (list (map list (partition forms))))
````

to the beginning of the macro so it behaves a bit more than the old `let`.

**Comment by paultag** [comment]
https://github.com/paultag/hy/tree/paultag/let-over-lol?files=1 is tracking this idea
