### ISSUE TITLE
(macroexpand) lies

### ISSUE THREAD

**Issue by paultag** [hylang/hy#1004]
```hy
=> (defmacro foo [] '(print 1))
=> (defmacro bar [] '(print (foo)))
=> (macroexpand '(bar))
('print' ('foo'))
```

**Comment by paultag** [comment]
However, when you eval it:

```hy
=> (eval (macroexpand '(bar)))
1
None
```

**Comment by kirbyfan64** [comment]
So it's that `macroexpand` isn't expanding recursively?

**Comment by paultag** [comment]
Yeah, I think so:(I posted that on IRC but forgot to paste it here)

`04:07 < paultag> (macroexpand) must not be recursive`

cc @olasd (since you said it was recursive a few days ago)

**Comment by algernon** [comment]
There's `macroexpand-all` in `hy.contrib.walk`, which is recursive, and does the right thing.

At least it does, when I copy & paste the code to a repl. If I import it, it fails, which is weird as hell.
