### ISSUE TITLE
0.11.1?

### ISSUE THREAD

**Issue by tianon** [hylang/hy#1005]
Opening this to start a discussion of whether folks think a new point release might be warranted, especially since 0.11.0 currently doesn't work against Python 3.5 latest (https://github.com/hylang/hy/pull/997 is the fix I sent for that, which is the minimum I'd suggest for a new point release, but I don't know whether there are more fixes that might warrant a new release too).

**Comment by paultag** [comment]
I dig the idea and think it's worthwhile.

**Comment by paultag** [comment]
I'll start a `0.11

**Comment by paultag** [comment]
https://github.com/hylang/hy/tree/0.11 is open for changesets
