### ISSUE TITLE
Return value not generated when a function contains `yield from`

### ISSUE THREAD

**Issue by timmartin** [hylang/hy#1010]
When a coroutine function uses `yield from`, the compiler no longer generates a return value for the final expression in the function. For example:

```hy
(defn yield-from-and-return []
  (print "whatever")
  (yield-from (some-coroutine))
  42)

(defn without-yield-from []
  (print "whatever")
  42)
```

expands to:

```python
def yield_from_and_return():
    print('whatever')
    yield from some_coroutine()
    42

def without_yield_from():
    print('whatever')
    return 42
```

**Comment by timmartin** [comment]
The proximate cause appears to be this code in `compiler.py`:

```python
        if body.expr:
            if body.contains_yield:
                body += body.expr_as_stmt()
            else:
                body += ast.Return(value=body.expr,
                                   lineno=body.expr.lineno,
                                   col_offset=body.expr.col_offset)
```

It looks like it should be enough to weaken the condition so that the `ast.Return` is always generated in Python 3 (actually, Python 3.3+ I think?)

**Comment by paultag** [comment]
Sounds right to me, that was the idea I had in my head for this!

On Thu, Dec 31, 2015 at 4:22 AM, timmartin <notifications@github.com> wrote:

> The proximate cause appears to be this code in compiler.py:
>
>         if body.expr:
>             if body.contains_yield:
>                 body += body.expr_as_stmt()
>             else:
>                 body += ast.Return(value=body.expr,
>                                    lineno=body.expr.lineno,
>                                    col_offset=body.expr.col_offset)
>
> It looks like it should be enough to weaken the condition so that the
> ast.Return is always generated in Python 3 (actually, Python 3.3+ I
> think?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/1010#issuecomment-168154637>.
>



-- 
:wq
