### ISSUE TITLE
let error

### ISSUE THREAD

**Issue by ttkk1024** [hylang/hy#1021]
> hy 0.11.1 using CPython(v2.7.11:6d1b6a68f775) 2.7.11 on Windows
=> (let [x   5]
   ...      (print   x))
  File "<input>", line 1, column 9

  (let [x 5]
          ^^
HyMacroExpansionError: let lexical context element must be a list or symbol

I find the the same error in tests/native_tests/mathematics.hy

**Comment by tuturto** [comment]
If you're using Hy installed from PyPi, correct syntax is:

```hylang
=> (let [[x 5]]
...  (print x))
5
```

Syntax of ```let``` will change in the next release. Correct version of documentation can be found at: http://docs.hylang.org/en/stable/language/api.html#let

**Comment by ttkk1024** [comment]
@tuturto thank you very much

**Comment by kirbyfan64** [comment]
I think this can be closed now!
