### ISSUE TITLE
Code manipulation does not work

### ISSUE THREAD

**Issue by leiserfg** [hylang/hy#1026]
Documentation said that is valid code:
```lisp
(defmacro rev [code]
  (let [op (last code) params (list (butlast code))]
  `(~op ~@params)))
 (rev (1 2 3 +))
```
but I run that and this is the result:
```lisp
(rev (1 2 3 +))
  ^-------------^
HyMacroExpansionError: expanding `rev': TypeError("'map' object is not callable",)
```

**Comment by leiserfg** [comment]
Mmm, it hapend with the version installed from pypi, not with the code that are on master, update the package please.

**Comment by tuturto** [comment]
Syntax of ``let`` has changed between current stable version and the development version found in master. This will work

```hylang
(defmacro rev [code]
   (let [[op (last code)]
         [params (list (butlast code))]]
   `(~op ~@params)))

(rev (1 2 3 +))
```

Documentation for stable is at: http://docs.hylang.org/en/stable/index.html and should be valid. I scanned through the documentation of current stable branch and didn't find errors in macro definitions there. However, if you spot an error there, do let us know about the error and location in docs and it'll get fixed. Or submit a PR for fix, we're more than happy to have help with the project.

**Comment by leiserfg** [comment]
Ha ha ha. I was using the latest doc with the stable version of the code, sorry :D

**Comment by tuturto** [comment]
No problem at all, you aren't the first one do that. Closing this now then, but feel free to open new issues if you encounter more unclear things or bugs.

**Comment by madanh** [comment]
Please reopen, since the example code is in tutorial here http://docs.hylang.org/en/latest/tutorial.html#basic-intro-to-lisp-for-pythonistas , which says hy 0.11.0+ and i does not work for 0.11.1 from pypi. I mean the tutorial has to be changed

**Comment by Kodiologist** [comment]
The version number 0.11.0+383.g5df8f38 means Git revision 5df8f38, not 0.11.1. But see #1198.

**Comment by madanh** [comment]
Thanks, for the expl., commented on #1198
