### ISSUE TITLE
Add link to forking guide into contributing.rst

### ISSUE THREAD

**Issue by tuturto** [hylang/hy#1028]
In file: https://help.github.com/articles/fork-a-repo/ from contributing.rst from an appropriate point at the beginning of https://github.com/hylang/hy/blob/master/CONTRIBUTING.rst

**Comment by berkerpeksag** [comment]
Fixed in https://github.com/hylang/hy/commit/a820d8ee39f484cd4680a95224f74c0d97968bbc.
