### ISSUE TITLE
Add link to git starter guide in contributing.rst

### ISSUE THREAD

**Issue by tuturto** [hylang/hy#1029]
Add link to http://rogerdudler.github.io/git-guide/ into contributing.rst (https://github.com/hylang/hy/blob/master/CONTRIBUTING.rst) to get new contributors up and running quickly.

**Comment by berkerpeksag** [comment]
Fixed in https://github.com/hylang/hy/commit/a820d8ee39f484cd4680a95224f74c0d97968bbc.
