### ISSUE TITLE
Link to a good squashing tutorial

### ISSUE THREAD

**Issue by tuturto** [hylang/hy#1032]
In contributing.rst we have “Before committing a PR, try squashing the commits”, that could link to good squashing tutorial (I remember how others had to hold my hand while I did my first few squashes as I didn't know how to do this).

**Comment by kirbyfan64** [comment]
What about http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html?

**Comment by tuturto** [comment]
Looks good to me, but I might be biased since I have been taught how to do that.

**Comment by berkerpeksag** [comment]
Thanks to https://github.com/blog/2141-squash-your-commits, we can now do the work via GitHub's UI.

**Comment by Perif** [comment]
Adding a link to the *gitready* squashing guide would make sense but since GitHub helps to do that when merging, is this issue still current ?

**Comment by gilch** [comment]
Is this necessary anymore? GitHub has "squash and merge" button now. We can squash at merge time.

**Comment by Kodiologist** [comment]
Yeah, that should suffice. I knew GUIs were good for something.
