### ISSUE TITLE
Support the new async/await coroutines

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1054]
This was attempted by @zackmdavis in #805, then aborted. As with other optional Hy features, like `nonlocal`, Hy need only support this when hosted on Python versions supporting it (3.5+), though we could perhaps emulate the behavior with `yield`-based coroutines in earlier versions. See [PEP-0492](https://www.python.org/dev/peps/pep-0492/#new-coroutine-declaration-syntax), and https://docs.python.org/3/reference/compound_stmts.html#coroutines

**Comment by zackmdavis** [comment]
Yeah, sorry for losing momentum and ghosting on #805 (this time last _year!_). The blocking issue that I perceived there was `await` not working inside of `let`. Since we already know that `let` is subtly broken in several other ways, maybe we shouldn't regard that as blocking (uh, no pun intended) the coroutines feature? With this issue serving as a reminder, it's _possible_ I'll find time to rebase and finish up [my branch](https://github.com/zackmdavis/hy/tree/async_awaits) soon, but (it _should_ be needless to say) anyone else is welcome to use my commit from the other year (or not!) and submit their own PR first.

**Comment by gilch** [comment]
We already have that problem with `yield` #663. I still think removing `let` altogether is our best option.

**Comment by tuturto** [comment]
I went through some of current code of mine to see what would happen if ```let``` were removed. Code had 330 (if I did my grep correctly) instances of ```let```. With random sampling, I didn't find any instance where ```let``` couldn't have been replaced with ```setv```, as they were mostly used in beginning of the function and never to shadow another symbol with same name. Removing ```let``` would break all those 330 places of code, but if we were to replace ```let``` with a macro that generates ```setv``` instead, it should be (mostly) smoothly sailing.

However, we have to remember that this is just a one project and out there might code that uses ```let``` differently. At the minimum, I would like to see ```let``` macro like I described before. Documentation would have to point out very explicitly what's going on with it and even then I suspect there would be cases where programmer assumed that ```let``` works the same way as in other lisps and didn't check the documentation.

But I would be totally thrilled to see ```yield```, ```await``` and co. work. Sorry for hijacking the ticket.

**Comment by gilch** [comment]
>However, we have to remember that this is just a one project and out there might code that uses let differently. At the minimum, I would like to see let macro like I described before.

We've totally broken API already. It's not just `let`. I sympathize, but we should just expect that all old code will break. `let` has very confusing behavior now if you think it should work like Lisp. Merely introducing a local should not break `await`/`break`/`continue`/`yield`. That's confusing. The macro replacement you propose would also be confusing, but for different reasons. No closures. No scoping. Why does it even have a body?

If we do put in a `let` macro that translates to `setv`, it had better be in contrib and marked as deprecated. I would rather fix old code or just use legacy Hy than have a core `let` that still makes no sense forever. If we don't have a `let` in core and we do **eventually** get it working, we can add it back in without breaking API again. If the `setv` `let` is already in core, we can't do that.

> But I would be totally thrilled to see yield, await and co. work. Sorry for hijacking the ticket.

So would I, but nobody's figured it out after a year, not that we haven't tried #1055 #1000 #844 #688 #673 #664 #663.

I have ideas on how it might be possible, but I still can't make it work. Keeping `let` as-is requires us to remove or replace the the things it breaks. I got a `break`/`continue` replacement working in #1055. Removing `await` and `yield` means giving up coroutines (I'd sooner give up `let`, wouldn't you?). Re-implementing `await` and `yield` might require some kind of functional coroutines. Maybe we could re-implement coroutines using something like Scheme's `call/cc`? Maybe someone who knows more Haskell or category theory than me could do it with a monad or something. Maybe it's enough to backport `await` to Hy on Python 2 using `yield-from`. I haven't used the new `await` coroutines enough to tell.

If we keep the things `let` breaks, then we have to remove or replace `let`. You already know what I think of that. But considering replacement possibilities, I think Emacs Lisp somehow managed to make a lexically-scoped `let` using dynamic-scope-only macros. Maybe if we had `macroexpand-all` we could do something similar. It could perhaps be done with our contrib walk module. I don't understand how they did it well enough to be sure.

**Comment by zackmdavis** [comment]
> Maybe it's enough to backport await to Hy on Python 2 using `yield-from`

Except the `yield-from` backport is [also](https://github.com/hylang/hy/issues/692) [broken](https://github.com/hylang/hy/issues/691), so we'd have to fix that first/too ...

**Comment by tuturto** [comment]
> If we do put in a let macro that translates to setv, it had better be in contrib and marked as deprecated. I would rather fix old code or just use legacy Hy than have a core let that still makes no sense forever. If we don't have a let in core and we do eventually get it working, we can add it back in without breaking API again. If the setv let is already in core, we can't do that.

That would make sense. Then the wart would be hidden away and only used by people explicitly choosing to use it. I would be more than happy with such a decision.

**Comment by rcarmo** [comment]
I'd really like to see async/await support in some fashion (and a new release, but that seems to be coming)

**Comment by rcarmo** [comment]
Well, so I'm here doing some Python 3.6, using yield from a coroutine, and wondering... How's this coming along?

**Comment by Kodiologist** [comment]
It isn't. Nobody's working on it right now.

Speaking for myself, I have no interest in this feature and hence no plans to add it. I did get rid of `let`, though.

**Comment by gilch** [comment]
@rcarmo I think we'll get around to it eventually, but (given our limited resources) it's not a hy-priority, since you can still use the old `@asyncio.coroutine` decorators. We do consider PRs if you want to try to speed things up.

**Comment by Kodiologist** [comment]
[rcarmo has left the building.](https://news.ycombinator.com/item?id=14913092)

**Comment by rcarmo** [comment]
Yeah, well, at least for the moment. I need `async` for the Python stuff that I do, and it is true that the lack of `let` breaks most of my existing Hy code, so I've version-pinned all my projects to an older release and am rewriting some in pure Python and fiddling with ClojureScript and Chez Scheme...

But don't let that stop you from improving Hy to keep up with mainstream Python - I'll use it if I can. 😉

**Comment by Kodiologist** [comment]
You're missing a lot of bugfixes and performance improvements if you stick with an old version. Remember that it's easy to write `let` as a macro that works in 99% of actual use cases. It's because we can't get the semantics exactly right, due to Python's scoping rules, that we removed it.

**Comment by rcarmo** [comment]
Yes, I am fully aware of that. But I can't spare the time to experiment - I need to make sure I won't have to rewrite them again, so moving back to normal Python or to a regular Scheme is the safest option.

Right now, I'm heavily into `asyncio`, so I can't really use Hy.

I have other projects I can keep using Hy on, but the question will come up time and again if I want to have a "pretend" `let` or just use a normal Scheme.

**Comment by vodik** [comment]
I managed to hack something together, I'll put up a PR shortly as I clean it up as I'd like to see this added, but I have no idea if anyone will like the syntax I've chosen, nor have I written any tests:

```hy
=> (import asyncio)
=> (setv loop (.get_event_loop asyncio))
=> (asyncdefn test [] "Hello World")
=> (.run_until_complete loop ((asyncfn [] (await (test)))))
'Hello World'
```

**Comment by rcarmo** [comment]
Hmmm. Interesting. I’m curious about what sort of syntax would be feasible for async for and await in comprehensions:

```
result = [i async for i in aiter() if i % 2]
result = [await fun() for fun in funcs if await condition()]
```

**Comment by Kodiologist** [comment]
@rcarmo Currently, comprehensions in general are being overhauled; see #1437 and #1471.

**Comment by vodik** [comment]
@rcarmo `await` inside `list-comp` works with my patch, but `async for` inside comprehension isn't implemented yet. I'll see what I can make work once the comprehension changes land.
