### ISSUE TITLE
Get rid of break/continue and restrict yield to new defgn/gn special form

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1055]
If we could make `yield`, `break`, or `continue` in a `let`-form a syntax error, then `let` would almost work properly. Unfortunately, detecting this correctly in all cases seems _really_ difficult.

With that done, the only remaining potential issue would be a local assignment shadowing a nonlocal. I don't think this is such a big deal, since Python can _read_ nonlocals just fine and Clojure seems to get along fine without writable locals period. We could work around this the same way Clojure(script) does--with an atom construct. We can even use explict `nonlocal` statements instead in Python 3.

It would be easier to get `let` working if we got rid of `yield`, `break` and `continue`. But maybe we don't have to go _quite_ that far.
#### Get rid of `break`/`continue`

It seems contradictory to me that we don't have `return`, and yet allow `break` and `continue`, since the main arguments against `return` apply equally to them, and Python uses explicit returns to compensate for its lack of labels anyway. To be consistent, why not get rid of them too?

We could replace them with forms that don't compile to Python's `break`/`continue`, but throw exceptions instead. A `LabelBreak` exception would still work in infinite loops, and would work properly inside `let` as implemented now. The required `try`/`except` could be hidden with a required explicit `label` macro.

``` Hy
(label :x
  (while 1
    (let []
      (break :x))))
```

Which becomes something like:

``` Python
try:
  while 1:
    def _hy_anon_fn_1():
      raise LabelBreak('\ufdd0:x')
except LabelBreak as :G_1234:
  if :G_1234.is_not_named('\ufdd0:x'):
    raise
```

Getting `continue` behavior is as simple as moving the label inside the loop:

``` Hy
(while (foo)
  (label :y
    (let []
      ;; do stuff?
      (break :y))))
```

Which becomes:

``` Python
while foo():
  try:
    def _hy_anon_fn_1():
      # do stuff?
      raise LabelBreak('\ufdd0:y')
  except LabelBreak as :G_1234:
    if :G_1234.is_not_named('ufdd0:y'):
      raise
```

Since they re-raise exceptions that don't match the label, there's no reason you can't use both inner and outer labels when required. You can also break out of nested loops. `try` forms can also have an `else` block like Python loops do, so any `else` logic the loop needs could be moved to the `label` form itself.

There's actually no reason that break logic has to be attached to a loop, and this `label/break` construct cleanly separates the ideas. It works just like Java's [labeled block statements](https://docs.oracle.com/javase/specs/jls/se7/html/jls-14.html#jls-14.7); a more structured alternative to a full-on `goto` like in C.

This will also compensate for the lack of `return`.

``` Hy
(defn foo []
  (label :return
    ;; do stuff?
    (setv res something)
    (break :return))
  res)
```

We could even build this behavior into the label form, so that `(label :x (break :x res))` has a value of `res`. See [Drython's statement module](https://github.com/gilch/drython/blob/master/drython/statement.py) for more examples of how this could work.
#### Restrict `yield` to `gn`

`yield` is such a powerful feature of Python, and so important to coroutintes, that I can't imagine getting rid of it is a good idea. But maybe we can make it behave better in Hy.

A generator function is a very different beast in Python from a normal function `def`, with its own quirks and rules. Fewer special cases make macro writing easier. They would be easier to deal with in Hy, both in `let` and other macros, if we cleanly separated them.

Rather than trying to detect the presence of `yield` in the `let` macro, I propose adding a new special form `gn` (for generator) analogous to `fn`. It would also have an equivalent `defgn` macro.

 The ast generator will always add the lines

``` Python
    return
    yield
```

to the end of a `gn`'s `def` expansion. This guarantees that Python will always treat it as a generator function (since it contains a `yield`), even if it's empty (since it always returns before it reaches the final `yield`), but won't change the behavior of any code above it in the `def`.

If you need a generator, you can't use `fn`/`defn` with `yield` anymore. Use `gn`/`defgn` instead.

Hy's ast generator must enable `yield` when inside a `gn` special form, _and disable it_ again when inside a `fn` special form, especially if a `fn` is nested inside a `gn`. This way, we can leave `let` as-is, that is, defined in terms of a `fn`, which now can't possibly contain a `yield` to muck things up. Other macros would also be free to use `let` in their expansions in the traditional Lisp manner without the same worry.

**Comment by kirbyfan64** [comment]
The `break`/`continue` removal sounds nice in practice, but that would likely have *serious* performance issues.

Also, it actually isn't hard to detect `yield`, `break`, or `continue` inside a `let` expression. What if `let` were implemented in the *compiler* instead of in the bootstrap file? That would allow a simple the creation of an instance variable to determine whether or not a let expression is currently being compiled. The majority of `fn`'s code is to handle arguments and yields, but `let` wouldn't need to deal with *any* of that.

**Comment by gilch** [comment]
>The `break`/`continue` removal sounds nice in practice, but that would likely have serious performance issues.

A valid point if true, but I'm not convinced. Python does use exceptions internally for break-like behavior, like the `StopIteration` exception terminating an iterator in an ordinary `for` loop. A Python `try` has virtually no overhead when no exception is raised, but actually catching an exception does.

I'm a bit more concerned about using an inner label as a continue, since that could happen nearly every loop. You could easily refactor that to a `cond` in most cases though. And also, like 97% of the time performance doesn't matter. You can always profile and rewrite the 3% bottleneck in Python (or C or Cython).

Python was never about performance to begin with. Furthermore, if performance is such a concern, we really should get rid of `let` instead. Macros can use `setv` on gensyms to get most of the benefit of a local scoping provided by `let`. Locals are much faster in Python than the extra function call `let` requires. Explicit closures would still be possible with `fn` instead of `let`, but won't be surprising when you add a `yield`, and you won't be tempted to add a `break` or `continue` where it doesn't belong.

>Also, it actually isn't hard to detect yield, break, or continue inside a let expression. What if let were implemented in the compiler instead of in the bootstrap file?

Again not convinced, but you're more familiar with Hy's ast generation than me. Can you just as easily detect these things when it's nested in other fns? In classes in fns? Can you allow a loop totally contained inside a `let` to `break`/`continue`? Wouldn't you have to re-implement Python scoping rules? It's definitely worth considering if it actually works. I could still add the `label` macro as a contrib library or something.

**Comment by gilch** [comment]
On second thought, just detecting `break`/`continue` in the compiler and raising an error isn't going to help at all. Hy (or Python, rather) already does this:
```Hy
(while 1 (let [] (break)))
;; SyntaxError: 'break' outside loop
```
Even given this error, it's still a problem, because macros tend to use `let` a lot in their expansions, so even if users know better than to `break` through a `let` (they learned from the error message), they won't know which macros wrap their code in a `let`. `break` and `continue` just mysteriously break in Hy code. But with `label`, (and without `break`/`continue`) all this will just work.

**Comment by gilch** [comment]
For the same reasons as above, just raising an error on encountering a `yield` inside `let` isn't good enough either. Because macros. But it is, at least, better than what happens now:
```Hy
=> (let [] (yield))
<generator object _hy_anon_fn_1 at 0x000000000376C090>
```
Which makes no sense. It should be an error, since it's a near equivalent to this:
```
=> (do (setv) (yield))
SyntaxError: 'yield' outside function
```

**Comment by gilch** [comment]
As @zackmdavis pointed out in #1054, `await` won't work in `let` either. It will have the same problem as `yield`.

**Comment by gilch** [comment]
I got a [yield coroutine replacement](https://github.com/gilch/drython/blob/master/drython/expression.py) working in my [Drython](https://github.com/gilch/drython) project, similar to the way I had done it in [Saccharin](https://github.com/gilch/saccharin/blob/master/src/com/github/gilch/saccharin/sequential/Generator.java), but Drython's version is two-way.

It could perhaps be adapted for Hy. It works through a `let`, and for the same reason makes `yield from` unnecessary. It uses a `Thread` object to create an independent stack that stores the position of the interrupted generator function, and a pair of queues to communicate between threads. The thread is marked as a daemon so that even if it is never exhausted, it won't persist past program exit.

It potentially has some serious problems, however. I think a normal `yield` generator can get garbage collected, even if it's not exhausted, as long as the object is unreachable. I'm not sure a blocked daemon thread can be collected like that, so it's a memory leak, which would be really bad in a long-running server process. Another issue is that because the generator is running in a separate thread, it might cause race conditions if it has side effects (though the queues should be safe). And finally, daemon threads get killed instantly on program exit, without a chance to resolve `try`/`finally` blocks and context managers. If the generator was used to read some of the lines in a file or something, it might not get released. Threads seem like more trouble than they're worth.

If we could translate this into single-threaded coroutines, it might be a viable option, but I haven't figured out how to do it without threads. Is there a general way to translate threaded programs into coroutines? It seems like Javascript would need something like this. Or maybe someone with more Python threading experience could fix the problems with the threaded version.

**Comment by gilch** [comment]
I think Drython's zombie daemon generators are getting properly killed now.

(These are technical terms.)
