### ISSUE TITLE
remove let proposal (again!) and maybe replace with deprecated contrib shim

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1056]
#### Proposal

Remove `let` from core Hy. Redefine any library functions/macros in terms of `setv` if possible, or `fn` if it requires a closure.
##### Sub-Proposal

As a compromise, to make porting old code easier, implement a deprecated `let` macro in contrib, with dire warnings that it may be removed in future versions of Hy, and an explanation of why it's broken. We could even have different versions with double brackets or not and with a `((fn ...))` or `do`/`setv` expansion.
#### Rationale

Keeping `let` as-is requires us to remove or replace the the things it breaks, namely `break`/`continue`, `yield`, and now `async`/`await` #1054 (and possibly any other future Python syntax). I think I can replace `break` and `continue` #1055, but nobody knows how to replace `yield`/`async`/`await`. Removing them is out of the question. I'd sooner give up `let` than coroutines, wouldn't you?

Keeping the things `let` breaks requires us to remove or replace `let`. Nobody's figured it how to fix `let` after a year, not that we haven't tried #1055 #1000 #844 #688 #673 #664 #663, and this problem has all but deadlocked Hy development in that time.

Furthermore, if performance is a concern (it's not so much for me), then it's much more efficient in Python to set locals than to declare a function, call the function, and set locals. Most Python implementations don't inline functions (last I checked) yet `let` is almost exclusively used for lexically-scoped locals now.

If we _don't_ have `let` in core, and IF we get it working eventually, we can put it back in without breaking API again. Accepting this proposal leaves us that hope, but if we settle for any version of `let` that doesn't quite work right, we can't do that.

---

I know that my original proposal #844 got closed with the loose consensus that we'd replace `let` with a working version. After banging our heads against this for about a year with no success, perhaps some of us have changed our minds?

The rules say it only takes three to push through a change, one to commit, and two (from core) to approve. @kirbyfan64, @tuturto, what say you? Of course, three more could revert it, so I'll call that a veto. @hylang/core, objections? Vetoes? Approval? Counter proposals? Crazy ideas?

**Comment by tuturto** [comment]
I'm in favour of this :+1:. As much as I would like to see ```let``` stay in Hy, I think it's time to move forward and get this over with. Having ```let``` macro in contrib would be a remedy and give people time to update their code when we release (syntax of many other things will break too, so it'll be pretty substantial change anyway).

**Comment by kirbyfan64** [comment]
:+1: `let` is cool and all, but ATM it's ridiculously broken and needs to die in a very, very large and hot fire.

**Comment by rwtolbert** [comment]
I know I've been quiet around here, +1 from me.

After the experiment with uvloop I just got sent from a colleague, I'd really like to see us be able to support the good parts of 3.5+ instead of a very old, broken construct.

I wonder if we finally make this leap, if a bunch of past backlog might come unstuck.

**Comment by algernon** [comment]
:+1:

I came to the conclusion, that a contrib `let` is fine with me.
