### ISSUE TITLE
is there a fast way to access the elements for matrix in hy?

### ISSUE THREAD

**Issue by larluo** [hylang/hy#1057]
y = df.iloc[0:100, 4].values
how i should translate the expression in hy way?

for me, i only know (get [1 2 3 4] 3) (slice [1 2 3 4] 0 2) method to access the array element.

**Comment by kirbyfan64** [comment]
Try `(. df.iloc [(slice 0 100)] [4] values)`. See [the docs](http://docs.hylang.org/en/latest/language/api.html#id1) for more info.

Note that this only works with the version of Hy from Git, not the version on PyPI.

**Comment by larluo** [comment]
i get the error for the following expression:
(. [[1 2 3] [4 5 6] [7 8 9]] [(slice 0 2)])                                                                                                           
i could not find the related doc, the list can just be single element.
such as: (. [[1 2 3] [4 5 6] [7 8 9]] [2])

**Comment by larluo** [comment]
the result is different, can you help look at it?

in python
```python
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)
 X = df.iloc[0:100, [0, 2]].values
type(X)
=> <type 'numpy.ndarray'>
X[:50, 0]
=> array([ 5.1,  4.9,  4.7,  4.6,  5. ,  5.4,  4.6,  5. ,  4.4,  4.9,  5.4,
        4.8,  4.8,  4.3,  5.8,  5.7,  5.4,  5.1,  5.7,  5.1,  5.4,  5.1,
        4.6,  5.1,  4.8,  5. ,  5. ,  5.2,  5.2,  4.7,  4.8,  5.4,  5.2,
        5.5,  4.9,  5. ,  5.5,  4.9,  4.4,  5.1,  5. ,  4.5,  4.4,  5. ,
        5.1,  4.8,  5.1,  4.6,  5.3,  5. ])
```
in hy:
```
(let [df (read-csv "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data" :header None)                                          
      x (. df.iloc [(slice 0 100)] [[0 2]] values)]                                                                                                  
  (type x)
  (. x [(slice nil 50)] [0]))
=>  <type 'numpy.ndarray'>         
=> array([ 5.1,  1.4])      
```

**Comment by larluo** [comment]
solved:
```hy
(. x [(, (slice nil 50) 0) ] )
```
thanks
