### ISSUE TITLE
(comment ...) or #_ macro to comment a block as in Clojure

### ISSUE THREAD

**Issue by ghost** [hylang/hy#1058]
do hy has a **comment** or **#_** macro to comment block?
i can not find the comment block function in hy, 
 it's very convenient to comment one whole block rather text line.

**Comment by kirbyfan64** [comment]
If you text editor has Clojure support, you can probably just use whatever your editor has for commenting blocks. In Howl, you select the text and press ctrl+`/`.

Otherwise, you could always define a macro like this:

```hy
(defmacro discard [&rest x] `nil)
```

Then you could do:

```hy
(discard (print 123)) ; Does nothing.
(discard (. nil error)) ; Also does nothing.
```

**Comment by gilch** [comment]
Your `discard` macro becomes `nil` which is equivalent to Clojure's `comment` macro, but that's different than `#_`, which doesn't even become `nil`.
```Clojure
user=> (println (do 1 2))
2
nil
user=> (println (do 1 (comment 2)))
nil
nil
user=> (println (do 1 #_2))
1
nil
```
You see the difference. Sometimes you need a `nil` placeholder and `comment` is what you want, but usually you want the entire form to not exist temporarily. I think it's worth adding `#_` to Hy proper.

**Comment by algernon** [comment]
I agree, `#_` would be great. It needs to be on a parser level, I suppose, since it needs to be ignored, and not even make it to the AST.
