### ISSUE TITLE
Doc error describing "if"

### ISSUE THREAD

**Issue by rcarmo** [hylang/hy#1064]
```
(print (if (< n 0.0) "negative"
           (= n 0.0) "zero"
           (> n 0.0) "positive"
           "not a number"))
HyTypeError: `if' needs at most 3 arguments, got 7
```

So someone needs to go over that section and describe how `if` is supposed to work...

**Comment by gilch** [comment]
The documentation is correct.
```Hy
=> (defn test-if [n]
...   (print (if (< n 0.0) "negative"
...              (= n 0.0) "zero"
...              (> n 0.0) "positive"
...              "not a number")))
=> (test-if -1.0)
negative
=> (test-if 0.0)
zero
=> (test-if 1.0)
positive
=> (test-if nan)
not a number
```
I suspect you're still using the old version of Hy on PyPI, but are using the unstable/development version of the docs. Use the docs that match your version of Hy.

If there's a link somewhere that pointed you at the wrong docs, that's what should be fixed. Where did you find them?

**Comment by rcarmo** [comment]
Well, I googled for “hylang if”, obviously. :)

Anyway, when is the new release coming out? It’s been ages.

**Comment by gilch** [comment]
I think it's coming out some time last September.

We're a little behind schedule :)

We do accept pull requests (sometimes), if you think you can help us with our issues.

I can't fix Google, but you're certainly not the first to find the wrong docs. It got better when we put up both links in the README.md. Maybe we could rename the "latest" docs to "unstable" and give it a red color scheme or something. I don't know. We should probably just release the next version already, but it's _really_ not ready yet.
