### ISSUE TITLE
make assoc use a gensym

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1068]
Clojure:

``` Clojure
user=> (defn spam [] (println "Spam!") {})
#'user/spam
user=> (assoc (spam) 1 10, 2 20, 3 30)
Spam!
{1 10, 2 20, 3 30}
```

Hy:

``` Hy
=> (defn spam [] (print "Spam!") {})
=> (assoc (spam) 1 10  2 20  3 30)
Spam!
Spam!
Spam!
```

This is surprising. It could be corrected with a gensym.

Also `assoc` doesn't return the dict as in Clojure. But in Python's standard library, all of the mutating functions and methods I can think of return `None`, so perhaps this was intentional.

**Comment by gilch** [comment]
The easiest way to accomplish this is probably to simplify `assoc` in the compiler to only accept one pair, then rename to `assoc*`, and then re-implement the multi-pair `assoc` as a macro in terms of `assoc*` with a gensym. The common case of one pair need not expand to use a gensym, unless we want to change `assoc` to return the dict instead of `nil`.

**Comment by woodrush** [comment]
Oh snap, this was open with no PRs when I started working on it last night. I'll just close my PR.
