### ISSUE TITLE
Style guide: suggest an extra space where Clojure uses comma.

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1069]
In an `assoc`/`map`/`let`, etc. usually Clojure uses line breaks to show pairs.

``` Clojure
{1 11
 2 22
 3 33}
```

Hy also adopts this style where applicable. More lines aren't more readable in every situation. Too much whitespace is also noise. But Clojure has an alternative of using commas when it's short enough to fit on one line:

``` Clojure
{1 11, 2 22, 3 33}
```

The pairs are still distinct, even if there are many of them:

``` Clojure
{1 9, 2 8, 3 7, 4 6, 5 5, 6 4, 7 3, 8 2, 9 1}
```

If you wrote this without commas, it could be difficult to tell key from value in the middle.

``` Clojure
{1 9 2 8 3 7 4 6 5 5 6 4 7 3 8 2 9 1}
```

This is rightly considered bad style in Clojure.

Hy can't use commas this way, and I don't really want to change that #198, but Hy could use a space instead of a comma:

``` Hy
{1 9  2 8  3 7  4 6  5 5  6 4  7 3  8 2  9 1}
```

In a fixed-width font, the pairs are still distinct. Programmers nearly always use a fixed-width font.

I suggest adding this format to Hy's style guide, and adjusting Hy's editing tools to use it as well.

**Comment by kirbyfan64** [comment]
Nice idea!

**Comment by gilch** [comment]
The repr for HyDict should also add the space. (Also hy-repr?)

**Comment by paultag** [comment]
I like this idea; the example (dicts) totally makes sense. A bit funny at first, but I do like it a bit! I find myself adding newlines, this seems like a great way to do it on one line. :+1:
