### ISSUE TITLE
Change Hy's __version__ string

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1070]
I suggest changing Hy's version number to "0.11.0-github" or something ("-develop", "-bleeding", "-experimental"?), so we can distinguish it from the PyPI version 0.11. Maybe we could automatically append the git hash or something. That would make it easy for us to tell which version we're testing.

Users are often confused by the version differences we've introduced. It would be easier to talk to them if we had better names for these versions and could ask them for the `__version__` string, instead of "did you get this from PyPI or github and when?". It would also be easier for them to tell the online documents apart if they had very distinct version strings.

We must also be sure to take that bit back off for the next PyPI release branch to prevent that confusion again.

**Comment by zackmdavis** [comment]
0.12a0, like Python does it?

**Comment by berkerpeksag** [comment]
+1 for 0.12a0.

**Comment by gilch** [comment]
That's fine with me, but we need to agree on the rules for when exactly we change the version number and how. Do we increment with every pull request? I think Python's versioning rules are here: https://www.python.org/dev/peps/pep-0440/

Our rules may not need to be that complex yet.

**Comment by Kodiologist** [comment]
I'd recommend appending the Git hash or a 7-character prefix. That way, the version number alone tells us exactly what commit a user is running.

Regarding the "0.12a0" style, what would increment the alpha number "a0"? How would one translate from alpha numbers to commits?

**Comment by gilch** [comment]
Although I suggested it in the first place, I don't think we can just hardcode the git hash in the version string, since the hash doesn't exist until after the commit has been made. Perhaps there is some way for Python to generate it programmatically though. Have you seen any other projects that can do this?

**Comment by Kodiologist** [comment]
> I don't think we can just hardcode the git hash in the version string, since the hash doesn't exist until after the commit has been made. Perhaps there is some way for Python to generate it programmatically though.

Right. I figured the way to do it is to call `git log -1 --format=%H` at build-time, putting it in a generated file.

> Have you seen any other projects that can do this?

[Cataclysm DDA](https://github.com/CleverRaven/Cataclysm-DDA) comes to mind. That's C++, though.

**Comment by tuturto** [comment]
Is this closed by #1135, or do we want to have more automation in place at this point?

**Comment by Kodiologist** [comment]
I think the need's covered.
