### ISSUE TITLE
Hy does not provide an iter_import_module, breaks Django functionality

### ISSUE THREAD

**Issue by elfsternberg** [hylang/hy#1071]
importer.py's functionality hooks into the sys.meta_path mechanism, which is good enough for standard functionality.  Django, unfortunately, uses the iter_modules feature of pkgutils to list the modules present in management/commands, but without an importer in sys.path_hooks, and without registering that importer with pkgutils, Django commands written in Hy do not show up in the list of available commands when using manage.py, and calling them does not work.

**Comment by Digenis** [comment]
This is not specific to django; lot of software uses pkgutil.iter_modules.

**Comment by elfsternberg** [comment]
True.  Closing until I find a better fix.
