### ISSUE TITLE
Interpreter does not work the same as documented

### ISSUE THREAD

**Issue by egregius313** [hylang/hy#1075]
Hi, I have been playing around with Hy and I realized two minor problems in the tutorial, namely set and fraction literals. The tutorial shows

=> #{3 1 2}
{1,2,3}
=> 1/2
1/2

However, this does not work in my interpreters. (Python 3.4, 3.5 or Python 5 (ie, 2.7))

**Comment by kirbyfan64** [comment]
@egregius313 Classic doc issue: the documentation is pointing to the Hy version from Git (i.e. the development version), but you're probably using the release version (maybe from PyPI). Try:

```
$ pip install git+https://github.com/hylang/hy.git
```

This should give you the dev version, which supports these.

**Comment by kirbyfan64** [comment]
Also, here are the docs for the stable version:

http://docs.hylang.org/en/stable/

**Comment by jwilk** [comment]
I don't care about Homebrew, and this PR wasn't about Homebrew.
