### ISSUE TITLE
Implementation of operators

### ISSUE THREAD

**Issue by khinsen** [hylang/hy#108]
The Python operators are currently implemented as special forms in the compiler. They are not functions and thus cannot be used with higher-order functions such as map. They cannot be redefined either.

Python has function equivalents in the operator module, which can be used as  a workaround. But that's more pythonic than lispy.

We could make + - etc. ordinary functions using the implementations from module operator. I suspect this would slow down expression evaluation. It also creates ugly Python code when decompiled.

In order to allow redefinition, we'd have to have + - etc. as symbols in a namespace. I don't think Python namespaces would allow that, but perhaps they do.

Can we have the best of both worlds? The compiler could check if the + symbol is associated with standard addition, and use Python's + operator if that's the case, defaulting to a function call otherwise.

**Comment by kirbyfan64** [comment]
Can this be closed now?

**Comment by Kodiologist** [comment]
I say yes. This is what we have `hy.core.shadow` for.
