### ISSUE TITLE
Please upgrade/sync hylang release

### ISSUE THREAD

**Issue by fragrans** [hylang/hy#1082]
I just installed latest hy using pip install hy:
give the following error:

```
hy 0.11.1 using CPython(v2.7.11:6d1b6a68f775) 2.7.11 on Windows
=> (let [a {}]
... (print a))
  File "<input>", line 1, column 9

  (let [a {}]
          ^^
HyMacroExpansionError: let variable assignments must contain two items

=> (exit)
```

and no issue with git/master branch.

**Comment by kirbyfan64** [comment]
You can install the latest version using:

```
$ pip install git+https://github.com/hylang/hy.git
```

Also, please don't write the issue titles in all caps. There really isn't a need for it.

**Comment by paultag** [comment]
The point is valid; we should really update the pypi release. Can someone file a new bug for a minor version release? (0.X.0)

**Comment by hcarvalhoalves** [comment]
Pleeeeeeease

**Comment by Kodiologist** [comment]
#1126 is the issue for this now.
