### ISSUE TITLE
Speed up startup time?

### ISSUE THREAD

**Issue by xificurC** [hylang/hy#1087]
A simple print in hy:

```bash
$ time hy test.hy
I was going to code in Python syntax, but then I got Hy.
hy test.hy  0.70s user 0.01s system 99% cpu 0.708 total
```
Same in python:

```bash
$ time python test.py
And this is Python syntax.
python test.py  0.03s user 0.00s system 91% cpu 0.033 total
```

So that's 0.03 seconds for the simplest python script and 0.7 seconds for the simplest hy script. Is there any way to speed this up? Python is used (among other things) for simple, small, throwaway scripts. Like a replacement for overgrown bash scripts. I would love to try using hy for some of these cases but the startup time would need to be in the same ballpark as python's.

**Comment by lthibault** [comment]
Could you profile the code?  I suppose the bottleneck could be rewritten with Cython _in principle_, but it would be up to the maintainers to decide whether the added complexity is worthwhile.

**Comment by gilch** [comment]
If you need faster startup for scripts, try using the included `hyc` tool. You'll get a pre-compiled `.pyc` file that you can launch with Python.

**Comment by xificurC** [comment]
@gilch that indeed takes the time down to the same as python. The fact that one needs to now compile makes it a little bit less convenient, nevertheless the drastic startup time improvement is worth it. Thank you for your input, I will close the issue.
