### ISSUE TITLE
Command line options with `defmain`

### ISSUE THREAD

**Issue by drewokane** [hylang/hy#1091]
Currently it seems difficult to call a hy script from the command line with "traditional" keyword arguments, e.g. `python some_script.py --start-date 1979-01-01`. Is there any thought about implementing this?

**Comment by kirbyfan64** [comment]
Can't you just access `sys.argv`?

**Comment by gilch** [comment]
See also the [argparse module](https://docs.python.org/3/library/argparse.html).
