### ISSUE TITLE
Question on performance

### ISSUE THREAD

**Issue by viksit** [hylang/hy#1092]
I've been looking at hylang to build a custom DSL for my project.

I haven't been able to find any details of performance considerations, however - could someone please point me to documentation or commentary on what the perf hits of writing something in hylang would be?

Does hylang also do TCO or some sort of optimization like that?

Thanks!

**Comment by kirbyfan64** [comment]
Hy performs no optimizationss over Python, FYI.

**Comment by viksit** [comment]
Ah I meant - if one were to write something in Python and the same thing in hy - how much of a perf hit could you expect?

**Comment by kirbyfan64** [comment]
Ah, ok.

If you write your code exactly like Python, then it should be minimal performance impact, pretty much all from implicit results that Hy generates.

If you go more Lisp-y, before of statements in short-circuiting expressions (e.g. `(and (setv a 1) 2)` and, in particular:

BEWARE OF `let`. It's not fast.

Other than that, I don't recall anything else of interest.

**Comment by viksit** [comment]
Well I'd like to use macros and other lispy features of course rather than emulate the procedural style. Did you mean that doing that will have an impact here?

Thanks for the pointer on let!

**Comment by gilch** [comment]
The beautiful thing about macros is that they've already expanded by "runtime". This only happens once, so they have no further impact on performance.

If you write a DSL in Python, your program normally becomes a kind of interpreter for that DSL. But if you use Hy macros to define the DSL, your program acts more like a compiler for that DSL. Using macros in this way can actually improve performance compared to the alternative.

Use the `$ hy --spy` option or `(disassemble)` to see what the Hy code is turning into. If you're accustomed to how Python performs, this can clarify the relative impact of various Hy forms.

Early optimization is evil. Program in a way you can get right and maintain first. Then profile it and optimize where it counts. Hy can import arbitrary Python modules, even those written in C for performance.
