### ISSUE TITLE
Automate hyc invocation

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1094]
CPython automatically compiles its files to speed up subsequent startups. This generally works well. If the corresponding script hasn't changed (or is missing), and you're using the same Python version, CPython skips the compilation step and startup is faster.

Hy already has `hyc` to perform this compilation step, but `hy` doesn't appear to use it automatically the way `python` does. #1087. There's really no reason it couldn't, is there?

**Comment by Kodiologist** [comment]
Provided by #1269.

**Comment by xificurC** [comment]
Hey, great to see more action on this. Thanks!
