### ISSUE TITLE
Using a string as an lvalue

### ISSUE THREAD

**Issue by ntrifunovic** [hylang/hy#1100]
Following code returns `HyMacroExpansionError: defn/defun takes a name as first argument`

``` hy
(defmacro fun1 [method name]
  `(defn ~(+ method "-" name)  [] print "hello"))

(fun1 new fun)
(new-fun)
```

Modifying the code to:

``` hy
(defmacro fun2 [method name]
  `(def ~(+ method "-" name) (fn [] print "hello")))

(fun2 new fun)
(new-fun)
```

Gives following error:  `NameError: name 'new_fun' is not defined`

Finally modifying the code to:

``` hy
(defmacro fun3 [method name]
  `(def ~(+ method "_" name) (fn [] print "hello")))

(fun3 new fun)
(new-fun)
```

Makes example work.

I think that all 3 examples should be working. 

I've tested this with latest release and with current state of the master with Python 2.7.5.

**Comment by algernon** [comment]
The thing is, `(+ method "_" name)` will result in a string, while `def` requires a symbol. Try wrapping that in `(HySymbol ...)`.

**Comment by ntrifunovic** [comment]
@algernon: This works:

```hy
(defmacro fun1 [method name]
  `(defn ~(HySymbol (+ method "_" name))  [] print "hello"))

(fun1 new fun)
(new-fun)
```

I still needed to convert `-` to `_` to make it work.

**Comment by Kodiologist** [comment]
I think the question is, should `(defn ~x [] ...)` work when `x` is a string? That is, should strings automatically be wrapped to HySymbols in this context? Since `defn` is currently just a macro that uses `setv`, we may as well ask the same question of `(setv ~x ...)` while we're at it.
