### ISSUE TITLE
'with' doesn't work

### ISSUE THREAD

**Issue by EMayej** [hylang/hy#1101]
This is the example we have in http://docs.hylang.org/en/latest/language/api.html?highlight=with#with

```hy
(with [f (open "NEWS")] (print (.read f)))
```

hy reports NameError:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'f' is not defined

This is the output of hy2py:
```python
with f:
    with u'NEWS' as open:
        _hy_anon_var_1 = print(f.read())
    _hy_anon_var_2 = _hy_anon_var_1
```

version: hy 0.11.1

**Comment by kirbyfan64** [comment]
@EMayej You're using the docs for the in-development version of Hy, but you have installed the stable version. Try either:

the docs for the stable version:

http://docs.hylang.org/en/stable/language/api.html?highlight=with#with

or installing Hy from source:

    $ pip install git+https://github.com/hylang/hy.git

**Comment by kirbyfan64** [comment]
Related: #1082

**Comment by EMayej** [comment]
Thanks. It's OK now.
