### ISSUE TITLE
Add more operators to shadow

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1103]
We've currently only got `'#{+ - * / < <= = != >= >}` shadowed. Python has more operators than this, and so does Hy. I don't think there's any reason not to shadow these other binary operators: `'#{** @ // % << >> & ^ |}`.

The unary operator `'~` should also be easy to shadow, but the other unary operators `'#{+ -}` present some ambiguity. I propose importing the `operator.neg` and `operator.pos` functions for these, (as `neg` and `pos`).

There are a number of other operators in the `operator` module. The distinction between operator and function that Python has is unnatural in a Lisp like Hy. We should automatically import the remaining operators, perhaps with some renaming, as was done for `itertools`. We can treat these as a macro or special form when in the function position, but as a function name otherwise.

**Comment by gilch** [comment]
On second thought, if we fix #1109, then the shadowed `'#{+ -}` operators should just work as unary when applied to a single argument. There's no need to import `neg` and `pos`.

**Comment by Kodiologist** [comment]
It looks like we also need to shadow some alphabetic operators, like `not`:

    => (setv f not) (print (f 1))
    NameError: name 'not' is not defined

But not all of them. There's no sense in shadowing `and` because of its short-circuiting magic, which can't be captured by a mere function.
