### ISSUE TITLE
[feature] Shorthand for `:kwarg True`, `:kwarg False`, and `:kwarg kwarg`

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1119]
It's common to want to set a keyword argument to a Boolean, and also common to want to set a keyword argument to the value of a variable with the same name. I propose the following syntactic sugar for keywords when they're used for keyword arguments:
- Translate `:+foo` to `:foo True`
- Translate `:!foo` to `:foo False`
- Translate `:^foo` to `:foo foo`

(One might also be tempted to add a construct for `:foo None`, but this seems like an unusual enough case that having Hy programmers learn another piece of shorthand isn't worth it.)

I included the first two translations (`:+foo`) and (`:!foo`) in [my own implementation of keyword arguments for Hy](https://github.com/Kodiologist/Kodhy/blob/88631400ce/kodhy/macros.hy#L32), which I made because Hy didn't have that feature built-in yet. I've found this sugar handy and use it frequently in practice. It's a bit like `--flag` and `--no-flag` in command-line arguments.

 I haven't previously used the last translation (`:^foo`). It's similar to a GHC extension to Haskell called ["record puns"](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#record-puns).

**Comment by gilch** [comment]
Here's a better idea: 
```
(def T true  F false)
```
Now it's `:foo T` instead of `:+foo`, and `:foo F` instead of `:!foo False`. Your version is only one character shorter than mine, but mine doesn't have to change the rules.

Complexity has _costs_. Lisp gets its phenomenal macro powers precisely by being as regular as possible. As demonstrated above, the benefit of the new syntax is marginal, and thus not worth the cost in complexity.

I'm much more willing to consider new syntax if there's precedent in Python, Clojure, or Common Lisp, but as far as I know, you made this up.

The case for the third `:^` syntax is much stronger, but I think we could come up with better options that don't require changing syntax.

**Comment by Kodiologist** [comment]
> Complexity has *costs*. Lisp gets its phenomenal macro powers precisely by being as regular as possible.

I don't see how the proposal would interfere with macros.

> The case for the third :^ syntax is much stronger, but I think we could come up with better options that don't require changing syntax.

Such as?

**Comment by Kodiologist** [comment]
> `(def T true  F false)`

I like this, although I would expect adding builtins with one-character names to rustle a lot of jimmies, so presumably this would have to be in a contrib module or not in core Hy at all.

**Comment by gilch** [comment]
I didn't mean to suggest we put this in core, or even in contrib (It's one line, c'mon.), but come to think of it, that actually might not be a bad idea.

The relevant precedents for booleans:

- Common Lisp (and Emacs Lisp) `T`/`nil`
- Clojure `true`/`false`
- Python `True`/`False`.

Hy supports all of the above but `T`. (I think this is pointless redundancy.) So there's a fairly strong case for making `T` mean Python `True`. I've argued in #908, that we should have only one obvious way to do it, but nobody seems to like the default first choice of Python's `True`/`False` (not even me), so I thought we'd probably end up with Clojure's `true`/`false`. The case for making `F` false is not as strong, but it has a sensible symmetry to it, also, Scheme uses `#t`/`#f`, so it's not that strange for Hy to use `T`/`F`.

**Comment by gilch** [comment]
> Such as?

Besides something like your `kwc` macro? Python has a `vars` function that can collect locals into a dict. I've sometimes used it it Python to avoid the repetition of local variable names. I've just written a macro that can collect only those variables in scope that you name:
```Hy
(import [hy.models.string [HyString]])
(defmacro vars-of [&rest vs]
  `{~@(interleave (map HyString vs) vs)})
```
This will write a dict literal with string keys and symbol values with the same name (that eval in the current scope):
```Hy
=> (def spam 1  eggs 2  bacon 3)
(1, 2, 3)
=> (vars-of spam eggs)
{'eggs': 2, 'spam': 1}
```
Note I didn't say `bacon`, so it's not in the dict (unlike Python's `vars`). You can use `apply` to make a dict the kwargs in a call (like Python's `**`).
```Hy
=> (defn foo [&kwargs kw] (print "got:" kw))
=> (apply foo [] (vars-of spam bacon))
got: {'bacon': 3, 'spam': 1}
```
Now the `apply` syntax itself could perhaps be improved. #891. It's not as flexible as Python3 which now lets you use multiple `**` in the same call, so we have precedent for changing it. But this approach does eliminate the common repetition of `:foo foo`.

**Comment by Kodiologist** [comment]
Yeah, that's not very helpful without an easy way to include punned keyword arguments and regular keyword arguments in the same call. It also forces use of `apply`.

**Comment by gilch** [comment]
I feel like there should be an easy way to do that. See #1128.

**Comment by Kodiologist** [comment]
Almost certainly not gonna happen in Hy itself. Maybe I could add something to Hyrule for punning, but evidently I'm the only one who cares, anyway, and I find the need hasn't come up for a while, for whatever reason.
