### ISSUE TITLE
Rename `for` to `doiter` and then `for*` to `for`.

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1125]
See #1124, #874. This step would make Hy more consistent with both Python and Clojure, and make Hy less confusing.

**Comment by gilch** [comment]
We also need to update the docs with this. In particular, mention in the documentation of `for` (formerly `for*`), that Clojure users that want a list comprehension should use `genexpr` instead.

**Comment by allison-casey** [comment]
Obsolete since the unification of for with comprehensions in #1626
