### ISSUE TITLE
Release a new minor version (0.X.0)

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1126]
Paul asked for this on July 7th [here](https://github.com/hylang/hy/issues/1082#issuecomment-231130753). Our last release was in 2015, so it's been a while.

**Comment by tuturto** [comment]
I'll start working on releasing 0.12.0

**Comment by tuturto** [comment]
- [ ] check news and update it if needed
... (all the missing steps here)
- [ ] tag release in github
- [ ] build and test install packages
- [ ] let @paultag know that everything is ready for uploading to PyPi

**Comment by Kodiologist** [comment]
Awesome, thanks for doing this. It would also make sense to close outstanding pull requests (that aren't too complicated) before the release.

Don't forget to create a new Git tag for 0.12.0. If #1135 is merged, you won't need to edit version.hy manually.

**Comment by tuturto** [comment]
It'll take some time to go through a year of commits and pull relevant things into NEWS file. But that's probably the most time consuming part. I'll be happy to include all the PRs that are closed into release and we really should aim to release a bit more often anyway.

**Comment by gilch** [comment]
We're still in the process of making breaking changes. We were reluctant to make a release, since that would break everyone's code twice instead of once. But perhaps incremental changes are easier to deal with than big changes? Just saying.

**Comment by tuturto** [comment]
I don't like breaking code more often than absolutely necessary either, but 0.11.0 is over a year old now. I agree with inceremental changes. Easier to fix 2 months worth of changes than 12 months worth of changes.

**Comment by tuturto** [comment]
https://pypi.python.org/pypi/hy/0.12.0

**Comment by gilch** [comment]
Which versions of Python do we support? I thought we stopped supporting 2.6 and added tests for 3.6? That's not what the pypi page shows.

**Comment by Kodiologist** [comment]
We certainly haven't dropped support for 2.6 yet, and we intend to support 3.6 given that we have tests for it and it's the newest stable Python 3.

**Comment by kirbyfan64** [comment]
> We certainly haven't dropped support for 2.6 yet

[Uhhh...](https://github.com/hylang/hy/pull/843#issuecomment-123787785)

I'm guessing @paultag just forgot to update the classifiers...

**Comment by gilch** [comment]
Do we also need any non-CPython classifiers?

**Comment by gilch** [comment]
It looks like Travis is also running PyPy tests. It's still showing `3.6-dev`, but Python 3.6 has been released now. Can we update that yet? We also might want to consider supporting other Python implementations officially #934.

**Comment by Kodiologist** [comment]
Are we ready to make announcements? It would make sense to make a post to /r/lisp, for example.

**Comment by tuturto** [comment]
So far it's been announced in:

- Twitter: https://twitter.com/hylang/status/821786120086290432
- Google Groups: https://groups.google.com/forum/#!topic/hylang-discuss/lL0iQmGMP3s

/r/lisp would be good and I'm sure there are still others. @Kodiologist would you do /r/lisp?

**Comment by Kodiologist** [comment]
Sure thing: https://www.reddit.com/r/lisp/comments/5ouno4

(Huh, I didn't know that Twitter account existed.)

**Comment by gilch** [comment]
Can we update the [try-hy](https://try-hy.appspot.com/) app too?

**Comment by tuturto** [comment]
We should, but I don't know where or how try-hy is updated. Docker image and debian packages need some love too.

**Comment by Kodiologist** [comment]
I guess nobody knows how to do the Docker image or the Debian package, huh? Maybe we should just pass the buck on those, since we already have two official release channels, GitHub and PyPI.

**Comment by tianon** [comment]
Arg, I'm on both Docker and Debian -- Debian is at 0.12.1 now (https://packages.debian.org/sid/hy), and I need to look into my Docker automation to figure out why it didn't pick up 0.12.1.  I'll get that fixed ASAP. :+1:

**Comment by tianon** [comment]
Ok, Docker update is in queue: https://github.com/docker-library/official-images/pull/2781

**Comment by tuturto** [comment]
Great, thank you @tianon

**Comment by Kodiologist** [comment]
@tuturto, if you do the last checkbox (writing release instructions), I'll handle a new release, say 0.13.0, around June.

**Comment by tuturto** [comment]
Quick and dirty version: https://github.com/hylang/hy/wiki/Release-instructions
Should cover all the important bits. Not sure if I forgot any forgotten bits, but they can be added later.
