### ISSUE TITLE
Implement PEP 448 Additional Unpacking Generalizations

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1128]
See [PEP 448](https://www.python.org/dev/peps/pep-0448/) for what I'm talking about. See also #891.

**Comment by gilch** [comment]
Hy would need its own syntax for this kind of thing. We are already use to doing similar things with reader macros and syntax quotes, `~@` is very similar to Python's `*` when you think about it.

I propose  `#*` and `#:`, for example:
```
=> [1 #*[2 3 4] 5 6 #*[7 8 9]]
[1, *[2, 3, 4], 5, 6, *[7, 8, 9]]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
=> {#:{1 10} #:{2 20} 3 30}  ; hy --spy
{**{1: 10}, **{2: 20}, 3: 30}
{1: 10, 2: 20, 3: 30}
```
The `#` makes it clear that this is reader syntax, and `*` because that's how Python does it. The `:` has two dots like Python's equivalent `**`, and also reminds you of Python's `{:}` syntax and Hy's `:keywords`. But I suppose we could use `#**` instead. We don't have to restrict reader macros to one character. #1046.

**Comment by Kodiologist** [comment]
I'm wondering if I should work on this, so we can get rid of `apply`, rather than fixing #647. Personally, I like the `:*` and `:**` syntax you introduced first rather than `#`-prefixed symbols, but I guess it shouldn't make much of a difference.

**Comment by gilch** [comment]
An improved `apply` form could use `:*` and `:**` as kwargs. (This could even be done as a macro in terms of the current apply.), but using that syntax for all unpacking would be inconsistent, since it blocks what would otherwise be valid kwarg names in function calls. They would also only work once each per form, since a kwarg can only take one value per call.

The unpacking generalizations, on the other hand, can be used multiple times per form. Like `quote`/`'` in most lisps, they could be special forms with a macro shortcut. It has to be `#`-prefixed, unless we want to use up another dispatch character.

**Comment by Kodiologist** [comment]
No, I mean making `:*` and `:**` magic, so you can write `(f :* a :* b)` or whatever. It doesn't require any changes to the reader; it's just another special case for how to interpret literal keywords when they appear in a function call. `*` and `**` are crummy names for keyword arguments, so no loss there.

**Comment by gilch** [comment]
The Python unpacking generalizations can appear not just in function calls, but in tuple, list, set, and dictionary displays. (And they may also appear in comprehensions in the future.) So Hy would also need them in the equivalent special forms, but keywords aren't magic there--they're data. It seems a lot more consistent to me to use `#`-something. You wouldn't have to add so many exceptions and special cases.

I'm also not certain how #1127 should look, but it seems like a similar idea, so it would be nice if they had common syntax.

**Comment by Kodiologist** [comment]
Good point. `#*` and `#**` it is, I guess.

> I'm also not certain how #1127 should look, but it seems like a similar idea, so it would be nice if they had common syntax.

I assumed you'd use the identical syntax, like `(setv [a #* b c] x)` for `a, *b, c = x`.
