### ISSUE TITLE
"foo".format is legal syntax but does the wrong thing

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1137]
`(. "foo" format)` works, but `"foo".format` doesn't (`NameError: name '' is not defined`). hy2py shows that `"foo".format` is parsed as two separate statements, `"foo"` and `.format`.

**Comment by kirbyfan64** [comment]
IMO this isn't really a bug because of Lisp's notion of expressions. The main bug would be that doing `.x` as an expression is possible. It should be a syntax error.

Maybe the error message could read more like ```cannot have attribute without a name (in order to get attributes of expressions, use `(.format <expression>)`)```.

For your use case, `(.format "foo")` works well enough.

**Comment by Kodiologist** [comment]
Yeah, I think that makes sense. (I want `(. "foo" format)` rather than `(.format "foo")` in this case because I want to put the bound method in a list rather than call it immediately.)
