### ISSUE TITLE
Installation issues when using easy_install and python2.7

### ISSUE THREAD

**Issue by cratuki** [hylang/hy#1139]
I'm running ubuntu LTS, which has python2.7.9.

Here is a running sheet showing me creating a fresh virtualenv directory, and installing hy. And then, of a basic usage failure. http://pastebin.com/YdD4n2FH

paultag on irc speculates as follows,
16:39:25 < paultag> Here's why:
16:39:46 < paultag> cratuki: https://github.com/hylang/hy/blob/master/hy/importer.py#L181-L186
16:40:00 < paultag> cratuki: in the hy importer, the only way we put hy into sys.path is by using a PEP 302 import loader
16:40:11 < paultag> cratuki: this crawls sys.path for .hy rather than .py files
16:40:20 < paultag> of course, if the egg is there, that won't be present because it won't go into the egg
16:40:28 < paultag> as a result, I think we need to augment the loader to find the hy files

For interest: the languages.hy file is within the egg. To demonstrate this, I expand the egg file to a subdir of /tmp. See http://pastebin.com/iwzX2mJG

**Comment by Kodiologist** [comment]
I don't think there's any reason to use easy_install rather than pip.
