### ISSUE TITLE
Release new version on PyPI registry

### ISSUE THREAD

**Issue by h2non** [hylang/hy#1155]
First of all, thanks a lot for creating this project, I'm really enjoying it!

Since 0.12.0 is not ready yet, I think it worth updating PyPI registry with at least the most recent patch release since it's a bit annoying and confusing to install it from PyPI which is suppose to be stable but having syntax errors and features not supported by the compiler or API.

**Comment by Kodiologist** [comment]
The most recent patch release is what's already on PyPI. Believe me, I'm as eager to get 0.12.0 out the door as you are.

**Comment by h2non** [comment]
Cool, Thanks! Any estimated release date for 0.12.0?

**Comment by Kodiologist** [comment]
My very unofficial guess would be: about a month from now. You can follow its progress at #1140.

I'm going to close this issue, since #1126 is on the same subject.
