### ISSUE TITLE
Fix flake8 warnings regarding requiring two empty lines after class definition

### ISSUE THREAD

**Issue by tuturto** [hylang/hy#1157]
From PyCQA/pycodestyle@1477fce8dfb65fa3d31a9757a477d3b6239b2f8e

"Added check E305 for two blank lines after toplevel method and toplevel class"

Which seems to be reason Travis builds are failing.

**Comment by gilch** [comment]
Ignoring this is the easier fix and perhaps we should do that for now, but we might want to consider fixing our spacing later and enabling that check again. @Kodiologist has also pointed out that we're using the nonstandard spacing for grouping things. We could replace this with header comments.

**Comment by tuturto** [comment]
Ignoring would work too. The whitespace error isn't that major (normally I don't like ignoring errors and saying that it'll be fixed later).
