### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by abhi18av** [hylang/hy#1159]
Hey @hylang team!

As suggested on the quickstart I did `pip install git+https://github.com/hylang/hy.git` and it carries through to completion but the `hy` command on the shell still showed `command not found` error. 

So, I just used the `python setup.py install` to deal with it - however I wanted to bring this to your notice. Feel free to close the issue.

P.S. Don't freakin' give up on this one - it's the only thing keeping me from straying to `julia-lang` :P

**Comment by Kodiologist** [comment]
It seems to work for me. Can you get this to happen again if you uninstall and reinstall? Is there anything unusual about your environment? What versions of Python and pip are you using?

**Comment by abhi18av** [comment]
I'm on Ubuntu 16.04 which comes with `python3` by default - you reckon that might be the issue?

`pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5)` is what `pip -version` prints out.

But for the first question, I don't really know how to uninstall a module installed via `python setup.py install`.

**Comment by Kodiologist** [comment]
Python 3.5 should be fine.

Your pip is kind of old, so you might want to upgrade.

Check out http://stackoverflow.com/questions/1550226

**Comment by abhi18av** [comment]
Hey, @Kodiologist  I did update the pip and now it works fine. Whoops :)

Thank you for your time, I appreciate it 👍
