### ISSUE TITLE
Allow hy2py to use standard input instead of a file

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1160]
Then, at the command line, you could say

    echo '(print "hello")' | hy2py

instead of

    hy2py <(echo '(print "hello")')

The construct `<(...)` only works in Zsh, anyway.

**Comment by kirbyfan64** [comment]
```
ryan@DevPC-LX ~ $ echo '(print 123 [456] "789 ")' | hy --spy
hy 0.11.0 using CPython(default) 2.7.6 on Linux
=> print(123L, [456L], u'789 ')
123 [456L] 789 

=> ryan@DevPC-LX ~ $ 
```

**Comment by Kodiologist** [comment]
True, but that executes the code, which one doesn't always want to do.

**Comment by gilch** [comment]
>The construct `<(...)` only works in Zsh, anyway.

Bash has heredocs and herestrings
```Bash
# Herestring
hy2py <<<'(print "hello")'
# Heredoc
hy2py <<END
(print "a string" 'a-symbol)
END
```
Adding stdin seems like a fairly easy change but I'm not sure why we need it.

**Comment by Kodiologist** [comment]
Huh, I didn't realize that Bash here documents worked like files. I expected them to work like strings because that's what they do in Perl.

Anyway, I guess supporting standard input would be nice if only because that's how most Unix filter-like programs work, like the GNU versions of `cat`, `head`, and `expand`.

**Comment by gilch** [comment]
No, not like files, like streams. `hy2py` would have to accept stdin as you propose for the heredoc examples to work. Your zsh example actually does work in bash, even now.

**Comment by Kodiologist** [comment]
Oh. Huh.
