### ISSUE TITLE
Remove eg/ and hy/contrib/, or make guidelines for what belongs there

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1162]
eg/ and hy/contrib/ have a lot of miscellaneous stuff that isn't part of the core language. (I am, admittedly, part of the problem, having approved several pull requests that add to the latter.) So I'm inclined to think they shouldn't be in Hy's core repository. They represent a maintenance burden for the core development team, when they ought to live freely on their own elsewhere and get maintained by their individual authors, like ordinary Python packages. Python's package system is lightweight enough that it's not unreasonable to have a Python package with only 20 lines of content code.
 
If we think one of these directories or both should stay, we should have some guidelines as to what sort of code belongs and what doesn't. (CONTRIBUTING.rst is probably the right place to put such guidelines.) Like, right now, I have a lot of useful bits of code in my generic utility library [Kodhy](https://github.com/Kodiologist/Kodhy), like macros for indexing NumPy and pandas data structures, and I don't know which if any of these would be at home in contrib.

Some of this code might be of interest to Hy core development only for its tests. It can be helpful to have nontrivial programs in a programming language's test suite in addition to unit tests. If we take that philosophy towards any of the eg/ or hy/contrib/ code, it should perhaps be moved to test/.

**Comment by tuturto** [comment]
Eg is useful as it shows some examples of how to use the language for various tasks. We could have a wiki, blog or something else too, but then the examples would be dead in a sense that they wouldn't be tested when hy itself changes. I would like to keep the examples there and point them out in the docs if they already aren't.

contrib on the another hand might be problematic in the future as they tend to grow (at least in quite many projects I quickly checked). I have treated it as sort of experimental side of hy, where one can introduce new features that might not yet be quite there. Eventually they could be pulled into the core if we so decide (I think this hasn't happened ever happened). But definitely, we should put up a guideline what goes here and how.

**Comment by Kodiologist** [comment]
> Eg is useful as it shows some examples of how to use the language for various tasks. We could have a wiki, blog or something else too, but then the examples would be dead in a sense that they wouldn't be tested when hy itself changes.

Unless I'm missing something, they already aren't being tested. I can see that several of them haven't been updated for changes in Hy.

**Comment by tuturto** [comment]
Good catch. Eg should go then.

**Comment by Kodiologist** [comment]
@hylang/core Any other comments before I make a PR to rip these guys out?

**Comment by gilch** [comment]
`eg/` is useless if not updated for changes to Hy. It might belong in its own repository for now. I don't really want to update it until Hy has stabilized more.

`contrib/` has experimental candidates for the standard library. Perhaps some can be spun off to their own repositories, but other parts might belong in Hy's standard library. I think `contrib/` should stay for now.

We need more experience with the contrib modules to decide what parts to keep in Hy proper, and what modifications are necessary for that step.

**Comment by Kodiologist** [comment]
"Experimental candidates for the standard library" isn't a bad use for `contrib`, I guess. Let's run down the list of what's there now and see whether what should stay and what should go:

- `alias`: I don't see why you'd put this in the standard library. I guess it could be useful for when you're maintaining a library and you want to change the name of a function or macro but keep the old name around for a while so people's code doesn't break immediately. But that's a pretty limited purpose. I say remove it.

- `anaphoric`: This should be ready for inclusion in the standard library, although it should probably require a `require` rather than polluting the default namespace.

- `botsbuildbots`: Apparently a joke about the Portal 2 soundtrack (3f01ed5014). We ain't gonna need it.

- `curry`: Undocumented and of dubious value. I say remove it.

- `dispatch`: Just a utility class used by `contrib/multi`, so it should probably be moved there.

- `flow`: Not tested, and sure enough, a glance at the code suggests that `case` and `switch` will evaluate their first argument once for every clause, which is unlikely to be desirable. I say remove it, but if anybody wants to fix and test it and re-add `case` (and change it to a square-bracket syntax like `cond`), be my guest.

- `loop`: A replacement is in progress over in #1166. In the meantime, I guess it can stay in /hy/contrib.

- `meth`: This seems to be specific to a Flask, a web framework, so it should go.

- `multi`: Stay in /hy/contrib.

- `profile`: Stay.

- `sequences`: Stay.

- `walk`: Stay.

What do y'all think of that?
