### ISSUE TITLE
Should keywords be mangled?

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1168]
By "mangled", I mean having hyphens changed to underscores, `:foo?` changed to `:is_foo`, etc.

I'm inclined to say yes, because keywords are supposed to be a kind of symbol, and we mangle ordinary symbols. Currently, keywords aren't mangled.

**Comment by algernon** [comment]
We mangle ordinary symbols because of Python interop. Keywords are already a pain to interop with from Python, so mangling there does not buy us anything useful, in my opinion.

**Comment by tuturto** [comment]
For Python, keywords are just fancy strings that start with specific symbol (``\ufdd0:`` to be specific). Symbols are mangled, because ``foo?`` isn't valid name for a function for example, while ``is_foo`` is. For strings there's no such a restriction. I wouldn't mangle them.

**Comment by gilch** [comment]
```Hy
=> (defn greet [&kwonly a-name!] (print "hy" a-name!))
=> (greet :a-name! "Bob")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: greet() got an unexpected keyword argument 'a_name!'
```
Does anyone else find the above confusing? Because I think the users would find that confusing.

It is possible to call `greet`, but since keywords aren't mangled, you have to do it like this:
```Hy
=> (greet :a-name-bang "Bob")
hy Bob
```

We might want to rethink how we do mangling altogether #1173, but it's not at all obvious to me why keywords shouldn't be mangled with exactly the same rules as symbols. You create keyword arguments with symbols, but you call them with keywords!

**Comment by Kodiologist** [comment]
Why does `(dict :a-b 1)` produce `{'a_b': 1}`, anyway? Are keywords already partly mangled if they happen to be used as keyword arguments?

**Comment by Kodiologist** [comment]
And look at this disgustingness:

    hy 0.11.0+379.ged930ed using CPython(default) 3.5.2+ on Linux
    => (defn foo [a?] a?)
    def foo(is_a):
        return is_a
    => (foo :a? 3)
    foo(a?=3)
    Traceback (most recent call last):
      File "/usr/lib/python3.5/code.py", line 91, in runcode
        exec(code, self.locals)
      File "<input>", line 1, in <module>
    TypeError: foo() got an unexpected keyword argument 'a?'

**Comment by tuturto** [comment]
Indeed, had to write some rather nasty code because of this :
```
(apply helper [] (dict-comp (cond [(= (first x) :match?) "is_match"]
                                  [(= (first x) :match!) "match!"]
                                  [(= (first x) :no-match!) "no_match!"])
                            (second x)
                            [x (group funcs)])))
```
So obviously I was wrong earlier and we probably should mangle them in some cases. But should we mangle them when they're used as dictionary keys?

**Comment by gilch** [comment]
>But should we mangle them when they're used as dictionary keys?

I would argue yes, since we can apply dictionaries as keyword arguments. This is a common Python pattern. Always mangle them in any context, with exactly the same rules as for symbols.

If you don't want to give up the ability to have keyword with certain special characters, see #1117. The quotation can suppress mangling.

**Comment by kirbyfan64** [comment]
Can we collapse this into #1173? Seems to be a really similar idea.

**Comment by Kodiologist** [comment]
They seem to be orthogonal issues to me. This issue is about what gets mangled, whereas #1173 is about, given a thing to be mangled, what we do to it.

**Comment by kirbyfan64** [comment]
#1173 is also covering whether or not some mangling rules should be removed, and how Unicode characters should behave. This seems like a fitting addition.

Also, if mangling were to be changed, I would think this would all end up happening at the same time.

**Comment by Kodiologist** [comment]
Okay, you can merge them if you like.
