### ISSUE TITLE
eval doesn't use hy.models._wrappers

### ISSUE THREAD

**Issue by dangom** [hylang/hy#1174]
I came across this issue trying to narrow down a compiler error I was getting from a macro.
Why should the following piece of code throw an error?

```
=> (import numpy)


=> (= "." (get (name numpy) 0)))
False
=> (eval '(= "." (get (name numpy) 0)))
False
=> (eval `(= "." ~(get (name numpy) 0)))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/dg/anaconda3/lib/python3.5/site-packages/hy/importer.py", line 110, in hy_eval
    hytree.replace(foo)
  File "/Users/dg/anaconda3/lib/python3.5/site-packages/hy/models/list.py", line 31, in replace
    x.replace(other)
TypeError: replace() takes at least 2 arguments (1 given)
```

**Comment by tuturto** [comment]
Hm.. I don't know why would it do that from top of my head. But, I have found using ``macroexpand`` really useful when debugging macros:

> => (macroexpand `(= "." ~(get (name numpy) 0)))
> ('=' '.' 'n')

**Comment by dangom** [comment]
Thx for the quick reply. 
The expansion seems correct. I'd expect it to eval just fine...

**Comment by tuturto** [comment]
Rather interesting really. I can't seem to pinpoint why this is happening or what exactly is going on. But maybe this sheds some light into the problem:

> => (type (first `(= "." ~(get (name numpy) 0))))
> <class 'hy.models.symbol.HySymbol'>
> => (type (get `(= "." ~(get (name numpy) 0)) 1))
> <class 'hy.models.string.HyString'>
> => (type (get `(= "." ~(get (name numpy) 0)) 2))
> <class 'str'>

First two elements of the expression are in internal representation and the third one is plain string. If/why this would cause such an error message, I don't know. Not yet at least.

**Comment by dangom** [comment]
Wow, that must be it.
Casting the `str` to a `HyString` solves the issue.

```
=> (eval `(= "." ~(HyString (get (name numpy) 0))))
False
```
Wouldn't know how to fix it though. Should `str` be cast to `HyString` internally?

**Comment by tuturto** [comment]
I don't really know what would make most sense. In theory, we could have ``quasiquote`` to check for types and cast Python ones to Hy ones where needed. Have to ask if rest of the team has good ideas about this and how it should be handled. Interesting corner case in any case.

**Comment by Kodiologist** [comment]
The thing is that we have autoboxing for macro expansions, but not for `eval`. So ``(eval `~(str "a"))`` raises an error (``Exception: Unknown type: `<class 'str'>'``) but ``(defmacro m [] `~(str "a")) (m)`` works fine.

**Comment by kirbyfan64** [comment]
Maybe quoted expressions should be auto-boxed in general?

**Comment by Kodiologist** [comment]
@kirbyfan64 I'm thinking you're right. More precisely, `~` and `~@` inside backticks should recursively autobox their arguments. I can't think of a case where you wouldn't want this to happen. Note that we'll need to keep the existing autoboxing feature, too, in order for things like `(defmacro m [] (setv n (+ 1 1)) n) (print (m))` to keep working.

**Comment by edouardklein** [comment]
I'm just commenting to say that I'm affected by this too.

I'll use the explicit cast to HyString as a workaround for now.

**Comment by Kodiologist** [comment]
Come to think of it, we might as well go even further and just have the evaluator itself autobox. That would eliminate this kind of problem once and for all.

**Comment by Kodiologist** [comment]
Note the following:

    => (eval `(repr ~"a"))
    Traceback (most recent call last):
      [...]
    hy.errors.HyCompileError: Internal Compiler Bug 😱
    ⤷ Exception: Unknown type: `<class 'str'>'
    Compilation traceback:
    No traceback available. 😟
    => (eval `(repr ~[]))
    'None'

Why doesn't a list create the same error as other non-HyObjects? Because lists are treated specially by the compiler: see `compile_raw_list`, which is decorated `@builds(list)`. This seems to mean that we can't make the compiler autobox lists without replacing the usage of lists here with some other bespoke datatype.
