### ISSUE TITLE
Add some functional utilities

### ISSUE THREAD

**Issue by tuturto** [hylang/hy#1176]
- compose, used to compose two functions to one
- constant, used to define function returning constant value
- flip, used to define new function with parameter order flipped
- complement (working on understanding this still)

Originating from email exchange with Philip Xu and their excellet Hymn project (https://github.com/pyx/hymn/blob/cacac3cd3b1ddef8879e8488056a9310cd0ab13d/hymn/utils.hy#L64)

**Comment by gilch** [comment]
The threading macros take care of most of these cases I think. Though macros can be hard to use with HOF, I think they'd be more efficient.

I didn't see the complement function in the link you provided. Is it in the same file?

Can we call it `comp` to match [Clojure's naming](https://github.com/clojure/clojure/blob/010864f8ed828f8d261807b7345f1a539c5b20df/src/clj/clojure/core.clj#L2448)?

**Comment by tuturto** [comment]
complement isn't in the file, that's something @pyx mentioned in email. I asked about the details, but I think it's the same as Clojure's complement.

Following Clojure's naming convention sounds reasonable to me.

**Comment by pyx** [comment]
Thank you @tuturto, the complement function is the same as Clojure's, except we don't need to write it as multi-motheds :)

@gilch is right, those functions will be convenient to use with HOFs while in other cases, threading macros are probably more suitable. 

Please note that the constant function in Hymn generates a customized docstring on the fly from the value, but we usually do not want that happen in more general cases (e.g in stdlib), as there is no guarantee that ```.__str__``` / ```.__repr__``` / ```.__unicode__``` of the value will be pure functions.

Last but not least, let me take this opportunity to say thank you to all of you.  Hy is great, and I still remember the jaw-dropping moments when on that lighting talk, Paul showed us importing hy modules in python and stepping through hy in gdb...

**Comment by pyx** [comment]
FYI, I found out the anaphoric macro version is called ap-compose.

**Comment by gilch** [comment]
How is `filp` supposed to work in Hy? Clojure doesn't have it. I didn't see an example in Hymn either. I think in Haskell's case, flip swaps the order of the first two arguments to a function. But in Haskell, all functions are technically of one argument and it has auto-currying, while in Hy, even normally binary functions like `-` can have multiple arguments. I don't think it gets you as far in Hy. The usual way to handle this in Clojure is with `#()`, I think. (Or `xi` in Hy). But that's macros again.

**Comment by tuturto** [comment]
I was assuming that for ``flip`` we would just reverse the arguments as a whole. Maybe we should prototype it a bit with examples before implementation? Like where it would be mostly used.

**Comment by gilch** [comment]
I agree we should think about this some more.

I vaguely recall using `rotatef` in Common Lisp when I needed a flip. For a binary function it does the same thing as a reverse. It might also be more efficient than reversing the whole list. In Python3:
```Python
def flip(f):
    def flipped(*args,**kwargs):
        it = iter(args)
        return f(*it,next(it),**kwargs)
    return flipped
```
```Python
>>> flip(lambda *a: a)(1,2,3,4,5)
(2, 3, 4, 5, 1)
>>> import operator as op
>>> flip(op.sub)(3,2)
-1
```

Haskell's version (which only affects the first two arguments) may not be that unreasonable. You can sort of do currying with `functools.partial`. Forth's stack manipulation operators may also be worth looking at. One of them is `SWAP` and is essentially like Haskell's `flip`. It also has `ROT` which rotates the first three.

**Comment by pyx** [comment]
On second thought, ```flip``` in languages without auto currying (as in Haskell and ML family languages) might be of little use, as in, to partially apply the flipped function (the most general use cases of ```flip```), we need explicit function call (```functools.partial```) or lambda expression anyway, there is no saving compare to a plain old lambda in the first place.

**Comment by Kodiologist** [comment]
Point-free programming is nice in Haskell, where support for it is baked deeply into both the syntax and semantics, but in Hy I've found myself happier just using anaphoric macros and lambdas, so I don't see myself getting much use out of any of these. And `flip` seems the least useful of the four. Does anybody have an example of where it would be nice to have?

**Comment by Kodiologist** [comment]
Enthusiasm for `flip` seems low, and we have the other three now, so I'm going to close this issue.
