### ISSUE TITLE
Inconsistent behaviour between operator and shadowed version

### ISSUE THREAD

**Issue by swhalen** [hylang/hy#1191]
Certain operators have behavior inconsistent with their shadowed counterparts. For instance, see the example below using a Sympy symbol (which overloads `__lt__` and `__gt__`).

```
hy 0.11.0+367.gbc4d678 using CPython(default) 3.5.2 on Linux
=> (import sympy)
import sympy
=> sympy.__version__
sympy.__version__
'1.0'
=> (setv x (sympy.Symbol "x"))
x = sympy.Symbol('x')
=> (< 0 x 1)
(0 < x < 1)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/simon/.virtualenvs/hy-git/lib/python3.5/site-packages/sympy/core/relational.py", line 195, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
=> (setv lt <)
from hy.core.shadow import <
lt = <
=> (lt 0 x 1)
lt(0, x, 1)
And(x < 1, x > 0)
```

The reason for this is that Python expands `(0 < x < 1)` to `(0 < x) and (x < 1)`; the Sympy `Relational` class, an instance of which is created by `(0 < x)`, overrides `__bool__` and raises an error therein. On the other hand, `hy.core.shadow.comp_op` uses `operator.and_` which is `&`; as a result `(lt 0 x 1)` in the snippet above expands to something more like `(0 < x) & (x < 1)`. The behavior of `&` can be modified by overriding `__and__`, and the Sympy `Relational` class does this.

In my opinion the latter behavior (invoking the overridable `__and__`) is desirable in this case, though it may not be so in all cases. One way to resolve this would, I suppose, be to use the shadowed versions of the operators everywhere, rather than sometimes using the builtin versions.

*edited to correct a mistake*

**Comment by kirbyfan64** [comment]
TBH, this is mostly just a lose-lose scenario. :(

If we use shadow operators everywhere, that would give a really bad performance hit. Python already isn't the fastest language around, and making that worse would likely be a bad idea.

As a result, the option left would be to make the shadow operator behavior match the normal operator by using `and`.

**Comment by swhalen** [comment]
Thank you for the input. I've submitted a (trivial) PR  #1194 making the shadow operator behavior more consistent with normal operator behavior.

I would point out that unlike Python's `and`, the usage of `and` in that PR is not short-circuiting. To fix this would, I guess, require either lazy evaluation of the chained comparisons or some macrology. Multiple comparisons are also short-circuiting in Guile, but I have not checked any other Lisps/Schemes. However, the existing code in `hy.core.shadow` is not short-circuiting so I have not attempted to make this change. I am happy to update this if desired.

**Comment by gilch** [comment]
In Clojure they're not short-circuiting:
```Clojure
user=> (< 1 2 0 (print 'hi'))
hi'false
user=> (doc <)
-------------------------
clojure.core/<
([x] [x y] [x y & more])
  Returns non-nil if nums are in monotonically increasing order,
  otherwise false.
nil
user=>
```
