### ISSUE TITLE
Multi-arity defmacro

### ISSUE THREAD

**Issue by noxecane** [hylang/hy#1196]
I was trying to recreate `if-let` macro from clojure and it has multiple versions, one with a form for `then` and the other for `then` and `else`. I know it's possible to do this with `&optional` argument but that's because this is a simple use case where a single `if` statement might not look dirty compare to three versions(hence two `if`s)

```hy
(defmacro [[form test ] then &optional [else nil] &optional [others []]]
  (print "unclean spirit"))

;; compared to

(defmacro
  ([[form test] then])
  ([[form test] then else])
  ([[form test] then else others]))
```

**Comment by Kodiologist** [comment]
I've having a lot of trouble understanding your description. Are you trying to request a new feature or report a bug? If the former, how exactly should the proposed feature work? Why are your examples missing names for the new macros? Are you aware that multiple `&optional` keywords in one parameter list is currently illegal, and if so, what semantics are you proposing for them? And so on.

Please edit your issue to be more precise.

**Comment by danceasarxx** [comment]
whoah

**Comment by Kodiologist** [comment]
Yes, thank you, that's much clearer. Using a problem to motivate a feature request is fine; it's just that you have to clearly state the feature that you want, too.

Macro definitions can't use `&kwargs`, by the way.

In bleeding-edge Hy, multi-arity functions are available as a macro named `defn` in `hy.contrib.multi`. `defmulti` now provides something more like a Common Lisp generic function. So I guess the way we would get what you want is to add a macro named `defmacro` to `hy.contrib.multi` that works similarly to its `defn`.

**Comment by Kodiologist** [comment]
I forgot to mention that you can get something close to this right now by defining your macro as simply

    (defmacro m [&rest args]
      (apply f args))

and writing a multi-arity function `f` with the `defn` from `hy.contrib.multi`.

**Comment by gilch** [comment]
If we do add a multi-arity `defmacro`, we might also want to add multi-arity versions of `defmacro/g!` and `defmacro!`.

**Comment by danceasarxx** [comment]
makes sense

**Comment by allison-casey** [comment]
multiarity functions and apply are no longer part of Hy since 0.18.0, 0.14.0 respectively. Use optional parameters instead.
