### ISSUE TITLE
Remove @rwtolbert from core

### ISSUE THREAD

**Issue by rwtolbert** [hylang/hy#1197]
I really don't have time to participate, so it only makes sense to remove me from the core folks.

Good luck on keeping Hy on track and moving forward.

**Comment by tuturto** [comment]
Thanks for all the help and you're always welcome back when time is right again.

**Comment by Kodiologist** [comment]
We'll miss you!

I don't have the administrative powers needed to remove you from the GitHub team, but you can do it yourself by going to https://github.com/orgs/hylang/teams and clicking "Leave".

**Comment by berkerpeksag** [comment]
Thanks for all of your work, Robert!

We don't need to remove Robert from the GitHub team. He can always come back and add himself to `docs/coreteam.rst` again (of course, he can also always remove himself from the GitHub team)
