### ISSUE TITLE
Strange defn bug

### ISSUE THREAD

**Issue by handicraftsman** [hylang/hy#1202]
Hy input:
```clojure
(defclass Log []
  (defn write [&optional [msg "Moo"]] (
    (setv x (time.strftime "[%Y.%m.%d|%H:%M:%S] "))
    (setv y (str msg))
    (setv z (+ x y))
    (print z))))
```

Py output:
```python
class Log:
    def write(msg='Moo'):
        x = time.strftime('[%Y.%m.%d|%H:%M:%S] ')
        y = str(msg)
        z = (x + y)
        return x(y, z, print(z))
```

**Comment by kirbyfan64** [comment]
Not really a bug. There's no need to surround the body of a `defn` with parens. This works:

```hy
(defclass Log []
  (defn write [&optional [msg "Moo"]]
    (setv x (time.strftime "[%Y.%m.%d|%H:%M:%S] "))
    (setv y (str msg))
    (setv z (+ x y))
    (print z)))
```

What's happening is that parens are (usually) syntax for some kind of function call. So, here, since you surrounded the whole thing with parens, Hy sees it like this:

```hy
(  ; Function call
    (setv x (time.strftime "[%Y.%m.%d|%H:%M:%S] "))  ; This is the target
    (setv y (str msg)) ; argument #1
    (setv z (+ x y)) ; argument #2
    (print z) ; argument #3
)
```

Hy then lifts out the assignments, and you get the code you posted.

**Comment by handicraftsman** [comment]
@kirbyfan64, thanks - it works. BTW your nickname sounds familiar.

**Comment by kirbyfan64** [comment]
@handicraftsman Only other sites I visit with a similar username are Reddit and GameFAQs...

**Comment by handicraftsman** [comment]
@kirbyfan64, i am about first part of nickname - `kirby`. Isn't it nintendo game?

**Comment by kirbyfan64** [comment]
@handicraftsman [Yup!](https://en.wikipedia.org/wiki/Kirby_(series))

**Comment by handicraftsman** [comment]
@kirbyfan64, lol.
