### ISSUE TITLE
require form in hy 0.12.1 breaks with module in package

### ISSUE THREAD

**Issue by pyx** [hylang/hy#1210]
Hi, when I was porting my library to hy 0.12 with new syntax of require, I found a weird bug, qualified macro breaks when the macro is defined in a module inside a package, I setup a repository for demonstration, please checkout:  
https://github.com/pyx/hy-issue-1210
then run ```make``` for details

Actually, the bug I encountered (when porting my library hymn) is a bit different:
```
ImportError: import of 'hymn.operations' halted; None in sys.modules
```
This happened when I tried to use the trick mentioned here: http://hy.readthedocs.io/en/stable/language/api.html#require
with something like (heavily simplified), in module ```hymn.operations```
```
(defmacro some-macro-in-hymn.operations-that-expand-to-other-macro-call
`(do (require hymn.operations)
    (hymn.operations.other-macro ...))
```

I could not reproduce this out of context, but I guess these two are related.

**Comment by pyx** [comment]
Oh, I am sorry, I made a mistake when I tried to reproduce the bug I encountered with this testing repository, I should used ```(require p.m)``` instead of ```(require m)```.

I will close this now, sorry about that.

PS. I still have no clue about that `import halted` bug, I got the qualified names correct in that case.

**Comment by kirbyfan64** [comment]
Regardless of what goes wrong in your script, I'm pretty sure the second one (the "import ... halted") shouldn't be happening.

**Comment by kirbyfan64** [comment]
Actually, I'm just an idiot and ignored that you had just opened #1211...
