### ISSUE TITLE
Modules can't require themselves

### ISSUE THREAD

**Issue by pyx** [hylang/hy#1211]
With the new syntax of require and macro call with qualified name as mentioned here:
http://hy.readthedocs.io/en/stable/language/api.html#require

this will fail.
file m.hy:
```
(defmacro bar [expr]
  `(print ~expr))

(defmacro foo [expr]
  `(do (require m)
     (m.bar ~expr)))

(foo 42)
```

The error message is:
```
$ hy m.hy
...
hy.errors.HyCompileError: Internal Compiler Bug 😱
⤷ ImportError: import of 'm' halted; None in sys.modules
...
```
Notice the macro ```foo``` is being used in the same file.
Is it by design?  If so, the documentation might need to be updated with this information, and/or have better error message.

PS. issue #1210 was my failed attempt to reproduce this.

**Comment by Kodiologist** [comment]
#1134 is the bug for circular imports and self-imports. This ought to be implemented, no question, and so one might logically think the same for macros and `require`, but I'm not quite sure this makes sense: is a sensible semantics possible for circular requirement or self-requirement, given that macros change the code that's ultimately imported? I haven't thought it through.

**Comment by pyx** [comment]
@Kodiologist 
A real world scenario:
I have a script with repetitive patterns, think argparse setup code, I want to reduce boilerplate code. A locally defined/used one-off macro is a logical choice, acting like C-style macro.

FYI, I did my hy-0.12 port with macros factored out into a macro-only module, it is a good practice anyway in my use case, but still.

**Comment by Kodiologist** [comment]
I'm not asking why one would want to do it (your first example shows that pretty clearly), but how exactly one would want it to work.

**Comment by pyx** [comment]
@Kodiologist Without further investigation on how it should work, I am just feeling counter-intuitive that locally defined macros are not in the local scope (should I call it, macro namespace).

**Comment by Kodiologist** [comment]
But they are:

    $ hy -c '(defmacro m [] 5) (print (m))'
    5

The reason your code at the top crashes is not because you're calling a macro in the same file as it's defined, but that calling `foo` inside `m.hy` generates a form `(require m)`, leading `m.hy` to try to require itself. That's why I renamed this issue what I did.

**Comment by pyx** [comment]
@Kodiologist Yes, you wording is accurate, what I mean is, after the first macro expansion, the generated code is somehow not in the scope that have local macros, that's the reason we need another require form. And that macros not in that scope is what I call counter-intuitive.  Macro expansion supposed to be all turtles down :)

**Comment by Kodiologist** [comment]
> the generated code is somehow not in the scope that have local macros

But that's a pretty important property of macros, that the generated code ends up in the same scope as if you wrote it in that spot (where you called the macro, not where you defined it). That's what allows things like anaphoric macros.

**Comment by pyx** [comment]
> the generated code ends up in the same scope as if you wrote it in that spot (where you called the macro, not where you defined it).

If I understand what you mean correctly, that's also how I believe the way macro work.

In my example at the beginning of this thread, after the expansion of ```(foo 42)```, what I got should be ```(do (require m) (m.bar 42)))```, then the complier goes on to execute the do form, and require form inside, and then expand that bar macro, and on, and on.

Up until now, that's how I think lisp macro should work, but, what I mean is, the fact that we need ```(require m)```, here, it is because at that point, macro bar (lexically defined before the call site, in the same file) is undefined, that is what I call counter-intuitive.

**Comment by pyx** [comment]
To put it more clearly,

```(bar 42)``` works,
while
```(defmacro foo [e] `(bar ~e) (foo 42)``` which expends to ```(bar 42)``` at the same location does not work (undefined bar).

**Comment by Kodiologist** [comment]
No, you don't need the `(require m)` if you're calling the macro in the same file. That trick is for when you want to call the macro in a different file where `bar` isn't already in scope. This works:

     (defmacro bar [expr]
       `(print ~expr))

     (defmacro foo [expr]
       `(bar ~expr))

     (foo 42)

**Comment by pyx** [comment]
@Kodiologist oh, I am sorry, my bad, you are right, it works.

In the case that macro expansion happens in another file, it make perfect sense that other macros are not in scope without ```require```.  I forgot the reason that I added ```require``` inside macro, was I called those macros in different file, not because they are not in the scope of the same file. Thank you.

**Comment by Kodiologist** [comment]
No problem. I think macros are hard and I haven't even looked at how Hy implements them yet.

**Comment by kirbyfan64** [comment]
Closing as a dup of #1134.

**Comment by Kodiologist** [comment]
It's not obvious to me that getting circular imports to work will suffice to get circular requires to work.
