### ISSUE TITLE
xor does not return false if None as param

### ISSUE THREAD

**Issue by madhat2r** [hylang/hy#1214]
(xor False None) does not return anything, when I think it should return false.

**Comment by Kodiologist** [comment]
To be precise, it returns `None`, which is the second argument. I believe this is the correct behavior; remember that `None` is false in Boolean context. So it does return false; it just doesn't return `False`. This is the same thing that `or` does.

**Comment by madhat2r** [comment]
I guess you are correct @Kodiologist . I was just reading the docs and it says:

`xor is used in logical expressions to perform exclusive or. It takes two parameters. It returns True if only of the parameters is True. In all other cases False is returned. `

So I took that to mean that it letteraly retunred false in all other cases. But I can agree, it probabbly won't matter much. ;)

**Comment by Kodiologist** [comment]
Well, no wonder you were confused; the documentation is just plain wrong. I'll make a pull request.

**Comment by Kodiologist** [comment]
While I'm at it, let's make `xor` return the true argument instead of `True`, for consistency.

**Comment by Kodiologist** [comment]
Done in #1215.
