### ISSUE TITLE
Drop support for Python 2

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1217]
This is something that's been brought up many times but has no dedicated issue. Even if we don't want to do this soon, we might want to put it on a milestone or something.

Dropping Python 2 would let us clean up the codebase a lot and make it easier to support Python 3's new features.

If there's anybody who uses Hy on Python 2 and really can't upgrade, at least until another library adds Python 3 support, you should say that here and mention what you're waiting for. We have no idea how many of you exist.

**Comment by kirbyfan64** [comment]
Eh... I'd say Python 2 is still used widely enough to make this harder to justify.

We should probably make it clear which ones exactly we're supporting, though. Didn't we drop 2.6 at some point.

**Comment by gilch** [comment]
https://pythonclock.org/

Python 2 support officially ends in 2020. It's open source, so others might continue to support a fork (Red Hat, in particular, has some long-term service obligations out to 2027, but only to paying customers on Linux), but I don't think Hy has any need or obligation to support Python 2 past this date. I think we should remove Hy's Python 2 support by that date.

The only reason I'd like to continue supporting Python 2 now is to get Hy on more platforms. Jython, in particular hasn't released a version 3 yet. Jython support would open up Hy to most of the Java ecosystem, except, perhaps, Android, which uses an incompatible Java VM.

**Comment by Kodiologist** [comment]
If we release semi-annually, which I'd like to do, then we could drop Python 2 in mid-2019 or in early 2020. That sounds reasonable to me, although I hope we hit Hy 1.0 before then, so we might need to make that release Hy 2.0.

**Comment by berkerpeksag** [comment]
+1 for dropping Python 2 support *now*. Note that some super popular Python projects like Django and Gunicorn will drop Python 2 in their next major release this year. I think we can be more aggressive since we have much smaller user base than these projects :)

**Comment by davidkallie** [comment]
I am in favor of keeping support until 2020. I just ported hy to the FreeBSD ports tree, and python3 is not default. I think keeping in tune with support of Python 2 is reasonable and makes sense, as @glich mentions keeping compatibility ensures more exposure, which increases the chances of more users.

**Comment by Rogof** [comment]
In my case, I'm working on a Standalone QGIS application. QGIS only supports Python 2 for now and while the next mayor version will support Python 3, it seems it won't be ready any time soon.

So I really would like for python 2 to be supported for a while.

**Comment by Kodiologist** [comment]
It looks like this won't be happening soon, despite some support. So I'll close this.

**Comment by Kodiologist** [comment]
The Python people will officially end Python 2 support in 2020. So, presuming we'll continue our practice of making two Hy releases a year, one around the middle of the year and one around January, the last Hy release with Python 2 support can be in mid-2019, and we can start removing it immediately after.
