### ISSUE TITLE
Requiring PR reviews and CI pass before merge?

### ISSUE THREAD

**Issue by kirbyfan64** [hylang/hy#1222]
https://help.github.com/articles/about-required-reviews-for-pull-requests/
https://help.github.com/articles/about-required-status-checks/

We require it anyway, might as well enable it in GitHub, too...

@hylang/core ?

**Comment by Kodiologist** [comment]
Requiring a review seems fine. Requiring a checkmark from Travis is a Bad Idea because Travis gets confused sometimes.

**Comment by kirbyfan64** [comment]
@Kodiologist True...

**Comment by kirbyfan64** [comment]
Done.
