### ISSUE TITLE
Policy for copyright and license notices at the start of each file

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1225]
[GNU recommends these](https://www.gnu.org/licenses/gpl-howto.html) when you're using the GPL. However, I doubt they're necessary (we have a LICENSE file), and they add a lot of noise to files, especially small files. In any case, if we decide they should stay, they should probably be in every file, and we need a policy for exactly which people and years get credited in each file, whereas right now they're inconsistent.

- Thumbs-up this issue if you think the notices should be removed.
- Thumbs-down this issue if you think they should stay and be used consistently.

@paultag, could you provide your input?

**Comment by Kodiologist** [comment]
Also, @paultag, the LICENSE refers to "The above copyright notice", but there is no copyright notice. I think d206e327a92250616970410cf90184ce4f97c36b was a mistake.

**Comment by paultag** [comment]
I think they need to stay and not move. I'd be fine with the `LICENSE` file, but the header should stay.

Is there an actual reason or "It's kinda annoying sometimes when I look at a file"?

**Comment by Kodiologist** [comment]
It's kinda annoying sometimes when I look at a file. And, like I said, we'd a policy for exactly which people and years get credited in each file, whereas right now they're inconsistent. And we'd need to add a header to all the files that are missing one.

**Comment by kirbyfan64** [comment]
I'd personally stick with the headers. Maybe just shove "The Hy developers" as the copyright owner?

(FWIW, though, the MIT license has little legal bearing...but I still would prefer leaving it there, just in case. Legal matters are confusing, and every little bit can help.)

**Comment by Kodiologist** [comment]
I'm pretty sure the MIT license is enforceable, since the FSF's lawyers has no objections to it; I'm just talking about the headers.

I don't think "the Hy developers" are legally the copyright holders. With nobody having signed any copyright assignments, everybody probably still holds individual copyright on their individual contributions, as on Wikipedia.

**Comment by Kodiologist** [comment]
[Here](https://www.gnu.org/licenses/license-list.en.html#Expat) is GNU's description of the license, which they call the Expat license.

**Comment by Kodiologist** [comment]
Consensus seems to be to keep the headers, but now y'all have to decide on a policy for what files should have them, who should be named as the copyright holders, and what the copyright years should be.

**Comment by Kodiologist** [comment]
Nobody wants to bell the cat, eh? All right, I'll make a proposal. Every Git-tracked file that is conceivably copyrightable (i.e., has more than 10 lines of non-boilerplate code; if in doubt, consider it copyrightable) should have the following header:

    # Copyright 2017 the authors.
    # This file is part of Hy, which is free software. See the LICENSE.

with the copyright year for all files bumped after each new year, and the comment syntax altered as necessary.

What do you think of that?

**Comment by kirbyfan64** [comment]
> Copyright 2017 the authors.

Maybe "the Hy authors" would make a bit more sense?

> This file is part of Hy, which is free software.

I think it could be:

> This file is part of Hy, which is free software licensed under the MIT Expat license.

+1 to the idea, though!

**Comment by Kodiologist** [comment]
The reason I'm inclined to write "the authors" instead of "the Hy authors" is because it's not authorship of Hy in some general sense that confers copyright but authorship of the particular additions and changes to that file or its ancestors.

Naming the license is a good idea, although we should probably call it just "the Expat license" rather than "the MIT Expat license".

**Comment by kirbyfan64** [comment]
> The reason I'm inclined to write "the authors" instead of "the Hy authors" is because it's not authorship of Hy in some general sense that confers copyright but authorship of the particular additions and changes to that file or its ancestors.

How about then *the authors of this file*? The grammar nerd in me just keeps screaming "AMBIGUOUS PRONOUN"...

> Naming the license is a good idea, although we should probably call it just "the Expat license" rather than "the MIT Expat license".

Reason for that was that a lot of people know of it as just the "MIT license", though I guess it wouldn't be a big deal...

**Comment by Kodiologist** [comment]
Even then, the copyright applies to each author's individual contribution to the file rather than the whole file.

I got the idea of just attributing copyright to "the authors" from a scientific journal that did it, although now I can't remember which journal it was.

"The authors" isn't a pronoun. learn2grammarnerd, pleb. :P

**Comment by kirbyfan64** [comment]
> "The authors" isn't a pronoun. learn2grammarnerd, pleb. :P

Note to self: try to avoid writing GitHub messages when sleep deprived and mindlessly roaming the mall...
