### ISSUE TITLE
Removing u""

### ISSUE THREAD

**Issue by refi64** [hylang/hy#1227]
After looking through #1226, I realized the `u` prefix is discarded. Why is this even allowed? Seems like it'd be potential cause for confusion for a Hy newbie. IMO, it would be better if it printed an error saying that all Hy strings are already Unicode.

Thoughts?

**Comment by Kodiologist** [comment]
It is admittedly pretty pointless. Probably the reason it's implemented is just that Python 3 allows it. So keeping it increases Python 3 compatibility, sort of.

The relevant bit in Python 3's language reference is "As of Python 3.3 it is possible again to prefix string literals with a `u` prefix to simplify maintenance of dual 2.x and 3.x codebases."

**Comment by Kodiologist** [comment]
With the death of Python 2, this seems very reasonable.
