### ISSUE TITLE
document eval-when-compile and eval-and-compile

### ISSUE THREAD

**Issue by tuturto** [hylang/hy#1229]
These two have empty entries in docs. Fill them in and maybe explain where they are useful.

**Comment by gilch** [comment]
The names seem to have been taken from emacs lisp. Here's the doc for that.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Eval-During-Compile.html

They don't seem quite the same in Hy though. Maybe we could fix that.

They appeared with #187 by @khinsen, and the implementation is in the [compiler](https://github.com/hylang/hy/blob/db210929d0d74d38232eef1a3cfaf81fc6508087/hy/compiler.py#L2128), like you'd expect.

There are some tests showing what they can do, in [tests/native_tests/native_macros.hy](https://github.com/hylang/hy/blob/master/tests/native_tests/native_macros.hy)
