### ISSUE TITLE
reduce not available in shadow functions after compilation

### ISSUE THREAD

**Issue by Zabolekar** [hylang/hy#1233]
Lets consider the following file `test_shadow.hy`:

    (defn f [g] (g 1 2))
    (f +)

If we execute it directly, everything is well:

    > hy test_shadow.hy
    3

If we, however, compile it first, we get an error:

    > hyc test_shadow.hy
    > python test_shadow.pyc
    Traceback (most recent call last):
      File "reproduce_bug.hy", line 2, in <module>
        (print (f +))
      File "reproduce_bug.hy", line 1, in f
        (defn f [g] (g 1 2))
      File "C:\Users\zabolekar\AppData\Local\Programs\Python\Python36\lib\site-packages/hy/core/shadow.hy", line 34, in +
        (reduce operator.add args)
     NameError: name 'reduce' is not defined

The problem disappeared (without a need to recompile the pyc file) after I added the following code at the beginning of `/hy/core/shadow.hy`:

    (import functools)
    (def reduce
      (if-python2 reduce functools.reduce))

However, I do not understand the codebase fully and am not sure whether submitting a fix like that is a good idea.

**Comment by Kodiologist** [comment]
Hmm, sounds like I might've created a bug with #1221. But are you sure that you're using the same version of Python in both cases?

**Comment by Kodiologist** [comment]
For that matter, what's your Hy version?

**Comment by Zabolekar** [comment]
My Hy version is 0.12.1+24.g45b7a4a

I am reasonably sure that it is the same version of Python in both cases. If I add

    (import sys)
    (print sys.__version__)

at the beginning, it prints `3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]` in both cases.

**Comment by Kodiologist** [comment]
I can reproduce this. Looks like `hy.core.shadow` tries to use `reduce` from `hy.core.language` even though the compiler doesn't call `load_stdlib()` for files in `hy.core`. And usually, for some reason, this works, even though it shouldn't. Gross.

**Comment by kirbyfan64** [comment]
FWIW this also wasn't caused by #1221...

**Comment by kirbyfan64** [comment]
AHA!!

When you run the code using `hy`, Hy compiles it by instantiating a `HyASTCompiler` for the module `__main__`. During the initialization, `load_stdlib` is called. This means that, by the time `hy.core.shadow` is loaded, the entire stdlib is already loaded, and the `reduce` import is added.

However, when `hyc` is used and the code is then run using Python, the no `HyASTCompiler` is instantiated for any non-core modules. Therefore, when `hy.core.shadow` is loaded, the stdlib dict is empty.

Ideas for solutions:

- Add an extra check to `compiler.py` when compiling symbols that will never import them in a `hy.core` module, and update `hy.core.shadow` to manually import `reduce`.
- Allow `hy.core` modules to use auto-imports. This can make room for circular import errors, but they'd be pretty obvious to fix the second they came up. `hy.core.shadow` would remain untouched.

Both of these would be pretty simple fixes. Thoughts? @hylang/core

**Comment by Kodiologist** [comment]
I think the second idea is fine, assuming it's possible without big changes—I'm not 100% sure it is.

**Comment by kirbyfan64** [comment]
Anyone else? Right now I'm supporting option 1, and @Kodiologist is supporting option 2, so we need a tie breaker!! :D

**Comment by Kodiologist** [comment]
I think option 1 is perfectly acceptable, too.

**Comment by Kodiologist** [comment]
I can no longer reproduce this bug. I probably fixed it by accident as part of #1269.
