### ISSUE TITLE
the f"" prefix is not supported (python3.6)

### ISSUE THREAD

**Issue by philiparvidsson** [hylang/hy#1239]
if the backend is python 3.6, the f prefix for strings should be supported. see [this](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498) for more information.

example:

```
>>> name = "Fred"
>>> f"He said his name is {name}."
'He said his name is Fred.'
>>> width = 10
>>> precision = 4
>>> value = decimal.Decimal("12.34567")
>>> f"result: {value:{width}.{precision}}"  # nested fields
'result:      12.35'
```

```hy
(setv my-var "hello world")
(print f"my-var contains: {my-var}")
```

**Comment by kirbyfan64** [comment]
It would really be nice if Hy supported this other Python versions, too...it seems like it wouldn't he too hard to compile...

**Comment by Kodiologist** [comment]
It seems that the replacement can be most any Python expression (possibly followed by format specifiers):

    >>> f"{(lambda p: p + 'b')('a') if 1 else 2 !r:5}"
    "'ab' "

For Hy, It would perhaps make more sense to allow a Hy expression instead of a Python expression.

**Comment by philiparvidsson** [comment]
yes, we definitely want to allow hy expressions:

```
(setv a 3 b 3)
(print f"the sum of {a} and {b} is {(+ a b)}")
```

I think we have the advantage of being to bring this feature back to python 2.7 (by generating old code), ie:

```
a = 2
b = 3
print "the sum of {} and {} is {}".format(a, b, a + b)
```

it's very close to the code that needs to be generated for python 3.6:

```
a = 2
b = 2
print(f"the sum of {a} and {b} is {a + b}")
```

that is, we just insert the generated code in the {} in the string and replace the .format call with an f prefix.

**Comment by gilch** [comment]
The main advantage of f-strings seems to be the format specifiers. I'm not sure how that should look in Hy. If you don't need that part,  you can get pretty close with a `map` and `join`.
```Hy
=> (setv a 2  b 3)
a = 2
b = 3
(a, b)
(2, 3)
=> (defn f [&rest xs] (.join "" (map str xs)))
from hy.core.language import map

def f(*xs):
    return ''.join(map(str, xs))
=> (f "the sum of "a" and "b" is "(+ a b))
f('the sum of ', a, ' and ', b, ' is ', (a + b))
'the sum of 2 and 3 is 5'
```
It doesn't look quite as nice in the Python translation, but HyExpressions don't use comma separators.

**Comment by Kodiologist** [comment]
I figured that `f"{1 + 1 !r:5}"` would be written in Hy as `f"{(+ 1 1) !r:5}"` or something.

**Comment by kirbyfan64** [comment]
FWIW I've started work in this, but it'll be a while before it's done...

**Comment by Kodiologist** [comment]
@kirbyfan64 You might try implementing only forms like `{foo !r:5}` first, where the expression has to be an identifier, since that could be easier to implement but will cover most uses.

**Comment by Kodiologist** [comment]
It occurs to me that you could get the same effect on any version of Python with a pretty simple macro:

    (deftag f [string-literal]
      (import re)
      (setv exprs [])
      (defn repl-fn [m]
        (.append exprs (read-str (.group m "expr")))
        (+ "{" (or (.group m "suffix") "") "}"))
      (setv string-literal (re.sub :flags re.VERBOSE
        r"\{
          (?P<expr> [^}!:]+?)
          (?P<suffix> [!:] [^}]+)?
          \}"
        repl-fn
        string-literal))
      `(.format ~string-literal ~@exprs))

    (setv a 3   b 2000)
    (print #f"The sum of {a} and {b} is {(+ a b):,}.")

It would take work to make this permit things like nested fields and backslash-escaped `:`s and `!`s, but it could probably be done.

**Comment by philiparvidsson** [comment]
I usually use `def` for constants and `setv` for variables. Could we change `def` to prevent further assignments? Absolutely breaking change but we're still pretty early.
