### ISSUE TITLE
reader macro docs - clarify interface

### ISSUE THREAD

**Issue by tuturto** [hylang/hy#1240]
- how many parameters reader macros can handle (should be one, but are there any exceptions)?
- using for expressions and literals
  - #X1
  - #X(foo bar baz)

Docs are available online at: http://docs.hylang.org/en/latest/language/readermacros.html
Code is at: https://github.com/hylang/hy/blob/master/docs/language/readermacros.rst

**Comment by Kodiologist** [comment]
I would encourage attending to  #1230 first.
