### ISSUE TITLE
Missing Commandline Args under Windows

### ISSUE THREAD

**Issue by massmy** [hylang/hy#1251]
I've noticed that the following Script produces different results depending how its called via console.
```
#! /usr/bin/env hy
(import [sys [argv]])
(print argv)
```

hy cmdArgsTest.hy Test
   output: ['cmdArgsTest.hy', 'Test']

cmdArgsTest.hy Test
   output:['H:\\cmdArgsTest.hy']

Enviroment:
hy 0.12.1
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.14393 N/A Build 14393

**Comment by Kodiologist** [comment]
This issue indeed seems to be Windows-specific, or at least, I can't replicate it on Linux.

I have a hunch that #459 is related.

**Comment by kirbyfan64** [comment]
First thing: how does the second command actually work? IIRC Hy doesn't register any file extensions under Windows...? Hashbangs flat-out don't do anything under Windows.

Also, are you *sure* this isn't a side effect of however you did the first question?

**Comment by massmy** [comment]
Well, did set the hy.exe as standard executable for the file extension over the normal windows dialog.

**Comment by kirbyfan64** [comment]
@massmy Try running:

```
ftype Hy=hy.exe "%1" "%*"
assoc .hy=Hy
```

and then try again.

**Comment by massmy** [comment]
@kirbyfan64 It worked kind of
the assoc command did not work as expected.
I had to manually set the registry key from "hy_auto_file" to "Hy" under HKEY_CLASSES_ROOT\.hy

**Comment by kirbyfan64** [comment]
(FWIW maybe Hy on Windows should have a script to install this?)

**Comment by goyalyashpal** [comment]
> hy.exe
\- @ massmy at https://github.com/hylang/hy/issues/1251#issuecomment-285897182

hey @massmy , can u check and update if you are still able to find the `hy.exe` on your system? as i am on windows 10 python 3.11.2 and despite `pip install hy` or `pip install hy --user` - i can't find `hy.exe` anywhere on my system
