### ISSUE TITLE
numeric literals on print functions - (print 100,000) 

### ISSUE THREAD

**Issue by youngsu999** [hylang/hy#1254]
I'm a fan of hy. On the Document, [Hy (the language)](http://docs.hylang.org/en/latest/language/api.html), I see the numeric literals with comma and under bar.

> Underscores and commas can appear anywhere in a numeric literal. They have no effect on the value of the literal, but they’re useful for visually separating digits.

```python
(print 10,000,000,000 10_000_000_000)
```

And I tested the code and I got following result.

```python
=> (print 100,0)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name '100,0' is not defined
=> (print 100_0)
1000
```

I'm using ```hy 0.12.1 using CPython(default) 3.6.0 on Windows```.
Is it a bug? or is the document does not match to the current hy version?

**Comment by Kodiologist** [comment]
> or is the document does not match to the current hy version?

Yep. See #1198.
