### ISSUE TITLE
A strange operation for "as->" macro.

### ISSUE THREAD

**Issue by youngsu999** [hylang/hy#1255]
In the document for [as->](http://docs.hylang.org/en/latest/language/api.html#as), the example code expected following output. 

```hy
=> (as-> 0 it
...      (inc it)
...      (inc it))
2
```

However, I got the following result.

```hy
=> (as-> 0 it
... (inc it)
... (inc it))
(2, 2, 2)
=>
```

**Comment by Kodiologist** [comment]
This bug still exists in master but is fixed by pull request #1246. I'm hoping that will be merged soon.

**Comment by kirbyfan64** [comment]
@Kodiologist Wrong PR #? The issue here is that the docs are showing a single integer as the return value instead of a tuple, which doesn't really have much to do with your REPL PR...

**Comment by Kodiologist** [comment]
@kirbyfan64 No, that's the right PR. Try it. Apparently, the bug was fixed as a consequence of how I changed the internals of HyREPL.
