### ISSUE TITLE
Official support for evaluating strings of Hy code from Python

### ISSUE THREAD

**Issue by didibus** [hylang/hy#1256]
Is it possible to embed some hy code inside a python file? As opposed to having the whole file be full on hy?

**Comment by Kodiologist** [comment]
I first read this issue as being about embedding Python code in Hy (which is something that's been mentioned and I'd like to see, but I don't know if we have an issue for it), but now I see you're talking about the reverse. Well, we can't alter Python's syntax, so true embedded Hy in Python is out of the question. But you can put your Hy code in a string literal, and then use some of Hy's internal functions to read and evaluate it:

    >>> from hy.lex import tokenize; from hy.importer import hy_eval; hy_eval(tokenize("(+ 1 1)")[0], globals(), "__cmdline__")
    2

One might reasonably expect documented, public functions for this.

**Comment by Kodiologist** [comment]
I'd recommend providing separate functions for reading (i.e., turning a string into a HyModel) and evaluating a HyModel.

**Comment by jdanford** [comment]
Alright, would you rather the reading function be called `read` or `parse`?

**Comment by Kodiologist** [comment]
I think you should be able to export `read_str` or `read` (or both) from `hy.core.language`, in which case you should use the same name.

**Comment by jdanford** [comment]
Oh gotcha, your original example used `hy.lex.tokenize` so I thought I had to wrap that! So this is just a matter of exporting `read`, `read_str`, and `hy_eval`?

**Comment by Kodiologist** [comment]
Yes, if it doesn't lead to some kind of circular-dependency issue. Try it out.
