### ISSUE TITLE
`require` doesn't compile to anything, which interacts badly with bytecode

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1268]
Here's an example with Python 2. If you have a Hy program `foo.hy` like this:

    (require [hy.extra.anaphoric [ap-if]])
    (print (eval '(ap-if (+ "a" "b") (+ it "c"))))

then `hy foo.hy` works fine and prints `"abc"`. But if you say `hyc foo.hy` and then `python foo.pyc`, you get `NameError: name 'ap_if' is not defined`.

Here's why this happens. Currently, `require` doesn't contribute anything to the AST: its compilation method returns an empty `Result`. So `foo.pyc` ends up containing the same thing as if you compiled just `(print (eval '(ap-if (+ "a" "b") (+ it "c"))))`. The only reason `hy foo.hy` works is that the macros that Hy loaded during compile-time are still hanging around during run-time when we get to the `eval`.

The most obvious solution to this is to make `require` forms produce a piece of AST that does the same thing at run-time that the form does at compile time, namely, load the requested macros. The annoying thing about this approach is that it would give byte-compiled modules a dependency that they won't need unless they use a macro inside an `eval`, which is not something that most programs will do. That makes me think we should do the opposite, and prevent `(eval '(some-imported-macro ...))` from working at all. Then, if you want to use an imported macro in an `eval`, you'll need a corresponding `require` form in there, too.

**Comment by kirbyfan64** [comment]
As a side note, I'm starting the get the vibe that we need some tests specifically for hyc. This is around the third issue we've had recently involving something that either doesn't work or is just plain broken.

**Comment by Kodiologist** [comment]
We have some in `test_bin.hy`, but they're not much. However, I'm soon going to submit a PR to make Hy read and write bytecode automatically, which will make bytecode issues much more visible in general.

**Comment by brandonwillard** [comment]
I have a mostly work implementation of something like this here: https://github.com/brandonwillard/hy/blob/macro-changes/hy/compiler.py#L1197

I'll put in a PR when I get all the tests passing again (only a few to go, though).
