### ISSUE TITLE
Drop support for Python 3.3

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1270]
It was released in 2014, and we're already supporting three other minor versions of Python 3 (namely 3.4, 3.5, and 3.6; we really should be testing 3.7-dev, too).

**Comment by kirbyfan64** [comment]
Why? 3.3's not nearly that old, and it's the only version PyPy has support until very, *very* recently.

**Comment by Kodiologist** [comment]
> Why?

To reduce the sheer number of things we have to test and work around. Speaking of which, we still have a bunch of `if PY33:…` bits although we're not testing Pythons 3 younger than 3.3.

We're not testing PyPy 3 at all at the moment, only PyPy 2.

**Comment by Kodiologist** [comment]
According to [this table](https://docs.python.org/devguide/#status-of-python-branches), 3.3 will be officially retired this September. I'll make a note on my calendar and close this issue, since no action is currently required.

**Comment by gilch** [comment]
#1401
