### ISSUE TITLE
Drop support for Python 2.6

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1271]
It was released in 2008, so it's almost 10 years old. Also, we don't test it.

**Comment by kirbyfan64** [comment]
Yeah, this I can stand behind. Pretty sure it also reached its EOL already...

IIRC there was actually a semi-decision by @paultag to drop Py2.6 support, but it was never actually...done...

**Comment by Ealhad** [comment]
https://www.python.org/download/releases/2.6.9/

> With the 2.6.9 release, and five years after its first release, **the Python 2.6 series is now officially retired**. All official maintenance for Python 2.6, including security patches, has ended. For ongoing maintenance releases, please see the Python 2.7 series. The NEWS file lists every change in each alpha, beta, release candidate, and final release of Python 2.6.

I guess it's alright.
