### ISSUE TITLE
How do you pronounce `.`, the attribute access DSL (or any other symbol for that matter)?

### ISSUE THREAD

**Issue by yuvallanger** [hylang/hy#1274]
Is it pronounced "attribute access DSL" [1]?

Could you add a pronunciation guide to each of the symbols?

[1]: <https://github.com/hylang/hy/blob/18acfe6495e83dccc9c0f3ddf105dc7ccef5a86a/docs/language/api.rst#built-ins>

**Comment by kirbyfan64** [comment]
Usually I just call it "attribute dot thingy" or something...

**Comment by Kodiologist** [comment]
An interesting question. For Hy, as for many programming languages, nearly all the important communication occurs in writing, so there's no natural tendency to come to an agreement about pronunciation.

**Comment by Kodiologist** [comment]
In any case, this doesn't seem to really be in scope for Hy's documentation, so I should close this issue.
