### ISSUE TITLE
Crash with broken macro: AttributeError: 'HyExpression' object has no attribute 'start_line'

### ISSUE THREAD

**Issue by hrehfeld** [hylang/hy#1278]
https://gist.github.com/hrehfeld/075ea02c5bd9de157d7f12fc698755c4

**Comment by Kodiologist** [comment]
This seems to be a duplicate of #818.

**Comment by hrehfeld** [comment]
Ah, sorry!

**Comment by Kodiologist** [comment]
No problem; finding duplicates is often difficult.
