### ISSUE TITLE
First-class builtins

### ISSUE THREAD

**Issue by algernon** [hylang/hy#130]
While porting code to Hy, I often had the desire to pass built-in functions to other functions, like partial, or map:

``` clojure
(map (partial get collection) indexes)
(map first [[1 2 3] [2 3 4] [3 4 5]])
```

However, builtins are not first class in the sense that I can't do the above:

```
=> (map first [[1 2 3] [2 3 4] [4 5 6]])
Traceback (most recent call last):
 File "<console>", line 1, in <module>
NameError: name 'first' is not defined
```

It would be great if builtins would be proper functions within Hy too. I suppose the `builds` decorator could be further enhanced to export a wrapper or something (and possibly have both `builds` and `buildfn` or something, as not everything `builds` handles should be exported this way).

**Comment by Kodiologist** [comment]
I'm going to close this in favor of #1103, since that's presumably the way forward.
