### ISSUE TITLE
REPL history is lost on (quit)

### ISSUE THREAD

**Issue by asimjalis** [hylang/hy#1302]
REPL history is not flushed to disk if the REPL is exited using `(quit)`. 

A workaround is to remember to use `CTRL-D` to exit the REPL.

Would be nice if `(quit)` also worked.

**Comment by Kodiologist** [comment]
Confirmed. Thanks for reporting.

**Comment by asimjalis** [comment]
Here is a fix that works if I paste it into the REPL. This should probably be done in Python in the hy history code.

```
(import atexit readline os)
(def hist-file (os.path.expanduser "~/.hy-history"))
(-> hist-file (open "a") (.close))
(atexit.register readline.write_history_file hist-file)
```

**Comment by Kodiologist** [comment]
That sounds like it could be the start of a great first PR, if you'd like to get involved in Hy.
