### ISSUE TITLE
Feature Request => A better repl.

### ISSUE THREAD

**Issue by abhi18av** [hylang/hy#1319]
Hi hy-lang team:)

This little language is like a dream, thanks :+1: 

I dabble in `clojure`, `python` and `clojurescript` a lot and the repls are often of the highest quality like `ptpython` and `bpython`. So, I thought that there are more features that could be added to the `hy` repl to make it more friendlier, like 

- Colored Input / Output
- Better Code completion
- `doc` and `find-doc` family of functions

And mostly just things which aid a generic `code and play` experience.

I'm really looking forward to the progress made by `hy`, it's making python fun again :)

**Comment by kirbyfan64** [comment]
Hey there!

This was already being discussed in #324, and it ended up being closed as out-of-scope for this project. There's a bphython, but it hasn't been updated in a long time and has gotten out-of-sync with both vanilla bpython and Hy itself (FWIW I have an unfinished, updated version that actually works, but it's...errr...unfinished).

That being said, does `doc` not work for you? *That* might be a bug.

**Comment by abhi18av** [comment]
Ah, I see. Well, I was unaware of that. Feel free to close the request :)


Regarding, `doc`, here I try it with
- apply
- reduce
- eval

```clojure

➜  ~ hy
hy 0.13.0 using CPython(default) 3.5.1+ on Linux
=> (doc apply)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/hy/cmdline.py", line 102, in runsource
    ast_callback)
  File "/usr/local/lib/python3.5/dist-packages/hy/importer.py", line 176, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'doc' is not defined
=> (doc reduce)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/hy/cmdline.py", line 102, in runsource
    ast_callback)
  File "/usr/local/lib/python3.5/dist-packages/hy/importer.py", line 176, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'doc' is not defined
=> (doc eval)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/hy/cmdline.py", line 102, in runsource
    ast_callback)
  File "/usr/local/lib/python3.5/dist-packages/hy/importer.py", line 176, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'doc' is not defined
=> 
```

Neither does it show up in the `code-completions`

```clojure
=> do
do    doto  
=> do

```

**Comment by abhi18av** [comment]
@kirbyfan64 , I saw more `hy` libs in your profile and I've started this project `awesome-hy`. 

Please do fork and add to them!

**Comment by Kodiologist** [comment]
There is no function, macro, or special form named `doc`. Perhaps Kirby was thinking of `help`.

For what it's worth, I use Emacs's Inferior Lisp mode as a REPL. It's nice.

**Comment by kirbyfan64** [comment]
Uh, yeah, I was thinking of `help`...
