### ISSUE TITLE
`with` suppressing an exception can break temporary variable management

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1320]
Consider:

    (defclass E [] []
      (defn __enter__ [self])
      (defn __exit__ [self exc-type exc-value traceback]
        True)) ; Prevent the exception from being propagated

    (defn f []
      (with [(E)]
        (/ 1 0)))

    (f)

This crashes with `UnboundLocalError: local variable '_hy_anon_var_1' referenced before assignment.`, because it compiles to:

    class E:

        def __enter__(self):
            pass

        def __exit__(self, exc_type, exc_value, traceback):
            return True

    def f():
        with E():
            _hy_anon_var_1 = (1 / 0)
        return _hy_anon_var_1
    f()

The exception breaks out of the `with` statement before `_hy_anon_var_1` is assigned, but we still try to `return _hy_anon_var_1`.

**Comment by Kodiologist** [comment]
Probably the right solution to this is to define `with` as returning `None` when it's jumped out of with an exception, which can be implemented by putting `_hy_anon_var_[N] = None` before the `with` statement.

**Comment by tuturto** [comment]
returning ``None`` sounds like a reasonable approach
