### ISSUE TITLE
string.format seems to be broken

### ISSUE THREAD

**Issue by spiderbit** [hylang/hy#1330]
```
(defn test (words)
  (.format "{0} {0}" words))

(test (, "hello" "world"))

```
expected result:
u'hello hello'

result:
u"(u'hello', u'world') (u'hello', u'world')"

also if I use a list instead of a tuple and try to convert to a tuple with
*words
it says it dont know it and (* words) is of course the multiplier.

**Comment by Kodiologist** [comment]
That's how the method works in Python, too:

    >>> '{0} {0}'.format(('hello', 'world'))
    "('hello', 'world') ('hello', 'world')"

Perhaps you mean `(apply .format (+ (, "{0} {0}") words))` (or, with Hy master, `(.format "{0} {0}" #* words)`).

**Comment by gilch** [comment]
@spiderbit 
Protip: try running the repl with the `--spy` option. You'll get an approximate Python translation.
```Python
=> (defn test (words)
... (.format "{0} {0}" words))
def test(words):
    return '{0} {0}'.format(words)
None
=> (test (, "hello" "world"))
test(('hello', 'world'))
"('hello', 'world') ('hello', 'world')"
```

**Comment by spiderbit** [comment]
ok thanks for clearification. the hy master thing makes sense, the other suggestion I don't get. So basicly that problem is fixed in hy master and there is a workaround for older versions.

I thought *words transforms it to a tuple, and I thought I created a tuple with (, "hello" "world) in fact type gave me even type tuple.

So * dont is a shortcut for (tuple x)

Sorry for wasting your time then :D

**Comment by Kodiologist** [comment]
In Hy, `*words` is a just a variable whose name begins with an asterisk. But `(, "hello" "world")` is indeed a tuple.
