### ISSUE TITLE
Calling a tag macro whose name starts with `!` is lexed as a shebang line

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1334]
=> (deftag !a [x] 1)
    <function <lambda> at 0x7fcdb322ab70>
    => (+ 1 #!a 1)
      File "<stdin>", line 1, column 6

      (+ 1 #!a 1)
           ^
    LexException: Ran into a HASHBANG where it wasn't expected.

My thinking is that shebang lines shouldn't be expected by the lexer; instead, they should be removed in preprocessing. The trick will be to make sure that line numbers are adjusted to compensate.

**Comment by kirbyfan64** [comment]
Not really much of a trick TBH...I think a simple `re.replace('^#!.*', '', file)` should do the trick; since `.*` removes everything up to the newline, the line numbers will stay intact.
