### ISSUE TITLE
Toolz library?

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1339]
We've been gradually implementing things from Clojure's core that Python lacks. (For example, `interleave`, `interpose`, `partition`.) We've also added all of Python's `itertools` to Hy's core, and they do get used a lot.

But much of Clojure's core has already been implemented elsewhere in Python. Maybe we should get it over with and just add [Toolz](https://github.com/pytoolz/toolz) as a dependency so we can have it all in core by default.

Toolz has a compatible permissive license (BSD). It has both a pure Python and a fast Cython version.

Adding this would be more than a simple `from toolz import *`. We've already implemented some of these functions, so we'd want to remove our versions. There's also no point in importing things like `thread_first` that are much better implemented as our macros. But we should include as much as makes sense.

And while we're at it, we might want to add some things from Python's `functools` to Hy's core too, and set up everything from Python's `operators` module that isn't already shadowed.

**Comment by kirbyfan64** [comment]
...I think this actually seems like a pretty nice idea. :+1: from me!

**Comment by ekaschalk** [comment]
I use toolz as much as hy builtins, +1 here. It would be great to see eg. valmap and variants first-class.

FYI there are some differences between toolz and hy overlap. toolz.get has reversed arguments order compared to hy.get, I currently use both gets depending on the form. Also merge-with accepts **kwargs and toolz.do is different than lispy do.

**Comment by gilch** [comment]
How does Toolz compare with [funcy](https://funcy.readthedocs.io/en/stable/cheatsheet.html)?

**Comment by gilch** [comment]
Hy's core has about 200 symbols. 

Clojure's core has like 600 symbols. (Although many of these are not really applicable to Python.) Toolz has a tenth of that. Adding Toolz won't just get it over with. But it has some things Hy doesn't currently. Funcy has more (177) but only some of it overlaps.

The two libraries seem about equally popular on github with ~1.5K stars. I don't know if there's some other Python library that does this better. Adding Toolz would certainly be easier, just because there are fewer functions we'd have to evaluate for inclusion.

**Comment by gilch** [comment]
> toolz.get has reversed arguments order compared to hy.get, I currently use both gets depending on the form. 

Toolz ordering actually makes more sense when currying. One would be more likely to want a partial get function with a fixed index than with a fixed collection. By Hy's `get` is a special form used for the `getitem`/`setitem`/`delitem` operators, and it uses the same ordering as Python and Lisp. 

#683 is related. We can't just shadow `get` because it's actually three operators, not one. I'd like to have both versions, but Toolz's `get` is not good enough to replace Hy's, since it's only the `getitem` version.

**Comment by gilch** [comment]
> Toolz ordering actually makes more sense when currying

But it's more Clojure-like to put the collection first because of `->` and `doto`. Currying in Python is less efficient than macros are in Hy due to the overhead of the extra function calls. Therefore, we should prefer Clojure's ordering. This might make it difficult to use Toolz, since they're all backwards.

**Comment by xificurC** [comment]
See https://github.com/sfermigier/awesome-functional-python for a list of interesting libraries. I started using pyfunctional in a python codebase and worked quite well for now. Not exactly a hy candidate though I think.

My 2 cents - don't bring in another dependency. I like it when the core is lean and mean.

**Comment by gilch** [comment]
After looking at these, I don't think adding a dependency is the right way to go. Too many of the functions make more sense in Python than Hy. We'd have to add them to core on a case-by case basis anyway. It's not like it will save much time, so we might as well implement them individually like we've been doing. They're still worth looking at for ideas though.

**Comment by Kodiologist** [comment]
Sounds like a plan.
