### ISSUE TITLE
Numbers should not start with _

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1340]
#1223 allowed commas and underscores in number literals.
Python also allows underscores in numbers. The key word there being "in".
In Python `_42` is a valid identifier. In Hy, it's parsed as a number.
Any valid Python identifier must be a valid symbol, or it will make Python interop more difficult.
`_` and `,` should not be allowed at the start of a number literal, and probably not at the end either.

**Comment by Kodiologist** [comment]
- You're not supposed to touch another module's name that begins with `_`.
- `_42` is a really bad name for a variable.
- `x._42` still works (just like `x.42`).

So, it's hard to see how this would be a problem for Python interoperability in practice.

**Comment by gilch** [comment]
> You're not supposed to touch another module's name that begins with `_`.

Usually. Some modules have their own conventions.

> `_42` is a really bad name for a variable.

I think it's better than `forty_two`.

This kind of thing can come up in Python metaprogramming. The most direct translation of an integer to a valid identifier is to simply add a leading underscore, and I think that's how it's usually done.

> `x._42` still works (just like `x.42`).

It seems weird that `x._42` works, but `(. x _42)` can't.

There's not good reason not to fix this.

**Comment by tuturto** [comment]
Would make sense to fix this so Hy would work in the same way as Python (even when ``_42`` and similar are really rarely used names).

**Comment by Kodiologist** [comment]
It's not as if being able to start an integer literal with an underscore is very useful, either. So I doubt that whether or not this change is made or not will make much of a difference.

**Comment by kirbyfan64** [comment]
IMO Hy is ultimately still Python, so there's no reason to not accept anything that Python accepts.
