### ISSUE TITLE
Add more recent repl history globals

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1341]
Python and Hy have `_` bound to the last result in the repl. And I think that's it, or at least it's not easy to find documentation. But a good repl usually has more than this.

IPython has `_` and also has `__` and `___` for the two results before that.
Clojure calls them `*1`, `*2`, and `*3`. It also has `*e` for the last exception.
(Common Lisp has them too, but calls them `*`, `**`, and `***`, which wouldn't be compatible with Python.)

Some repls also save the most recent *input*. IPython saves all inputs strings, but calls the last three `_i`, `_ii`, and `_iii`. (Common Lisp saves input *forms* and calls them `+`, `++`, `+++`, again, not compatible.)

Did we set up the `_` ourselves, or did that come with something else? If we did it, perhaps we could change it to be like Clojure with `*1`, `*2`, `*3` and `*e`.

Hy's `eval` works on *forms*, not strings, so that's what the input globals should store. I'm not sure what to name them though. Clojure's basic repl doesn't seem to have that feature, but if there's some other standard, we should consider that.

**Comment by tuturto** [comment]
That's by us (https://github.com/hylang/hy/blob/7c53a07b93084a0970cdf192d4aa2d712d557154/hy/cmdline.py#L116 for relevant spot). I like the idea of ``*1``, ``*2`` and so on. Three should be enough I suppose?

**Comment by Kodiologist** [comment]
`_` is now `*1` as of #1517.

**Comment by waigx** [comment]
PSA: I will grab this one, please let me know if you have any concern.
