### ISSUE TITLE
Requesting blog

### ISSUE THREAD

**Issue by alphapapa** [hylang/hy#1353]
Hi,

I'm very interested in Hy, but as a user, I'm not sure when I should begin using it more seriously, as I see that breaking changes are still being made now and then.  I would love to read some occasional blog posts or a monthly newsletter, something like that, that would give insight into the developers' mid-to-long-term plans and help me get a feel for where Hy's going, how fast it's moving, etc.

I realize that doing this would take time.  I'm not asking for deep, detailed articles, but some basic, semi-regular updates would be very helpful for enthusiastic bystanders like me.  :)

Thanks.

**Comment by Kodiologist** [comment]
First of all, despite what it may seem, Hy is effectively ready for general use. I among others use it for most of my everyday programming tasks. The breaking changes do occasionally require you to update your code, but I've never found this difficult, even for the relatively large [Rogue TV](https://github.com/Kodiologist/Rogue-TV).

One easy way to keep up with changes to the language is to watch the NEWS file. It gets updated with every pull request that has a user-visible change. If you want more detail, look at the Git commit log. As for future changes, you can look at the outstanding pull requests to see what's coming down the pipe. Further out in the future, it's tough to give a good prediction. In my own case, I've written most of the changes to the code for the last 9 months or so, and I don't plan very far ahead—I just work on what feels most pressing or most doable. I have a vague idea of releasing Hy 1.0 in one or two years, but ultimately I'm only going to push for 1.0 once (a) there are no known major bugs, (b) all the major features I want are in, and (c) I'm happy with the documentation. The last one in particular is probably going to take an annoyingly long time.

**Comment by Kodiologist** [comment]
Whenever 1.0 happens, though, I'm aiming to release a new stable version once every 6 months.

**Comment by Kodiologist** [comment]
@hylang/core Does anybody want to maintain a blog? I don't. We do have a Twitter account, but I don't know who controls that.

**Comment by paultag** [comment]
I am currently manning @hylang :)

**Comment by Kodiologist** [comment]
Oh, that makes sense. Well, I guess this issue could be interpreted as a request to post more frequently.

**Comment by tuturto** [comment]
Like @Kodiologist said, it's hard to see what's coming up in the future. We're fairly loosely knit group and don't really have any concrete long term plans and people work on things that they find interesting or most pressing at any given time. For what it's worth, I'm writing about Hy semi-randomly at https://engineersjourney.wordpress.com/category/hy/ but wouldn't really want to commit into maintaining an official blog.

**Comment by alphapapa** [comment]
@tuturto Thanks, those look like the kind of posts I'm looking for!  I added the feed for that to GWENE at gwene.com.wordpress.engineersjourn.category.hy
