### ISSUE TITLE
banned from IRC :(

### ISSUE THREAD

**Issue by xificurC** [hylang/hy#1381]
Any particular reason why I'm banned from the IRC channel?

**Comment by paultag** [comment]
I had to ban a web client since some spam bots looked to be using #hy as a C2 Channel. It's not you, it's the web client.

I'll drop the ban for the web client - but another fix is to make an account with a cloak and log in - I'll close this bug when I remove the ban

**Comment by xificurC** [comment]
Thanks for the quick response. I'm not sure where and how to get a cloak. But if the problem is only the one web client I don't mind switching to another one. Unfortunately I have to go through a web client since the IRC ports are blocked here.

**Comment by paultag** [comment]
Sorry about that, I'll drop that ban when I get to a terminal.

**Comment by paultag** [comment]
@xificurC try again, re-open if you're still banned and I'll hack more :)

**Comment by xificurC** [comment]
@paultag thanks, I can connect with The client again. Hope for no more spambots

**Comment by paultag** [comment]
@xificurC sadly, spambots are back. I put the ban back up. Is there any chance you could use another WebIRC client, like Freenode's IRC client, or something? So sorry.

**Comment by xificurC** [comment]
@paultag I can use freenode's web irc client, sure. The only reason I used kiwi was because when I lock my PC I get disconnected (no idea why exactly) and kiwi reconnected me automatically.
