### ISSUE TITLE
Shadow `cut`.

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy#1383]
A common use-case is cleaning dataframes, for instance removing a footer number from column names.

I have a flip/curry tag macro, tz.flip, and would like to do:

```
(.rename df #f(cut 0 -1))

;; Instead must do
(.rename df (fn [x] (cut x 0 -1)))
```

**Comment by Kodiologist** [comment]
If you're interested in contributing to Hy (and we do always need more contributors), this would be a good first pull request. It shouldn't be hard to do.
