### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [hylang/hy#1391]
I build this image on aarm64 architecture and successed. So I think we can add it to support arm64 architecture

**Comment by kirbyfan64** [comment]
...huh? Hy should run anywhere that Python runs on, including arm64, airplane infotainment systems, and the inevitable AI toilet seats. Not sure exactly what we'd need to do here...

**Comment by Kodiologist** [comment]
Yeah, Hy is written in pure Python (and Hy), so it should be architecture-independent. I don't think there's anything to do here. Although, @longquan7, if you write any Android programs in Hy, that would be super cool, so totally let us know.

> the inevitable AI toilet seats

Now that's what I call /r/shittyprogramming! [Laugh track.]

**Comment by tianon** [comment]
I think https://github.com/docker-library/official-images/pull/3353 might be what @longquan7 had in mind. :+1:

**Comment by tianon** [comment]
... and the follow-up: https://hub.docker.com/r/arm64v8/hylang/ :metal:

**Comment by kirbyfan64** [comment]
Ahhhh... @longquan7 is that what you had in mind?

**Comment by longquan7** [comment]
@tianon @kirbyfan64 What I want is to push it to the authorities,if can be support arm64,thanks

**Comment by kirbyfan64** [comment]
@longquan7 Uhh...what exactly do you mean by *authorities*? Can you start from the top explaining what it is you want?

**Comment by longquan7** [comment]
@kirbyfan64 If this image support arm64 I want to add it to  https://hub.docker.com/u/arm64v8/

**Comment by kirbyfan64** [comment]
@longquan7: @tianon already did that:

https://hub.docker.com/r/arm64v8/hylang/

**Comment by longquan7** [comment]
@kirbyfan64 ok,thanks
