### ISSUE TITLE
add Clojure's condp macro to core

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1393]
Add something like Clojure's [condp macro](https://clojuredocs.org/clojure.core/condp). We might want to call it `ifp` instead, since our `cond` has the extra brackets and our `if` is more like Clojure's `cond`.

I'd recommend putting it in core like Clojure does--because it's that useful.

**Comment by gilch** [comment]
A working prototype. I think.
```Hy
(defmacro! ifp [o!pred o!expr &rest clauses]
  (setv expansion `(if)
        extend (. expansion extend)
        clauses (list clauses)
        default (if (odd? (len clauses))
                  (.pop clauses)
                  `(raise (TypeError (+ "no option for "
                                        (repr ~g!expr)))))
        clauses (iter clauses))
  (for [test clauses]
    (setv then (next clauses))
    (if (= then ':>>)
      (extend [`(do
                  (setv ~g!test ~test)
                  ~g!test)
               `(~(next clauses) ~g!test)])
      (extend [`(~g!pred ~test ~g!expr)
               `~then])))
  (.append expansion default)
  expansion)
```

**Comment by Kodiologist** [comment]
As I understand, this macro is meant to let you write something like

    (ifp f x
      y1 :>> g
      y2 z2
      z3)

and have that work like (ignoring issues of evaluation order and evaluation count):

    (cond
      [(f y1 x)
        (g (f y1 x))]
      [(f y2 x)
        z2]
      [True
        z3])

It seems better to have a more general construct like the following, which lets you specify the test directly rather than obliging you to use a binary operator and a starting value:

    (ifp (fn [y] (f y x))
      y1 :>> g
      y2 z2
      z3)

Since you'd usually need a `fn`, it would be convenient if it were anaphoric:

    (ifp (f it x)
      y1 :>> g
      y2 z2
      z3)

And if we use brackets like `cond`, then we get implicit `do`s and clearer grouping of conditions and outcomes. By using special syntax for the default value, we can ensure that the default value looks like an outcome instead of a condition.

    (condp (f it x)
      [y1 :>> g]
      [y2 z2]
      [&else z3])

I'd also like to see an `econdp` that raises `LookupError` instead of returning `None` when none of the clauses match, which is useful when you mean to be exhaustive.

**Comment by gilch** [comment]
> I'd also like to see an econdp that raises LookupError instead of returning None when none of the clauses match, which is useful when you mean to be exhaustive.

Clojure's `condp` does throw an exception when none of the clauses match, and so does my `ifp`. I used a `TypeError` though. If you want a default `None` you have to make it explicit.

> It seems better to have a more general construct [...] which lets you specify the test directly rather than obliging you to use a binary operator and a starting value

Python > Clojure > Common Lisp.

A construction that different from those three standards doesn't go in core. We can try crazy variations of things in contrib or libraries separate from the main project. But if we all try variations in core, we'll never settle on anything. My version works like Clojure's, and will be familiar to those coming from Clojure, which I expect is a sizable segment of Hy's users.

One of the main benefits of Python's batteries-included standard library is to avoid the proliferation of incompatible third-party libraries to handle the basics. Hy's core is supposed to extend this for the needs of a Lisp, mostly drawing from Clojure and Common Lisp.

Maybe your version is better than Clojure's, maybe it isn't. Call it `ap-condp` or something and put it in with our other anaphoric macros. It seems like it would fit there.

**Comment by Kodiologist** [comment]
> Clojure's `condp` does throw an exception when none of the clauses match, and so does my `ifp`. I used a `TypeError` though. If you want a default `None` you have to make it explicit.

Oh, that works, too.

I don't see the point in forcing Hy's core to imitate that of other languages (beyond providing Python's preexisting builtins, which we do). We can take inspiration from other languages, by all means, but what's the sense in limiting ourselves to them? Where we can do better than Clojure or Common Lisp, let's do better. Besides, if you want to use Clojure, why not use Clojure? Compared to Hy, it has better performance, a more stable implementation, a bigger community, and comparable library support.

**Comment by gilch** [comment]
I don't see it as a "limitation", rather as "direction". We can still go our own way in our extra libraries. But Clojure's core was designed by more experienced people with the benefit of decades of hindsight from other Lisps. I do use Clojure. Having used both it, and many other languages, Clojure seems very well designed to me.

Where we can _clearly_, objectively, do better--let's do so. If even the Clojure people say something was a mistake, let's not repeat it. But when the choice is arbitrary, rather than a clear improvement, take direction from Python>Clojure>Common Lisp, to be more familiar to our users. We could all make arbitrary changes, but we'd pick different ones.

I don't think the rest of the proposal is an improvement at all. It's mere subjective preference.

Clojure's aesthetic is "minimal ceremony". Among other things (like eschewing extra brackets), that means we make the common case the easy one, but make the uncommon case possible.

A binary operator is by far the common case. So let's make that case the easy one. If you need more than two arguments, you can pass in a data structure. A zero argument "predicate" is useless here, since it'd be a constant--so why have branches?

Thinking about actual use cases, when would you ever need to use a single-argument predicate? When you have a partially applied binary operator handy. So use `> 0` instead of `pos?`. Not good enough for your particluar predicate? The use case is getting very rare now, but we can still do it. Use `#(%2 %1) foo-pred?`
--or `(xi x2 x1) foo-pred?` in Hy.

How much more ceremony is that compared to `(foo-pred? it)`? How often does that come up? And how much less ceremony is `> 0` compared to `(> it 0)`? How common is that? We don't need `it`. Make the common case easy.

Clojure's syntax has another benefit. My current macro implementation doesn't do this, but it could be modified to detect (at expansion time) if the predicate is already a symbol, and it could then avoid gensyming it. This means that it could expand to using the faster Python operators instead of requiring the overhead of a function call in all cases.

That just leaves the extra brackets. They're the norm in Common Lisp. Either approach has tradeoffs (many of which are subjective), but Hy prioritized Clojure style over Common Lisp's. It would be more consistent to stick with that. The common case in the common functional style does not have side effects, so the implicit `do` doesn't really help. And an explicit `do` calls attention to them.

**Comment by Kodiologist** [comment]
> I do use Clojure.

So, why use and improve Hy?

> objective

I don't see how there can be an objective argument for some design choice being better than another without a formalization of the goals of the language and how to evaluate proposals.

Besides, I see no reason to presume that Clojure's or Common Lisp's (or Python's) choices were good ones. Some of them seem good, to be sure, but some seem bad. The people who worked on these languages had lots of experience, but experience doesn't guarantee good choices, either.

> A zero argument "predicate"

I don't know what you mean by that.

> Thinking about actual use cases, when would you ever need to use a single-argument predicate? When you have a partially applied binary operator handy.

I shouldn't think so; it seems that one most commonly tests a single value at a time when testing different possibilites for suitability. Something like:

    (condp (clean? it)
      [shelf ...]
      [desk ...]
      [floor ...])

> That just leaves the extra brackets. They're the norm in Common Lisp. Either approach has tradeoffs (many of which are subjective), but Hy prioritized Clojure style over Common Lisp's. It would be more consistent to stick with that.

I don't understand; more consistent how? We have both the bracketed `cond` and the unbracketed `if`.

**Comment by Kodiologist** [comment]
Not actually relevant, but funny:

https://twitter.com/planetclojure/status/908752041207414784

**Comment by allison-casey** [comment]
`ifp` was added in #1940 and will find a new, more appropriate, home in the whatever utility module comes out of #1992. Closing
