### ISSUE TITLE
NameError: name 'defsharp' is not defined

### ISSUE THREAD

**Issue by ttkk1024** [hylang/hy#1394]
``` hylang
hy 0.13.0+87.g062e24d using CPython(default) 3.5.2 on Windows
=> (defsharp ♣ [expr] `[~expr ~expr])
Traceback (most recent call last):
  File "d:\Program Files\Anaconda3\lib\site-packages\hy\importer.py", line 201, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'defsharp' is not defined
```

I don't know how to slove the problem,can you help me？Thank you very much.

**Comment by tuturto** [comment]
``defsharp`` has been renamed to ``deftag``

```
=> (deftag ♣ [expr] `[~expr ~expr])
<function <lambda> at 0xb6a317c4>
```

**Comment by gilch** [comment]
The master branch has breaking changes compared to the previous release. More breaking changes are planned. Keep up with the NEWS file and make sure you use the docs that match your version of Hy.

**Comment by gilch** [comment]
Also, tag macros can be more than one character, unlike the old sharp macros.

**Comment by tuturto** [comment]
Looks like NEWS doesn't mention ``deftag`` change.

**Comment by ttkk1024** [comment]
The hylang team should change hylang documention.

**Comment by gilch** [comment]
We need to fix that NEWS file, but the unstable docs do show `deftag` now.

**Comment by tuturto** [comment]
Documentation (the little what we have) for ``deftag`` is here: http://docs.hylang.org/en/master/language/api.html#deftag The version of docs depends on the version of Hy (master or stable) and can cause confusion if wrong version is used.

**Comment by Kodiologist** [comment]
> Looks like `NEWS` doesn't mention deftag change.

https://github.com/hylang/hy/blob/062e24d71f5582d12c06aaf549c3adcbb8b067c4/NEWS#L8-L9

To be clear, in line with what has been said above, tag macros are also documented, but only in the documentation for the versions of Hy that actually have this change.
