### ISSUE TITLE
hy -i should support the debugger

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1395]
The `pdb` debugger can list the current source position even when starting Python in interactive mode with the `-i` switch.
```
$ py -i foo.py
>>> foo()
--Return--
> c:\users\me\documents\github\hy\foo.py(3)foo()->None
-> import pdb;pdb.set_trace()
(Pdb) l
  1     def foo():
  2       bar = 42
  3  ->   import pdb;pdb.set_trace()
  4
[EOF]
(Pdb) bar
42
(Pdb) c
>>>
```
But this doesn't work in Hy.
```
> vi foo.hy
> cat foo.hy
(defn foo []
  (setv bar 42)
  (import pdb)(pdb.set-trace))

> hy -i foo.hy
hy 0.13.0+52.g30dd07a using CPython(v3.6.1:69c0db5) 3.6.1 on Windows
=> (foo)
--Return--
> <eval_body>(1)foo()->None
(Pdb) l
[EOF]
(Pdb)
```
Somehow the source gets lost.

**Comment by waigx** [comment]
Thinking to pick up this one if possible.

It seems that we need to override this function (I might be wrong): https://github.com/python/cpython/blob/master/Lib/pdb.py#L1194

Sorry for being unfamiliar with the code base and probably easier asking you guys: have we done similar thing (override a method in Python library) before?

**Comment by waigx** [comment]
Okay, probably should go `hy/hy/contrib/` folder

**Comment by vodik** [comment]
@waigx let me first see if its fixed if i run it under #1518

**Comment by vodik** [comment]
Nope

@waigx I think that's a red hearing. Dig into the `__code__` object first, you'll see some inconsistencies.

In python:

```
>>> foo.__code__
<code object foo at 0x7f3e158a7930, file "moo.py", line 1>
```

and in Hy:

```
=> (. foo __code__)
<code object foo at 0x7fd2d2c470c0, file "<eval_body>", line 1>
```

If you want my opinion on what's likely happening, Python imported foo.py, but Hy evalled it instead.

**Comment by vodik** [comment]
If you like, I can add this into #1518 since a lot of this stuff is already getting overhauled in that PR. I'm actively working on it currently. I appreciate the enthusiasm though.

**Comment by waigx** [comment]
Ah, thanks for the heads-up. I honestly just started looking into it, and not familiar with it at all.

I think it's better to leave this for a more experienced developer, and implement it in a correct way. BTW if this enhancement significantly enlarges the scope of that PR, you might want to focus on that PR and back to this issue with a separate PR.

I would like to see how do we map lines between .hy and .py 😁

**Comment by vodik** [comment]
> I would like to see how do we map lines between .hy and .py 

@waigx its part of the AST. Every AST entry needs to have `line_no` and `coll_offset`. Have a look at compiler.py - notice how theres this `Asty` object? Its part of the secret that helps us nicely propagate line number information from the lexer's output into the AST.

There's more to this, but its a good starting point to dig into it.

**Comment by vodik** [comment]
Oh, which is why its not working with the `-i` flag. These lines are inside `hy_eval`:

https://github.com/hylang/hy/blob/6c25fc23df62cf0bd4cd16d034c6e8d088d6bef9/hy/importer.py#L187-L206

Which trashes the line numbers. This is because typically `hy_eval` is used in this context:

```clj
(eval '(1 + 1))
```

And that quoted expression doesn't properly have line numbers associated with it, and thus its thrown away.

**Comment by waigx** [comment]
Thanks for all these details - I thought this a problem of the way `pdb.do_list` read source files but I was wrong.

Thanks again for your time!
