### ISSUE TITLE
fix neglected ci for code quality

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1398]
We don't seem to be running `flake8` and `coverage` anymore, but maybe I'm reading the logs wrong. Why did we stop? I don't think it was on purpose, or they wouldn't still be in `requirements-travis.txt`. We also need to add something like [parlinter](https://github.com/shaunlebron/parlinter) to our ci, to enforce a *basic* level of legibility in the `.hy` files. Indentation is all over the place, which can make them really hard to read. See also #972.

**Comment by Kodiologist** [comment]
> Why did we stop?

It looks like I forgot to add back flake8 when I redid the Travis configuration for pytest. As for Coveralls, that seems to have stopped running in 2014, which is before my time.

**Comment by Kodiologist** [comment]
Can't say I miss it. Code quality has improved over the past 5 years, partly from not having to appease linters. I've seen for myself that this project isn't immune to the tendency of programmers to treat linters as authorities to be obeyed unquestioningly, rather than tools. Let's not backslide.
