### ISSUE TITLE
Implement `else` clause for `while` loops

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1405]
For some reason, we have `else` for `for`, but not `while`.

**Comment by gilch** [comment]
Is there some reason the `else` in `for*` doesn't have an implicit `do`? It does in `try`.

**Comment by rkday** [comment]
I've created #1419 to cover that (as a separate PR, in case there *is* some reason).

**Comment by Kodiologist** [comment]
> Is there some reason the `else` in `for*` doesn't have an implicit `do`?

Nope, sounds like a bug to me.
