### ISSUE TITLE
How do I make an optional tuple bind in the arguments list?

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1410]
Hy can do destructuring binds in the args list of a fn.
```Hy
=> (defn foo [(, a b)] (print a b))
def foo(_hy_anon_var_1):
    (a, b) = _hy_anon_var_1
    return print(a, b)
None
=> (foo 1 2)
foo(1L, 2L)
=> (foo [1 2])
foo([1L, 2L])
1 2
```
Strangely, this requires a compiler anon var, even on Python 2, which should just be able to do it.
```Python
>>> def foo((a,b)):
	print a, b

	
>>> foo([1,2])
1 2
```
Anyway, what if I want a default for that?

This works in Python2
```Python
>>> def foo((a, b)=[1, 2]):
	print a, b

	
>>> foo()
1 2
```
Let's try that in Hy.
```Hy
hy 0.13.0+74.g1faee7a.dirty using CPython(default) 2.7.12 on Linux
=> (defn foo [&optional [[a b][1 2]]] (print a b))
  File "<input>", line 1, column 22

  (defn foo [&optional [[a b][1 2]]] (print a b))
                       ^----------^
HyTypeError: Only strings can be used as parameter names


=> (defn foo [&optional [(, a b) [1 2]]] (print a b))
  File "<input>", line 1, column 22

  (defn foo [&optional [(, a b) [1 2]]] (print a b))
                       ^-------------^
HyTypeError: Only strings can be used as parameter names


=> (defn foo [&key {(, a b) [1 2]}] (print a b))
  File "<input>", line 1, column 17

  (defn foo [&key {(, a b) [1 2]}] (print a b))
                  ^-------------^
HyTypeError: Only strings can be used as parameter names


```
Not working.

**Comment by Kodiologist** [comment]
> Strangely, this requires a compiler anon var, even on Python 2, which should just be able to do it.

It's not worth implementing Python 2's native support, in my opinion. Python 3 is the future and all that.

**Comment by gilch** [comment]
> It's not worth implementing Python 2's native support, in my opinion. Python 3 is the future and all that.

I'm kind of inclined to agree with that much.

I'm working on a `fn=:` macro for my destructure branch, which is why I'm finding these issues. It would support the full Clojure-like destructuring syntax, (including dicts) in its args list. If we have that, perhaps we should remove the argument destructuring in the compiler altogether, like Python 3 did. Macros can make up for it.

**Comment by Kodiologist** [comment]
Yep, no reason to do with a special form what we can do with a macro.

**Comment by kirbyfan64** [comment]
FWIW the reason for Python 2 using anon vars was also because tuple destructing seriously screwed with the `inspect` module.

**Comment by gilch** [comment]
Closing due to #1590.
