### ISSUE TITLE
Consider moving macros to a __macros__ object in each module

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1416]
We're currently maintaining a separate, parallel namespace structure for macros. Why not put them in the module being compiled instead?

Macros would be more discoverable from the repl using `(dir)` (like `__builtins__`), and we could access their documentation using Python's `help` #356.

The compiler needs to be working incrementally #1414, which requires access to the globals dict of the module it's compiling, giving it access to `__macros__` too.

**Comment by Kodiologist** [comment]
This makes sense prima facie, and could help choose something for `require` to compile to (#1268).

**Comment by gilch** [comment]
It might also help Sphinx autodoc find them in the right module #1044.

**Comment by ekaschalk** [comment]
I'm trying to support macros in `eldoc-mode`.

I was working through `hy.compiler` and noticed the `@builds` forms don't have docstrings/any extractable arguments.

If they had docstrings I could do: `(. (get hy.compiler.-compile-table "try") --doc--)` to extract them for Emacs and they could contain the argspec as a string within the docstring.

Alternatively I could do this hy-side and maintain such a table of special forms and their eldoc representation.

**Comment by gilch** [comment]
@ekaschalk yes, the `@builds` functions are the obvious place to put them. The problem is that one build function can compile multiple special forms. We could document all aspects in the same string, but that's not good for one-line summaries.

Perhaps the `@builds` decorator could also take a "docstring" argument for each forms it compiles and store them somewhere convenient. (And append them to the decorated function's docstring too.) That would keep the docstring near the code that it documents.

**Comment by ekaschalk** [comment]
Sort-of overlapping is #1441 for inspecting their arguments. Ideally each (or the whole) would take another argument for the `@builds` function's arguments, or the more involved adjustment Kodiologist mentioned of rewriting `@builds` functions to take their arguments rather than an `expr`.
