### ISSUE TITLE
Completion not complete.

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy#1417]
`hy.completer.Completer` misses many hy builtins such as: `accumulate, reduce, return, cons, constantly, ...`.

There also does not seem to be support for completions with modules.

With both we should have full autocompletion support.

**Comment by Kodiologist** [comment]
That's an A+ issue title.

We have `hy.extra.reserved`, so we should probably be using that.

**Comment by ekaschalk** [comment]
This issue can be closed unless you specifically want Hy itself to have full completion.

I've implemented full (ie. same as python/jedi) autocompletion as a Hy module emacs-side.

**Comment by Kodiologist** [comment]
Okay, I don't use this feature, so it's a non-issue for me. If anybody else wants this, reopen the issue.
