### ISSUE TITLE
macroexpand-all expands too much

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1420]
`macroexpand-all` in `hy.contrib.walk` should not be expanding anything in quotations, because the compiler doesn't either.
```Hy
=> (print '(if 1 2 3))
('if' 1 2 3)
=> (macroexpand-all '(print '(if 1 2 3)))
('print' ('quote' ('if*' 1 2 3)))
```
It also needs to track quote depth for `quasiquote`.

Currently, `macroexpand-all` is only somewhat useful as a debugging tool, but some advanced macro use cases require a well-behaved `macroexpand-all`, such that `(eval (macroexpand-all ~form))` is **always** equal to `(eval ~form)`

(Well, barring weird nondeterministic macros that wouldn't equal themselves between runs even without `macroexpand-all`, like `(defmacro weird [] (import random) (random.random)`.)

I _think_ those are the only special cases we'd have to account for. In Hy, special forms always take precedence over any other use of the symbol when in function position. And macros take precedence over function calls, so we don't have to worry about locals shadowing macros or anything.

**Comment by Kodiologist** [comment]
> In Hy, special forms always take precedence over any other use of the symbol when in function position.

With the exception of when you use `#*` or `#**` in the form, in which case it's interpreted as a function unconditionally. But I think that's the only exception.

**Comment by gilch** [comment]
That's weird. Macros still work.
```
=> (if #* a)
*a
Traceback (most recent call last):
  File "c:\users\me\documents\github\hy\hy\importer.py", line 201, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "c:\users\me\documents\github\hy\hy\importer.py", line 30, in ast_compile
    return compile(ast, filename, mode, flags)
  File "<eval>", line 1
SyntaxError: can't use starred expression here
=> (print (if #* [1 2]) :sep "/")
print(*[1, 2], sep='/')
1/2
```
But if you use the special form--
```
=> (print (if* #* [1 2]) :sep "/")
print(if*(*[1, 2]), sep='/')
Traceback (most recent call last):
  File "c:\users\me\documents\github\hy\hy\importer.py", line 201, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'if*' is not defined
```
I don't think the compiler should work like that.

**Comment by Kodiologist** [comment]
Yeah, that's strange. `(print (if #* [1 2]) :sep "/")` ought to try to call a function named `if`, I think.

**Comment by Kodiologist** [comment]
On second thought, `#*` need not force its parent not to be a macro. The only reason I created the exception was so that special forms like `+` will get their shadow function called, because Python's native operators don't allow unpacking. Thus, `(+ #* a)` calls `hy.core.shadow.+` and works. This shouldn't be an issue for any macros, whether core macros or user macros.

Perhaps it would make sense to restrict the exception further to only apply to special forms that actually have shadow functions.
