### ISSUE TITLE
Colored reprs don't play nicely with HyMacroExpansionError

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1429]
=> (defmacro m [x] (raise (ValueError (repr x))))
     <function _hy_anon_var_1 at 0x7f44974d9510>
     => (m [1 2 3])
       File "<input>", line 1, column 1

       (m [1 2 3])
       ^---------^
     HyMacroExpansionError: b"expanding `m': ValueError('\\x1b[36m\\x1b[22mHyList\\x1b[39m\\x1b[22m\\x1b[36m\\x1b[22m([\\x1b[39m\\x1b[22m\\n  HyInteger(1)\\x1b[36m\\x1b[22m,\\x1b[39m\\x1b[22m\\n  HyInteger(2)\\x1b[36m\\x1b[22m,\\x1b[39m\\x1b[22m\\n  HyInteger(3)\\x1b[36m\\x1b[22m])\\x1b[39m\\x1b[22m',)"

**Comment by gilch** [comment]
`(repr '[1 2 3])` is enough to show that, what does that have to do with `HyMacroExpansionError` in particular?
```
=> (repr '[1 2 3])
'\x1b[36m\x1b[22mHyList\x1b[39m\x1b[22m\x1b[36m\x1b[22m([\x1b[39m\x1b[22m\n  HyInteger(1)\x1b[36m\x1b[22m,\x1b[39m\x1b[22m\n  HyInteger(2)\x1b[36m\x1b[22m,\x1b[39m\x1b[22m\n  HyInteger(3)\x1b[36m\x1b[22m])\x1b[39m\x1b[22m'
=> (import [hy.models])
=> (with [(hy.models.pretty False)] (repr '[1 2 3]))
'HyList([HyInteger(1), HyInteger(2), HyInteger(3)])'
```

**Comment by Kodiologist** [comment]
Typing `(repr '[1 2 3])` at the command line is requesting a `repr` of a `repr`, so that makes sense, but `ValueError` expects a string, so the additional layer of `repr` imposed by `HyMacroExpansionError` doesn't seem to be helping. Contrast with:

    => (raise (ValueError (repr '[1 2 3])))
    Traceback (most recent call last):
      File "/home/hippo/Desktop/hyenv/hy/hy/importer.py", line 198, in hy_eval
        eval(ast_compile(_ast, "<eval_body>", "exec"), namespace)
      File "<eval_body>", line 1, in <module>
    ValueError: HyList([
      HyInteger(1),
      HyInteger(2),
      HyInteger(3)])

**Comment by kirbyfan64** [comment]
```
HyMacroExpansionError: b"
```

Wait...why are we using `bytes` here?

**Comment by Kodiologist** [comment]
No idea; it's pretty weird. :/

**Comment by Kodiologist** [comment]
Actually, `ValueError` will take a non-string and stringify it, but this doesn't seem much better:

    => (defmacro m [x] (raise (ValueError x)))
    <function _hy_anon_var_1 at 0x7fcd279f1400>
    => (m [1 2 3])
      File "<input>", line 1, column 1

      (m [1 2 3])
      ^---------^
    HyMacroExpansionError: b"expanding `m': ValueError(\x1b[36m\x1b[22mHyList\x1b[39m\x1b[22m\x1b[36m\x1b[22m([\x1b[39m\x1b[22m\n  HyInteger(1)\x1b[36m\x1b[22m,\x1b[39m\x1b[22m\n  HyInteger(2)\x1b[36m\x1b[22m,\x1b[39m\x1b[22m\n  HyInteger(3)\x1b[36m\x1b[22m])\x1b[39m\x1b[22m,)"

**Comment by kirbyfan64** [comment]
Yeah, I'm pretty sure this has to have *something* to do with the whole `bytes` thing here...

**Comment by gilch** [comment]
> Wait...why are we using bytes here?

I have been wondering about that for a while, but priorities. Maybe it was for Python2 compatibility? Can we try not using bytes here, or do we need to have pretty off by default?

**Comment by kirbyfan64** [comment]
Maybe not using bytes would help? I mean, off the top of my head I know special characters in byte strings aren't evaluated, so switching to str might fix the problem.
