### ISSUE TITLE
Copy toolz.curry to Hy?

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy#1439]
Currying is useful regardless of threading macros. Consider

    (*map (fn [k v] (.format "[{} {}]" k v)) (.items {1 2 3 4}))

    (*map (tz.curry str.format "[{} {}]") (.items {1 2 3 4}))

    ;; I personally have it bound as a tag macro
    (*map #$(str.format "[{} {}]") (.items {1 2 3 4}))

    ;; Also possible but breaks code introspection and not ideal
    (*map (xi str.format "[{} {}]" x1 x2) (.items {1 2 3 4}))

I saw a previous issue discuss adding `functools.partial` but it was never merged and closed.

I specify toolz implementation because it will curry kwargs as well.

I'd also support `flip` getting added but saw it was ignored for lack of support. I'd say now that more operators are shadowed, its usecases are a bit more diverse, eg. flipping shadowed `get` in a thread or reversing the addition or division of items in a thread.

**Comment by Kodiologist** [comment]
> breaks code introspection

What do you mean?

**Comment by ekaschalk** [comment]
At the moment I'm referring to just eldoc. Because it's a lambda, unlike currying, I cannot make assumptions on its further sexps. In the tag macro case eldoc works already and the funcall case it can be made to work as a special case (by prepending "curried" to the eldoc output of the eldoc for the second sexp).

I dislike `xi` as a macro and think implementing it as a compiler construct like was done with the unpacking generalizations would be better. Much quicker/easier would be just porting curry.

**Comment by Kodiologist** [comment]
I see.

> I dislike `xi` as a macro and think implementing it as a compiler construct like was done with the unpacking generalizations would be better.

Why's that? We always try to implement things as macros rather than special forms when possible, to make the language more flexible and the compiler simpler.

**Comment by ekaschalk** [comment]
One reason is the above case.

Another is a bit more vague/personal - that `xi` breaks the rule that you can look at the first sexp of the form and know what's happening. The code being "conceptually evaluated" starts at the second sexp. This often results in a double-take whenever I glance at code I wrote using it. 

This is relative but to me currying is a fundamental operation on par with eg. unpacking. I feel a tag macro/compiler construct is the natural representation as the form is not polluted by the curry call. `with-decorator` as `#@` isn't all that different imo.

**Comment by Kodiologist** [comment]
You seem to be concerned by the syntax of `xi` rather than whether it's implemented as a macro or as a special form. The choice of implementation, when something is possible to implement either way, should make no difference for syntax and little difference for semantics.

**Comment by ekaschalk** [comment]
You're right, I didn't think through the compiler construct portion (I meant removing the tag part like `%(func %1 %2)` which might not be worth the trouble).

**Comment by gilch** [comment]
I wrote `xi` in the first place #879. I'd support doing it exactly like Clojure does, but that was controversial. Clojure used `#()` with `%` parameters, instead of `(xi)` with `x` parameters. One-liners work fine, but indentation makes more sense if the function is in the function position where it belongs.

Having worked with it a while, I think `xi` makes much more sense as a tag macro. The minimal change would be `#xi()` with the same `x` parameters. But it would be just as easy to do something like `#%()` with `%` parameters. We can't use `%` as the first argument like Clojure does (since that's already Python's  `%` operator), but the explicit `%1` is fine.

Tag macros currently work about the same as normal macros but I think some edge cases are still broken. How do you require a tag macro from another module? I don't think we've implemented that properly. We can't possibly provide a tag macro in a separate module without that. But we could certainly move it to core.

I was also thinking of changing them to work more like Clojure tagged literals. But Python doesn't make this easy. We could instead make them more like Common Lisp reader macros, since we have more control at the compiler level. But we don't _exactly_ have a reader to begin with.

**Comment by ekaschalk** [comment]
> How do you require a tag macro from another module?

Unless I'm misunderstanding, `require` works for tag macros already, I certainly import them in my projects.

Also, a good time as any to bring up that `require` isn't transitive unlike `import`. The effect of this is that I maintain a `macros.hy` file which requires the anaphorics, however in every file which I do `(require [src.macros [*]])` I must require the anaphorics once again.

**Comment by gilch** [comment]
> I require them via * though, I'm not sure if they can be required by name.

It looks like they can. Maybe that got fixed while I wasn't looking. Or maybe one of my weird experiments made me think it was broken. If you have a normal macro of the same name, you get both though. I'm still not confident we've thought this through properly, but I did the PR for making xi a tag macro.

>  require isn't transitive unlike import

Yeah. It alters the state of the compiler, but has no effect on the resulting module object. Unlike `import`. Macros don't exist after compilation. Maybe #1416 could help with that.

> that xi breaks the rule that you can look at the first sexp of the form and know what's happening.

`apply` kind of does that too. How do other Lisps handle it?

> I specify toolz implementation because it will curry kwargs as well.

What do you mean? I'm pretty sure Python's `functools.partial` implementation does that. Maybe we could import `functools` into core like we do with `itertools`.

> I'd also support flip getting added but saw it was ignored for lack of support. I'd say now that more operators are shadowed, its usecases are a bit more diverse

How should it work though? Lisp doesn't distinguish operators from functions. Python's binary operators have all been generalized to *n*-ary operators somehow.

Do we reverse the arguments list? Do we rotate them? Left or right? Do we swap the first two and leave the rest in place? Do we force it to be a binary function and raise an error if there are more arguments? How do we handle `&kwargs`? These all do _exactly_ the same thing when *n*=2, but are completely different when *n*=3 or more. It's not at all obvious what "flip" means to a ternary operator. `xi` was explicit, at least.

**Comment by ekaschalk** [comment]
> How should it work though?

I'd suggest it be the same as curry but in reverse. That operators are n-aray doesn't really matter, it's still well-defined. It's more about being non-commutative. 

I wasn't aware that partial works with keywords. However curry is still nicer as it collapsed partial and `partialmethod`.

Overall though the new `xi` syntax is nice enough that I'm not convinced `flip` is worth it.

**Comment by ekaschalk** [comment]
With the new `%i` and specifically the ``%*` construct curry/flip aren't needed, this can probably be closed.
