### ISSUE TITLE
Introspecting -compile-table constructs.

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy#1441]
To complete `eldoc-mode` I need to introspect the arguments and docs for compile table constructs. Looking at the code I see that:

1. Arguments can't be introspected.
2. `@builds` is variadic.

Since most of the variadic variations are either shadowed (`@builds(and, or)`) or are the same (`@builds(def, setv)`), point 2 is not generally an issue.

I'm looking for the go-ahead to make the eldoc strings with formatted args their docstrings.

There is precedent for this in Python, as functions that are implemented in C can't have their arguments introspected so they format their argstrings in their docstring:

    print.__doc__
    Out[2]: "print(value, ..., sep=' ', end='\\n', file=sys.stdout, flush=False)\n\nPrints the values ....
    inspect.getargspec(print.__call__)
    Out[3]: ArgSpec(args=['self'], varargs='args', keywords='kwargs', defaults=None)

As of yesterday `eldoc-mode` now formats lispy-like and catches all arg definitions (and highlights them). 

For reference:

     (defn x [a &optional b &rest c &kwargs d &kwonly e [f 1]] "some-docs\nMore details" "bar")

     ;; Has eldoc string in the minibuffer
     x: (a &optional b &rest c &kwargs d &kwonly e [f 1]) - some docs

So I would write docstrings with first line taking the above format for `compile_require`, `compile_cut_expression`, etc... and then add a wrap in checkargs.

    def checkargs(exact=None, min=None, max=None, even=None, multiple=None):
        def _dec(fn):
            @functools.wraps(fn)
            def checker(self, expression):

This doesn't work for the non-shadowed but variadic constructs like `@builds("list_comp", "set_comp", "genexpr")`, but it does get almost all of them.

**Comment by Kodiologist** [comment]
I would think it better to change how the `@builds` methods work so that they actually receive separate arguments instead of just an `expr` argument. This might be a little tricky because we need to keep the position information of `expr` around, but it should be doable, perhaps by continuing to pass in the original `expr` as the first argument.

Also, I would caution against writing docstrings for `@builds` methods before we have to a way to automatically synchronize docstrings and the HTML documentation. We already have such a documentation-duplication problem for core functions and macros.

**Comment by ekaschalk** [comment]
> keep the position information of expr around

You are referring to `["start_line", "end_line", "start_column", "end_column"]` in `HyObject` right?

> caution against writing docstrings 

We gain a lot by having the docstrings, if you haven't yet check out `eldoc-mode` and autocompletion that also uses eldoc, it's getting pretty great. Right now it is pretty easy to write the docstrings, it took very little time to update all of `hy.core`. I'd rather not wait on the html sync which will be more involved.

**Comment by Kodiologist** [comment]
>> keep the position information of expr around 
>
> You are referring to `["start_line", "end_line", "start_column", "end_column"]` in HyObject right?

Right.

> Right now it is pretty easy to write the docstrings

Perhaps so, but redundant documentation that isn't up to date is worse than a single source of documentation.

**Comment by Kodiologist** [comment]
This should no longer be an issue now that special forms are gone (#2104).
