### ISSUE TITLE
Optional dictionary argument reusing dictionary from previous call

### ISSUE THREAD

**Issue by dannyfreeman** [hylang/hy#1442]
I ran into this problem today when working on a school project I'm doing in hy. I have a function that takes an optional dictionary argument. It is supposed to default to an empty dictionary. On the first call to the function without passing in the optional dictionary argument, the empty dictionary is used. On the second call without the optional argument, if that dictionary was modified in the funciton, the modified dictionary is used instead of the default empty dictionary. I sketched up an example that replicates the issue using the hy master branch in a fresh python virtual environment. All of my example code here was done in a plain old hy repl from the command line, not from an emacs inferior-lisp repl or anything fancy like that. 

Here is my version information that hy prints out: `hy 0.13.0+141.ge0e8506 using CPython(default) 3.6.2 on Linux`

Here's my example to replicate the issue.

```
(defn test [foo &optional (bar {})] 
  (assoc bar foo "test")
  bar)
```
The first call `(test "a") ` returns `{'a': 'test'}`, 

the second call `(test "b")` returns `{'a': 'test', 'b': 'test'}`,

and the thrid call `(test "c")` returns `{'a': 'test', 'b': 'test', 'c': 'test'}`

and so on.

I thought that maybe the function declaration was declaring the argument `bar` as a global variable, but trying to evaluate `bar` in the repl will throw a `NameError` because `bar` is not defined outside of the scope of the function. Re-evaluating the function defintion in the repl will also redefine the optional argument and reset the issue. 

If anyone else is experiencing this issue, my work arounds were to just provide an empty dictionary with each function call, make the argument mandatory, or to wrap it in another function that provides the empty dictionary. When one of these is done, the foreced empty dictionary is used and I don't get any of the cached values from the previous function call stuck in the dictionary. Hope this helps and thanks for all the wonderful work you folks have done creating this language.

**Comment by tuturto** [comment]
This is due to how Python handles functions. They're first class citizens and come with their own state. I got bitten by this couple of times, before I learned what was going on. In short, ``test`` is a function object, that has optional ``bar`` argument. Value of ``bar`` is initialized when function is defined. Calls to ``bar`` then modify that value and cause the effect you observed in subsequent calls. Well written bug report, thanks.

http://effbot.org/zone/default-values.htm explains this in more detail.

**Comment by dannyfreeman** [comment]
Thanks for the answer!

**Comment by Kodiologist** [comment]
It's probably possible to write a macro that works like `defn` but evaluates default arguments when the function is called instead of when it's defined. I know I'm not the only one who thinks that this isn't one of Python's better features.
