### ISSUE TITLE
Astor update 0.6 10/31 change in API (astor.codegen to astor.code_gen) breaks hy.cmdline

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy#1446]
Good timing, started a Hy project today and noticed the change.

Either update the import or specify version 0.5 as the requirement.

**Comment by gilch** [comment]
I'd prefer we use 0.6 if possible. It has some nice improvements.

**Comment by gilch** [comment]
I tried updating Hy to astor 0.6, but it's choking on `NaN`.
