### ISSUE TITLE
`let` isn't aware of `import`

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1451]
$ hy -c '(require [hy.contrib.walk [let]]) (let [foo 5] (import [math :as foo]) (print foo)) (print foo)'
    5
    <module 'math' (built-in)>

I would've expected `let` to recognize the `foo` in the `(import …)`.

**Comment by Kodiologist** [comment]
@gilch Bug or feature?

**Comment by gilch** [comment]
Feature, in the sense that it was documented to work that way. Imports are always hoisted to Python scope. You can use `__import__` instead if you need it to work in the local `let` scope, though I can't imagine this happening often, it is also documented.

`let` could probably be modified to work differently for `import` statements if you prefer. This shouldn't interfere with the other forms. But it's not easy. Python syntax doesn't allow dict lookup targets in import statements. You'd have to expand to something else as a workaround, and it would have to be valid for any possible `import` form.

**Comment by Kodiologist** [comment]
> Python syntax doesn't allow dict lookup targets in `import` statements.

Dang, I didn't know that. Stupid arbitrary Python limitations.

> it was documented to work that way

Somehow I missed that. Well, that's on me. Let's close this and hope nobody complains. `__import__` is a good workaround, anyway.

**Comment by kirbyfan64** [comment]
What do you mean by "dict lookup targets in `import` statements?

**Comment by Kodiologist** [comment]
Matthew was referring to my suggestion to compile `(let [foo 5] (import [math :as foo])` to `… (import foo as _;let|1235['foo'] ) …`. It turns out that Python doesn't allow this: the right-hand side of `as` has to be an identifier.
