### ISSUE TITLE
Hy 0.13.0 retrieves astor 0.6 but requires astor 0.5

### ISSUE THREAD

**Issue by h8hawk** [hylang/hy#1452]
I've got error while lunching Hylang on Ubuntu 16.04 with python3.6.
  File "/usr/local/lib/python3.6/dist-packages/hy/cmdline.py", line 14, in <module>
    import astor.codegen
ModuleNotFoundError: No module named 'astor.codegen'

**Comment by kirbyfan64** [comment]
Did you download this via pip, or did you clone the GitHub repo? Sounds like you have an old version of astor installed.

**Comment by tianon** [comment]
This is https://github.com/hylang/hy/issues/1446 -- if you `pip install hy` right now, it'll fail in this manner because it'll pull in the newer 0.6 `astor` which has breaking changes.  If you explicitly install `astor` 0.5 instead, it works. :+1:

**Comment by Kodiologist** [comment]
I agree with @tianon's diagnosis. The setup.py of Hy 0.13.0 is now broken because it allows newer versions of astor, but you can either `pip install astor==0.5` or run Hy master, which supports astor 0.6. Perhaps we should release Hy 0.14.0 immediately so people don't encounter this every time they try to install Hy from PyPI. Or we could just release Hy 0.13.1, which would just change setup.py. That's probably the way to go for a quick fix.

**Comment by tuturto** [comment]
Releasing 0.13.1 sounds like a plan to me.

**Comment by h8hawk** [comment]
I've installed with pip. hy __version__ is 0.13.0 . astor.__version__ is 0.6. I'v edited "/usr/local/lib/python3.6/dist-packages/hy/cmdline.py" , change "import astor.codegen" to "from astor import codegen" . It runs well. However there are bug's in running wrong codes in Hylang shell. such:
"""
=> (pr fka)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/hy/cmdline.py", line 102, in runsource
    ast_callback)
  File "/usr/local/lib/python3.6/dist-packages/hy/importer.py", line 176, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'pr' is not defined
""""

**Comment by Kodiologist** [comment]
@h8hawk, that strategy won't work because astor 0.6 introduced several backwards-incompatible changes, not just changing the module name. Use  `pip install astor==0.5` for now.

**Comment by Kodiologist** [comment]
I added a 0.13.1 release on GitHub. @paultag, could you post it to PyPI?

**Comment by berkerpeksag** [comment]
By the way, I just released astor 0.6.1 so the current hy release no longer raise an `ImportError` when you invoke `hy`.

**Comment by berkerpeksag** [comment]
(Also, you can ping me on IRC or open an issue at berkerpeksag/astor if you notice an obvious compatibility error like this one in a new astor release.)

**Comment by gilch** [comment]
Can't we close this now that Astor 0.6.1 fixed the compatibility issue?

**Comment by Kodiologist** [comment]
Even if 0.13.1 is no longer necessary, it should be on PyPI for consistency.

**Comment by Kodiologist** [comment]
It's now uploaded.
