### ISSUE TITLE
document the hidden &compiler parameter in defmacro

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1455]
The new `let` implementation (actually the improved `macroexpand-all` function it's built upon) required this feature. But it should be documented. `defmacro` now automatically has an `&name` parameter which is set to the name of the module it's expanding in.
```Python
=> (defmacro this-module [] `(print ~&name))
from hy import HyExpression, HySymbol
import hy
hy.macros.macro('this_module')(lambda &name: HyExpression([] + [HySymbol(
    'print')] + [&name]))

<function <lambda> at 0x00000224644B6F28>
=> (this-module)
print('__console__')

__console__
```

**Comment by willemhb** [comment]
Where would be a good place to include this documentation? After looking through everything it seems like the other ampersand-prefixed argument forms are documented with `defn`, but this issue seems pretty inside baseball for being included alongside those.

**Comment by Kodiologist** [comment]
Under `&defmacro` or in a general reference section about macros.

**Comment by Kodiologist** [comment]
#2104 has replaced this parameter with `&compiler`.
