### ISSUE TITLE
__main__.hy doesn't work like __main__.py

### ISSUE THREAD

**Issue by Zirak** [hylang/hy#1466]
(All snippets below tested with hy master and python 3.6.3)

When running a directory with a `__main__` file, hy fails while python succeeds:

    % ls
    __main__.hy __main__.py
    % python .
    hey
    % hy .
    hy: Can't open file '.': [Errno 21] Is a directory

Same applies to egg files, but that may be its own independent problem.

Passing the `-m` flag does execute the `__main__`, *unlike python*:

    % hy -m .
    hy
    % python -m .
    python: Relative module names not supported

Fixing the first block is relatively simple: In [`cmdline`, `run_module`](https://github.com/hylang/hy/blob/e0e664c030266ead171de2a7fe887ceff4832d32/hy/cmdline.py#L199) already does the correct thing when running a directory/file according to [the respective function in cpython](https://github.com/python/cpython/blob/9454060e84a669dde63824d9e2fcaf295e34f687/Modules/main.c#L1439).

However, making the 2nd block fail is a breaking change, as `run_module` does not do the same thing as [the respective function in cpython](https://github.com/python/cpython/blob/9454060e84a669dde63824d9e2fcaf295e34f687/Modules/main.c#L228) (wraps [`runpy._run_module_as_main`](https://github.com/python/cpython/blob/9454060e84a669dde63824d9e2fcaf295e34f687/Lib/runpy.py#L167))

In the end, the question may be is this worth fixing on a lower level? Does hy want to copy the behaviour of `run_file` and `run_module` as implemented in cpython, or is it good enough to be able to run a directory/zip/whatever with a `__main__`?

**Comment by Kodiologist** [comment]
Huh, I didn't even know this Python feature existed. #459 might be related. Thanks for reporting.
