### ISSUE TITLE
Support user introspection and modification of the currently defined macros

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy#1467]
Help me understand `hy.macros.-hy-macros` initialization.

First run will print `hy.macros.-hy-macros` fine. Second and subsequent runs will print an empty dict.

Deleting the `foo.pyc` will reset the `-hy-macros` dict as expected.

Is this intended behavior? If intended - how do I test code referencing `-hy-macros`?

`pkg/foo.hy`

    (import hy.macros)

    (defn foo []
      (print hy.macros.-hy-macros))

`pkg/test_foo.hy`

    (import [pkg.foo [foo]])

    (defn test-foo []
      (foo)
      (doc ->))  ; Similarly, will print on first runthrough, error on second run

**Comment by gilch** [comment]
Maybe related to #1324.

It's easy to force a compile at runtime though, just use `hy.eval`, e.g.
```Hy
(hy.eval '(print hy.macros._hy-macros))
```

**Comment by ekaschalk** [comment]
Ok thanks a simple `(hy.eval '(import hy.macros))` in the module being tested does the trick.

**Comment by Kodiologist** [comment]
I don't think `hy.macros._hy_macros` is intended for public use.

**Comment by ekaschalk** [comment]
Is there a better way to access all defined macros? `doc` takes the same approach. It's for code introspection for Emacs, not sure if that qualifies as public use.

**Comment by Kodiologist** [comment]
No, I don't think so. We've never worked on introspection of the macro system beyond Hy's own internal needs.

**Comment by Kodiologist** [comment]
Better support for introspection of the macro system could replace `hy.reserved` and perhaps also `delmacro`.
