### ISSUE TITLE
New async forms may need let tests.

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1476]
The `let` macro (really, the symbol macro machinery it's built upon) needs to correctly account for *every special form* to work properly. When Hy's special forms change, `let` might need an update. #1471 introduced new special forms, which `let` would probably treat as a default case. This may or may not work, but I'm not entirely sure how the new forms are supposed to work.

**Comment by Kodiologist** [comment]
The async forms should be identical to their non-async equivalents so far as syntax and variable scoping are concerned, so `let` should be able to treat them identically.

**Comment by vodik** [comment]
They are, it can basically be considered a "special case" of generator protocol with different protocol
