### ISSUE TITLE
Need tools like leiningen 

### ISSUE THREAD

**Issue by minghu6** [hylang/hy#1477]
Hylang is an amazing language and surprised me a lot, I do like it! 
Personally, I liked the lisp ast style, functional programming,  python philosophy and batteries included.
In many times, I think of how to write python using lisp style, and had a fortune of discovering hy!

However, before I try to write code for it, I found that there lacks a tool to manage  hy code and a site for the community repository. In my first impression, hy is similiar to clojure, and I found it did when I read the document. Hy can meet with similiar issue about clojure, we based on python/java(jvm), and keep the interoperating with it, though, the origin pip/maven can't meet up our need. Clojure has their leiningen and clojars.org, I wonder that what do you think of it ?

In my opinions, we need a plugin for pip to wrap hy module and we can use it like a common package.

**Comment by Kodiologist** [comment]
Why do you say that pip "can't meet up our need"? What would your proposed plugin make pip do that pip can't already do? And why don't you think PyPI is a suitable community repository? Users should be able to use a Hy module as a Python module without even being aware it was written in Hy.

**Comment by minghu6** [comment]
wow, so scary, maybe you misunderstand my meaning because my poor expression. I am just not sure that if hylang is a independent language,  I guess it‘s like clojure, or just a python module.
If it is the former, It seems to need what I mentioned，or else that‘s okay.

so，maybe need a chapter about it usage ?Othewise it is confused if emphasized it is a lisp dialect and called hy-lang.

To be honest, I agree with you, however, I misunderstand your means before your comment.

**Comment by Kodiologist** [comment]
Don't be frightened; I very rarely bite. :P

Hy isn't a fully independent language. It's ultimately just another way to write Python code, similar to how CoffeeScript is to JavaScript. One of the advantages of this is that we can reuse a lot of Python tools, like pip.

> so，maybe need a chapter about it usage ?

I don't know what you mean. What aspect of Hy's usage do you think is not covered in the existing documentation?
