### ISSUE TITLE
A tiny mistake of document ?

### ISSUE THREAD

**Issue by minghu6** [hylang/hy#1478]
In http://docs.hylang.org/en/stable/language/interop.html#using-hy-from-python, there is a demo:
```hy
(setv *this-will-be-in-caps-and-underscores* "See?")
(defn greet [name] (Print "hello from hy," name))
```
however, when I run it both in python2.7 and python3.5 on ubuntu16.04,  It just reports:
```sh
NameError: name 'Print' is not defined
```
I guess it's just a clerical error according to its coding style?

**Comment by Kodiologist** [comment]
Fixed in #1464. You'll see documentation updates in the stable version of the documentation once a new stable version of Hy is released.
