### ISSUE TITLE
How to write compat for new feature of hy

### ISSUE THREAD

**Issue by minghu6** [hylang/hy#1487]
For example, I am trying the new macro `let` of hy. However, I found it's still in contrib module of the master branch (up to now). Then if I want to write a compat for now and future, I should write caompaty code like:

```
if default loaded?
elif should require from hy.extra
elif should require from hy.contrib.walk
else should define manually the macro using code of master branch
``` 
In details, I find that no propery func to do something like `fn?`  `macro?` `(*in "let" hy.extra)` 

So, my question is how to write compat for new featue of hy in a proper way and if we need extra func/macro 's support?

**Comment by Kodiologist** [comment]
No such feature is implemented, but see #740 for a preexisting feature request.
