### ISSUE TITLE
Need more "good-first-bug" issues tagged.

### ISSUE THREAD

**Issue by langford** [hylang/hy#1490]
The GitHub label "good-first_bug" is empty. It is linked to from https://github.com/hylang/hy/blob/master/CONTRIBUTING.rst and the [read the docs](http://docs.hylang.org/en/stable/hacking.html#contributor-guidelines) version.

**Comment by Kodiologist** [comment]
We have a [good first issue] label. Maybe somebody renamed it and forgot to update the documentation. In any case, nobody's really stewarding issue labels, so my inclination would be to remove the mention from the documentation, so as not to give the impression that a label is a reliable source of good first issues.

**Comment by Alex-Keyes** [comment]
@Kodiologist what would you recommend as the best place to start?

**Comment by Kodiologist** [comment]
@Alex-Keyes How about fixing this error message? https://github.com/hylang/hy/issues/1486#issuecomment-356675221

**Comment by Alex-Keyes** [comment]
Okay awesome I'll check it out! Thanks!
