### ISSUE TITLE
wrong order of statement execution

### ISSUE THREAD

**Issue by v217** [hylang/hy#1495]
```
;  hy 0.13.0+207.gcf87de5
(import sh)
(do
	(print "before")
	(sh.sleep 10)
	(print "after")
)

```
This should print
before
than wait 10 seconds and print
after

but instead of doing the above it waits 10 seconds and then prints
before
after

hy 0.13.0+207.gcf87de5 on ubuntu 17.10
importing https://github.com/amoffat/sh (apt-get install python3-sh)

**Comment by Kodiologist** [comment]
The code works as expected for me. You seem to have a few commits that aren't on master, so try switching back to the HEAD of master. Also make sure that you can't replicate this with Python; your copy of Python might be buffering more aggressively than you expect.

**Comment by Kodiologist** [comment]
Finally, I notice that Ubuntu's python3-sh is a bit behind PyPI's latest sh (1.11-1 vs. 1.12.14).

**Comment by v217** [comment]
# OK any combination works fine!
Whether provided by apt or pip3
I had the problem only with the build script of sublimetext. Sorry for the false bug report.

**Comment by Kodiologist** [comment]
No problem. Happy Hying.
