### ISSUE TITLE
`with-decorator` should work with lambdas

### ISSUE THREAD

**Issue by vodik** [hylang/hy#1506]
If the preferred way of writing is with the attribute list, then we probably want to make `with-decorator` work with lambda by forcing a function to be defined instead (rewrite `fn` -> `fn*`).  Otherwise we'll trip up around `classmethod` (and `property`, technically, even though its more natural to construct it directly).

For example:

```clojure
(defclass Foo []
  [from-string #@(classmethod (fn [cls str] ...))])
```

Fails with `HyTypeError: Decorated a non-function`

See #855 where I had to workaround this.

**Comment by vodik** [comment]
I have a patch for this, should we agree its desirable, but I'll wait for #1504 so its significantly cleaner.

**Comment by vodik** [comment]
Actually, another option is to drop lambdas altogether and only ever emit functions. They have the same performance characteristics anyways...

**Comment by Kodiologist** [comment]
Decorator syntax is not necessary in this case. You can write simply

    (defclass Foo []
      [from-string (classmethod (fn [cls str] ...))])

**Comment by vodik** [comment]
Should I close this then?

**Comment by Kodiologist** [comment]
Works for me.
