### ISSUE TITLE
`unquote-splice` interacts with HySymbol weirdly

### ISSUE THREAD

**Issue by vodik** [hylang/hy#1509]
I think this can be addressed in #1504, if I also break `HySymbol` so it doesn't inherit from `str`, like I did with `HyKeyword`, because otherwise this happens:

```clojure
=> `(~@'range)
HyExpression([
  'r',
  'a',
  'n',
  'g',
  'e'])
```

`HySymbol` shouldn't be iterable.

**Comment by Kodiologist** [comment]
Why not? That seems like a fine behavior to me.

**Comment by vodik** [comment]
Because its an implicit type coercion that makes no sense imho:

```
=> (list 'foo)
['f', 'o', 'o']
```

A symbol was turned into a string that was iterated on. I mean, if this behaviour showed up, how much more likely is to have been a bug than the intended behaviour?

But imho I'm really not a fan of treating symbols as strings.

**Comment by Kodiologist** [comment]
They seem very string-like to me, is all I can say, I guess. Certainly I wouldn't have expected `(list 'foo)` to do something else.

**Comment by vodik** [comment]
Honestly, I would have expected a TypeError or ValueError. I think its more the type cohesion to string that's happening is what's bothering me (e.g. `(= (string? 'foo) True)` also rubs me the wrong way).

I think I can understand why it was done intentionally, when getattr and co take strings, and python objects are really just tables, but they're not really the same thing. Attributes are a subset of valid keys. so I have no expectation for them to be interchangeable. I guess Hy is also not limited to Python's rules for identifiers.

I mean, I can live with it.

**Comment by Kodiologist** [comment]
Things have changed since this issue such that `(= 'foo "foo")` is no longer true, but it's still true that `(list 'foo)` produces `["f" "o" "o"]`, and I still think that's correct. If there is substantial disagreement, we can reconsider this.
