### ISSUE TITLE
`yield` inside `with` can lead to generation of a spurious `return`

### ISSUE THREAD

**Issue by paultag** [hylang/hy#151]
it tried to return it, d'oh.

we need to disable return mangling on generator functions

**Comment by vodik** [comment]
I'm still noticing problems with yield when mixed with `with` blocks in the latest release:

```hy
(import contextlib)

(with-decorator contextlib.contextmanager
  (defn test-file-open [filename]
    (with [fp (open filename)]
          (yield fp))))
```

generates

```python
import contextlib

@contextlib.contextmanager
def test_file_open(filename):
    with open(filename) as fp:
        _hy_anon_var_1 = yield fp
    return _hy_anon_var_1
```

and fails to load:

```
SyntaxError: 'return' with argument inside generator
```

And I see it in both python2 and python3.

**Comment by kirbyfan64** [comment]
@vodik That's been brought up somewhere else (though I don't recall where). We really need a way to suppress auto returns...

Meanwhile, I think a good solution would just be disabling auto-returns completely when in a generator...

**Comment by vodik** [comment]
@kirbyfan64 played around with your fix, seems to do a comprehensive job, can't seem to break it.
