### ISSUE TITLE
`load_module` is deprecated (since 3.4)

### ISSUE THREAD

**Issue by vodik** [hylang/hy#1512]
https://docs.python.org/3/library/importlib.html#importlib.abc.Loader.load_module

> Deprecated since version 3.4: The recommended API for loading a module is exec_module() (and create_module()). Loaders should implement it instead of load_module(). The import machinery takes care of all the other responsibilities of load_module() when exec_module() is implemented.

**Comment by vodik** [comment]
And as a heads up, the `Finder` API (what we've incorrectly named `MetaImporter`) as also deprecated. Looking into this.

**Comment by Kodiologist** [comment]
> And as a heads up, the `Finder` API (what we've incorrectly named `MetaImporter`) as also deprecated.

#1085 and #1188 might be related.

**Comment by vodik** [comment]
I'm knee deep in this now, and I think there's some really interesting potential with a reworked importer... I got some ideas I'll put up in a proposal, if this work pans out.

**Comment by vodik** [comment]
Yeah, digging into this and #1513 got me looking under the hood and I think I've been effectively nerd snipped. 😉 

I've got something that's working on both python 2 and python 3, using only 3.4 and newer `importlib` API on python 3, and much simpler than the reverted polyloader.

I've also took the opportunity to deal with some of other bugs like #1466. The following application:

```clojure
"Tool to dump __spec__, __loader__, and other metadata"
(print "name:" __name__)
(print "doc:" __doc__)
(print "package:" __package__)
(print "loader:" __loader__)
(print "spec:" __spec__)
(print "file:" __file__)
(print "cached:" __cached__)
```
prints
```
$ hy .
name: <run_path>
doc: Test tool to dump __spec__, __loader__, and other metadata
package: 
loader: <hy.importlib.bootstrap.HyLoader object at 0x7f7c2ff00c88>
spec: ModuleSpec(name='__main__', loader=<hy.importlib.bootstrap.HyLoader object at 0x7f7c2ff00c88>, origin='/home/simon/src/hy/dumpers/__main__.hy')
file: /home/simon/src/hy/dumpers/__main__.hy
cached: /home/simon/src/hy/dumpers/__pycache__/__main__.cpython-36.hyc
```

(I'm also playing with changing the bytecode cache extension to `.hyc` at the moment. I won't try to get that merged in - well, unless you guys like that idea - but I've got some ideas on some extra information we can store in the cache that would justify changing the extension).

**Comment by vodik** [comment]
Going to close this in favour of a bigger issue.
