### ISSUE TITLE
Add Simon Gomizelj to core

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1521]
@vodik has been completing [a lot of difficult work](https://github.com/hylang/hy/pulls?q=is%3Apr+author%3Avodik). @hylang/core?

**Comment by Kodiologist** [comment]
The ayes have it. @paultag, would you do the honors?

**Comment by Kodiologist** [comment]
@paultag pls.

**Comment by paultag** [comment]
Gah. Will do, congrats!

**Comment by paultag** [comment]
Done, thanks for all your work, @vodik!
