### ISSUE TITLE
Import failures prevent from re-trying

### ISSUE THREAD

**Issue by etanol** [hylang/hy#1523]
During development, it is common to import faulty modules from the *repl*.  If a Hy module fails to load due to a `HyTypeError` or `LexException`, it cannot be loaded again until the *repl* is restarted.

There is a different exception treatment [in the importer][l].  One of the exception blocks is **not** cleaning up `sys.modules` before returning and that leaves a trace of the failure.

[l]: https://github.com/hylang/hy/blob/c1e5c3e48ca68ad2372e1fd6dca5a1dda9419e9b/hy/importer.py#L114-L122

**Comment by etanol** [comment]
The root cause of this is somehow also related to the root cause of #1134.  However, the fix is different.

**Comment by vodik** [comment]
If you're interested, dig into #1514 and #1518. I started digging into this a few weeks ago and there's a lot of problems with the loader.

**Comment by etanol** [comment]
I think efforts should go into completing #1518.  Hy's importer is not even compliant with [PEP-0302](https://www.python.org/dev/peps/pep-0302), therefore it's a matter of implementing it right in order to match the expectations of the average Python user.

**Comment by brandonwillard** [comment]
This should be closed by #1672 (and/or after #1683 for Python 2.7).

**Comment by etanol** [comment]
Definitely.
