### ISSUE TITLE
Expose pytest integration as a plugin

### ISSUE THREAD

**Issue by vodik** [hylang/hy#1526]
So, was going to put this off until I got some of my other ideas completed, but someone just opened an issue on an old project I started the last time I was playing with Hy: https://github.com/vodik/hytest/issues/1

That project was me fiddling with writing a pytest plugin that integrated Hy into pytest.

But we already do this. So, my proposal is to do the following:

- Move the Hy specific logic out of `conftest.py` and move it somewhere inside the `hy` package (say `hy.contrib.pytest_plugin`)
- Update `conftest.py` to use `pytest_plugins = ['hy.contrib.pytest_plugin']`

Now we have two options for exposing this to the general pytest community:

1. Hy itself could register a pytest plugin directly as an entry_point.
2. Publish another package under hylang organization called something like `pytest-hy` that registers a pytest plugin which contains a single line along the lines of:

```python
from hy.contrib.pytest_plugin import *
```

I'm more in favour of the later, as its more explicit. It is also how I've seen other libraries do it, for example [pytest-aiohttp](https://github.com/aio-libs/pytest-aiohttp/blob/master/pytest_aiohttp/__init__.py)

We could also promote a few useful functions like `can_compile`, `can_eval`, etc as pytest fixtures for other projects to reuse.

**Comment by Kodiologist** [comment]
Sounds cool. I'd lean toward option 1 because otherwise we'd create a lot of organization and boilerplate (a GitHub repo, a PyPI package, etc.) for a one-liner. Users will already have to add "hy.contrib.pytest_plugin" to their `pytest_plugins`, which seems explicit to me.

I would name it `hy.extra.pytest_plugin` or just `hy.pytest_plugin` rather than `hy.contrib.pytest_plugin`.

**Comment by vodik** [comment]
We can start with option 1 and move to option 2 if it ever becomes a problem with it being a default.

**Comment by arjaz** [comment]
Hi!
I created a [plugin](https://pypi.org/project/pytest-hylang/) for pytest for my needs which is based on the hy's conftest.py!
I'll be glad to see it integrated.

**Comment by Kodiologist** [comment]
Cool, thanks. Perhaps we'll do that.

**Comment by Kodiologist** [comment]
At this point, you can get pytest working with Hy with about 5 lines of configuration, so [I've documented them on the wiki](https://github.com/hylang/hy/wiki/Compatibility-tips), and a plugin seems like overkill.
