### ISSUE TITLE
Triple-quoted docstrings trigger internal compiler bug

### ISSUE THREAD

**Issue by saketh** [hylang/hy#1533]
If I accidentally use triple quotes in my docstrings (say, when playing with the Hy tutorial and assuming too much similarity to Python class docstrings), I trigger an internal compiler bug (`IndexError: string index out of range`), rather than a more readable Hy syntax error.

I first saw this in v0.14 and am able to replicate it in the bleeding-edge commit b023ebd0b5340a666df83e3fc0b72d7734636e04.

(Maybe the discussion in #1527 is relevant.)

**Comment by gilch** [comment]
I am unable to verify. Can you provide a minimal example? Does this appear in the repl, or just .hy files?

We've noticed some issues with stale .pyc files after upgrades. Can you reproduce in a bleeding-edge install in a fresh virtual environment?

**Comment by gilch** [comment]
No wait, I see it. It's only class docstrings, not function docstrings.

**Comment by gilch** [comment]
Minimal example:
```
(defclass Foo [] "doc" "")
```
That's not supposed to fail.

**Comment by vodik** [comment]
That has nothing to do with docstrings, this fails the same way:

```clojure
(defclass Foo [] "doc" 42)
```

And then there's some other weirdness in how classes compile:

```
$ hy - <<<'(defclass Foo [] "test" test)'
class Foo:
    __doc__ = 'test'

```

Where did `test` go?

**Comment by vodik** [comment]
This might be the root of the problem:

```
=> """test"""
""
```

**Comment by Kodiologist** [comment]
>     => """test"""
>     ""

I don't know if you meant to imply otherwise, but just to be clear, this example is correct. The input is parsed as `"" "test" ""` and the REPL prints only the final value.

**Comment by vodik** [comment]
Oh that makes sense. I expected it to fail (or work like Python), but I guess there's no requirement for white space between expressions.

**Comment by saketh** [comment]
It seems like the issue is with atoms in the body of `defclass` expressions, and has nothing to do with triple quotes as I had initially thought, as @vodik insightfully noted.

For example, if I just skip the `macroexpand` as in the [attached patch](https://github.com/hylang/hy/files/1813350/defclass_atom_body.patch.txt) (which probably breaks the compiler logic, so isn't a fix!), then the atoms don't choke the `defclass` expansion.

The offending `defclass`es with atoms in their bodies, like `(defclass Foo [] "doc" 42)`,  then compile just fine.

I just started looking at Hy today, so I don't yet have an intuition for what might be breaking — perhaps the iterated `macroexpand_1`?

**Comment by vodik** [comment]
@saketh I think I know. The error gives a bit more information:

    TypeError: 'HyInteger' object does not support indexing
Compilation traceback:

And its tripping up here:

    if expr[0] == HySymbol("setv"):

In https://github.com/hylang/hy/blob/b023ebd0b5340a666df83e3fc0b72d7734636e04/hy/compiler.py#L2033-L2048

Which is probably called from here lower in the `defclass` compiler:

https://github.com/hylang/hy/blob/b023ebd0b5340a666df83e3fc0b72d7734636e04/hy/compiler.py#L2085-L2086

`macroexpand` is probably a red herring as it should have no effect in this case:

```clojure
=> (macroexpand "test")
"test"
=> (macroexpand 42)
42
```

The problem is likely that we expect expressions inside classes to be all `HyExpressions`, but don't actually check for it. Note we dig right into `expr[0]` without first checking of `isinstance(expr, HyExpression) and len(expr) >= 1` as you'll see it lots of other places in the code base.

**Comment by vodik** [comment]
@saketh got a fix, let me put it up:

```
=> (defclass Foo [] "test" 41)
  File "<input>", line 1, column 25

  (defclass Foo [] "test" 41)
                          ^-^
HyTypeError: expected an expression.
```

**Comment by gilch** [comment]
> Where did `test` go?

Look at this:
```Python
>>> class Hi:
	print("hi")

	
hi
```
```
=> (defclass Hy [] (print "hy"))  ; Nothing!
=>
```
This is another bug. The statement is completely dropped. The `defclass` body should execute all statements for possible side-effectds, not just assignments.
