### ISSUE TITLE
->> can duplicate an argument when called in a macro

### ISSUE THREAD

**Issue by tuturto** [hylang/hy#1537]
I came across a bug (feature) that I can't really understand. In macros, threading with ``->>`` into a ``tuple`` gives error "TypeError('tuple() takes at most 1 argument (2 given)',)" if I have ``tuple`` as expression. Instead, if I have that as just a symbol (ie. without enclosing parentheses), the error isn't raised.

Looking into code, I thought that the both would result the same code. Both ``(->> body (tuple))`` and ``(->> body tuple)`` should turn into ``(tuple body)``. This has been around at least since 0.12.1, so I don't expect it to be anything new.

Minimal example I could come up with:
```
(hy-master)tuukka@eevertti:~$ hy
hy 0.14.0+48.gcb72a8c using CPython(default) 3.4.3 on Linux
=> (defmacro not-ok [&rest body]
...   (setv uniques (->> body
...                      (tuple)))
...   `(print "ok"))
<function _hy_anon_var_1 at 0xb6a53a04>
=>
=> (not-ok (foo bar (baz)))
  File "<input>", line 1, column 1

  (not-ok (foo bar (baz)))
  ^----------------------^
HyMacroExpansionError: expanding `not-ok': TypeError('tuple() takes at most 1 argument (2 given)',)


=> (defmacro ok [&rest body]
...   (setv uniques (->> body
...                      tuple))
...   `(print "ok"))
<function _hy_anon_var_1 at 0xb6a47b24>
=>
=> (ok (foo bar (baz)))
ok
```

**Comment by Kodiologist** [comment]
A smaller example:

   $ hy --spy
   => (defmacro m [] (->> x (f)))
   import hy
   hy.macros.macro('m')(lambda hyx_ΔampersandΔname: f(x, x))

Notice the two copies of `x`.

I'm working on a PR now.

**Comment by gilch** [comment]
Possibly related to #1424 and #1423.

We can whack-a-mole these mutability bugs as they appear, but we're clearly not testing for them well enough. Immutable Hy Models would fix all of this, but that's a very breaking change. I don't know that rewriting the compiler to copy everything before modifying it is any easier or more efficient though.

**Comment by Kodiologist** [comment]
> Immutable Hy Models would fix all of this, but that's a very breaking change.

It would probably be more of a hassle for us, in terms of rewriting parts of the compiler, than for users, who I expect are only relying on mutable Hy models in a minority of macros. Macros typically use the syntax quote to construct new models.

**Comment by tuturto** [comment]
I have bunch of macros that rely on mutable Hy models, but it wouldn't be big hassle to rewrite them I suspect. I rather have immutable Hy models, if it will help preventing strange bugs like these (this one had me scratching my head for a while)
