### ISSUE TITLE
Pygments Hy lexer needs improvements

### ISSUE THREAD

**Issue by vodik** [hylang/hy#1541]
See #1522, all remaining syntax highlighting problems seem to be deficiencies in their lexer.

Issues:

- [ ] Hy doesn't lex unicode literals: [Issue 1422][1422]
- [ ] Hy lexer should accept colons inside identifier: [PR 754][754]

  [1422]: https://bitbucket.org/birkenfeld/pygments-main/issues/1422/hy-doesnt-lex-unicode-literals
  [754]: https://bitbucket.org/birkenfeld/pygments-main/pull-requests/754/hy-lexer-should-accept-colons-inside/diff

**Comment by vodik** [comment]
Digging into this a bit more, looks like the hylang pyments lexer has specific problems with lexing symbols with colons in the middle of them (trailing or embedded). These are both legal identifiers and valid for Python output, so easy patch to the lexer.

After that's done, there's still the issue of unicode literals, which I don't know how to fix.

**Comment by vidjuheffex** [comment]
updated link for the first issue: https://github.com/pygments/pygments/issues/1126

**Comment by Kodiologist** [comment]
This kind of thing should be tracked on pygments/pygments, not here, and we already have an issue there.
