### ISSUE TITLE
unable to access attributes on complex numbers, possibly type bug.

### ISSUE THREAD

**Issue by waigx** [hylang/hy#1548]
I am not sure if I am doing it right in `hy`:
```
hy 0.14.0 using CPython(default) 3.6.4 on Darwin
=> (.imag (* 1+1j 2+9j))
Traceback (most recent call last):
  File "/hy/importer.py", line 201, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
TypeError: 'float' object is not callable
```

Actually if I do the similar thing in `python` 2 or 3:
```
>>> ((1+1j) * (2+9j)).imag
11.0
```

Regular complex number calculations work fine:
```
=>  (* 1+1j 2+9j)
(-7+11j)
```

Sorry if I have missed something.

**Comment by Kodiologist** [comment]
`(.imag x)` in Hy means `x.imag()` in Python. You want `x.imag` or `(. x imag)`.

**Comment by waigx** [comment]
@Kodiologist - just tried and seemed still doesn't work

**Comment by Kodiologist** [comment]
What exactly did you try? In what sense did it fail to work?

**Comment by waigx** [comment]
@Kodiologist -- sorry my bad. I was should have use `(. x imag)`
