### ISSUE TITLE
Rewriting Hy on top of Perl instead of Python 

### ISSUE THREAD

**Issue by kirbyfan64** [hylang/hy#1562]
Many of our issues have been due to Python's strict semantics. This leads me to wonder: why not just rewrite the whole thing in Perl? 

Advantages:

- We probably wouldn't even need a custom parser. Literally everything is valid Perl. 
- Semantics issues? No problem! We'll just add a new way to things each time. 
- Better backwards compatibility, related to the above. 
- We don't have enough documentation. Trying to explain all the intricacies will definitely bolster the documentation effort. 

Thoughts?

**Comment by tuturto** [comment]
Should we aim for Perl 5 or Perl 6?

**Comment by kirbyfan64** [comment]
Why not both?

**Comment by kirbyfan64** [comment]
Ok, one of:

- Hy.js - Written in React using a purely functional, statefulness NoSQL bytecode cache. 
- Hy.rs - Now the compiler can check our code to make sure it doesn't violate lifetimes, human rights, or the Amazon rainforest. 
- iHy - Written in Swift, and integrates with Apple's BodyOdorKit to tell you when you need to take a break, stretch, and get a life.

**Comment by paultag** [comment]
:shipit:

**Comment by vodik** [comment]
How about target rpython and build our own JITed runtime? (e.g. like [pixie](https://en.wikipedia.org/wiki/Pixie_(programming_language)))

**Comment by kirbyfan64** [comment]
When I tried sorting priorities, `import antigravity` came out on top, so we should probably stick with Python.
