### ISSUE TITLE
#@() throws an `IndexError`

### ISSUE THREAD

**Issue by vodik** [hylang/hy#1565]
Should probably throw a nicer error message like `(with-decorator)` does

**Comment by gilch** [comment]
I'd like to get rid of `#@` altogether. #952

**Comment by allison-casey** [comment]
fixed in #1758

**Comment by Kodiologist** [comment]
Hang on; don't close a bug if there's no test for it.

**Comment by allison-casey** [comment]
good point, will add a test today
