### ISSUE TITLE
read-str doesn't use the whole input

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1591]
=> (read-str "1")
    HyInteger(1)
    => (read-str " 1")
    HyInteger(1)
    => (none? (read-str "\n1"))
    True
    => (read-str "1 2")
    HyInteger(1)

This behavior may be consistent with `read`, but it doesn't seem very useful and is likely to be surprising. I would expect the first expression after any leading whitespace to be returned, and any remaining expressions to raise an error.

**Comment by gilch** [comment]
Clojure
```Clojure
user=> (read-string "1 2")
1
```
It's the same as Hy, so I'm not willing to call this a bug.

sbcl
```Lisp
* (read-from-string "1 2")

1
2
```
Common lisp does the whole string at once, returning multiple values. I suppose the Python equivalent of a `(VALUES ...)` multiple return would be a tuple. But then should the usual single-return also be wrapped? Maybe we could have a separate `read-string-all` that always returns a tuple. I think MzScheme had something similar.

Emacs Lisp
```elisp
ELISP> (read-from-string "1 2")
(1 . 1)
ELISP> (read-from-string "(+ 1 2) (- 3 4)")
((+ 1 2)
 . 7)
```
Emacs returns a pair. The car is the `OBJECT-READ` (parsed code) and the cdr is the `FINAL-STRING-INDEX`, i.e. where it left off. `read-from-string` also takes optional `START` and `END` arguments, so you could read a string one object at a time in a loop.

So there are certainly other approaches.

**Comment by allison-casey** [comment]
closed in #2242 use `hy.read-many` 
```clojure
=> (hy.read "1 2")
'1
=> (list (hy.read-many "1 2"))
['1 '2]
```

**Comment by Kodiologist** [comment]
True, although this may be worth pointing out in the documentation. The new `read` has no docstring, in fact, which in hindsight is probably a mistake.

**Comment by allison-casey** [comment]
It definitely is. I'll go ahead and add one since I'm already working on the dotted symbol stuff anyways
