### ISSUE TITLE
hy2py syntax error with toolz.partial

### ISSUE THREAD

**Issue by daniel-severo** [hylang/hy#1600]
I've been having a pretty good experience using [toolz](http://toolz.readthedocs.io/en/latest/api.html) with hylang, although the following scenario is pretty confusing:

**file.hy**
```clojure
(import [toolz [partial]])


(defn eq [x]
  (partial = x))
```

**file.py** (converted with `hy2py file.hy > file.py`)
```python
from hy.core.shadow import =
from toolz import partial


def eq(x):
    return partial(=, x)
```

When executing `file.py`:

```
  File "file.py", line 1
    from hy.core.shadow import =
                               ^
SyntaxError: invalid syntax
```

I was able to bypass it by changing the `eq` function to, although I wish I didn't have to :/

```clojure
(defn eq [x]
  (partial (fn [a b] (= a b)) x))
```

**Comment by Kodiologist** [comment]
Fixed in master (as of #1517). Don't forget to check whether a bug still exists in master before reporting.
