### ISSUE TITLE
the arguments order of ap-compose is counter-intuitive

### ISSUE THREAD

**Issue by pyx** [hylang/hy#1605]
Of all the functional ([programming paradigm](https://en.wikipedia.org/wiki/Function_composition_(computer_science)) and/or [mathematics](https://en.wikipedia.org/wiki/Function_composition)) literatures and conventions (**_unscientific guesswork by myself_**, think textbooks teaching programming/lambda calculus, existing libraries), `compose` works from right to left.

Provided `compose` is the function composition operator, 
`((compose f  g) x)` should means `(f (g x))`

I understand that `ap-compose` is by no means a `compose` function (or a macro, for that matter) in the traditional functional programming sense as it takes forms not functions, but the name suggests otherwise, this is **counter-intuitive** at best and **error-prone** at worst to someone already familiar to functional programming (that is, 90% of hy's user base, okay, I am also guessing here, but you get the point).

Thus, I suggest, either

#### Option 1
Changing the name of the macro into `ap-pipe-fn`, not only the order is in line with `ap-pipe`, but also emphasize there is a function being created, the only true difference between the two.

#### Option 2
Reversing the order of the arguments, and name it `ap-compose-fn`.
In this case, we have `ap-pipe` but no `ap-compose`, and `ap-compose-fn` without the counterpart, `ap-pipe-fn`.  This feels incomplete and the choices are arbitrary, we should also add `ap-compose` and `ap-pipe-fn`.

I can make a PR if needed, albeit it is quite a small change.

**Comment by Kodiologist** [comment]
What's the point of `ap-compose` in the first place? The value of the typical composition operator is that given some existing named functions `f` and `g`, you can write `(compose f g)` instead of `(fn [x] (f (g (x)))`. But an anaphoric composition operator only lets you write something like `(ap-compose (+ it 1) (* it 3))`, which you could just as easily write `(fn [it] (+ (+ it 3) 1))`. You can't do point-free programming with an anaphoric function.

**Comment by pyx** [comment]
@Kodiologist 

> What's the point of ap-compose in the first place? The value of the typical composition operator is that given some existing named functions f and g, you can write (compose f g) instead of (fn [x] (f (g (x))). But an anaphoric composition operator only lets you write something like (ap-compose (+ it 1) (* it 3)), which you could just as easily write (fn [it] (+ (+ it 3) 1)). **You can't do point-free programming with an anaphoric function**.[emphasis mine]

**I am actually 100% with you in this regard, especially the last sentence**. (Proof: if you remember what sides I was taking when I added `comp` into stdlib).  I did not follow the development of Hy lately, thus have no idea about _when_ and _why_ regarding this `ap-compose`, it might even existed before `comp`.

But that's not the point of this issue, I should make it clear that since `ap-compose` is already there, we should at least make it consistent.

**Comment by pyx** [comment]
Re-read @Kodiologist's make me believe removing `ap-compose` might be a better idea, it can be done with `(fn [x] (ap-pipe x (+ it 1) (* it 3)))` if so desire. (I confess, I wouldn't do that :yum:)

**Comment by Kodiologist** [comment]
Actually, `ap-pipe` seems no more useful than `ap-compose`, for the same reason.

**Comment by pyx** [comment]
Yes. Like I said here (#1179), `pipe` as a function is more useful.

Quoting myself

> Assuming we are building a file processing pipeline, and have these functions:
> `read-file` `write-file` `parse-file` `rename` `transform-phase-1` `transform-phase-2` `transform-phase-3` , etc.
> They are all of type
> 
> `file -> file`
> We can build the pipeline like this:
> 
> ```clojure
> (setv process
>   (pipe
>     read-file
>     parse-file
>     transform-phase-1
>     transform-phase-2
>     transform-phase-3
>     rename
>     write-file))
> ```
> 
> It's just more natural to read in this case than `comp`.

**Comment by pyx** [comment]
I have a real use case, cause I wrote a static site generator in Hy that's powering a few websites, in the top level of the program, it's similar to the `process` function above, assembling each phase into a pipeline, except that I am using monadic functions, so the code is a chain of `bind` instead, some think like:

```clojure
(setv compile
  (>=>
    parse-rst
    parse-md
    remove-private
    add-tag-pages
    add-category-pages
    add-archives
    add-index))

(setv generate (>=> render add-extra-assets))

(setv build (>> source (ignore hidden?) compile generate output))
```

Each step, `parse-rst`, `compile`, `generate`, `output`, etc, is a monadic function.

If I am chaining normal (not monadic) functions here, `pipe` (in place of `>=>`[1]) is the perfect fit.

[1]: `>=>` is the operator of the left-to-right Kleisli composition of monads, alias of [k-pipe](https://hymn.readthedocs.io/en/latest/api/operations.html#hymn.operations.k_pipe) in hymn.

**Comment by Kodiologist** [comment]
Would you like to open a PR that just removes `ap-compose` and `ap-pipe`?

**Comment by pyx** [comment]
[Done](https://github.com/hylang/hy/pull/1606).
