### ISSUE TITLE
we seem to be requiring astor==0.7.0, but pip installs 0.6.2

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1607]
When you install Hy in a fresh venv, you get astor==0.6.2, which is the latest on PyPI. But we've also got a dependency link to git+https://github.com/berkerpeksag/astor.git#egg=astor-0.7.0

This seems inconsistent.

**Comment by Kodiologist** [comment]
Unfortunately, you need the `--process-dependency-links` option to `pip install` in order for the dependency link to actually work. I don't know a way around this, but hopefully there will be a new astor release before Hy 0.15.0.

**Comment by berkerpeksag** [comment]
FYI, I want to fully support Python 3.7 in astor 0.7 and the only blocker for now is https://github.com/berkerpeksag/astor/pull/102.

**Comment by Kodiologist** [comment]
> @Kodiologist even with the --process-dependency-links option I'm getting 0.6.2. How have you installed 0.7.0?

Did you see something like this?



    $ pip install --process-dependency-links -e .
    Obtaining file:///tmp/tenv/hy
    DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.                                                         
    Collecting rply>=0.7.5 (from hy==0.14.0+132.geec4a17)
      Cache entry deserialization failed, entry ignored
      Using cached https://files.pythonhosted.org/packages/02/e9/05c04324d1bd0581df638d34415d5549f054830534dda60ddc1976f41006/rply-0.7.5-py2.py3-none-any.whl
    Collecting astor (from hy==0.14.0+132.geec4a17)
      Cloning https://github.com/berkerpeksag/astor.git to /tmp/pip-install-i7jo09mj/astor
    DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.                                                         
    Collecting clint>=0.4 (from hy==0.14.0+132.geec4a17)
      Cache entry deserialization failed, entry ignored
    Collecting appdirs (from rply>=0.7.5->hy==0.14.0+132.geec4a17)
      Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
    Collecting args (from clint>=0.4->hy==0.14.0+132.geec4a17)
      Cache entry deserialization failed, entry ignored
    Building wheels for collected packages: astor
      Running setup.py bdist_wheel for astor ... done
      Stored in directory: /tmp/pip-ephem-wheel-cache-t1h8d6wc/wheels/1b/17/42/63a7a063e0be10a2e32871c9cbb423ba837bac9af6478ff03e
    Successfully built astor
    Installing collected packages: appdirs, rply, astor, args, clint, hy
      Running setup.py develop for hy
    Successfully installed appdirs-1.4.3 args-0.1.0 astor-0.6.2 clint-0.5.1 hy rply-0.7.5

Even though the installed package is detected by pip as being 0.6.2, you're actually getting astor's current `master`, which you can verify by looking at the installed code. I put `egg=astor-0.7.0` at the end of the dependency link to make it possible to "upgrade" from the real 0.6.2, although I'm not sure this works. There is no real astor 0.7.0 (at least, not yet).

**Comment by gilch** [comment]
I got
```
DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.
Requirement already satisfied: rply>=0.7.5 in c:\users\me\envs\hylang\lib\site-packages (from hy==0.14.0+143.g6cc74ac.dirty) (0.7.5)
Collecting astor==0.7.0 (from hy==0.14.0+143.g6cc74ac.dirty)
  Cloning https://github.com/berkerpeksag/astor.git to c:\users\me\appdata\local\temp\pip-install-590d2q8j\astor
  Requested astor==0.7.0 from git+https://github.com/berkerpeksag/astor.git#egg=astor-0.7.0 (from hy==0.14.0+143.g6cc74ac.dirty), but installing version 0.6.2
```
I guess that's master then.
