### ISSUE TITLE
Perhaps HyFloat and HyComplex should convert their input to floating point later

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1610]
HyFloat and HyComplex currently convert their input to `float` and `complex`, respectively, in their constructors. This means that precision in the input that can't be represented in 64-bit floating point is lost, so if you do something like

    (import decimal)
    (deftag d [x] `(decimal.Decimal ~(str x)))
    #d .1234567890123456789012

then you get `Decimal('0.12345678901234568')`. If we represented HyFloat and HyCompile as strings or sequences of digits or something like that, only converting to `float`s or `complex`es when they're compiled, we could avoid this. Likewise, macros could tell the difference between `1.0` and `1.00`, `10.0` and `1e1`, etc.

**Comment by gilch** [comment]
Or you could use quotes.
```
=> #d".1234567890123456789012"
decimal.Decimal('.1234567890123456789012')

Decimal('0.1234567890123456789012')
```
It's just one character longer, since you don't need the space now.

Really, for a lot of these tag macro applications, you could even use an unquoted symbol.  Prefix it with a character so it doesn't get parsed as a number.
```
(deftag d [x] `(decimal.Decimal ~(-> x name (cut 1))))
```
```
=> #d !0.1234567890123456789012
decimal.Decimal('0.1234567890123456789012')

Decimal('0.1234567890123456789012')
```
Again, just one character longer. You could even dispatch to different constructors based on that first character, so you can reuse the tag.

**Comment by gilch** [comment]
Actually, in the particular case of `Decimal`, we could extend Hy's literal syntax to use the `M` suffix like Clojure does. We've added more literals that Python doesn't have before, like the fractions `1/2` and `Inf`.

**Comment by Kodiologist** [comment]
True, but it's always nicer to be able to implement new features with things like macros than extending the lexer and parser. It helps to advertise the utility of metaprogramming.

**Comment by Kodiologist** [comment]
This is probably too weird. It should be enough for numeric models to hold a value rather than the literal syntax. So, one can use a string (or a reader macro, once reader macros exist) for this instead.
