### ISSUE TITLE
Hy terminal seems to get blocked up by async printing 

### ISSUE THREAD

**Issue by riatzukiza** [hylang/hy#1628]
When using the hy command as a terminal with async operations, soon as something is printed, I cannot enter any input to hy with out with out escaping out, like there is an incomplete expression
```lisp
;; ...sent in a bunch of text with emacs funcions, some are async events.
=> ... ... ... ... => => ... ... ... => => Logged in as
Duck
449279570445729793
(print "yo") ;; I try running another command after the async



  C-c C-c=> (print "yo")
yo
=> 
```

**Comment by Kodiologist** [comment]
Can you provide a reproducible example?

**Comment by vodik** [comment]
What does async printing mean here? `asyncio`? threads?

**Comment by riatzukiza** [comment]
I used the discord.py library
```lisp
(import discord)
(import asyncio)
(with-decorator client.event
  (defn/a on_ready []
    (print "Logged in as")
    (print client.user.name)
    (print client.user.id)))
```

to produce the above, in an emacs terminal

**Comment by Kodiologist** [comment]
That could be an Emacs issue. Does it work in a real terminal? Also, the equivalent Python code works okay in Python's native REPL, right?

**Comment by kirbyfan64** [comment]
Yeah, I personally think this is probably an Emacs issue. I'm not at a computer right now, but it'd probably be easy to repro by using `asyncio.ensure_future` on a future that sleeps and then prints stuff.

**Comment by Kodiologist** [comment]
> Also, have you checked that the equivalent Python code works okay in Python's native REPL?

**Comment by riatzukiza** [comment]
It does not...

**Comment by Kodiologist** [comment]
Okay then, presumably this is an issue with Python, not Hy.
