### ISSUE TITLE
Edge case with symbol contains special characters (/ . *, etc.) and import

### ISSUE THREAD

**Issue by pyx** [hylang/hy#1629]
I found an edge case.
Let's say, if we have a symbol `/.*`, it worked in REPL
```clojure
=> (setv /.* 42)
=> /.*
42
```
If it is in a module, then importing will fail if we name it directly
```bash
$ cat test.hy
(setv /.* "Hidden Files")
```
```clojure
=> (import [test [/.*]])
Traceback (most recent call last):
  File "/home/pyx/.virtualenvs/hy/lib/python3.6/site-packages/hy/importer.py", line 198, in hy_eval
    eval(ast_compile(_ast, "<eval_body>", "exec"), namespace)
  File "<eval_body>", line 1, in <module>
ImportError: cannot import name '/.*'
=> (import test)
=> test./.*
'Hidden Files'
=> (import [test [*]])
=> /.*
'Hidden Files'
```

Notice that with both qualified name and `import all` worked, but explicit import failed.

> **Background, in case you are curious why I came up such a weird name, can be skipped.**
> The static site generator I wrote, implements a DSL, there is a function to test file name patterns, when I wrote a predefined function for hidden files, I thought the function name `/.*` is both _ingenious and insane_ . Something like:
> ```clojure
> (defn name= [&rest patterns]
>   "create a function that test if the name of document matches ``patterns``"
>   (fn [document]
>     (-> document get-filename (match? #* patterns))))
> (setv
>   hidden-file? (name= ".*")
>   /.* hidden-file?)
> ```
> 
> Everything went well, I could write the following and be proud of myself :rofl:  
> ```clojure
> (remove /.* files)
> ```
> ... until I tried to import it from other file, then I encountered the problem described above.

**Comment by Kodiologist** [comment]
You realize that `/.*` refers to the attribute `hyx_XasteriskX` of the shadow `/` operator, right? You shouldn't be setting attributes of shadow operators. And Hy doesn't implement importing dotted names. I'm not sure what exactly `(import [foo [bar.baz]])` would do if it worked.

**Comment by Kodiologist** [comment]
The change in the syntax of `import` shouldn't affect this because all it will do is make `(import test [/.*])` work like `(import [test [/.*]])`.

Do you still believe there is a bug here? If so, what exactly do you think should be different?

**Comment by pyx** [comment]
Thanks. I am fine with disallowing . (dot) in symbols in import form except expressing relative import path, I am just thinking, maybe better documentation and/or error message can reduce the surprise factor.

**Comment by Kodiologist** [comment]
Okay, it would make sense for `import` and `require` to protest if you try to import a name with a dot in it.

**Comment by pyx** [comment]
Yes, that will help.

While we're at it, it might help to also address `(require [.macros [some-macro]])`, we should mention that in documentation somewhere, the current behaviour, `ModuleNotFoundError: No module named HySymbol('.macros')`, is surprising.
