### ISSUE TITLE
#; as discard syntax instead of #_

### ISSUE THREAD

**Issue by pyx** [hylang/hy#1639]
I didn't know this feature as it's not mentioned in documentation until I saw #1636 
It's hard to search on `#_` so I bisected the repository and found out that it's been added quite a while https://github.com/hylang/hy/commit/203965d0fa55cedbb9af6249c7c2aee4d54ed983, since last Aug.

But still, I suggest using `#;` as descard syntax instead of `#_`.

#### Rationale
- `;` is the comment character (my wording maybe wrong) already
- `#;` is being used in scheme ([SRFI-62](https://srfi.schemers.org/srfi-62/srfi-62.html)), some implementations, [Chichen](http://wiki.call-cc.org/man/4/Non-standard%20read%20syntax#expression-comment), [Guile](https://www.gnu.org/software/guile/manual/html_node/SRFI_002d62.html)
- free up `_`  (I know it can be shadowed, BTW) as user defined tag macro, in the case of i18n, function `gettext` is most likely imported as `_`,  adding `(_ ...)` to every single string to existing code base is no fun, users can then define a tag macro, aptly named `#_`, as

```clojure
(deftag _ [str]
  `(_ ~str))
```

;; using new import syntax #1614 
```clojure
(require .macro [_])
(import gettext [gettext :as _])

...

(defn run []
  (message-box #_ "hello world"))
```
and be done with it.

The cost of rename should be minimal, since it's not mentioned in documentation, I doubt many people using it currently, rename should not cause much trouble, while `;` as tag macro is impossible to define by users, so nobody using it.

**Comment by pyx** [comment]
Edit: I was unaware of this section http://docs.hylang.org/en/stable/language/api.html#discard-prefix , it is documented already. I am sorry.

**Comment by pyx** [comment]
I sort of understand the reason `_` being chosen in the first place, originated from a way to signify the value is of no importance, which in term, borrowed from ML languages.

In both python and strict MLs (OCaml for example), the expression being bound to `_` is evaluated, then the result is discarded, while `#_` as it is now, the next expression is discarded right away, not even being turned into AST, so I believe, in this regard, `#;` is actually telling what really happened behind the scenes.

**Comment by gilch** [comment]
`#_` is the discard prefix used by Clojure and EDN, which is where we got the idea from in the first place. `#;` would have been a fair choice for Clojure, I suppose, but we've mostly been following Clojure's syntactic conventions, not Scheme's.

**Comment by kirbyfan64** [comment]
`#;` would also be harder for editors to highlight.

**Comment by pyx** [comment]
So this is an official "no", am I right?
If so, I will close this.

**Comment by pyx** [comment]
Thanks for the clarification. I might use `#tr` or `#trs` for `gettext` then, and `#i18n` for extra fun :). I will close this at the moment.  In case someone else bring this up again, I will still be voting for `#;`
