### ISSUE TITLE
Don't include the namespace in the import's name for hy models.

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1644]
Brandon Rhodes expressed it well at PyCon
https://youtu.be/x-kB2o8sd5c?t=1048

In his example, 
```Python
import piano
piano.Bench()      # yes!
```
Is preferable to
```Python
import piano
piano.PianoBench()  # no!
```
We should not bake the namespace into the name itself.

Similarly for the Hy models, we should have 
```
hy.List
hy.Expression
hy.Dict
```
etc. not
```
hy.HyList
hy.HyExpression
hy.HyDict
```
like we have now.

**Comment by Kodiologist** [comment]
Contrast with #1045.

**Comment by kirbyfan64** [comment]
I'm a bit out of the loop here, but are we still importing these models automatically? If so, then the names would be cause for some nasty potential conflicts...

**Comment by kirbyfan64** [comment]
We could always import `hy` automatically, which also pollute the global scope a bit less.

**Comment by gilch** [comment]
We could also leave `eval` in there but not auto import `from hy.core.language import eval` like we do now. 

Then Hy's eval would be `hy.eval`, (not `hy.hy-eval`) and Python's builtin would just be `eval`.
