### ISSUE TITLE
Suggestion on `let` reimplementation

### ISSUE THREAD

**Issue by dluciv** [hylang/hy#1648]
Despite of #844 and friends, i think that `let` is really must-have for any LISP. No doubt that this is a problem for Python as it does not have structural scopes, but here we can try two (at least) ways as described below.

1. The way Haxe uses: mangle variable name within lexical scope for `let`. Adding line number to variable name for example. Resulting Python will be a bit unobvious or even ugly, but Python itself has no such feature. This way requires compiler change.
2. Add standard macro as listed below (actually it is the first time for me to write Hy macros, so please be patient =))

`lets.hy` file:

```
(import itertools)
(import sys)

(defn interleave [lst base ofs]
  (list-comp
    e [(, i e) (zip (itertools.count) lst)]
    (= (% i base) ofs)))

(defmacro le1 [var val code]
  (print "Performance warning: using `let` simulation" :file sys.stderr)
  `((fn [~var] ~code) ~val)
)

(defmacro lei [varvals code]
  (print "Performance warning: using `let` simulation" :file sys.stderr)
  `((fn [~@(interleave varvals 2 0)] ~code) ~@(interleave varvals 2 1))
)
```

`test.hy` file:

```
(require [lets [le1 lei]])

(le1 (, a b) (, 1 2)
  (do
    (print a b)
    (le1 (, b c) (, 20 100)
      (print a b c))
    (print a b)))


(lei [a 1 b 2]
  (do
    (print a b)
    (lei [b 3 c 4]
      (print a b c))
    (print a b)))
```

As we see there, there are two macros — `le1` for one variable, which, thanks to Python, allows using tuples though, and `lei` — just like usual LISP `let`. Names are changed here intentionally to emphatize the fact that both them are not real `let`'s, but a sort of hacks. However they do work and may be considered as something that is better than nothing =).

**Comment by Kodiologist** [comment]
You know that a version of `let` was added back in in 0.14.0, right?

**Comment by dluciv** [comment]
Oops. Missed it. `hy.contrib.walk`, right?

**Comment by Kodiologist** [comment]
Right.

**Comment by dluciv** [comment]
Yeah, nice, thank you! =)

It might however be useful to create reference from core lenguage documentation to contributed [`walk` module](http://docs.hylang.org/en/stable/contrib/walk.html) about this because I guess many of readers expect having `let` in some form...

**Comment by dluciv** [comment]
And one more comment.

It looks working ok, but it can not produce valid Python code, e.g. it creates dictionary named `_;let|1235`. Replacing `;let|` with `_let_` everywhere works, but no idea why not generate valid Python from beginnging here. Why so?

**Comment by Kodiologist** [comment]
That's fixed in #1517. Make sure to check that a bug still exists in Hy master before reporting it.

**Comment by dluciv** [comment]
Yeah, really works from master.

Actually Python code produced by those macros looks creepy a bit.

For such an example

```
(let [a 1 b 2]
  (do
    (print a b)
    (let [b 3 c 4]
      (print a b c))
    (print a b)))
```

it generates

```
_hyx_XsemicolonXletXvertical_lineX1235 = {}
_hyx_XsemicolonXletXvertical_lineX1235['a'] = 1
_hyx_XsemicolonXletXvertical_lineX1235['b'] = 2
print(_hyx_XsemicolonXletXvertical_lineX1235['a'],
    _hyx_XsemicolonXletXvertical_lineX1235['b'])
_hyx_XsemicolonXletXvertical_lineX1236 = {}
_hyx_XsemicolonXletXvertical_lineX1236['b'] = 3
_hyx_XsemicolonXletXvertical_lineX1236['c'] = 4
print(_hyx_XsemicolonXletXvertical_lineX1235['a'],
    _hyx_XsemicolonXletXvertical_lineX1236['b'],
    _hyx_XsemicolonXletXvertical_lineX1236['c'])
print(_hyx_XsemicolonXletXvertical_lineX1235['a'],
    _hyx_XsemicolonXletXvertical_lineX1235['b'])
```

Not sure it is faster or slower, but with above `lei` macro resulting code looks much prettier

```
def _hy_anon_var_1(a, b):
    print(a, b)
    (lambda b, c: print(a, b, c))(3, 4)
    return print(a, b)


_hy_anon_var_1(1, 2)
```

**Comment by gilch** [comment]
The output only looks scary because gensyms haven't been updated for the new mangling rules yet. It used to be a lot prettier. #1531. This might also be improved by #1577.

We actually had something like `lei` originally, but it did weird things to `break`/`continue` and `yield`/`yield from` and it prevented us from implementing `async`/`await`.

The current (experimental) version is more like what Haxe does. I'm not completely satisfied with it. It doesn't quite work right inside class definitions. Also an immutable version like Clojure has might be faster. That way we could probably just use gensym'd locals instead of going through a dict.
