### ISSUE TITLE
Keep the who-uses-Hy page up to date

### ISSUE THREAD

**Issue by alphapapa** [hylang/hy#1649]
Is there a list anywhere of projects written in Hy? If not, I think there should be. 

On the other hand, is Hy stable enough yet (in terms of changes) to write serious projects in? Looking at the recent versions, it seems like things get changed and removed in each version. I'd like to start using it "for real," especially since `let` was put back in, but I don't know if it's practical since it seems likely to break things whenever a new version is released.

What are the long term plans for stability? Is Hy ready to settle down yet?

Thanks.

**Comment by gilch** [comment]
I don't think Hy is stable yet. It's certainly powerful enough to write a serious project now, but there are still big problems that would probably require breaking changes to fix. I'm not willing to call a version `1.0` until those are resolved.

#1542 and #1342 are critical problems. And we might need something like #277 to get macros working reliably. There are probably others.

**Comment by Kodiologist** [comment]
> Is there a list anywhere of projects written in Hy?

We have [this wiki page](https://github.com/hylang/hy/wiki/Who-uses-Hylang), but nobody's been updating it.

Like Gilch says, we're still a while away till 1.0. The language is definitely mature enough for serious use: I'm a scientist and I've been using it for data analysis for years, and [my website](http://arfer.net) is written in Hy using CherryPy. Still, I have to go back and regex-replace code when there are syntax changes, which is annoying.

**Comment by gilch** [comment]
> Is there a list anywhere of projects written in Hy?

Not really, but it's easy to ask GitHub to generate one:

https://github.com/search?l=&o=desc&q=language%3AHy&s=updated&type=Repositories

**Comment by alphapapa** [comment]
Thanks for your thoughts.  Is there any kind of timeline that the developers are aiming for with regard to a stable 1.0? I only ask because Hy is already several years old, and with as much potential as it has, I'd hate to see it go several more years without stabilizing.

**Comment by Kodiologist** [comment]
I'd like to release 1.0 in about a year, but that's probably not realistic.

**Comment by gilch** [comment]
@alphapapa we do consider pull requests. If you're good at Python (or even documentation) or know people who are, you could help speed things up.

**Comment by ekaschalk** [comment]
@alphapapa Hy can be used for serious projects, but you have to consider the tradeoff of increased productivity versus handling breaking changes when they occur (relatively often up to this point, but no fix that difficult). I use it at work for a medium-sized algorithm at 2800+ commits now, which I assume is by far the largest Hy project. This project is a solo one (though this is changing) - so I cannot comment on team reception.

Was it worth it? It's made work unquestionably more enjoyable and, now, quick, but the startup cost associated with building out hy-mode to support myself muddies it.

Once let and friends are merged and a few key issues are resolved, I think Hy has a chance at becoming more mainstream.

@gilch @Kodiologist I'm building a front-end demo-only to my work through Django and am debating whether to use Hy for it.

I'm already aware Hy can be dropped in /almost/ seamlessly, example repos exist and I've done so myself in the past already. I'm more concerned about integration with container and compute technologies, which I know very little about.

Is there any technology that Hy's approach is not compatible with?

**Comment by Kodiologist** [comment]
Not that I know. Especially with the latest Hy, since hy2py should now be 100% accurate, so you can compile your Hy code to Python and use that if you need to. It's even possible to write Hy programs this way that don't have Hy itself as a dependency.

**Comment by notagoodidea** [comment]
>   It's even possible to write Hy programs this way that don't have Hy itself as a dependency.
Even using Hy Core or similar namespaces (as stated in the documentation with the exemple of `name`) in the Hy program ? That can be great!

**Comment by Kodiologist** [comment]
> Even using Hy Core or similar namespaces

No. (Unless you copy the relevant bits into your own code, of course.)

**Comment by Kodiologist** [comment]
Having thought about it some more, I feel that trying to maintain some list of active projects in Hy or organizations that use Hy is out of scope of the maintenance of Hy itself. It would take a lot of checks of a lot of other people's projects. The wiki page can stay up, but we need not take responsibility for keeping it up to date.
