### ISSUE TITLE
Enable Mergify

### ISSUE THREAD

**Issue by jd** [hylang/hy#1658]
It seems that this repository has some proper rules and criteria define to merge pull requests. Therefore I'd like to suggest to enable [Mergify](https://mergify.io) on it to automate some of its workflow, such as auto-merging pull requests with 2 approvals and CI passing.

And let me know if you have any question.

**Comment by Kodiologist** [comment]
I'd rather not have pull requests merged automatically. Even when there are two approvals, for example, there might be some minor tweaks to be made. Merging is an important enough thing that it should require a human explicitly pressing a button.

**Comment by kirbyfan64** [comment]
I also prefer the manual merging, and our pull request volume is hardly that of e.g. CPython's, so it's not like PRs are going idle and getting buried.
