### ISSUE TITLE
comp with list of function?

### ISSUE THREAD

**Issue by xuqinghan** [hylang/hy#1666]
list_fn = [f g]
......
    ((comp list_fn) x))
TypeError: 'list' object is not callable

how to convert (comp list_fn) to (comp f g) ?

-----------------------------------------
and if use macro

```
list_expr = [HyExpression([
  HySymbol('/'),
  HyInteger(2)]), HyExpression([
  HySymbol('+'),
  HyInteger(1)])]
```

    (-> x list_expr ))
TypeError: 'list' object is not callable

what is the right way to use ((comp list_fn) x)) and (-> x list_expr ))  ?

**Comment by gilch** [comment]
Did you try `#*`?

This is Hy's issue list (for bugs and complaints), not a help forum. For help with Hy, ask on our IRC channel (may take up to a day), stackoverflow with the [hy] tag or on our mailing list.
