### ISSUE TITLE
Weird behavior of map function

### ISSUE THREAD

**Issue by falematte** [hylang/hy#1667]
Why I do not get the values? 
![selection_999 406](https://user-images.githubusercontent.com/25055204/43466535-4430b0dc-94cf-11e8-8ed2-07325d4e1076.jpg)

**Comment by gilch** [comment]
Because you're running on Python 3.

This is Hy's issue list (for bugs and complaints), not a help forum. For help with Hy, ask on our IRC channel, stackoverflow with the [hy] tag or on our mailing list.
