### ISSUE TITLE
why a redundant quote auto added?

### ISSUE THREAD

**Issue by xuqinghan** [hylang/hy#1670]
python 3.6.5 x64 with  hy-0.15.0+15.g109c0b0

I hope flatten nested list : e.g.  ['(identity) ['(/ 2) '(np.ceil)]]  ->  ['(identity) '(/ 2) '(np.ceil)]

the flatten buit-in return ['quote 'identity 'quote '/ '2 'quote 'np.ceil] , so I write one:

```
(defn flatten_list [list_in_list]
  (setv res [])
  (defn iter1 [x]
    (if (= (type x) HyList)
      (lfor item x (iter1 item))
      (.append res x)
  ))
  (iter1 list_in_list)
  res
)
```
and test in py
```
        str_input = "['(identity) ['(/ 2) '(np.ceil)]]"
        expr_input = hy.read_str(str_input) #HyExpression
        #print(expr_input)
        print('input ', hy_repr(expr_input))
        expr_parsed = util.flatten_list(expr_input)
        list_expr_res = hy_repr(expr_parsed)
        #print(expr_parsed)
        print('output', list_expr_res)
```

but  a redundant quote is added on each item:

> input  '['(identity) ['(/ 2) '(np.ceil)]]
> output [''(identity) ''(/ 2) ''(np.ceil)]

My questions are:

1 which step is the redundant "quote" be added,  is it a bug?
2 How to got the wanted result ['(identity) '(/ 2) '(np.ceil)]
3 Can let built-in "flatten"  work for this case?

**Comment by xuqinghan** [comment]
Thanks. I found the problem is list VS HyList.
the difference between python list and HyList is subtle.

1. when change the setv line by add ` or ':
from
```
(defn flatten_list [list_in_list]
  (setv res [])
  ...

```
to
```
(defn flatten_list [list_in_list]
  (setv res `[])
  ...
```

the result is just I wanted

```
input  '['(identity) ['(/ 2) '(np.ceil)]]
output '['(identity) '(/ 2) '(np.ceil)]
```

```
input  '[(identity) [(/ 2) (np.ceil)]]
output '[(identity) (/ 2) (np.ceil)]
```

2because  the ['(identity) ['(/ 2) '(np.ceil)]] is other defn is return value. I dont know how to " parse str to HySymbol " in hy and without ' outside. as:

>  ("ceil")  ->  (np.ceil) 

now I format string f"(np.{f_name})"  in py , and call hy.read_str()  return the exor to hy.

Is there a elegent way instead?

**Comment by Kodiologist** [comment]
I don't think I understand your question. Try one of Hy's support channels.
