### ISSUE TITLE
Add documentation for package management

### ISSUE THREAD

**Issue by Risto-Stevcev** [hylang/hy#1676]
What's the correct idiomatic way to publish hylang packages? should it be published on pip using `hylang-[packagename]`?

I want to write a package that uses hylang features that python doesn't have (ie: macros)

Edit: This should be added to the docs

**Comment by Kodiologist** [comment]
This is Hy's issue list. For help using Hy, try elsewhere.

**Comment by Risto-Stevcev** [comment]
@Kodiologist Apologies, I didn't phrase this well -- this is an actionable item: Adding documentation for how to package Hy packages
