### ISSUE TITLE
cut bug

### ISSUE THREAD

**Issue by acekingke** [hylang/hy#1681]
The bug of cut
```
=>  (setv collection (range 10))
from hy.core.language import range
collection = range(10L)
None

=> (cut collection)
collection[None:None:]

Traceback (most recent call last):
  File "d:\work\hy\env\lib\site-packages\hy\importer.py", line 199, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
TypeError: sequence index must be integer, not 'slice'
```

**Comment by Kodiologist** [comment]
This is just how Python 2 works, I'm afraid:

    $ python2
    Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
    [GCC 7.3.0] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> xrange(10)[:]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: sequence index must be integer, not 'slice'

**Comment by acekingke** [comment]
http://docs.hylang.org/en/stable/language/api.html#cut

```
=> (setv collection (range 10))

=> (cut collection)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

=> (cut collection 5)
[5, 6, 7, 8, 9]

=> (cut collection 2 8)
[2, 3, 4, 5, 6, 7]

=> (cut collection 2 8 2)
[2, 4, 6]

=> (cut collection -4 -2)
[6, 7]
```

**Comment by Kodiologist** [comment]
Those examples are from Hy running on Python 3. Please upgrade.
