### ISSUE TITLE
HTTPS on docs.hylang.org is broken

### ISSUE THREAD

**Issue by phoe** [hylang/hy#1684]
https://docs.hylang.org/en/stable/

![screenshot from 2018-10-03 16-03-01](https://user-images.githubusercontent.com/15045546/46415572-d5d4a380-c725-11e8-87f2-9e0377215c05.png)

**Comment by Kodiologist** [comment]
@paultag

**Comment by kirbyfan64** [comment]
Ah, I remember this from another site. Can't find the RTD issue #, but [here's how gunicorn fixed it](https://github.com/benoitc/gunicorn/issues/1862).

**Comment by Kodiologist** [comment]
It is currently not broken.
