### ISSUE TITLE
Hy repl doesn't open on clean install python 3.7

### ISSUE THREAD

**Issue by vshesh** [hylang/hy#1690]
Did the following on a mac:

```
$ brew install python
$ python3
Python 3.7.0 ....
$ pip3 install hy
...
$ hy
-bash: /usr/local/bin/hy: /usr/local/opt/python3/bin/python3.5: bad interpreter: No such file or directory
```

When I ``cat `which hy``` I get:

```
#!/usr/local/opt/python3/bin/python3.5

# -*- coding: utf-8 -*-
import re
import sys

from hy.cmdline import hy_main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(hy_main())
```

Why is there a shebang line pointing to python 3.5? I can run ``python3 `which hy``` and everything (so far as I can tell) works just fine.

Tried with latest git (pip install git+...) and same issue.

**Comment by Kodiologist** [comment]
Pretty mysterious, but it sounds like your Python might be misconfigured somehow. I know that Mac OS X has a default Python that can sometimes compete with user-installed Pythons. Which version of the OS are you running? Can you (or anybody else) replicate this issue on another system?

**Comment by vshesh** [comment]
Mac OS 10.13.2 (high sierra)
I don't have access to another mac to test it on...

**Comment by vshesh** [comment]
how is that shebang line made? /usr/local/opt/python3/bin/python3.7 exists, and there's no python3.5 anywhere on my machine, so I'm not sure where the pip install picked that up from.

**Comment by Kodiologist** [comment]
I don't know; you'd probably have to look into the innards of setuptools or fastentrypoints.

**Comment by Kodiologist** [comment]
Nobody's been able to (or tried to) replicate this issue after 3 years, and I still suspect a misconfiguration, so I'm closing this for now.
