### ISSUE TITLE
Move parsing and compilation functions out of `importer.py`

### ISSUE THREAD

**Issue by brandonwillard** [hylang/hy#1695]
Currently, `hy_eval`, `hy_parse` and `ast_compile` all reside in `importer.py`, yet, by functionality and filename, it seems like those functions should be somewhere else&mdash;like `compiler.py`.

Since `importer.py`'s core functionality has a couple intrinsic dependencies in `compiler.py`, and `compiler.py` could easily drop its dependency on `importer.py` with only the transfer of `hy_eval`, it makes even more sense to move those functions to `compiler.py`.

If there are no objections, I can put in a PR to that effect.

**Comment by Kodiologist** [comment]
I think that's fine. Two of those functions are one-liners and the third isn't that big.
