### ISSUE TITLE
`HyREPL` calls `hy_compile` on every processed command

### ISSUE THREAD

**Issue by brandonwillard** [hylang/hy#1698]
`HyREPL` calls `hy_compile` on every processed command.  When that happens, a `HyASTCompiler` is constructed and all the stdlib imports are triggered again and again.

We should probably create and reuse a single `HyASTCompiler` instance for the lifetime of `HyREPL`, no?

_Originally posted by @brandonwillard in https://github.com/hylang/hy/issue_comments#issuecomment-437527370_

**Comment by Kodiologist** [comment]
Probably.
