### ISSUE TITLE
Make `HyASTCompiler` (more) stateless

### ISSUE THREAD

**Issue by brandonwillard** [hylang/hy#1701]
In order for a compiler instance to&mdash;for example&mdash;simply [re]use itself when calling `hy_eval` (e.g. during `eval-and-compile`), we need to make the compiler "stateless".  Current `HyASTCompiler` class members `imports` and `temp_if` attach state to a compiler instance that prevent its immediate reuse.

To replace `imports`, we could enable consistent tracking/use of `Result` objects and the `imports` within those.  Basically, we can&mdash;and should&mdash;keep all "state" within `Result` objects (or a suitable replacement/analog, e.g. annotated/stateful AST type).  This looks like it will involve an interface-like change to the compiler, though; namely, that all `HyASTCompiler.compile_*` methods must return and take `Result` objects.  While that's often the case (well, the former at least), it's not always true, and this inconsistency isn't good for the compiler's design.

For instance, `HyASTCompiler.compile_symbol` doesn't return a `Result` object, but it can be made to do so, and&mdash;with that change&mdash;it can assign stdlib auto-imports to the current state of compilation via `Result.imports` instead of the actual compiler instance.  Likewise, with that in place, we can make `HyASTCompiler.imports_as_stmts` produce AST for a `Results`'s `imports` and return those in another `Result` object&mdash;bringing it more in-line with its adjacent `compile_*` methods.  Additionally, the logic currently in `hy_compile` could then be moved to `HyASTCompiler.imports_as_stmts` and disentangle essential compilation logic from `hy_compile`.
   
At the very least, these changes would get us closer to a compiler that better isolates its functionality and is significantly easier to extend and debug.  

Regarding `HyASTCompiler.temp_if`, I'm having a hard time understanding exactly what its functional "intentions" are and the exact scope/constraints of its role.  I can see that it's attempting to avoid the unnecessary use/creation of temporary variables in an `if*`, but how it's using the compiler state to do this isn't very clear or well contained.  I can't tell whether or not the addition of a `temp_if` field to `Result` would work, or if there's something much simpler that would avoid such an undesirable addition.

Related issues and ideas: #1542, #1482, [this comment](https://github.com/hylang/hy/issues/1697#issuecomment-437526626) in #1697.

_Originally posted by @brandonwillard in https://github.com/hylang/hy/pull/1700#issuecomment-437704110_

**Comment by Kodiologist** [comment]
In order to support new features, we've ended up going in the opposite direction and giving the compiler a lot of new state information, such as dictionaries of local macros. This is unlikely to change in the foreseeable future.
