### ISSUE TITLE
Broken arglist parsing --- missing dependency?

### ISSUE THREAD

**Issue by david-morris** [hylang/hy#1702]
I've switched to a new (arch) install, and previously-working code with destructuring binds and default values in the arglist has started failing with errors like this:

```
hy 0.15.0+48.gc5abc85a using CPython(default) 3.7.1 on Linux
=> (defn herp [&optional (a 1)] "derp")                                                                                                                                                                           
  File "<input>", line 1, column 30

  (defn herp [&optional (a 1)] "derp")
                               ^-----^
HyTypeError: parse error for special form 'fn*': should have reached end of form: HyExpression([
  HySymbol('a'),
  HyInteger(1)]): derp
```
I've installed hy both through my distro package manager, and Pip.  Maybe there's a missing dependency for the parser?

**Comment by Kodiologist** [comment]
This feature was removed by #1590.

**Comment by david-morris** [comment]
Is there a new way to define default arguments?

**Comment by Kodiologist** [comment]
Oh right, I missed that part of this issue. Sorry. Default arguments work the same as before except that the compiler is stricter and you can no longer use parentheses where square brackets are expected (#1582), so that has to be written as `(defn herp [&optional [a 1]] "derp")`.

**Comment by david-morris** [comment]
Thanks!  I didn't see it in tutorial.rst before.
