### ISSUE TITLE
Internal Python Code Formatting

### ISSUE THREAD

**Issue by brandonwillard** [hylang/hy#1704]
Anyone interested in handing over all Hy internal Python code formatting to something automated&mdash;like [`black`](https://github.com/ambv/black)?  Would definitely streamline some of the dev process!

**Comment by Kodiologist** [comment]
How to best space code is subjective and depends on things like what you want to bring the reader's attention to. Rigid rules that are automatically applied defeat the purpose.

**Comment by Kodiologist** [comment]
Related: #972.

**Comment by allison-casey** [comment]
as has been brought up in #1962, internal py code has over 300 flake8 errors. I'm in favor of reformatting the code base with black to make things more consistent. I've used it for all my personal projects and several work projects and it's consistently been very good. I'd personally also like to see `isort` added along with `black` as a precommit hook as well.

**Comment by refi64** [comment]
I believe we had flake8 active at one point, but it wasn't really maintained and there were aspects of the style that weren't really entirely accepted by all team members.

**Comment by allison-casey** [comment]
There isn't much I can add to the [write up](https://github.com/django/deps/blob/master/accepted/0008-black.rst#motivation) that the Django team did when they accepted Black as their formatter so I'll just highlight some of the key points I find most compelling. 

> "As for disagreeing with some of Black's choices - you learn very quickly to live with those choices, and forget those choices. (...) I'm in favour of using Black's double quotes for strings. I hated this decision when it was first made, but have seriously come around to it, and prefer it aesthetically too." - Josh Smeaton

This mimics my experience to a T as well. 

> The point of adopting an automatic code formatter isn't to have our own Django-flavored code formatting style. It's about making our Python code look as much as possible like what everyone else in the Python community writes. Code formatters maximize their usefulness by not being configurable.

> Finally, as Black is maintained in the Python GitHub organization, it has a good chance of becoming a standard tool of the Python community.

Even if it's an unenforced defacto standard, I still think its better to have code that looks like most other's code than not. You can see this in other languages that ship with a formatter as well like `rustfmt` and `gofmt`
