### ISSUE TITLE
Should multiprocessing be working?

### ISSUE THREAD

**Issue by cynseok** [hylang/hy#1706]
Is it possible to run multiprocessing codes in Hy?

The following code results in error

```
(import [multiprocessing :as mp])

(setv pool (mp.Pool 5))
(defn f [x] (print x))
(defmain []
  (pool.map f (range 5 20)))


AttributeError: 'NoneType' object has no attribute '__spec__'
```

**Comment by Kodiologist** [comment]
A direct translation into Hy of the first example [here](https://docs.python.org/3/library/multiprocessing.html) works fine for me on Python 3.7 and Hy master. Are you sure your code is right? Are you using Hy master?

    (import [multiprocessing [Pool]])

    (defn f [x]
      (* x x))

    (when (= __name__ "__main__")
      (with [p (Pool 5)]
        (print (p.map f [1 2 3]))))

**Comment by cynseok** [comment]
Running hy2py then running with python test.py works

**Comment by cynseok** [comment]
What is Hy master? Is it different from the one I installed with `pip install hy` ?

**Comment by Kodiologist** [comment]
> What is Hy master? Is it different from the one I installed with `pip install hy`?

Yes, it's what you get by clicking the big green "Clone or download" button [here](https://github.com/hylang/hy). Install that and try again.

**Comment by Kodiologist** [comment]
> Well, I tried the master version, it would not load any .hy codes, after tinkering for couple of hours I decided to stay on stable release.

We only fix bugs on master, so if you go back, you're on your own.

What error message did you get from `python -mhy`? Or, if that doesn't raise an error, `hy -c 1`?

> What would be the reason multiprocessing support would be on the master version but not available on the stable version?

I doubt that any of the errors you've seen have to do with multiprocessing.

**Comment by brandonwillard** [comment]
The first `multiprocessing` example seems to work interactively:
```clojure
hy 0.15.0+39.gd2319dc using CPython(default) 3.6.6 on Linux
=> import multiprocessing as mp
None

=> ... def f(x):
    return x * x


None

=> None

=> ... _hy_anon_var_1 = None
with mp.Pool(5) as p:
    _hy_anon_var_1 = p.map(f, range(3))
_hy_anon_var_1

[0, 1, 4]
=> None
```

Otherwise, from the command line (e.g. `hy test.hy`), the `defmain` macro fails with empty arguments (e.g. `(defmain [x] ...)` appears to work).

**Comment by brandonwillard** [comment]
Likewise, the following works fine after adding an unused `x` to the `defmain` arguments:
```clojure
;; test.hy
(import [multiprocessing :as mp])

(defn f [x]
  (print x))

(setv p (mp.Pool 5))

(defmain [x]
  (p.map f (range 5 20)))
```

```bash
> hy test.hy
5
6
8
7
10
11
12
9
13
14
15
16
17
18
19
```

**Comment by brandonwillard** [comment]
@cynseok, if you're still seeing errors, try deleting the corresponding `.pyc` files (e.g. `./__pycache__/test.cpython-36.pyc` in my examples)

**Comment by Kodiologist** [comment]
I'm closing this due to lack of response, but we can reopen if you look into it.
