### ISSUE TITLE
Can you run hy on Pythonistas on iPad?

### ISSUE THREAD

**Issue by kwccoin** [hylang/hy#1713]
Not sure it is a feature request but more a practical reality I would not have a notebook with me all the time but my iPhone and my iPad are there always.

Any chance to have even a mini-hy that can run on pythonista as full lisp is not really there?  Not even myLisp is close.

For your kind consideration.

**Comment by Kodiologist** [comment]
I haven't used that program, and Hy includes no special support for it, but you can certainly try and post whatever issues arise.
