### ISSUE TITLE
parse-args macro

### ISSUE THREAD

**Issue by alphapapa** [hylang/hy#1719]
I came up with this macro, which makes `argparse` much easier to use:
```clj
#!/usr/bin/env hy3

(defmacro/g! parse-args [&rest args]
  "Return arguments parsed from sys.argv with argparse according to ARGS.

ARGS should be a list of arguments passed to argparse.ArgumentParser.add_argument."
  `(do
     (import argparse)
     (setv g!parser (argparse.ArgumentParser))
     ~@(lfor arg args
             `(.add-argument g!parser ~@arg))
     (.parse_args g!parser)))

(defmain [&rest args]
  (setv args (parse-args
               ["files" :nargs "+" :help "Files"]
               ["-v" "--verbose" :action "store_true"]))
  (when args.verbose
    (print "verbose"))
  (print (.join "\n" args.files)))
```
Used like:
```
$ script.hy -v file
verbose
file
```
Would this be useful to include in Hy?

**Comment by Kodiologist** [comment]
I like it, except that it should be written as a function (since it need not be a macro), and it should also provide ways to pass arguments to the `ArgumentParser` constructor and to `parse_args`.

**Comment by alphapapa** [comment]
Hi again,

Messing with some Hy again, I'm trying to convert it to a function, but it seems awkward and difficult.  The problem I'm having is that each list of argparse argument options must be passed to the `add-argument` method properly, meaning that non-keyword arguments must be passed as plain arguments, and keyword arguments as keyword arguments.  

Doing it as a macro is easy, as backquoting and splicing constructs the sexp naturally, which Hy then parses as if the sexp were written that way in the first place (the whole point of a macro, of course).

But, as far as I can tell, doing it as a function requires awkward munging of the argument lists.  I'm sure there's a way, but I haven't figured it out yet, and I'm not sure it's worth the trouble when doing it as a macro handles it naturally.  I feel like I would end up writing a lot of code that already exists in the code that provides macros.  For example, I've got this, that almost works (ignore the debugging `print`s):

```hy
(defn parse-args-fn [&rest args]
  "Return arguments parsed from sys.argv with argparse according to ARGS.

ARGS should be a list of arguments passed to argparse.ArgumentParser.add_argument."
  (import argparse)
  (setv parser (argparse.ArgumentParser))
  (lfor arg args
        :do (print "allargs" arg)
        :setv largs ((fn [&rest args &kwargs kwargs] args) arg)
        :setv kwargs ((fn [&rest args &kwargs kwargs] kwargs) arg)
        :do (print "largs" largs)
        :do (print "kwargs" kwargs)
        (.add-argument parser #* largs #** kwargs))
  (.parse_args parser))
```
But it doesn't work properly:
```
Traceback (most recent call last):
  File "/home/me/.local/bin/hy3", line 11, in <module>
    sys.exit(hy_main())
  File "/home/me/.local/lib/python3.4/site-packages/hy/cmdline.py", line 363, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/home/me/.local/lib/python3.4/site-packages/hy/cmdline.py", line 351, in cmdline_handler
    return run_file(options.args[0])
  File "/home/me/.local/lib/python3.4/site-packages/hy/cmdline.py", line 224, in run_file
    pretty_error(import_file_to_module, "__main__", filename)
  File "/home/me/.local/lib/python3.4/site-packages/hy/cmdline.py", line 197, in pretty_error
    return func(*args, **kw)
  File "/home/me/.local/lib/python3.4/site-packages/hy/importer.py", line 116, in import_file_to_module
    eval(code, module.__dict__)
  File "/home/me/.bin/checktwitch.hy", line 17, in <module>
    *url-prefix* "https://api.twitch.tv/kraken/streams/")
  File "/home/me/.bin/checktwitch.hy", line 68, in _hy_anon_var_9
    ["-s" :action "store_true" :help "Show status"])
  File "/home/me/.bin/checktwitch.hy", line 257, in parse_args_fn
  File "/home/me/.bin/checktwitch.hy", line 46, in _hy_anon_var_2
    (.add-argument parser #* largs #** kwargs))
  File "/usr/lib/python3.4/argparse.py", line 1335, in add_argument
    if dest in self._defaults:
TypeError: unhashable type: 'list'
allargs ['streamers', HyKeyword('nargs'), '+', HyKeyword('help'), 'Streamers']
largs (['streamers', HyKeyword('nargs'), '+', HyKeyword('help'), 'Streamers'],)
kwargs {}
```
Now I'm no Hy expert, so maybe I'm missing something obvious.  But why write all this extra code to munge the arguments when that's what macros are for?  And if I would have to mess with internal objects like `HyKeyword`, that seems double-bad.  I thought the whole point of Hy was to allow me to write Python as if it were Lisp, which includes writing macros to handle cases like this.

Alternatively, `eval` works with minimal changes to the macro:
```hy
(defn parse-args-fn [&rest args]
  "Return arguments parsed from sys.argv with argparse according to ARGS.

ARGS should be a list of arguments passed to argparse.ArgumentParser.add_argument."
  (import argparse)
  (setv parser (argparse.ArgumentParser))
  (for [arg args]
    (eval `(.add-argument parser ~@arg)))
  (.parse_args parser))
```
But `eval` is generally frowned upon in Lisp when not strictly necessary.

So how should this be handled in Hy?

Thanks.

**Comment by Kodiologist** [comment]
I'd say that `eval` is better than using a macro in this case, where performance isn't a concern, but it's not hard to do without `eval`, either:

    (defn parse-args [&rest args]
      (import argparse)
      (setv parser (argparse.ArgumentParser))
      (for [a args]
        (setv pargs [])
        (setv a (list a))
        (while (and a (not (keyword? (get a 0))))
          (.append pargs (.pop a 0)))
        (setv kwargs (dfor [k v] (partition a)
          [(name k) v]))
        (.add-argument parser #* pargs #**kwargs))
      (.parse-args parser))

**Comment by alphapapa** [comment]
Hi again,

I'm revisiting this idea.  As you suggested, this replaces the macro with a function, passes through arguments to the constructor, and allows the argument list to be passed to the parser method.

I think this API is simple and pleasant to use.  What do you think?  If this looks good to you, I'll prepare a PR.  Thanks.

```hy
#!/usr/bin/env hy3

(defn parse-args [spec &kwonly [args None] &kwargs parser-args]
  "Return arguments namespace parsed from ARGS or sys.argv with argparse according to SPEC.
SPEC should be a list of arguments to pass to repeated calls to
argparse.ArgumentParser.add_argument().  PARSER-ARGS may be a list of
keyword arguments to pass to argparse.ArgumentParser()."
  (import argparse)
  (setv parser (argparse.ArgumentParser #** parser-args))
  (for [arg spec]
    (eval `(.add-argument parser ~@arg)))
  (.parse-args parser args))

(setv *args-spec* [["strings" :nargs "+" :help "Strings to output."]
                   ["-n" "--number" :action "append" :dest "numbers" :help "Numbers to output."]])

(defmain [&rest _]
  (setv args (parse-args *args-spec*
                         :description "Script to test argument parsing."
                         :epilog "That was easy."))
  (when args.strings
    (print args.strings))
  (when args.numbers
    (print args.numbers)))
```
Output:
```
$ test.hy -h
usage: test.hy [-h] [-n NUMBERS] strings [strings ...]

Script to test argument parsing.

positional arguments:
  strings               Strings to output.

optional arguments:
  -h, --help            show this help message and exit
  -n NUMBERS, --number NUMBERS
                        Numbers to output.

That was easy.

$ test.hy a -n 1 -n 2
['a']
['1', '2']
```

**Comment by Kodiologist** [comment]
Looks good.

**Comment by alphapapa** [comment]
Which files/sections should the code and docs go in?  I'm guessing `contrib`, but I don't see an existing section it would fit in.

**Comment by Kodiologist** [comment]
Just add it to `language.hy` and document it in `core.rst`.
