### ISSUE TITLE
Make a fancy landing page for Hy

### ISSUE THREAD

**Issue by Immortalin** [hylang/hy#1738]

**Comment by Kodiologist** [comment]
Did you forget to add a description of your issue?

**Comment by Kodiologist** [comment]
It sounds like you're under the impression that we don't have a website, and intended this issue to be a request for one. We do have one. It's http://hylang.org .

**Comment by Immortalin** [comment]
Yes but a docs page isn't quite the same caliber as e.g. Nim or Rust's landing pages. Being flashy maybe be gimmicky but it helps conversion rates.

**Comment by Immortalin** [comment]
Even Clojure has a dedicated landing page.

**Comment by Kodiologist** [comment]
Okay, a hard-selling website is a valid feature request. I'm not personally interested in it (I think the kind of rhetoric currently shown on http://www.rust-lang.org is asinine, and encourages the naive chauvinism that some Rust programmers espouse), but perhaps other people feel differently.

**Comment by kirbyfan64** [comment]
Hmm, if no one else is interested I might try tackling this.

**Comment by yuhan0** [comment]
I think a better comparison would be with [Coconut](http://coconut-lang.org/) or [Dogelang](http://pyos.github.io/dg/) - both also being "compile-to-Python" languages with nice landing pages. 

Having side-by-side syntax examples up front showcasing some of the killer features would be great. 
(Threading macros? Multiline lambdas? Keyworded dictionaries without need for commas?)

Even better a live interpreter like on the Coconut page, showing the direct transpilation between Hy -> Python. The current one on https://try-hy.appspot.com is awesome but not very functional :P 

Here's one for Clojurescript -> Javascript: http://app.klipse.tech/

**Comment by Kodiologist** [comment]
Fair enough. I guess the chief features distinguishing Hy from Python are:

- Free-form, homoiconic syntax
- Macros and arbitrary compile-time computation
- Erasure of the distinction between statements and expressions (mostly)

**Comment by yuhan0** [comment]
Yeah, it depends who the target audience is - for anyone who's not already familiar with Lisps the advantages of "homoiconicity" is notoriously hard to explain.  
The ones I listed are more like immediate syntactical conveniences off the top of my head that someone coming from Python would be able to understand immediately?

**Comment by asemic-horizon** [comment]
Can we publicize issues in bounty hunting websites? There are some that tightly integrate to Github too.

This is relevant because making a landing page with freely available Bootstrap themes is really easy but I don't have the time to learn modern web dev right now and no one who's qualified to hack on Hy should be spending time on that. But I could quickly write some more detailed specs for the landing page (just did something like that last week) and kick a few dollars in for the bounty hunt.

It may seem that a "fancy landing page" for a hackers's language is pointless, but network effects being what they are, momentum is key. It's important for me as someone eager to adopt Hy for core business functionality to be able to sell it as something that's here to stay (like Clojure) and not a toy project (like, say, Liskell -- or Dogelang).

**Comment by refi64** [comment]
I've kind of thought about this for a while since I also do webdev, but design isn't necessarily my strongest suit. For some reason, imagine a site for Hy would have cursive on it somewhere though, no idea why...

**Comment by vidjuheffex** [comment]
https://624b23e73795c80f930f611f.clutch.host//

**Comment by Kodiologist** [comment]
I like that. It's informative and it looks nice. Do you want to take a stab at implementing that in GitHub Pages, @vidjuheffex?

**Comment by vidjuheffex** [comment]
Yeah sounds good

**Comment by vidjuheffex** [comment]
https://github.com/vidjuheffex/hy 
I have it here in the gh-pages branch, not sure how to open a pr to a non-existant branch

**Comment by Kodiologist** [comment]
I think we should probably make a new repository for it. Like https://github.com/hylang/gethy.org, except I'll ask Paul to use hylang.org for it (and not just let the domain name expire; whoops).

**Comment by Kodiologist** [comment]
Okay, I made https://github.com/hylang/hyhomepage and sent you an invitation for access. @paultag, could you point hylang.org to https://hylang.github.io/hyhomepage (ideally as a purely internal redirect, so the URL that people see will keep working if we leave GitHub Pages), while keeping docs.hylang.org where it is? Then I think we can close this.

**Comment by allison-casey** [comment]
This is fantastic work @vidjuheffex! Thank you for this

**Comment by Kodiologist** [comment]
It's finally up at http://hylang.org, along with a new Try Hy.
