### ISSUE TITLE
Proposal for the syntax of format strings

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1740]
I'm working on implementing f-strings (from scratch, rather than continuing Ryan's old PR). It's not entirely clear what the syntax should be, thanks to ugly cases like nested replacement fields, so here's a proposal for you to bikeshed before I put a lot of work into it.

    (setv a "foo")
    f"hello {a}"       →  "hello foo"
    f"hello {(+ 1 1)}" →  "hello 2"
    f"hello {a !r}"    →  "hello 'foo'"
    f"hello {a :7}"    →  "hello foo    "
    f"hello {a !r:7}"  →  "hello 'foo'  "

Note the whitespace before `!` and `:`. If you say `f"hello {a!r:7}"`, Hy will interpret everything as a single identifier and look for the variable `a!r:7` (or in mangled form, `hyx_aXexclamation_markXrXcolonX7`). Because of this sort of tokenization inside the braces, the main code part has to be a single form, so you need to use `do` to include more than one form:

    f"hello {(do (+= a "x") a) :7}"  →  "hello foox   "

In that example, the space before the `:` isn't actually necessary because `)` has already ended the form. In practice, it's good style to include a space, as in ordinary Hy code like `(f (g) x)`.

For readability, unlike Python, whitespace is also legal between the conversion specifier and the format specifier:

    f"hello {a !r :7}"  →  "hello 'foo'  "

As in Python, doubled braces create literal braces, and trying to backslash-escape braces just creates a literal backslash.

    f"hello {{a}}"  →  "hello {a}"
    f"hello \{a}"  →  r"hello \foo"

Also as in Python, the format specifier is like another f-string unto itself, in that it can include brace-delimited replacement fields. Unlike Python, the inner replacement fields can only be code; no inner conversion specifiers or format specifiers are allowed, because I'm at a loss for why you'd ever want them.

    (setv value 12.34  width 10  precision 4)
    f"result: {value :{width}.{precision}}"  →  "result:      12.35"

    f"hello {a :{(+ 1 6)}}"  →  "hello foo    "

Unlike Python, comments are allowed in the code form.

    f"hello { (do
      (setv a "bar") ; Reset `a`
      a)}"                        → "hello bar"

Also unlike Python, backslashes are allowed in replacement fields (for the sake of simplicity of implementation). Because backslashes are processed by the lexer before any attempt to parse the replacement fields, you may need to backslash your backslashes.

    f"hello {r\"\\n\"}"  →   r"hello \n"
    f"hello {r\"\n\"}"  →   "hello "  (the `r` applies too late)

Finally, you can use a bracket string as a format string if the custom delimiter is exactly `f` or begins with `f-`.

    #[f[Hello {a}.]f]  →  "hello foo"
    #[f-mydelim[Hello {a}.]f-mydelim]  →  "hello foo"

**Comment by Kodiologist** [comment]
Implementation-wise, the chief goal here is to get feature parity with Python 3.6, but I think it may be easy to generate equivalent AST for earlier Pythons, effectively backporting f-strings to as far back as Python 2.7.

**Comment by kirbyfan64** [comment]
I was able to make them work on older Python versions too, you can compile them to individual `format(xyz)` calls and add the results together.

**Comment by Kodiologist** [comment]
Okay, I'm now starting to work on this.
