### ISSUE TITLE
Typed AST Package

### ISSUE THREAD

**Issue by brandonwillard** [hylang/hy#1741]
The [`typed_ast`](https://github.com/python/typed_ast) package seems like it could be useful; especially if we want to handle typing hints (e.g. https://github.com/hylang/hy/issues/640).

**Comment by isidentical** [comment]
And it is merged to CPython itself with python3.8 [bpo-35766](https://bugs.python.org/issue35766)

**Comment by Kodiologist** [comment]
The user can now specify type annotations in Hy, which get included in the generated Python AST, so I think there's nothing more to do here.
