### ISSUE TITLE
Match @hylang/owners membership to add current developers

### ISSUE THREAD

**Issue by olasd** [hylang/hy#1743]
Hey,

I've been poked by @brandonwillard about adding him to the core group and I have no objection to that, but it would make more sense to me if people who are actually contributing to Hy these days had that power instead of us old farts.

@hylang/owners I think at least @Kodiologist and @kirbyfan64 should become owners and carry the project forward as they wish.

If I see no objection in the next few days I'll go ahead with the changes.

**Comment by paultag** [comment]
concur; I'd like to maintain my ownership just because I'm happy to keep helping and stuff, but this is absolutely right, the old farts must never remain in charge because we got here first. :+1:

**Comment by olasd** [comment]
Done. @Kodiologist and @kirbyfan64 are now owners of the @hylang org.

**Comment by paultag** [comment]
:confetti_ball: :tada:

**Comment by Kodiologist** [comment]
Noice.
