### ISSUE TITLE
Add Brandon Willard to core

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1744]
@brandonwillard wants in. I say let him. He obviously knows his stuff, and he's been working on long-neglected parts of Hy. (Also, I'm biased because he, like me, is a statistician.) What say you, @hylang/core? (Especially @kirbyfan64, since you and I are the official big boys now, Ryan.)

**Comment by brandonwillard** [comment]
I don't know if being a statistician is necessarily good; you seen `R`?

**Comment by Kodiologist** [comment]
Good point. :P I more or less write R for a living these days, but it is… not the best language.

**Comment by brandonwillard** [comment]
Joking aside, I might like it more than Python, but it's definitely no Lisp.

**Comment by brandonwillard** [comment]
By the way, the best language is Haskell...

**Comment by Kodiologist** [comment]
Haskell is very good, no doubt about that. Just here for the libraries, huh?

**Comment by brandonwillard** [comment]
Python libraries?  Not exactly.  It's something between Python's accessibility and the breadth and interests of its community (e.g. general scripting, machine learning, data-related things, etc.)

**Comment by kirbyfan64** [comment]
> Since you and are the official big boys now, Ryan.)

👀

Joking aside, this sounds great to me!

**Comment by gilch** [comment]
I approve of adding @brandonwillard to core.

**Comment by Kodiologist** [comment]
All righty, it's done. Welcome aboard!
