### ISSUE TITLE
Slow startup when Hy is installed from a wheel

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1747]
Testing the new release of 0.16.0, I see that startup is much slower when installing from the wheel than from the source distribution or directly from the repository. Likewise for older Hy releases. Even when I make sure the `__pycache__`s are included in the wheel and I can see they're installed. Either there's something wonky with my system, or wheel installation doesn't play nicely with premade byte-compiled files.

**Comment by brandonwillard** [comment]
Maybe a bytecode version thing?  If you turn on debug, does it say it's recompiling?

**Comment by Kodiologist** [comment]
Sorry, which debug mode do you mean? Should `HY_DEBUG` print such messages?

**Comment by brandonwillard** [comment]
I was thinking of [`-d`](https://docs.python.org/3.6/using/cmdline.html#cmdoption-d).

**Comment by Kodiologist** [comment]
I don't seem to get any messages about compilation from `python3 -d -m hy.core.language`.
