### ISSUE TITLE
Preparing to have to move CI from Travis

### ISSUE THREAD

**Issue by refi64** [hylang/hy#1751]
https://www.reddit.com/r/programming/comments/at5nrz/ibera_is_gutting_travis_ci_just_a_few_weeks_after/

Basically a ton of staff just got fired, ex employees are saying they're not sure if there's even enough left to maintain it. Maybe wait for some more official confirmation before jumping the gun, but this might be something we'd be better off preparing for in advance.

**Comment by Kodiologist** [comment]
Fun. Do you have any experience with alternatives, like CircleCI?

**Comment by kirbyfan64** [comment]
*Personally* I'm a huge fan of Azure Pipelines, since their free OSS tier is pretty liberal and is pretty fast.

**Comment by refi64** [comment]
So I'll probably take a look at this soon-ish, considering that Travis going down for nearly 8 hours is a pretty bad future sign.

**Comment by Kodiologist** [comment]
Accomplished by #2066.
