### ISSUE TITLE
HyKeyword __getstate__ w.r.t. pickle

### ISSUE THREAD

**Issue by ambrad** [hylang/hy#1754]
In approximately 0.14, this worked:
```(with [f (open "test.pickle" "w")] (pickle.dump {:a 1} f))```
In 0.16 one gets:
```TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled```
because HyKeyword does not implement `__getstate__`. This is with
```hy 0.16.0 using CPython(default) 2.7.7 on Linux```

**Comment by Kodiologist** [comment]
I  think that the use of `__slots__` is basically a micro-optimization, anyway, so perhaps we should drop it.

**Comment by Kodiologist** [comment]
This bug is no longer so obvious because the default pickle protocol is newer in newer versions of Python, but you can still see it with `:protocol 0`.
