### ISSUE TITLE
Possible destructuring bug

### ISSUE THREAD

**Issue by ambrad** [hylang/hy#1755]
Previously, defn argument destructuring of this sort worked:
```(defn foo [[a b]] (print a b))```
In 0.16, one gets:
```
HySyntaxError: parse error for special form 'fn*': should have reached end of form: HyList([
  HySymbol(u'a'),
  HySymbol(u'b')]): HyList([
  HyList([
    HySymbol(u'a'),
    HySymbol(u'b')])])
```
This is with
```hy 0.16.0 using CPython(default) 2.7.7 on Linux```

**Comment by Kodiologist** [comment]
Not a bug; see #1590.
