### ISSUE TITLE
eval cant return a function  after updated to 0.16.0?

### ISSUE THREAD

**Issue by xuqinghan** [hylang/hy#1756]
OK with 0.15.0 but failed with 0.16.0   
```
(setv mydict {"a?" (fn [x] (print x))})

(defn factory1 [env]
    (fn [uid] ((.get env "a?") uid))
)


(defn make2 [str_fn_body]
    (fn [env]
        (eval '(fn [uid] ((.get env "a?") uid)))
    )
)

(do
    ;1 make my_factory by send "mydict"
    (setv my_fn (factory1 mydict))
    ;2 run my_fn
    (my_fn 1111)
    (setv str_fn_body '((.get env "a?") uid))
    ;failed @0.16.0, but OK @0.15.0
    (setv factory2 (make2 str_fn_body))
    (setv my_fn2 (factory2 mydict))
    (my_fn2 1111)
)
```

with 0.16.0, eval in make2 failed: 
> ;   File "<string>", line 1, in <lambda>
> ; NameError: name 'env' is not defined

how to fixed the function make2?

**Comment by Kodiologist** [comment]
A minimal version of this phenomenon is:

    (defn factory [upper]
      (eval '(fn [] upper)))

    ((factory 9))

which raises `NameError: name 'upper' is not defined`. I guess `eval` isn't looking as hard for applicable names as it ought to. Intuitively, `(eval '(fn [] upper))` and `(fn [] upper)` should be equivalent.

This may be related to #1041, but unlike this case, I don't think the examples in #1041 ever worked.

**Comment by brandonwillard** [comment]
What about this:
```clojure
(defn factory [upper]
  (eval `(fn [] ~upper)))
```
It yields
```clojure
=> ((factory 9))

9
```

The original formulation has the lambda's `upper` as a generic symbol object, so I'm not sure why it would/should bind with the function argument `upper`

**Comment by brandonwillard** [comment]
It appears directly related to #1041.  One might be able to get the desired effect in the original `factory` formulation, and some of the examples in #1041, by setting the `locals` and/or `module` differently.

**Comment by brandonwillard** [comment]
@xuqinghan, try the following instead:
```clojure
(defn make2 [str_fn_body]
    (fn [env]
        (eval `(fn [uid] ((.get ~env "a?") uid)))
    )
)
```

**Comment by brandonwillard** [comment]
OK, I know what's happening.  The expression `(factory 9)` is using the local function namespace to evaluate `(eval '(fn [] upper))`, and that namespace includes `upper`, as expected.  Unfortunately, the presence of a binding for `upper` doesn't matter in that situation, because it's only creating the function/closure object that is `(fn [] upper)`.  What's desired/assumed is for the resulting function/closure object to adopt the evaluation namespace.

We could do that, I suppose, but it might become a little tricky when an `eval` produces nested closures.

**Comment by xuqinghan** [comment]
@brandonwillard   thanks a lot,  it works!

I rewrite my scene:

```
(import types)

(defn create_fn_of_env [expr_fn]
    (fn [env]
        (setv local-mod (types.ModuleType "local-mod"))
        (setv local-mod.env env)
        (eval expr_fn :module local-mod)
    )
)

(do
    ;-------create a dict as env----------
    (setv my_env {"a?" (fn [x] (+ x 9))})

    ;------create my_fn by 3 steps----------------------
    ;1 assemble expr of a fn's body and head
    (setv expr_fn_body '((.get env "a?") uid))
    (setv expr_fn `(fn [uid] ~expr_fn_body))

    ;2 create factory_fn via expr_fn
    (setv factory_fn (create_fn_of_env expr_fn))
    ;3 create fn via env
    (setv my_fn (factory_fn my_env))

    ; -----create a fn as ground truth--------
    (defn factory_gt [env]
        (fn [uid] ((.get env "a?") uid))
    )
    (setv fn_gt (factory_gt my_env))

    ;-----call fn---------------------
    (print (my_fn 1))
    (assert (= (my_fn 1) (fn_gt 1)))
)
```
