### ISSUE TITLE
Keyword argument unpacking unbalances dict

### ISSUE THREAD

**Issue by Wagk** [hylang/hy#1768]
In `hy 0.16.0+19.ga3962ad`:

```
=> (setv foo {:a 1})
=> {**foo :b 1}
```
Generates `ValueError: Dict doesn't have the same number of keys as values`

In python, the equivalent looks like:
```
>>> foo = {"a": 1}
>>> {**foo, "b": 2}
{'a': 1, 'b': 2}
```

**Comment by Kodiologist** [comment]
`**foo` is a symbol in Hy. You want `#** foo`.
