### ISSUE TITLE
Proposal: Remove the attribute list of `defclass`

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1771]
Currently, `defclass` allows you to write

    (defclass C [Superclass]
      [foo 1  bar 2])

as shorthand for

    (defclass C [Superclass]
      (setv foo 1  bar 2))

But this need not be implemented in the compiler. If there was instead a special form called `defclass*` that didn't support attribute lists, you could get the same effect with

    (defmacro defclass [class-name superclasses &rest body]
      `(defclass* ~class-name ~superclasses
        ~@(if (and body (instance? HyList (first body)))
          [`(setv ~@(first body)) (cut body 1)]
          body)))

But the shorthand saves few characters, anyway, so perhaps we shouldn't even bother providing the macro.

What do you guys think?

**Comment by brandonwillard** [comment]
I will generally agree that removing little niceties like that from the compiler&mdash;without them needing to be there&mdash;is good.

**Comment by refi64** [comment]
I'd be +1 for removing it tbh, it's kinda odd to read and not much of an improvement.
