### ISSUE TITLE
Common Lisp Loop Macro

### ISSUE THREAD

**Issue by digikar99** [hylang/hy#1775]
Is there a way to add the Common Lisp [Loop Macro](https://github.com/sbcl/sbcl/blob/master/src/code/loop.lisp) facility to hylang? (At the bottom: `C-f defmacro loop <space> <return>`.) 

I took a brief look - but I'm clueless as to whether there's an equivalent of  `&environment env` in python.

**Comment by Kodiologist** [comment]
I'm sure that most of the syntax of `loop` could be implemented in Hy, although there would probably have to be semantic differences in the fine details. `&environment` arguments isn't the kind of thing that can easily be simulated when generating Python code.

See, however, `for`/`lfor`/`gfor` for Hy's existing fancy iteration tools.

**Comment by digikar99** [comment]
Hmmm.... Okay. I wanted a way to combine for and while loops, or a simple way to loop simultaneously - I guess `break` and `zip` could meet my needs.
