### ISSUE TITLE
Move from Google Groups

### ISSUE THREAD

**Issue by Pebaz** [hylang/hy#1778]
I agree with #1738 that there needs to be an *actual* website for Hy.

I think Hy is an amazing language and it's not professional for it to be lacking a public-facing (non-docs) website.

However, my issue is more broad than this:

> We need a less archaic community meeting place.

[Google Groups](https://groups.google.com/forum/#!forum/hylang-discuss) used to be good and all, but compared to the likes of [Discord](https://discordapp.com/), [Discourse](https://www.discourse.org/), and even [Gitter](https://gitter.im/), it is less attractive.

In addition, no one is ever on IRC so it's difficult to communicate with others who enjoy this project.

Can someone tackle making another chatting place using something of equivalent quality with the above choices?

**Comment by Pebaz** [comment]
Didn't want to post this in the issue itself, but the main reason I wanted to get with the community was to let them know of an open source project I created named [j2do](https://github.com/Pebaz/j2do). I added it to the Wiki also [here](https://github.com/hylang/hy/wiki/Who-uses-Hylang).

Enjoy!

**Comment by Kodiologist** [comment]
I personally don't see why Discord, Discourse, and Gitter are better than Google Groups.

**Comment by Pebaz** [comment]
Hi Kodiologist!  The functionality Google Groups provides is sufficient, yes.  It is (only) my opinion that the other choices are better because they look nicer and more updated to me.  While I don't think that we should have lots of community meeting options (keep it simple), Google Groups urks me just enough not to use it.

**Comment by refi64** [comment]
I will agree Groups is a bit of a mess, but Discord and Gitter aren't really alternatives (more about realtime chat, e.g. an IRC alternative), and Discourse would need someone to host it (e.g. cost ~$3/mo on Hetzner, on DigitalOcean or others you'd need more RAM so ~$10/mo).

**Comment by Kodiologist** [comment]
GNU Mailman seems like a pretty popular option for mailing lists.

**Comment by Pebaz** [comment]
Interesting, plain email could be a good option using GNU Mailman. [Slack](https://slack.com/) keeps 10,000 messages per channel on the free tier before it starts deleting the oldest ones so that could be a good alternative to a forum. I believe Discord has a similar cap.

**Comment by Pebaz** [comment]
Looks like Slack also has unlimited users on Free tier.

**Comment by daslu** [comment]
In some parts of the Clojure community, we recently had a good experience moving the discussions to Zulip.

Zulip is kind of a sweet spot between the lightness of chat platforms and the organization of mailing lists. It seems to feel well for both slow and fast conversations, and the hierarchy of streams and topics is rather comfortable. We also found it useful to be able to have the full history (unlike Slack) and have a url of any stream, topic or message. Messages are markdown and behave well with syntax-highlighted code blocks, etc. There are both public and private streams, which is sometimes handy.

It is also open source.

It may be good idea to observe a bit the Clojurians Zulip, and think whether it may feel good for Hy, too.

**Comment by Pebaz** [comment]
I like it!  That could work.  It's like Slack + Discourse almost.

**Comment by refi64** [comment]
For the record I really like Zulip as well, maybe we could get the message search restriction lifted since this is an OSS project? For the record there's also a [Zulip instance for Python](https://python.zulipchat.com).

I don't really see any advantage to GNU Mailman, really it's still a mailing list like Groups, sure the subscribe UI is a bit less messy but that's pretty much it. Feels more like a loss than a gain overall IMO.

**Comment by refi64** [comment]
Okay so bringing this up again, IMO a Hy Zulip would be rather nice, and if the community gets seen as important enough (or maybe for any OSS community, not sure yet), you get [free commercial-tier hosting](https://zulipchat.com/for/open-source/). Still no public archives but this will be added *at some point*.

OTOH there is also Spectrum now, which was bought by GitHub and is sort of a mix between forum and chat. Publicly searchable but IMO not as polished yet.

**Comment by 0atman** [comment]
+1 for Zulip
-1000 for slack, discourse, irc or anything linear.

**Comment by allison-casey** [comment]
There's been an influx of new faces recently (Hy everybody!) so i want restart this discussion since there's not much activity on IRC for people to talk about what they're using Hy for etc. I'm going to put on vote behind a Discord server since it's something many of us are already active on and has worked for other languages like Python and Clojure and its 👉  free 👈

**Comment by sheganinans** [comment]
+1 for Discord
Zulip seems nice as well, would strongly consider trying it.
Personally I'd definitely want to avoid Slack/Discourse/IRC.
Google Groups I'm willing to compromise on, since it requires no downloads.

**Comment by 0atman** [comment]
For me the combo of discord and discourse give us the best chat and best forums, respectively. 👌

**Comment by allison-casey** [comment]
Discourse doesn't have a free tier :(

**Comment by 0atman** [comment]
Discourse is open source, and easy to self-host! 💪

My local Makerspace hosts one, for instance: https://discourse.southlondonmakerspace.org/

Big bonus of discourse, as far as I'm concerned, is that it's open - you can't Google for answers inside Discord or Zulip - they're closed ecosystems. Discourse is a forum (albeit the best forum)

HAVING SAID THAT: I think what we need currently is discord, for chat and community.

**Comment by allison-casey** [comment]
That's pretty cool! Id be willing to look into self hosting down the road if we keep growing as a community. 

That was what I was thinking too. there isn't really a place to hang out and foster that kind of community right now and I think discord could help with that since a lot of us are already on discord all the time anyways

**Comment by allison-casey** [comment]
Went ahead and enabled github [discussions](https://github.com/hylang/hy/discussions) for Hy! Go check it out when you have the chance. It's still pretty new so we'll be figuring it out as we go, but it seems pretty nice so far. It has threads and acts pretty much like a typical form, and it's free :eyes: If we like it after a month or two we can look at retiring google groups/irc etc.

**Comment by 0atman** [comment]
PERFECT!!!

**Comment by allison-casey** [comment]
It's been a month since we opened discussions and I'm pretty happy with it. It's much more user friendly than google groups imo. How would we feel about changing the readme to point to discussions instead of IRC/Google Groups and give it another month?

**Comment by Kodiologist** [comment]
Fine by me. We're already pretty committed (heh) to GitHub.

**Comment by allison-casey** [comment]
its been a month, is it time to finally archive the Hy google groups? I don't have permissions to do that kind of thing though. @Kodiologist do you have that power?

**Comment by Kodiologist** [comment]
I don't think so. I never used it. @paultag?

**Comment by paultag** [comment]
I can do so! If you assign this to me I'll try and spin it down today

**Comment by paultag** [comment]
The google group has been deleted. Thank you for the cleanup effort! It's very appreciated. Given that this is now resolved, I will be closing this issue. Thanks for the assignment @Kodiologist - I was on my phone :)
