### ISSUE TITLE
Weeding the core team

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1779]
I'd like to remove inactive members from the core development team. The below users haven't posted an issue, pull request, or comment on this repo for at least 2 years. If you'd like to resume maintaining Hy, or if I just made a mistake, please let me know. Otherwise, I'd like to remove you from the @hylang/core team in a few days, although you'll remain part of the hylang organization.

- @agentultra
- @aldeka
- @berkerpeksag
- @cndreisbach
- @cwebber
- @khinsen
- @microamp
- @rwtolbert

**Comment by khinsen** [comment]
I don't expect to be contributing to Hy any time soon, so it's OK to remove me.

**Comment by paultag** [comment]
Great effort! My only input is that we be sure to be as quick to add people who show a set of good contributions -- it's one of our better qualities as a community. Let's keep Core liberal, but yes, let's remove people as they drop off! 

:+1: Thanks for your work!

**Comment by Kodiologist** [comment]
It is done.

**Comment by Kodiologist** [comment]
Likewise, as of 23 May 2020:

- @theanalyst
- @rkday

**Comment by olasd** [comment]
Feel free to drop me as well.

Thanks for all the fish <3

**Comment by Kodiologist** [comment]
So be it, although I'm sad to learn that we had a dolphin in the core team only to lose him.

**Comment by Kodiologist** [comment]
It is done.
