### ISSUE TITLE
[RFC] Annotation syntax

### ISSUE THREAD

**Issue by refi64** [hylang/hy#1794]
I've been thinking about the best way to handle annotations for a while, especially with Python 3.8 shipping type comment parsing in the built-in ast module. The main issue is that I want the syntax to be consistent across function definitions, variables, etc.

Here's what I've currently come up with:

```hy
; VARIABLE ANNOTATIONS

(setv x &of int 1)

; GENERIC TYPE SHORTHAND

; Instead of e.g. (get List int) for List[int] which sucks
(setv x &of (of List int) 1)

; FUNCTION ANNOTATIONS
(defn myfunc [x &of int y &of str] ...)
; Should we use nested braces instead for consistency with defaults?
; Arguably yes but now we lose consistency with setv.
(defn myfunc [[x &of int 2]])  ; like def myfunc(x: int = 2)
; Or we could only require nested braces for said defaults, e.g.
(defn myfunc [x &of int y &of int [z &of int 2]])  ; def myfunc(x: int, y: int, z: int = 2)

; TYPE COMMENT ALTERNATIVES

; Type comments suck with Hy's style so let's try something else.
; On Python 3.6 we can just lift these out to variable annotations but 3.5 might be messier
(for [[x &of int y &of int] pairs] ...)
(with [(thing) x &of int] ...)

; However we still need to support a # type: ignore equivalent, maybe:
(#ignore
  ...)
```

Some random thoughts:

- This could probably be shipped in a "tech preview" state at first to give us some time to try it out and amend what's necessarily, while letting people know that a bit of potential breakage wouldn't be unexpected.
- Do we really want to support 3.5? 3.6 has already been out for a while, and this would likely be far simpler if we can restrict what needs to be compiled to type comments to just `# type: ignore`. Heck, outside of `# type: ignore`, everything shown here should would in pre-3.8 *without* 
requiring typed_ast.

**Comment by Kodiologist** [comment]
I haven't really been in the loop on the whole typing annotations thing. I understand that Python itself ignores them, so what software is currently in use that uses them?

**Comment by refi64** [comment]
Function and variable annotations are still present in various forms at runtime, the part that Python ignores is the *meaning* of the annotations. That's interpreted by type checking tools.

There are two reasons I think this would be great:
- It would make room for static types in Hy. Sure we could argue about whether that fits with the Lisp ideology, but it would probably be useful for many people.
- We're starting to see libraries take advantage of the presence of these annotations at runtime. E.g. Python 3.7+ adds dataclasses which are kinda like mutable named tuples / the attrs library, and there's Pydantic which uses these type annotations to perform validation of JSON-style data.

**Comment by Kodiologist** [comment]
> the part that Python ignores is the *meaning* of the annotations

Yes, that's what I mean.

Regarding the proposal, an infix syntax, where e.g. `(List &of int)` isn't the same kind of form as `(List foo int)` doesn't seem ideal for Lisp. Can you think of a prefix-style way to accomplish this?

**Comment by refi64** [comment]
I guess we could just do `(&of List int)` though that's pretty much identical in looks to get. It just feels like `(get List int)` to represent a type is rather...odd.

**Comment by Kodiologist** [comment]
Yeah, using the name `get` for that is confusing, so using `of` or something instead makes sense even if it's formally redundant.

**Comment by refi64** [comment]
Actually `of` could be a bit different, e.g. `(of Dict int str)` would compile to `Dict[int, str]`, but the equivalent `get` would compile to `Dict[int][str]`. I guess then `of` could just be something like:

```hy
(defmacro of [item &rest args]
  `(get item (, ~@args)))
```

**Comment by refi64** [comment]
Okay so I updated the original proposal, what do you think of the last two points as well?

**Comment by Kodiologist** [comment]
Can we get a prefix syntax for scalars as well, like `(of x int)` instead of `x &of int`? As a bonus, we can then support whatever syntax for nested types we want purely through our design of `of`'s behavior as a special form, like `(of x (List int))` or whatever.

> This could probably be shipped in a "tech preview" state

That's fine. Technically, the whole language is still a tech preview.

> Do we really want to support 3.5?

Ignoring 3.5 is probably fine. Its end-of-life is in a little over a year, on 13 Sep 2020.

**Comment by refi64** [comment]
I mean I do understand that, but it looks a bit ugly:

```hy
(setv (of x int))  ; ?
(defn myfunc [(of x int)])  ; how would this even work?
```

Also the generic syntax can be used outside of that, e.g. how would this work in the other syntax:

```hy
(setv some-var &of Any {})
(cast (of Dict str str) some-var)  ; this is Dict[str, str]
```

> Ignoring 3.5 is probably fine. Its end-of-life is in a little over a year, on 13 Sep 2020.

~~Sweet less work for me then.~~

**Comment by Kodiologist** [comment]
> `(setv (of x int))`

This probably shouldn't be legal because it isn't an assignment. It would make more sense to allow `of` at the top level.

> `(defn myfunc [(of x int)])  ; how would this even work?`

Presuming you can't declare the types of a function without defining it in Python, this shouldn't be legal, either.

> e.g. how would this work in the other syntax:
>
> `(setv some-var &of Any {})`

As `(setv (of some-var Any) {})`.

> `(cast (of Dict str str) some-var)`

`(cast (of (Dict str str)) some-var)`.

**Comment by refi64** [comment]
Hmm I don't know, I get the idea of prefix syntax being better given that this is Lisp, but it also feels rather verbose...

Looking at the syntax some other lisps use:

- Typed Clojure: Not a fan overall because it seems a bit inconsistent.
  - For variables: `(ann variable Type)`, separately from the assignment.
  - For functions, `(fn [arg :- Type])`, so this is more like the `&of` proposal.
- Racket:
  - For variables: `(: variable Type)`, separately from the assignment.
  - For functions, `(fn [arg : Type])`, again more like `&of` in being infix.

Also in the setv I forgot to have a value for the variable, pretend it's being assigned something, and the `defn` had an empty body so you could use your imagination... But both were supposed to be normal assignments / definitions.

**Comment by Kodiologist** [comment]
I see. I think a prefix syntax for both `setv` and `defn` should be able to work the same way, using the rule that a symbol `foo` can be replaced with `(of foo Type)`, so e.g.

    (defn myfun [a &optional b [c 2]] …)

could be fully typed as

    (defn myfun [(of a int) &optional (of b int) [(of c int) 2]] …)

I think the only verbosity required beyond your original proposal will be more parentheses, at least in some circumstances.

**Comment by asemic-horizon** [comment]
> I haven't really been in the loop on the whole typing annotations thing. I understand that Python itself ignores them, so what software is currently in use that uses them?

I heavily use type annotations, and not as a nice-to-have, Package `pydantic` reads and validates JSON inputs and populates the corresponding Python object. Mini-web framework  `fastapi` (really intended for rest endpoints) heavily uses `pydantic` to the effect that JS objects are mapped to Python objects. 

Here's a simplified example: with `pydantic`'s metaclass `BaseModel` once can do something like

````
class AgeSpec(BaseModel):
    age : int
class MatureSpec(BaseModel):
    is_mature : bool
```
then in your `app.py` you might write

```
@app.post('/is_mature/')
def old_enough(age_input : AgeSpec) -> MatureSpec:
    return Mature({is_mature: age_input.age >=21})
```

Python syntax for the data models is especially concise and readable by non-Python readers (read: node devs), but there is really no reason standard Python can't be used as a DSL for data models. OTOH it would be useful to write the app itself in Hy.

There's already a lot of controversy about syntax, so let me add the possibility of making `defn/t` a specialized constructor for typed functions (since they are not the norm in current Python usage). This may open type declaration syntax options without messing too much with the existing `defn` syntax.

**Comment by Kodiologist** [comment]
I can say that only I and Ryan (@refi64) are particularly active on Hy right now, and I have no plans to implement them because I'm not interested in them. Ryan, do you think you'll take a crack at this soon?

**Comment by Kodiologist** [comment]
(That comment was in response to a deleted comment asking when and if type annotations were going to happen in Hy.)

**Comment by asemic-horizon** [comment]
I went and deleted a comment that asked whether type annotations were in the horizon; on second thought it seemed way too imposing. In the mean time someone responded. Sorry.

**Comment by asemic-horizon** [comment]
I'm overbooked as I've never been for the next two months but following that I could help set up a "business model" (maybe a bounty system, Patreon, etc). I have some experience doing this for nonprofits professionally. Hy (and its developers) deserve more attention and resources.

**Comment by Kodiologist** [comment]
See #957. Speaking for myself, I have a full-time job and I'm not looking for more paid work right now, but others might be interested.

**Comment by refi64** [comment]
I definitely do really want to do this soon, though I am still having some second thoughts on the desired syntax as well...

**Comment by chysi** [comment]
Sorry for barging in like this, but I was just about to start hacking on something like this myself -- as a heavy Pydantic user, not having annotations directly in Hy stings a bit.

As far as I can tell, previous discussion here on this topic has converged on Clojure-style annotations with a caret; see #640 and #1482. Syntax-wise I would thus propose that, as it seems unobtrusive and nicely compatible with the use of `of` to annotate specialized types. So you would get:

```hy
; VARIABLE ANNOTATIONS
 
(setv ^int x 1)

; GENERIC TYPE SHORTHAND
 
; Instead of e.g. (get List int) for List[int] which sucks
(setv ^(of List int) x 1)

; FUNCTION ANNOTATIONS
; function args work like vars
(defn myfunc [^int x ^int y [^int z 2]])  ; def myfunc(x: int, y: int, z: int = 2)
; the return type could be after the function name like in Clojure
(defn myfunc ^(of List str) [^int x ^str y] ...)  ; def myfunc(x: int, y: str) -> List[str]: ...
; or before the function name for consistency, and possibly easier implementation
(defn ^(of List str) myfunc [^int x ^str y] ...)  ; def myfunc(x: int, y: str) -> List[str]: ...
``` 
The type comment equivalents would also work as above, just with the preposed caret syntax. Thoughts?

**Comment by Kodiologist** [comment]
That seems reasonable.

**Comment by refi64** [comment]
If everyone agrees I can go for that. One thing to note: we can technically do stuff like:

```python
x: 'X' = X()
```

How would we represent that with the above syntax? `(setv ^"X" x)`, correct?

This does also still leave how to do declarations without a definition. Maybe:

```
(^int x)  # x: int
(^(of List int) y)  # y: List[int]
```

We are also flipping the order from Python (annotation goes first here with the proposal), but since this is Lisp the normal parsing difficulties don't apply.

**Comment by chysi** [comment]
To the former question, yeah, you'd just put any expression after the caret and it would be written into `__annotations__`. This also allows working with libraries such as Plac, which use string annotations in function definitions.

The latter one is a good question. I think for top-level declarations this would work fine, but also I'm primarily thinking of using pure declarations in a classdef context, coming from pydantic. Here for me the most "natural" extension of the existing syntax would be something like:

```hy
(defclass Point []
  [^int x
   ^int y])

; or with defaults

(defclass Point []
  [^int x 2
   ^int y 2])
```
I'm not sure how annoying this would be to implement in the reader though, given that in this syntax you can also get cases like this:
```hy
; x: int
; y = 2
(defclass Patho []
  [^int x y 2])
```

**Comment by refi64** [comment]
[We dropped the `defclass` attribute list though](https://github.com/hylang/hy/pull/1789), so that exact syntax wouldn't work anyway.

Maybe could just do something like `(^int x)`, then if Hy sees an expression where the first term is annotation syntax, it compiles it down to `x: int`?

**Comment by chysi** [comment]
Ah, I didn’t catch that. That makes everything a lot easier! I fully support your idea then.

**Comment by asemic-horizon** [comment]
For whatever my support counts (I figure it's not much and that's okay), I like it.

**Comment by asemic-horizon** [comment]
I would add that there's some small value in aping Clojure syntax styles: we get to piggyback on Clojure tools for the various editors. (The VSCode Hy mode has subtle defects and there's none for Sublime Text, but in both Clojure syntax coloring works fine; and Parinfer for VSCode seems to be married to Clojure.)

**Comment by refi64** [comment]
While implementing this, I realized the standalone annotation syntax I proposed:

```hy
(^int x) ; x: int
``` 

is actually *really* painful to implement. The reason is that, like most other Hy magic operators, `^int` gets desurgared to `(annotate* int)`, so `(^int x)` becomes `((annotate* int) x)`, which is rather ugly to compile.

I also couldn't help but notice we lose some symmetry:

```python
a: int 
b: int 
c: int = 0 
d: int = 0
```

Vs the somewhat awkward (and badly indented, I'm typing this on mobile so please forgive):

```hy
(^int a)
(^int b)
(setv 
 ^int c 0 
 ^int d 0)
``` 

Here's my thought: what if setv could do plain annotations? They stick out easily, we could just drop off the value:

```hy
(setv 
 ^int a 
 ^int b 
 ^int c 0 
 ^int d 0)
```

It does have the odd attribute that, well, setv has "set" but plain type declarations aren't really *setting* anything in the traditional sense. (Though they are setting the annotation, maybe that counts?)

(I can't help but feel like this would actually look nicer if it were still def, I guess hindsight is everything ¯\\\_(ツ)\_/¯)

**Comment by Kodiologist** [comment]
> `((annotate* int) x)`, which is rather ugly to compile.

I don't think this should be that hard. You just need to insert a check in `compile_expression` that delegates to a new method for `annotate*`. Admittedly, I haven't tried this, so maybe there's something I haven't foreseen.

**Comment by refi64** [comment]
Hmm it's actually not too bad, though it's worth noting that Python also treats annotations in the AST as an assignment without a value, so the setv idea isn't too bad. ¯\\\_(ツ)\_/¯

**Comment by JamesTheAwesomeDude** [comment]
I see this was resolved -- does the documentation need to be updated?

https://docs.hylang.org/en/stable/language/api.html#id1

Nowhere does it currently show how to represent function _return value_ annotations

**Comment by allison-casey** [comment]
You are on an old version of the docs. You need to switch to master line to see the updated annotations. I'll see if I can get a header at the top to make that more clear
