### ISSUE TITLE
kwargs with symbolic :keywords as keys

### ISSUE THREAD

**Issue by asemic-horizon** [hylang/hy#1796]
This is more of an annoyance I probably will just learn to live with than anything else, but the following is counterintuitive (according to me).

```
(defn f1 [alpha beta] (* alpha beta))

(defn simple [] (f1 :alpha 3 :beta 7)) ;; works
(defn bad [] (f1 #**{:alpha 3 :beta 7})) ;; doesn't work
(defn good [] (f1 #**{"alpha" 3 "beta" 7})) ;; works
```
*I know* that (1) Lisp symbols are not naturally equivalent to strings and (2) `good` as defined above matches the closest to the behavior of `**kwargs` in Python. So what's really lacking is a comprehensive concept for mangling symbolic keywords -- and this for a behavior that one newbie finds off-putting. 

I wasn't planning on posting it as an issue, but issue #1765 points at something vaguely related in that his problem may not happen in a world where :keywords are already perceived by Python to be strings. One could want for example want `(f1 #**{:for 3 :with 7}))` to be interpreted as `f1(hy_for = 3, hy_with = 7)`.  This pseudo-solution is not good: it would need a redefinition of `defn` syntax  in a way that just breaks everything. Also: this may not be a problem for anybody else.

**Comment by Kodiologist** [comment]
> his problem may not happen in a world where :keywords are already perceived by Python to be strings

For what it's worth, this used to be the case. Earlier versions of Hy compiled HyKeyword objects not to themselves, as they currently do, but to strings (specifically, the text of the keyword preceded by a special Unicode character to hint that it was a keyword). The new behavior, which makes `(= :foo ':foo)` true, seems to generally work better.
