### ISSUE TITLE
Oddities in the parsing of quote constructs

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1798]
`'` isn't allowed in identifiers, but `` ` ``, `~`, and `@` are. Thus, compare:

- `a'b`  → `HySymbol('a'), HyExpression([HySymbol('quote'), HySymbol('b')])`
- ``a`b`` → ``HySymbol('a`b')``
- ``a~b`` → `HySymbol('a~b')`
- ``a~@b`` → `HySymbol('a~@b')`

So, an identifier can have `` ` ``, `~`, or `~@` in the middle, but not at the beginning. And you can't unquote a variable named `@foo` with a tilde, because `~@foo` is parsed as `(unquote-splice foo)`.

Probably we should remove `` ` `` and `~` from the list of identifier characters, but it's less clear what to do with `@`, since ideally that will remain usable as the Python operator of the same name.

**Comment by refi64** [comment]
Hmm so I guess this is sort of a lose-lose scenario, but as a slightly different thought, what if we:

- Allow ' inside identifiers (e.g. `x'`).
- Disallow @ at the start of multi-character identifiers.

This would be a pretty consistent rule: characters used in quoting aren't allowed at the beginning of multi-character identifiers.

We still end up special-casing for matmul, I almost feel like the cleanest solution would be to change that or ~@ but neither of those options are really *viable* solutions. (Can we even quote the @ operator as it currently stands?)

**Comment by Kodiologist** [comment]
> Can we even quote the @ operator as it currently stands?

Yep:

```
=> `@
HySymbol('@')
=> '@
HySymbol('@')
=> `~@
<function hyx_Xcommercial_atX at 0x7f9966d55ae8>
```

> We still end up special-casing for matmul, I almost feel like the cleanest solution would be to change that or `~@` but neither of those options are really *viable* solutions.

Why not? `@` is rarely used, so I don't imagine there would be a lot of resistance to renaming it `matmul` or something, and the character used for `~@` seems arbitrary, although it's established in Lisp.

**Comment by refi64** [comment]
IMO Changing `~@` seems like it would be a rather large breaking change for pretty small benefit (though I guess it could partly be done just via sed).

I *could* go for switching `@` to matmul or similar as a compromise, though we still won't be able to have `'` in identifiers (that's probably just the Haskell-er in me talking).
