### ISSUE TITLE
Macro expansion works differently from Lisp conventions

### ISSUE THREAD

**Issue by khinsen** [hylang/hy#180]
Given

```
(defmacro rev [&rest body]
  (quasiquote (do (unquote-splice (list (reversed body))))))
```

(shamelessly stolen from native-tests), the expression

```
(let [[rev math.sqrt]] (rev 2))
```

evaluates to `2` whereas in other Lisps I know it evaluates to `(sqrt 2)`. What's worse is that other Lisps' behaviour is more useful. Is this a bug or a feature?

**Comment by algernon** [comment]
Hey, lets revive this, and see if we can push this forward within the Grand Language Cleanup!
