### ISSUE TITLE
Why aren’t epub and pdf downloads available for the docs?

### ISSUE THREAD

**Issue by NightMachinary** [hylang/hy#1801]
readthedocs.io usually automatically creates HTML, PDF, and EPUB downloads available. E.g., see https://readthedocs.org/projects/splash/downloads/. But this is not the case for hy:

https://readthedocs.org/projects/hy/downloads/

Please fix this? Epubs are awesome :(

**Comment by Kodiologist** [comment]
I think I got it working. Check it out.

**Comment by NightMachinary** [comment]
Thanks!
