### ISSUE TITLE
Docs.hylang.org is broken

### ISSUE THREAD

**Issue by paultag** [hylang/hy#1806]
Anyone have an idea why? I'll fix the DNS!

**Comment by Kodiologist** [comment]
Aw dang, I noticed that a few days ago and assumed it was just a temporary blip. I have no idea what happened.

**Comment by paultag** [comment]
Yeah me either. I'll try and dig in later

**Comment by rcarmo** [comment]
Yeah, it would be handy to be able to check the docs now and then... Maybe generating a PDF is in order? :)

**Comment by Kodiologist** [comment]
This is just a DNS issue. You can still see the website at http://hy.readthedocs.org.

**Comment by rcarmo** [comment]
Search doesn't work there, because it links back to the missing domain.

**Comment by paultag** [comment]
I switched the CNAME to readthedocs.io rather than readthedocs.org (maybe stale config?) and also enabled HTTPS while I was in there (thanks @tianon for the docs tip) - let's see what that does

**Comment by tianon** [comment]
![it's working!](https://media.tenor.com/images/90b7fa4c392013cbbfed8603456d5fdc/tenor.gif)

**Comment by paultag** [comment]
I've got a bit of DNS TTL in front of me, I'm going to have to wait, if someone else feels like they were able to validate my work, feel free to close the ticket!

Really weird bug.

**Comment by refi64** [comment]
Looks like it's up ~~flying hy~~ now!

**Comment by paultag** [comment]
Thanks for validating! Sorry about that - I really don't understand the problem, much less why the solution worked.

My assumption was it was set to `.org` because that's what you were supposed to do when we set it up, and eventually rtd flipped over to their `.io` server, and something about that caused a cloudflare hiccup eventually.

If anyone wants to do more of a post-mortum I'd love to make sure that I didn't fix this by mistake :)

**Comment by tianon** [comment]
FWIW, `.io` is what https://docs.readthedocs.io/en/latest/custom_domains.html points to, so it does appear to be the correct thing to do (and IMO that points strongly to it being related and not accidentally fixed)

**Comment by paultag** [comment]
@tianon Relieving! I still have no idea how I got `.org` to begin with unless it changed over time and we got left behind

**Comment by tianon** [comment]
Took a bit of digging, but https://github.com/readthedocs/readthedocs.org/commit/ac6e879669b5d6421672f81240f2e835e51dd0f1#diff-8f1430e75d627f405efec844728afa19 seems relevant 😅

**Comment by paultag** [comment]
🤦‍♂️

**Comment by tianon** [comment]
I was hoping to find more details but even https://github.com/readthedocs/readthedocs.org/pull/2209 is scarce :confused:
