### ISSUE TITLE
Custom mangling

### ISSUE THREAD

**Issue by asemic-horizon** [hylang/hy#1808]
Here's a feature request for the back-burner/crank file/bottom of the pile. 

It would be interesting if we could customize how some specific Hy names are mangled to Python.

Use case: I have a bunch of macros and functions all dealing with database access; for visual niceness and typing conciseness their names all end in "=>". It would be nice if a future Python hire who doesn't want to deal with Hy could use what I call, eg. "(id=> stuff)" as "with_db_query_id(stuff)".

(Character-level conciseness gets a lot of criticism because of one-letter variables etc. but there's an accessibility issue involved for people who need to use large fonts. Then, this is a nightmare for screen readers for the blind.)

**Comment by Kodiologist** [comment]
Hy providing this itself could lead to some very mysterious bugs, I fear, but you can always implement it yourself for functions by looping over the names you've defined and creating aliases:

    (setv c "Xequals_signXXgreaterHthan_signX")
    (for [[k v] (list (.items (globals)))]
      (when (in c k)
        (setv k (+ "with_db_query_" (.replace (.replace k c "") "hyx_" "")))
        (setv (get (globals) k) v)))

For macros, you can do the same sort of thing, but macro introspection isn't officially supported (yet?).

**Comment by refi64** [comment]
In addition to what Kodiologist mentioned, maybe you could make `=>` a macro in your program, so that with some magic `(=> id stuff)` would be identical to `(with-db-query-id stuff)`.
