### ISSUE TITLE
Quoting and equality

### ISSUE THREAD

**Issue by asemic-horizon** [hylang/hy#1809]
This happens.

```
=> (= "name" (quote "name"))
True

=> (= (+ 2 3) (quote (+ 2 3)))
False
```

Equality with Python has always been weird, of course. But

````
=> (= (HySymbol "name") (HySymbol (quote "name")))
True

=> (= (HySymbol(quote(+ (2 3)))) (HySymbol (quote (quote (+ (2 3))))))
False
````

Can HySymbols be compared for equality?

*(Of course I'm writing some CRUD to access a nosql thing I don't even fully understand and instead I'm trying to write a function that creates macros that create functions.) But I can't blame the Hy team for my deteriorating mental health.)*

**Comment by brandonwillard** [comment]
`HySymbol` extends type `str`.

**Comment by Kodiologist** [comment]
Yes, they can. Everything looks correct to me. Can you explain what you find to be counterintuitive or incorrect? (And Brandon's right.)

**Comment by asemic-horizon** [comment]
Brandon just answered my actual question.

As for the background, I was thinking the entire time that `(eval . quote) == eval` should be always true so you shouldn't be able to cross "levels" of quoting in equality. But that thinking is right, it's just that upon further inspection it turns out that strings are fixed points of eval:
```
(= "any string" (eval "any string") ;; True
```

This doesn't happen in Python, but that's  because the Python function named eval takes strings, wile the Hy function named eval takes forms/expressions.  But anyway, that's the design of the language, not an exception to the (intuitive and true) relationship between eval and quote.
