### ISSUE TITLE
A new Try Hy

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1816]
I deleted our documentation's links to http://try-hy.appspot.com (https://github.com/hylang/tryhy) because it's not up to date (hylang/tryhy#6), and we can't update it because we don't control it. But an in-browser Hy shell would still be a nice thing to have, especially to get newbies playing with Hy. Perhaps it can be implemented entirely in JavaScript with e.g. Skulpt so we can host it on GitHub or Read the Docs.

**Comment by gilch** [comment]
Skulpt is Python2 only. Didn't we just drop support for that? Brython might be an option, but I'm not sure if enough of the standard library is implemented to run Hy.

The most complete browser Python I've seen is Pyodide. It's basically CPython compiled via emscripted, so it could probably run Hy. But it's a fairly big download, so the page would load slowly.

I also wonder if a free [python anywhere](https://www.pythonanywhere.com/pricing/) beginner account would be sufficient for our needs.

**Comment by Kodiologist** [comment]
> Skulpt is Python2 only

Oh dang, so it is (skulpt/skulpt#777).

**Comment by refi64** [comment]
Maybe related to #1738?

**Comment by Kodiologist** [comment]
Yeah, if we had both, Try Hy clearly ought to be on or linked from the fancy landing page.

**Comment by proppy** [comment]
Curious if https://wapm.io/package/python could also be potential solution

(btw https://github.com/hylang/tryhy/pull/7, sorry for the delay)

**Comment by albertjan** [comment]
Hi there, skulpt support python3 syntax now. 😄

**Comment by allison-casey** [comment]
Saw ya'll were looking for a Hy Playground page akin to Coconut and what not so I went ahead and built one, ya'll are welcome to it if you'd like it. 

You can find a link to the WIP version [here](https://allison-casey.github.io/hy-interpreter/).

![try-hy-interpreter](https://user-images.githubusercontent.com/18231154/99329115-8beaa100-284b-11eb-9c33-d701da472ba5.gif)

Still a few things to fix up with it, namely:
- Write a codemirror syntax mode for hy
- Linting on errors
- Filter out all but last stackframe from exception traces
- clean up the ui etc

This is essentially the same setup the Coconut uses for its landing page interpreter, just a aws lambda serverless flask app deployed to a github io page.

**Comment by Kodiologist** [comment]
Looks cool. I think it will suffice just as well as proppy's. The important thing is that we control the live instance, so we can update the Hy version when we do a new Hy release.

**Comment by allison-casey** [comment]
I'd be happy to transfer ownership of the app and client code to hylang once I iron out the bugs and clean up the codebase. I'll do a little write up with how to deploy everything to lambda and githubio so ya'll can do whatever you want with it.

**Comment by Kodiologist** [comment]
Thanks, that sounds great. Do you want to join the hylang organization?

**Comment by allison-casey** [comment]
Sure! That would certainly help justify how much time i spend looking through the compiler lol

**Comment by allison-casey** [comment]
managed to knock out the ui stuff, codemirror syntax mode, the stack trace filtering, and wrote up how to deploy the app and client. It'll be a bit before my github.io deployment updates all the changes and it doesn't have linting on errors, but it looks like it does everything that the coconut interpreter does well enough.

Repo can be found [here](https://github.com/allison-casey/hy-interpreter).

@Kodiologist Would you like me to transfer ownership to hy-lang as it is or is there a process you'd want me to go through first?

**Comment by Kodiologist** [comment]
I think that now that you're a member of hylang, you can use some part of the repository control panel on GitHub to move the repository to hylang. Then I guess either you need to give me and @refi64 the credentials to deploy the code to that Amazon service, or we need to create a new Amazon account for Hy development. I'm not familiar with AWS (or Node.js, or Zappa, or ClojureScript, etc.).

**Comment by allison-casey** [comment]
I moved it over to hylang, under the core team. I don't have access to the repo anymore since i'm not core but I think you can give me permission specifically for this repo. If you do, I can set up an initial deployment under a dedicated hylang aws account and give you those credentials so you can take it from there.

**Comment by Kodiologist** [comment]
The repository settings list you as having the "Write" role, so you should still have access. Are you getting an error message when you try to read from it or push to it?

**Comment by allison-casey** [comment]
was just worried I didn't have permission to muck around with github io with just write permissions, but it looks like it worked out fine. Interpreter is up, using my lambda endpoint for now, [here](https://hylang.github.io/hy-interpreter/). I can set up an aws account for hylang, but I think you should probably do that since that's what will have admin controls over the endpoint.

**Comment by Kodiologist** [comment]
> but I think you should probably do that since that's what will have admin controls over the endpoint

Okay, I'll take a crack at it tomorrow.

**Comment by paultag** [comment]
This rules, and I love all of this, nice work everyone :100:

**Comment by paultag** [comment]
(but specifically, @allison-casey - thank you!)

**Comment by Kodiologist** [comment]
@allison-casey I've created an AWS account for Hy with an IAM user for you. Do you have a PGP key so I can email you an encrypted copy of your credentials?

**Comment by Kodiologist** [comment]
Also, could you arrange the service to be automatically shut off when we exceed the free usage tier? I'd hate to have my credit card maxed out because somebody decided to DDoS our Hy console.

**Comment by allison-casey** [comment]
I sent my public key to your email. I'll see what I can do about the aws tier, luckily aws lambda with zappa is absurdly cheap/free. I'll enable usage alerts and I've also debounced the console so we'll hopefully see it before anything gets out of hand.

**Comment by allison-casey** [comment]
Fixed the css issues and moved it all over to the hylang dedicated endpoint. 
Idk what ya'll were planning to do in terms of landing pages but something like this seems to work okay
```rst
.. raw:: html

   <div style="margin: 2em 0 2em 0">
     <iframe
       style="width: 100%; height: 25em;"
       src="https://hylang.github.io/hy-interpreter/"
       title="TryHy!">
     </iframe>
   </div>
```
Gives us something like
![landing-page](https://user-images.githubusercontent.com/18231154/100134412-2ce1e900-2e56-11eb-9a33-c6174ae44e52.jpg)

Let me know if you want me to change the theme around or if you find something thats broken

**Comment by Kodiologist** [comment]
Nice! I think I'll just add a direct link to the https://hylang.github.io/hy-interpreter/ from the README so the user gets a full browser window for it.

**Comment by proppy** [comment]
Is that OK to archive https://github.com/hylang/tryhy now that this is closed? Or would you prefer to re purpose the repo for something else?

**Comment by Kodiologist** [comment]
Go ahead and archive it, sure. Thanks.

**Comment by Kodiologist** [comment]
It turns out that the AWSes we're using will start charging based on usage after a year of use, so I guess we need to replace this again.

I've had some success using Brython for a different project, so perhaps that's a good choice.

**Comment by allison-casey** [comment]
gosh darn it bezos, just let us have this. 

Anyways, do we know how much they would actually start charging? We have absurdly low usage rates for what Amazon is usually marketing towards. If it's not bad i'd be down to pay for it.

**Comment by Kodiologist** [comment]
Good question. I looked earlier and found [usage numbers](https://github.com/hylang/hy/files/7528529/billing.pdf), but it's not clear how much we'd be paying if we were paying.

**Comment by scauligi** [comment]
Brython seems like a good route, since it looks like it does everything client side? With AWS I'm just wary of someone submitting a pathological program for giggles and we're left footing the bill.

**Comment by Kodiologist** [comment]
@allison-casey Can you either decommission all the AWSes or give Amazon a payment method for yourself?

**Comment by Kodiologist** [comment]
I believe that charges start on November 30th.

**Comment by allison-casey** [comment]
I'll change the payment this weekend

**Comment by proppy** [comment]
re: Brython, would something like https://github.com/pyodide/pyodide also work?

**Comment by Kodiologist** [comment]
Allie is generously bankrolling AWS for us, so things are good for the time being.
