### ISSUE TITLE
Remove dependency on clint

### ISSUE THREAD

**Issue by nmeum** [hylang/hy#1820]
While packaging hy for [Alpine Linux](https://alpinelinux.org/), I noticed that it depends on [clint](https://github.com/kennethreitz/clint). Which wasn't packaged by Alpine either. I am not a python guy but it seems to me that clint is pretty dead. The repository is archived and the last release is from 2015.

Is there any particular reason why it is still being used, is not possible to use a command line argument parser from the python3 standard library, e.g. argparse, instead?

**Comment by Kodiologist** [comment]
It's just inertia. We should get rid of it.
