### ISSUE TITLE
error importing LET

### ISSUE THREAD

**Issue by tensorfoo** [hylang/hy#1822]
```
=> (import [hy.contrib.walk [let]])
Traceback (most recent call last):
  File "stdin-d8346bc6075bece22494c8b6b13014ef8b4cb349", line 1, in <module>
    (import [hy.contrib.walk [let]])
ImportError: cannot import name 'let'
```

With the latest master.

**Comment by Kodiologist** [comment]
Hy is case-sensitive, and you can't import a macro. (Technically, you can if you know its internal name, but importing it doesn't do what you'd expect and is rarely useful.) See `require`.

**Comment by tensorfoo** [comment]
Thanks, for anyone else who stumbles on the same thing: 

```
=> (require [hy.contrib.walk [let]])
True
=> (let [x 10]
... (+ x 1))
11
=> 
```
