### ISSUE TITLE
0.17 doesn't seem to require Python 3.5+

### ISSUE THREAD

**Issue by alphapapa** [hylang/hy#1828]
I updated Hy with `pip3` on a system that had Python 3.4, and it installed Hy 0.17, which doesn't work on Python 3.4.  I had to manually downgrade to Hy 0.16.

If there's a way to configure the minimum Python3 version so that `pip3` would automatically install 0.16 in such a case, that would be helpful.

**Comment by Kodiologist** [comment]
I don't think PyPI or setuptools or pip support that, no. We use classifiers like `Programming Language :: Python :: 3.5` to indicate which Pythons we support, but the Python packaging system doesn't enforce this in any way.

**Comment by refi64** [comment]
Indeed, afaik there's no way of doing this (3.4 is EOL anyway...).
