### ISSUE TITLE
Warn in documentation that Python's closures are late-binding

### ISSUE THREAD

**Issue by alphapapa** [hylang/hy#1829]
I may have missed something, but it seems that lexical closures require the use of the `let` macro, and this doesn't seem to be documented--or at least, not prominently.  This issue seems likely to be encountered by those accustomed to Lisps or Schemes, so I think it should be documented prominently.

For example, I wanted to conditionally wrap a function in another function at runtime.  This code (where `action-fn` is the function being wrapped) doesn't work, because `action-fn` is not lexically bound, so it's bound to itself, which causes infinite recursion:

```hy
(setv action-fn (fn [&rest args &kwargs kwargs]
                  (action-fn #* args #** kwargs)
                  (print-files #* args #** kwargs)))
```

But using `let` to save the original value of `action-fn` works:

```hy
(setv action-fn (let [orig-fn action-fn]
                  (fn [&rest args &kwargs kwargs]
                    (orig-fn #* args #** kwargs)
                    (print-files #* args #** kwargs))))
```
If I am indeed missing something, please forgive the noise.

Thanks for your work on Hy.

**Comment by Kodiologist** [comment]
No, closures don't require `let`. Here's an example of a closure in Python:

```
def f():
   a = 1
   def g():
       return a
   return g

print(f()())
```

The second example works fine with `setv` in place of `let`. I'm unclear why you expected the first example to work as written, but at any rate, a function's own name is not an exception to the function body's ability to see its outer scope.

**Comment by Kodiologist** [comment]
In particular, functions having their own names in scope is how one writes a recursive function in Python, and usually in Hy, too.

**Comment by alphapapa** [comment]
> I'm unclear why you expected the first example to work as written

I'm probably confused about something, but I'm thinking of these examples (Scheme, Common Lisp):

```scm
(let* ((a (lambda ()
            "a"))
       (a (lambda ()
            (list (a) "b"))))
  (a))
;; $1 = ("a" "b")
```
```cl
(let* ((a (lambda ()
            "a"))
       (a (lambda ()
            (list (funcall a) "b"))))
  (funcall a))
;; => ("a" "b")
```
The first function `a` is included in the environment of the second function `a`, so it can call the first function, and calling `a` in the `let`'s body calls the second function.

Trying to do that in Hy causes infinite recursion, e.g.
```hy
(setv a (fn []
          "a"))
(setv a (fn []
          (list (a) "b")))
(a)
;; RuntimeError: maximum recursion depth exceeded
```
Doing it inside of a function also causes infinite recursion, e.g.:
```hy
(defn test-fn []
  (setv a (fn []
            "a"))
  (setv a (fn []
            (list (a) "b")))
  (a))
(test-fn)
;; RuntimeError: maximum recursion depth exceeded
```
Even using `let` doesn't solve this in Hy/Python, e.g.
```hy
(let [a (fn []
          "a")
      a (fn []
          (list (a) "b"))]
  (a))
;; RuntimeError: maximum recursion depth exceeded
```
I do understand that this is Python, not a Lisp or Scheme.  My point is that these kind of issues are probably to Lispers and Schemers like short doorways are to tall people: likely to cause one to smack one's head.  It would be helpful if there were a warning sign.  :)

**Comment by alphapapa** [comment]
I adjusted the title of this issue to try to be more accurate.

Thanks for your help.

**Comment by Kodiologist** [comment]
I guess that what you're expecting is for the bindings between the names mentioned in a function and the values they refer to to be fixed as soon as the function definition ends. In Python, the search for a value occurs as late as possible, when the code is actually being run, although static properties of the function (`nonlocal` declarations, `global` declarations, and the presence of assignments elsewhere in the same function) affect which namespaces are searched.

I'm not sure where and how a documentation addition about this would be most helpful to programmers coming from other Lisps. Mostly we try to encourage readers to consult the Python documentation, rather than recapitulating the details of Python semantics. But a PR is welcome, I suppose.

**Comment by alphapapa** [comment]
> I guess that what you're expecting is for the bindings between the names mentioned in a function and the values they refer to to be fixed as soon as the function definition ends. 

Well, no, that's not how Lisps work, so it's not what I'm expecting here.  :)

>  In Python, the search for a value occurs as late as possible, when the code is actually being run

Which is basically how Lisps work, right?  (Other than some exotic ones that get statically compiled.)

> although static properties of the function (nonlocal declarations, global declarations, and the presence of assignments elsewhere in the same function) affect which namespaces are searched.

This is the key difference between Hy and other Lisps.  (Does Hy even refer to itself as "a Lisp"?)

> I'm not sure where and how a documentation addition about this would be most helpful to programmers coming from other Lisps. Mostly we try to encourage readers to consult the Python documentation, rather than recapitulating the details of Python semantics.

Of course, there is a limit to how much can be documented effectively.  The problem, as I see it, is that Hy is putting a Lispy face on Python, tempting users to use it like a Lisp, which unintentionally sets them up to run into some "low doorframes" that a "real Lisp" wouldn't have.

The Hy docs have a section called, "Basic intro to Lisp for Pythonistas."  I think it needs one called, "Hy for Lispers/Schemers," which should include some prominent examples of what one *can't* do in Hy that one would typically do in a Lisp/Scheme.  That could save new users a lot of trouble.

**Comment by Kodiologist** [comment]
> > I guess that what you're expecting is for the bindings between the names mentioned in a function and the values they refer to to be fixed as soon as the function definition ends.
>
> Well, no, that's not how Lisps work

If so, I'm really confused why the second `lambda` in `(let* ((a (lambda () "a")) (a (lambda () (list (a) "b")))) (a))`, when called after all the `let`-bindings have been made gets the first `a` when it asks for `a`, instead of itself.  What language is this code in, Scheme? I don't think it can be Common Lisp since Common Lisp is a Lisp-2.

> Does Hy even refer to itself as "a Lisp"?

Yes.

>  I think it needs one called, "Hy for Lispers/Schemers

[Like this one?](https://docs.hylang.org/en/master/whyhy.html#hy-versus-other-lisps)

**Comment by alphapapa** [comment]
> > > I guess that what you're expecting is for the bindings between the names mentioned in a function and the values they refer to to be fixed as soon as the function definition ends.
> > 
> > 
> > Well, no, that's not how Lisps work
> 
> If so, I'm really confused why the second `lambda` in `(let* ((a (lambda () "a")) (a (lambda () (list (a) "b")))) (a))`, when called after all the `let`-bindings have been made, gets the first `a` when it asks for `a`, instead of itself. What language is this code in, Scheme? I don't think it can be Common Lisp since Common Lisp is a Lisp-2.

Yes, that example is Scheme (eval'ed in Guile), and the second is CL.  The `let*` form binds sequentially, so the first lambda's definition is captured in the second lambda's environment.  (That's my simple explanation, anyway; I'm not a Scheme expert.)

> > I think it needs one called, "Hy for Lispers/Schemers"
> 
> [Like this one?](https://docs.hylang.org/en/master/whyhy.html#hy-versus-other-lisps)

When I Google or DDG for something like `hylang docs`, I get https://docs.hylang.org/en/stable/index.html, which doesn't have that section.  And since I'm running a stable version, I wouldn't seek out the `master` ("unstable", at the top of that page) version of the docs anyway.  :)

Having said that, that section is a pleasant read, but it doesn't give much specific guidance about differences between CL/Scheme and Hy.  A "common pitfalls" section could be very helpful.

**Comment by Kodiologist** [comment]
Okay, then I guess we'll need an expert in Scheme or something to write the desired piece of documentation, since I'm not clear what semantics are expected, so I can't explain how Hy is different.

**Comment by alphapapa** [comment]
I tried to find some information about this issue.  This link seems relevant: https://docs.python-guide.org/writing/gotchas/#late-binding-closures

For me, I guess it's an issue of "mental overhead" in switching between a traditional Lisp and Hy.  The Hy-Python hybrid model is similar enough to a traditional Lisp that I start to feel like I'm using one, and then I try to use certain patterns that I would use in a traditional Lisp which conflict with Python's model, so they don't work as expected.  

Since those patterns don't work in Python, most Hy users who are approaching it from the Python side probably wouldn't try to use them in Hy in the first place.  To put it another way, Hy is like a superset of Python, but a subset of a traditional Lisp.  Going from Hy to Python is liberating, but going from a traditional Lisp to Hy is slightly restricting (or subtly different enough that it can feel that way).  This isn't Hy's fault, of course, but the nature of being Python under the hood (Hy already does an amazing job layering a Lisp on top of Python).

So I think it would be helpful if there were a document describing traditional Lisp patterns that require alteration in Hy-land.  :)

Thanks for your work on Hy.

**Comment by Kodiologist** [comment]
> This link seems relevant: https://docs.python-guide.org/writing/gotchas/#late-binding-closures

Yes, that's what I meant by "the search for a value occurs as late as possible, when the code is actually being run".

**Comment by Kodiologist** [comment]
After some mature thought, I'm pretty certain that binding time is the issue here.

**Comment by Kodiologist** [comment]
But it turns out that "binding time" is used in several different senses. For example, Wikipedia defines it as being in terms of whether the namespace for a variable is selected at compile-time or run-time. And in that sense, Python is early-binding, because whether a given `x` refers to a global or local variable, and, in the local case, which function it belongs to, is decided by the time the code is compiled.

Furthermore, the phenomenon that you noticed in Common Lisp and Scheme doesn't occur in all previous Lisps. Emacs Lisp, in particular, will attempt to recurse infinitely until it hits `max-lisp-eval-depth`.

Just to check, @gilch, is it a bug that `(let [a (fn [x] 1)] [a (fn [x] (a))])` macroexpands to assign to a single dictionary element twice, instead of using a new dictionary element for the second `a` (so that the inner `(a)` will continue to refer to the first lambda in the body of the `let`), or is that intentional?

**Comment by alphapapa** [comment]
> But it turns out that "binding time" is used in several different senses. For example, Wikipedia defines it as being in terms of whether the namespace for a variable is selected at compile-time or run-time. And in that sense, Python is early-binding, because whether a given x refers to a global or local variable, and, in the local case, which function it belongs to, is decided by the time the code is compiled.

Makes sense, yes.

> Emacs Lisp, in particular, will attempt to recurse infinitely until it hits `max-lisp-eval-depth`.

Not when `lexical-binding` is enabled, which is not the default, but is recommended for all newly written code.  e.g.

```el
;;; alpha-0ac22.el ---                               -*- lexical-binding: t; -*-

(defun foo ()
  (let* ((a (lambda ()
              "a"))
         (a (lambda ()
              (list (funcall a) "b"))))
    (funcall a)))

(foo)  ;;=> ("a" "b")
```

**Comment by gilch** [comment]
We are not (or should not be) claiming that Hy's `let` is the equivalent of `let*`. It's not. I think it's actually closer to `letrec`. It does do sequential rather than parallel assignments, but it does so to a *single namespace*.

`let*`, on the other hand, is like *nesting* lets, creating a *new* (nested) namespace for each binding.

Try this in Hy:
```
=> (let [a (fn [] "a")]
... (let [a (fn [] [(a) "b"])]
...  (a)))
['a', 'b']
```
The above is Hy's equivalent of a `let*`.

**Comment by Kodiologist** [comment]
Okay, I guess we should mention this in the documentation for `let` and that should suffice.

**Comment by gilch** [comment]
One could probably write a macro to implement a `let*` in terms of Hy's `let`, but this seems inefficient for general use. It would allocate a new dict for each local. Here's an attempt:
```
=> (defmacro let* [bindings &rest body]
... (if bindings
...   `(let ~(cut bindings 0 2)
...      (let* ~(cut bindings 2 None) ~@body))
...   `(do ~@body)))
<function <lambda> at 0x000001318F0A7C80>
=> (let* [a (fn [] "a")
...       a (fn [] [(a) "b"])]
... (a))
['a', 'b']
```

**Comment by Kodiologist** [comment]
Maybe you could use only one dictionary if you remangled repeated names with a counter, like `gensym`. Not that it's necessarily worth the effort.
