### ISSUE TITLE
wishlist: a unified index of symbols in the hy distribution, perhaps also contrib

### ISSUE THREAD

**Issue by slippycheeze** [hylang/hy#1845]
In the current documentation the set of symbols I can reference in core hy is split into multiple distinct sections in the left-hand-side index: "Built-Ins", "Hy Core", "Extra Modules Index", and "Contributor Modules Index".  The "Hy Core" is further subdivided into "only one open at a time" lists of core, sequence, and itertools functions.

Especially with the built-in/core split this makes it more difficult than I'd like to navigate the system: I don't especially care if `instance?` is a built-in, or part of the core library, or supplied by itertools, when I just wanted to know what the function signature was.  

(OK, that one is kind of a gimmie when it comes to figuring out which section, but definitely things like `filter` or `name` are way harder to guess.)

Anyway, it'd be great if there was a single index that listed all those items so that I could scan the list to find what I'm looking for, click it, and get the right docs immediately.  In the Common Lisp HyperSpec (CLHS) this is their symbol index – it only covers symbols, as in functions, global vars, etc, and not, eg, syntax discussion, or anything like that.

I am not familiar enough with Python documentation generators to know how/if this can be done, and I'm unfortunately not in a position for a couple of months due to USA related work issues to be able to contribute to make this happen.  Sorry.

**Comment by Kodiologist** [comment]
It's a reasonable request and it's the kind of thing that Sphinx is supposed to make easy, but this probably won't happen before deeper changes to the documentation like embedding docstrings. In the meantime, there's always `help`.

**Comment by allison-casey** [comment]
So this seemed kind of important for newcomers so I started working through getting Sphinx properly set up with hy.
First step was to create a Hy domain extension which you can find [here](https://github.com/allison-casey/sphinxcontrib-hydomain) and then the autodoc extension. Once that's done i'll go through and update the hylang docs, but I wanted to post this here now in case anyone wanted to take a look/test the domain extension to see if I missed anything.

**Comment by Kodiologist** [comment]
I don't know much about Sphinx. What does providing a custom domain for Hy do?

**Comment by allison-casey** [comment]
Domains let you write in a different language. Sphinx comes built in with a Python domain and C domain. I added a Hy domain. With that we get all the nice things about sphinx. Internal links to hy methods and classes, hooks into autosummary and autodoc etc. Basically lets use do things like and sphinx will just get it.

```rst
* Link to :hy:func:`foo.add!`

.. hy:function:: (foo.add! ^float [a b])

   adds two numbers together
   
   :returns: Sum of `a` and `b`
```

**Comment by Kodiologist** [comment]
> we can autogenerate the docs for the entire core library so no more having to write docs in two places etc

Nice, that's definitely on our wishlist.

**Comment by Kodiologist** [comment]
I forgot, we have a separate issue for it, namely #1044.
