### ISSUE TITLE
`ap-reduce` assumes that iterables can be `cut`

### ISSUE THREAD

**Issue by falloutphil** [hylang/hy#1848]
Hi,

It looks like before passing an anaphoric macro the result of a map or zip, I first have to call list on it to explode the object into a list object (rather than directly pass the map or zip object).

It would be nice if the anaphoric macros could handle iterable objects directly - is this possible?  I'm guessing it would be a new feature request?

**Comment by Kodiologist** [comment]
What makes you think this isn't already implemented? From a casual glance at the code of all the macros, the only issue that jumps out at me is that `ap-reduce` tries to use `cut` when no initial value is provided.

**Comment by falloutphil** [comment]
Apologies, yes, I only saw the problem on ap-reduce. I'll update the title.

**Comment by Kodiologist** [comment]
It's a bug.
