### ISSUE TITLE
Support Python's chained comparisons

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1852]
In Python, `2 == 2 > 1` is true although `(2 == 2) > 1` and `2 == (2 > 1)` are both false.

To implement chained comparisons, we should probably add a special form with infix syntax, like `(compare 2 = 2 > 1)`, rather than try to detect forms like `(> (= 2 2) 1)` and give them magical semantics. It won't be very Lispy and it probably won't be used much, but at least it'll be available.

**Comment by Kodiologist** [comment]
The clarify, the existing forms work fine for chained comparisons that only use one distinct operator, like `(< 1 2 3)`. What's missing is support for mixed operators, and for a few pathologies that Python allows, like `[1] in [2] in [3]`.

**Comment by refi64** [comment]
How useful is this in practice? The only common case I could think of for
mixing two different operators in a chain would be something like a < b <=
c or a > b < c, an in that case maybe an in-range macro or similar would be
more readable while covering the use case nicely.

**Comment by Kodiologist** [comment]
It's not that useful, no. The point is just completeness: being able to generate any desired Python AST node.
