### ISSUE TITLE
ap-dotimes can not substitute variable for number

### ISSUE THREAD

**Issue by falloutphil** [hylang/hy#1853]
Hi,

I'd expect these to uses of `ap-dotimes` to produce the same result?

Could you confirm if this is a bug or if I've misunderstood us of the macro?

```hy
=> (ap-dotimes 3 (print it))
0
1
2
=> (setv i 3)
=> (ap-dotimes i (print it))
Traceback (most recent call last):
  File "stdin-156cdc3272dbec664aa1ca1a93db0b27f0d649f0", line 1, in <module>
    (ap-dotimes i (print it))
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/phil/.local/lib/python3.6/site-packages/hy/extra/anaphoric.hy", line 70, in ap_dotimes
    (raise (TypeError (.format "{!r} is not a number" n))))
hy.errors.HyMacroExpansionError: 
  File "<stdin>", line 1
    (ap-dotimes i (print it))
    ^-----------------------^
expanding macro ap-dotimes
  TypeError: HySymbol('i') is not a number


=> 
```

In particular because this does work:

```hy
=> (ap-each (range i) (print it))
0
1
2
=> 
```

**Comment by Kodiologist** [comment]
The implementation of `ap-dotimes` explicitly checks that `n` is a number, which makes no sense because it's a macro, so of course in general `n` is going to be an expression. I guess the moral is that `hy.extra.anaphoric` is hot garbage.

**Comment by Kodiologist** [comment]
If you happen to find more of these (at this point, I'm sure there are more), just add them to this issue and it can become the omnibus `anaphoric` bug.

**Comment by Kodiologist** [comment]
Here's another: `ap-last` calls `ap-each` in its expansion, so it doesn't work if you haven't `require`d `ap-each`.
