### ISSUE TITLE
Defmacro doesn't capture helper function definitions

### ISSUE THREAD

**Issue by zhanghaze** [hylang/hy#1859]
Sorry if this is a 

```
(defn mrest [x]
  (list (rest x))
  )
(defmacro ta [x]
  (setv yy (mrest x))
  `(print yy)
  )

(ta 'c)
```

 This macro will give error

`  NameError: name 'mrest' is not defined
`
So how can a macro call helper functions? does it have to be always inside of defmacro?

**Comment by brandonwillard** [comment]
See [`eval-and-compile`](https://docs.hylang.org/en/stable/language/api.html#eval-and-compile) and/or [`eval-when-compile`](https://docs.hylang.org/en/stable/language/api.html#eval-when-compile).

**Comment by Kodiologist** [comment]
Duplicate of #1414.
