### ISSUE TITLE
Source package can't be installed because it excludes fastentrypoints.py

### ISSUE THREAD

**Issue by yurivict** [hylang/hy#1861]
Version 0.17.0 fails:

```
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/wrkdirs/usr/ports/lang/py-hy/work-py36/hy-0.17.0/hy/__init__.py", line 21, in <module>
    import hy.importer  # NOQA
  File "/wrkdirs/usr/ports/lang/py-hy/work-py36/hy-0.17.0/hy/importer.py", line 20, in <module>
    from hy.compiler import hy_compile, hy_ast_compile_flags
  File "/wrkdirs/usr/ports/lang/py-hy/work-py36/hy-0.17.0/hy/compiler.py", line 9, in <module>
    from hy.model_patterns import (FORM, SYM, KEYWORD, STR, sym, brackets, whole,
  File "/wrkdirs/usr/ports/lang/py-hy/work-py36/hy-0.17.0/hy/model_patterns.py", line 8, in <module>
    from funcparserlib.parser import (
ModuleNotFoundError: No module named 'funcparserlib'
```

**Comment by Kodiologist** [comment]
funcparserlib is listed as `install_requires` in `setup.py`, so it should be installed along with Hy. How did you install Hy?

**Comment by yurivict** [comment]
I may have confused the package name. What about ```fastentrypoints```? There is the import statement, but no ```require``` statement.

**Comment by Kodiologist** [comment]
You didn't confuse the package name. The error message that you copied says "`funcparserlib`". `fastentrypoints` is actually included in the repository (it needs to be, because of how it works).

**Comment by yurivict** [comment]
setup.py has
```
install_requires = [
    'rply>=0.7.7', 
    'astor>=0.8',
    'funcparserlib>=0.3.6',
    'clint>=0.4']
```
and also
```
import fastentrypoints   # Monkey-patches setuptools.
```

Shouldn't ```fastentrypoints``` also appear in ```install_requires```?

**Comment by Kodiologist** [comment]
No, it should not, because it's already included.

I can't help you with your error message unless you tell me how you installed Hy.

**Comment by yurivict** [comment]
I'm building the FreeBSD port.

Here is the error message:
```
===>  Configuring for py36-hy-0.17.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 10, in <module>
    import fastentrypoints   # Monkey-patches setuptools.
ModuleNotFoundError: No module named 'fastentrypoints'
*** Error code 1
```

**Comment by yurivict** [comment]
You use ```fastentrypoints``` and not declare it in the ```require``` statement.

**Comment by Kodiologist** [comment]
That's a different error message from the one you created the issue for, and you still haven't told me how you installed Hy. I don't know what "building the FreeBSD port" in terms of installing a Python package. I have never used a BSD.

**Comment by yurivict** [comment]
>  you still haven't told me how you installed Hy

I said: FreeBSD port. It uses setuptools run by a framework.

Please disregard the original message - it was a mistake.

Clearly, you use ```fastentrypoints``` w/out declaring it as a dependency in ```require``` statement.

**Comment by Kodiologist** [comment]
I thought that by "`require` statement", you meant the parameter `install_requires` to `setuptools.setup(…)`, but I'm beginning to wonder if you mean something else, perhaps a parameter in some kind of BSD package installation script that we don't maintain. I hope it's clear that putting `"fastentrypoints"` in `"install_requires"` would be of no use, since `import fastentrypoints` is executed first, besides the aforementioned fact that `fastentrypoints.py` is in the repository already, so it doesn't need to be installed separately.

**Comment by yurivict** [comment]
Do you agree with these 2 facts:
1. fastentrypoints is used in setup.py
2. fastentrypoints is absent from install_requires

Using these 2 facts, please answer the question: who installs fastentrypoints for it to be used in the import statement?

**Comment by Kodiologist** [comment]
1. Yes.
2. Yes.
3. Nobody. [See the documentation.](https://pypi.org/project/fastentrypoints)

**Comment by Foxboron** [comment]
Well, this is a freebsd ports packaging mistake and not an upstream issue. It builds fine on Arch Linux.

**Comment by Kodiologist** [comment]
If I understand correctly, OP is trying to create said port. It sounds like there's a problem with however the OpenBSD toolchain uses `setuptools`.

**Comment by yurivict** [comment]
FreeBSD ports framework attempts to run setup.py in a clean system with only declared dependencies installed, and fails with the above message. I personally agree with this message, in a clean system, the package isn't installed and isn't available.

The docs you linked is simply wrong: fastentrypoints is a separate package, and as such it should be used via the ```require``` statement.

**Comment by Foxboron** [comment]
It builds fine in the clean chroots used by Arch Linux package maintainers. `fastentrypoints` isn't an actual dependency but refers to the actual file found in the root of this project.

**Comment by Kodiologist** [comment]
I think you're confused, but I don't know how to explain it to you more, given that neither my own explanation of why putting `fastentrypoints` in `install_requires` is pointless, nor the `fastentrypoints` documentation's explanation, have convinced you. At any rate, I'm certainly not persuaded that whatever error or errors you're encountering indicate that something needs to change on our side, considering the uncertainty in what the FreeBSD tools are trying to do.

**Comment by yurivict** [comment]
> fastentrypoints isn't an actual dependency but refers to the actual file found in the root of this project.

It's not in the tarball downloaded from PyPI for version 0.17.0.

**Comment by Foxboron** [comment]
@yurivict There we go!

That is indeed a hylang issue on the pypi side (cc @Kodiologist), but the github autogenerated one does have, that is what Arch uses. I also verified by looking at both tarballs.

**Comment by Kodiologist** [comment]
Yeah, probably what's needed is to add it to `MANIFEST.in`, which the fastentrypoints documentation mentions.

**Comment by yurivict** [comment]
Just add ```fastentrypoints``` to the ```install_requires``` statement and be done with.
It is just another python package, just like any other package.

**Comment by refi64** [comment]
@yurivict setup.py needs fastentrypoints already available in order to work, therefore it must be available at the time setup.py is run.

**Comment by yurivict** [comment]
@refi64 
fastentrypoints package needs to be installed for this.
