### ISSUE TITLE
fail load stable_baselines

### ISSUE THREAD

**Issue by niitsuma** [hylang/hy#1870]
When loading `stable_baselines` (  https://stable-baselines.readthedocs.io/en/master/ )
it fail.

```hy
(import stable_baselines)
=> 
google/protobuf/descriptor_database.cc:172] Symbol name "tensorflow.TensorShapeProto" conflicts with the existing symbol "tensorflow.TensorShapeProto".
google/protobuf/descriptor.cc:1367] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
Aborted
```

Sorry. 
It work  in updated OS.
Maybe depend on lib version

**Comment by Kodiologist** [comment]
> It work in updated OS.

It's unlikely to be a bug in Hy, then. When the code you're having an issue with has a direct Python equivalent (in this case, `import stable_baselines`), you should check that the Python version works before reporting a bug in Hy.

**Comment by niitsuma** [comment]
I checked `import stable_baselines` worked in python3.6.
But not work in hy. This bug was fixed by updating OS.
