### ISSUE TITLE
Unexpected behavior with defclass

### ISSUE THREAD

**Issue by zhanghaze** [hylang/hy#1871]
with hy 0.17

```
(defclass test []
  [context [{}]]
  (defn print [self]
    (print self.context)
    )
  )

```

(.print (test))

gives

```
Traceback (most recent call last):
  File "stdin-412d25cc2348437ead4dbf5b96471d893acc1fb2", line 1, in <module>
    (.print (test))
  File "stdin-55ac397c5cb2f100219a62e081b8d94c3fc1d27a", line 4, in print
    (print self.context)
  File "stdin-511f8c7d5f0dc234c7d1f89db9d5766f5f6d41e0", line 2, in print
    (print self.context)
AttributeError: 'list' object has no attribute 'context'

```

**Comment by Kodiologist** [comment]
That syntax hasn't been legal since #1789.

**Comment by zhanghaze** [comment]
new sytax

```
(defclass test []
  (setv context [{}])
  (defn print [self]
    (print self.context)
    )
  )
```

same error

**Comment by Kodiologist** [comment]
I can't replicate it on master. I get `[{}]`.

**Comment by zhanghaze** [comment]
you are right. I cannot replicated this with a fresh hy session. Something seems to mess up with the hy session I was using that this error persists.

**Comment by Kodiologist** [comment]
It might be a subtlety involving the name `test` and the REPL's unusual handling of automatic imports. There's a built-in Python module named `test` that's caused problems for us before. If you can figure out how to replicate the error, we can reopen the issue.
