### ISSUE TITLE
parse-args requires values to be representable as Hy models

### ISSUE THREAD

**Issue by redraiment** [hylang/hy#1875]
# Issue

The behaviors between `:type` keyword argument of parse-args function in hylang and `type` of argparse.ArgumentParser.add_argument method in Python are different.

* In Python: it's used for type conversion, and the value type is function, which accepts a string argument and returns the target type value. Therefore, I can define custom function to parse the string value.
* However, in hylang, the value type is symbol (i.e. `:type 'int`), and cannot use custom function.

For example, I'd like to set image size with `<width>x<height>` format, i.e. `--size 800x600`.

In Python:

```python
import argparse

def size(s):
    width, height = s.split('x')
    return int(width), int(height)

parser = argparse.ArgumentParser()
parser.add_argument('-s', type=size)
parser.parse_args(['-s', '800x600']) #=> Namespace(s=(800, 600))
```

In hylang will get an exception:

```hy
(defn size [s]
   (setv [width height] (s.split "x"))
   [(int width) (int height)])
(parse-args [["-s" :type size]] ["-s" "800x600"])
```

Exception message:

```
Traceback (most recent call last):
  File "stdin-29462993091ad78e6a5177ff794c993fe5d75f41", line 1, in <module>
    (parse-args [["-s" :type size]] ["-s" "800x600"])
  File "/Users/redraiment/Library/Python/3.7/lib/python/site-packages/hy/core/language.hy", line 404, in parse_args
    (eval `(.add-argument parser ~@arg)))
hy.errors.HyWrapperError: Don't know how to wrap <class 'function'>: <function size at 0x11094f0e0>
```

# Solution

After research, I found the root cause.

## Case 1: `:type size`

```hy
`(.add-argument parser ~@["-s" :type size])
```

The above code becomes `'(.add-argument parser "-s" :type <function size at 0x11094f0e0>)`, and `eval` couldn't works because `<function size at 0x11094f0e0>` is not function literal.

## Case 2: `:type 'size`

```hy
`(.add-argument parser ~@["-s" :type 'size])
```

The above code becomes `'(.add-argument parser "-s" :type size)`, and `eval` would raise `NameError: name 'size' is not defined` exception because `size` function not in context.

## Solution

My solution is call `add-argument` method direction with unpacking positional arguments and keywords arguments manually, rather than use `eval`.

```hy
(defn parse-args- [spec &optional args &kwargs parser-args]
  (import argparse)
  (setv parser (argparse.ArgumentParser #** parser-args))
  (for [arg spec]
    ;; (eval `(.add-argument parser ~@arg))
    (parser.add-argument
      ;; positional arguments
      #* (take-while (complement keyword?) arg)
      ;; keywords arguments
      #** (dfor [key value] (partition (drop-while (complement keyword?) arg) 2)
            [(name key) value])))
  (.parse-args parser args))
```

And it works well for me:

```hy
(parse-args- [["-s" :type size]] ["-s" "800x600"]) ;=> Namespace(s=[800, 600])
```

**Comment by Kodiologist** [comment]
But didn't you just close the pull request that would have made this change?

**Comment by redraiment** [comment]
> But didn't you just close the pull request that would have made this change?

The pull request was rejected automatically, so I close it.

**Comment by redraiment** [comment]
> But didn't you just close the pull request that would have made this change?

I forget to change the test case in last pull request, and I have submitted a new [one](https://github.com/hylang/hy/pull/1876) for instead.
