### ISSUE TITLE
How to write this chain-like assignments in hy?

### ISSUE THREAD

**Issue by shizhaojingszj** [hylang/hy#1877]
from https://python-docx.readthedocs.io/en/latest/

```py
p = document.add_paragraph('A plain paragraph having some ')
p.add_run('bold').bold = True
```

```hy
(setv p (document.add-paragraph "A plain paragraph having some "))
(setv tmp (p.add-run "bold") tmp.bold True)
```

Is there a better way to write the equivalent statements in hy?
E.g. not using tmp variable

**Comment by Kodiologist** [comment]
> Hy's issue list is for bugs, complaints, and feature requests.
