### ISSUE TITLE
loading quicklisp from hy

### ISSUE THREAD

**Issue by niitsuma** [hylang/hy#1878]
I made little compatibility layer between hy and common lisp.
Plz try

```shell
$ pip install hyclb
```
The following examle shows the usage

```hy
(import  [hyclb.cl4hy [*]])

(setv clisp (Clisp :quicklisp True))
(clisp.eval_qexpr  '(ql:quickload "alexandria"))
(clisp.eval_str  "(alexandria:destructuring-case '(:x 0 1 2)   ((:x x y z) (list x y z))  ((t &rest rest) :else))")
==> [0 1 2]
```

Other usages can be found in tests dir.
https://github.com/niitsuma/hycl/tree/master/tests

**Comment by Kodiologist** [comment]
Please stop posting non-issues to the issues list (#1867, #1872). This is your last warning.
