### ISSUE TITLE
`hy -c` doesn't clean up `sys.argv`

### ISSUE THREAD

**Issue by csabahenk** [hylang/hy#1894]
```
$ echo  '(import sys) (print sys.argv)' > args.hy
$ hy2py args.hy > args.py
```

In Python command line arguments are placed into `sys.argv` from index 1 (and index 0 is the name of the program).

```
$ python args.py a b c
['args.py', 'a', 'b', 'c']
```

Command line snippets adhere to above layout, with `-c` used as program name.

```
$ python -c "`cat args.py`" a b c
['-c', 'a', 'b', 'c']
```

Hy uses the same layout when a file is run.

```
$ hy args.hy a b c
['args.hy', 'a', 'b', 'c']
```

However, for a snippet it's something else.

```
$ hy -c "`cat args.hy`" a b c
['/home/csaba/.local/bin/hy', '-c', '(import sys) (print sys.argv)', 'a', 'b', 'c']
```
I need `(get sys.argv 3)` to access the first argument.

This is an unjustified departure from Python's ways and an unexpected inconsistency when switching between running program files and command line snippets.

For me personally, it partially beats the purpose of using Hy as a tool that bestows powers to run Python one-liners (I apologize if this purpose sounds lowly for a Lisp hacker).

```
$ hy --version
hy 0.18.0+18.gaa411bd
```

**Comment by Kodiologist** [comment]
This is a bug. It looks like we have no tests for `hy -c` with further arguments.

**Comment by Kodiologist** [comment]
I think making `-c` and `-m` interpret arguments as they ought to may require abandoning `argparse`. https://stackoverflow.com/questions/62364685

**Comment by refi64** [comment]
Randomly popping in: would it be possible to modify the argv array on -c to
add the -- and either continue or restart parsing from there or similar?

**Comment by Kodiologist** [comment]
I don't think `argparse` offers stream parsing. We would need to parse some options in order to figure out where to add the `--`, because `-c` might be the argument of another option, and by the time we've parsed the whole thing, it's too late.
