### ISSUE TITLE
GitHub Actions for stale issues/PRs and package deployment

### ISSUE THREAD

**Issue by brandonwillard** [hylang/hy#1900]
Should we try setting up GitHub Actions for PyPi deployment and automatically managing stale issues and PRs?

**Comment by Kodiologist** [comment]
PyPI deployment could be a small convenience. Closing old issues and PRs automatically, on the other hand, seems unwise.

**Comment by brandonwillard** [comment]
We could exclude issues marked as bugs, I believe.

**Comment by Kodiologist** [comment]
Automatic upload to PyPI is probably a little too dangerous, because you're not supposed to delete published packages or versions, so it would be bad to need to clean up after a mistake.

**Comment by allison-casey** [comment]
Having a dedicated `develop` branch and only auto upload on merge to `master` is a pretty standard CI/CD setup

**Comment by Kodiologist** [comment]
@brandonwillard I'm not sure it quite makes sense to reopen a two-year-old issue asking for old issues to be closed.

**Comment by brandonwillard** [comment]
> @brandonwillard I'm not sure it quite makes sense to reopen a two-year-old issue asking for old issues to be closed.

This issue isn't "asking for old issues to be closed"; it's asking if we want to set up some fairly standard project management automations.

**Comment by Kodiologist** [comment]
Isn't the fairly standard project management automation in question to close old issues?

**Comment by Kodiologist** [comment]
Like, I thought that by "managing stale issues and PRs", you meant closing them, but you tell me.
