### ISSUE TITLE
PyInstaller support

### ISSUE THREAD

**Issue by muqiuhan** [hylang/hy#1901]
Error Message : ModuleNotFoundError: No module named 'main
main is Hy source file, before importing Hy'

**Comment by Kodiologist** [comment]
PyInstaller is not supported (yet?).

**Comment by muqiuhan** [comment]
Hello, I've installed it, but the problem is still there. Perhaps Hylang does n'etre doesn't support PyInstaller.Thank you for your answer.
________________________________

**Comment by Kodiologist** [comment]
Yes, that's what I just said.

**Comment by muqiuhan** [comment]
I was doing C++ - work before, Hylang is not very familiar with, recently want to use Hylang call PyQt to write a Hylang integrated development environment, do not understand can not ask you?

X档案研究所[X-FI]发送

**Comment by muqiuhan** [comment]
I'm a c++ programmer, but I like Lisp. Because of my job, I can't use Lisp, but I still spend a lot of time learning Lisp. People around me don't think much of Hylang.
I believe Hylang will get better and better.

**Comment by muqiuhan** [comment]
Can I try to translate Hylang's document into Chinese and publish it?

X档案研究所[X-FI]发送

________________________________

**Comment by Kodiologist** [comment]
Sure, but it's a lot of work, and it may quickly go out of date unless you retranslate all the changes we make to the English version.

**Comment by muqiuhan** [comment]
There are a lot of Lisp enthusiasts around me, many of whom are Python programmers. Thank you very much for Hy's appearance.

X档案研究所[X-FI]发送

**Comment by jloow** [comment]
I'd just thought I'd add that there is way to make pyinstaller work with hy. I've detalied the steps [here](https://gist.github.com/jloow/0d255e8d691882b0763839e436b5d7ca). It's not the prettiest solution but it works for the simple cases I've tried.

**Comment by muqiuhan** [comment]
This is a feasible solution, thank you very much for your help

**Comment by allison-casey** [comment]
>  I've detalied the steps here.

This seems very useful, thank you jloow. I'll experiment with it some myself and make sure there's mention of it in the docs when I do the overhaul.

**Comment by muqiuhan** [comment]
Everything is getting better, thank you guys

**Comment by thinker5555** [comment]
> Happy to comment that hy works fine with Nuitka

@danieltanfh95 Is there anything special that needs to be done to build a hy script with Nuitka?
