### ISSUE TITLE
login shell

### ISSUE THREAD

**Issue by v217** [hylang/hy#1902]
Hi,
do you know if there exists something like
https://github.com/dundalek/closh
or
https://github.com/willghatch/racket-rash
for
hy?

Thanks!

**Comment by Kodiologist** [comment]
No, sorry, there isn't. I'm going to say that this too big for a feature request on this repository, but if you want to start on this, we'll make happy to make a repo for it under the hylang organization.

**Comment by v217** [comment]
I found an older project:
https://github.com/bollwyvl/hy_kernel
