### ISSUE TITLE
Use of ast.Name nodes for None/True/False crashes non-optimized CPython builds

### ISSUE THREAD

**Issue by mjwillson** [hylang/hy#1904]
CPython has an assertion prohibiting `"True"`/`"False"`/`"None"` ids for Name nodes. hy generates `ast.Name(id="None", ctx=ast.Load())` in a number of places, in particular when compiling things like `HySymbol("None")`. This can crash the interpreter when they're passed to `compile`:

> `assert.h assertion failed at third_party/python_runtime/v3_6/Python/compile.c:3022 in int compiler_nameop(struct compiler *, identifier, expr_context_ty): !_PyUnicode_EqualToASCIIString(name, "None") && !_PyUnicode_EqualToASCIIString(name, "True") && !_PyUnicode_EqualToASCIIString(name, "False")
> `

The assertion is skipped (seemingly without any adverse effects) when python is compiled with optimization flags, but it's not good to rely on this. I'm running under python 3.6.7 but the assertion still seems to be present in the latest python too.

For these special singleton constants, Hy should I think generate 
`ast.Constant(value=True)` from python 3.6 onwards, or `ast.NameConstant(value=True)` before that.

**Comment by Kodiologist** [comment]
Already done; see #1896. Remember to check that a bug exists in master before filing it.

**Comment by mjwillson** [comment]
Nice one! Sorry should have checked -- looks like this landed recently.
