### ISSUE TITLE
Some fault on accessing outter variable in function 

### ISSUE THREAD

**Issue by minghu6** [hylang/hy#1905]
How does the function access the outter variable ?
Exp:
```hy
    (defn f1 [] (print outter-var))
```

When you use `set-v` bind the outter-var in REPL or `defmain` scope, `(f1)` just woks:
    
    => (setv outter-var 1)
    => (f1)
    1

However, in other cases including use `let` macro and use `setv` in other function can't access the `outter-var`(restart REPL to test):

    => (defn f-f1 [] (setv outter-var 1) (f1))
    => (f-f1)
    Traceback (most recent call last):
    File "stdin-75998b1ba13bc19a8890c491ed82f3a9236d55e4", line 1, in <module>
    (f-f1)
    File "stdin-578b75482a8abe57e73d3229d925b3d5ef3e3d2d", line 1, in f_f1
    (defn f-f1 [] (setv outter-var 2) (f1))
    File "stdin-713e349ea27b070dcfe3c52983ad348ce2b50f88", line 1, in f1
    (defn f1 [] (print outter-var))
    NameError: name 'outter_var' is not defined

Same error for `let binding`:
    
    => (require [hy.contrib.walk [let]])
    True
    => (let [b 2] (f1)) 
    Traceback (most recent call last):
    File "stdin-edf744caf3147f9e1494390de67c66f06f15bdca", line 1, in <module>
    (let [b 2] (f1))
    File "stdin-713e349ea27b070dcfe3c52983ad348ce2b50f88", line 1, in f1
    (defn f1 [] (print outter-var))
    NameError: name 'outter_var' is not defined

**Comment by ynohtna** [comment]
Hy's scoping rules are the same as in Python, so you would need to declare outer-var as a global in f1 before it can be accessed within that function.

See: [https://docs.hylang.org/en/stable/language/api.html#global](https://docs.hylang.org/en/stable/language/api.html#global)

**Comment by minghu6** [comment]
@ynohtna maybe you don't read my issue carefully,
 I can ref `outter-var` which defined in REPL or `defmain` scope no need `global` declare.

And if the `defmain` scope variable are global variable?
(Is there a way to check a variable is global or not ?)

**Comment by Kodiologist** [comment]
@ynohtna is right. These semantics are the same as Python's.
