### ISSUE TITLE
adding a comma within a dict fails to compile

### ISSUE THREAD

**Issue by zcaudate** [hylang/hy#1908]
This expression fails when input into hy 0.18.0

```
(list (map (fn [e] {"name" (. e [0]), "fn" (callable (. e [1]))}) (.items __builtins__)))
```

But succeeds when the comma is removed

```
(list (map (fn [e] {"name" (. e [0]) "fn" (callable (. e [1]))}) (.items __builtins__)))
```

**Comment by brandonwillard** [comment]
A comma in that location is not part of the [Hy syntax](https://docs.hylang.org/en/stable/language/syntax.html).  The latter approach (i.e. without the comma) is the correct syntax.
