### ISSUE TITLE
having a comma in map passes compilation

### ISSUE THREAD

**Issue by zcaudate** [hylang/hy#1909]
Since I can't reopen [this issue](https://github.com/hylang/hy/issues/1908), I'll continue here

I think this is quite a deceptive error because commas are valid here:

```
{1 1, 2 2}
=> {1: 1, 2: 2}
```

This should be a really basic parser fix for the previous issue or to have a check to raise an error on commas.

It should be either one or the other.

**Comment by brandonwillard** [comment]
You should be able to comment in the closed issue if you have a follow-up question.

Also, this isn't a continuation of the question in #1908; it's essentially the reverse, but the answer is the same.  The Hy syntax allows [commas after numeric literals](https://docs.hylang.org/en/stable/language/syntax.html#numeric-literals), so your example is equivalent to `{1 1 2 2}`.

**Comment by zcaudate** [comment]
okay that makes sense now.

I'll need to start hacking on the clojure `pr-str` command
