### ISSUE TITLE
what happened to let?

### ISSUE THREAD

**Issue by zcaudate** [hylang/hy#1910]
I can't find it on `hy.contrib.walk` anymore.

**Comment by brandonwillard** [comment]
Can you provide an example of the exact issue?

For reference, here's a minimal example of how `let` is generally [`require`d](https://docs.hylang.org/en/stable/language/api.html#require):
```hy
=> (require [hy.contrib.walk [let]])
True
=> (let [a 1] a)
1
```

**Comment by zcaudate** [comment]
okay this is my fault. I was using an import statement:

```
(import [hy.contrib.walk [let]])
```

and when I looked through the walk namespace, it wasn't there.

<img width="195" alt="Screen Shot 2020-07-06 at 3 15 48 pm" src="https://user-images.githubusercontent.com/1455572/86566066-95115a80-bf9b-11ea-9098-4b513cb3214e.png">
