### ISSUE TITLE
Latest master E   NameError: name '__macros__' is not defined when running tests

### ISSUE THREAD

**Issue by xylix** [hylang/hy#1914]
On latest master (b9d3dd7e03fc21b133286ccf3b8343c78fd5a91f)

I get the following trying to run `make full` in my WSL2 ubuntu system.

Platform info: platform linux -- Python 3.8.2, pytest-6.0.1, py-1.9.0, pluggy-0.13.1

Are there some things I could try to debug this? Is this an issue with my setup I just can't detect?

```
_______________________________________________________________________________________________________________________________________ test_doc _______________________________________________________________________________________________________________________________________
capsys = <_pytest.capture.CaptureFixture object at 0x7f13771751c0>

>   ;; Copyright 2020 the authors.
E   NameError: name '__macros__' is not defined

tests/native_tests/core.hy:1: NameError
=============================================================================================================================== short test summary info ================================================================================================================================
FAILED tests/native_tests/core.hy::test_doc - NameError: name '__macros__' is not defined
============================================================================================================================ 1 failed, 606 passed in 11.08s ============================================================================================================================
make: *** [Makefile:43: test] Error 1
```

**Comment by Kodiologist** [comment]
Try `pip install .` instead. We haven't touched the Makefile in a long time.

**Comment by xylix** [comment]
Thanks for the fast answer, good to know that the makefile isn't really in use. `pip install .` worked.

After that however, just running raw `pytest` in the terminal gives me 2 test failures, see https://gist.github.com/xylix/3509ea0a4fd7d12ee6cf392f891dc1ad for details.

**Comment by Kodiologist** [comment]
The second failure is probably a duplicate of #1748. The first is new to me. Does it still happen if you do `git clean -dfx && pip install -e . && pytest`?

**Comment by xylix** [comment]
Runs succesfully after the cleanup. 

Would make sense that the other one was a duplicate of 1748.
