### ISSUE TITLE
Consider changing the Hy model objects' design

### ISSUE THREAD

**Issue by brandonwillard** [hylang/hy#1928]
Since `HyKeyword` is inheriting from a non-`__slots__` object, I believe it will have a `__dict__` attribute anyway, in which case we would be missing out on some of the space-saving advantages of using `__slots__`.  To fix that 
 we can make `HyObject` use `__slots__`; however, this will clash with all the `HyObject` + primitive subclasses.  

If the Hy model objects held references to the actual primitives, instead of actually _being_ those primitives, this problem would be easily solved.

Otherwise, we can probably just use the `abc` and/or `collections.abc` interfaces.

_Originally posted by @brandonwillard in https://github.com/hylang/hy/issues/1924#issuecomment-731694498_

**Comment by Kodiologist** [comment]
Better to just remove the `__slots__` entirely.

> If the Hy model objects held references to the actual primitives, instead of actually *being* those primitives

This strategy has some appeal. The annoying thing is that we'd need to add a lot of boilerplate methods to allow you to add a `HyInteger` to an `int`, to call `upper` on a `HyString`, etc. Maybe this could be worked around with `__getattr__`. I'm not clear in which cases `__getattr__` can substitute for a magic method.

**Comment by gwerbin** [comment]
@Kodiologist Even if `__getattr__` works in all cases like that, it could result in significantly slower (C)Python code, because CPython takes lots of special fast paths on basic types like numbers. There's some good discussion of this in https://www.youtube.com/watch?v=qCGofLIzX6g
