### ISSUE TITLE
No built-in method to create `__all__` using unmangled hy names

### ISSUE THREAD

**Issue by allison-casey** [hylang/hy#1934]
as far as i can tell, Hy doesn't have a way to define a module's `__all__` attribute using unmangled names. As in a method defined as `hello?` has to manually be set as
`(setv --all-- ["is_hello"])`
Which is very unintuitive, especially for the more complicated mangled names.
This is fixed pretty easily with a macro such as 
```
(defmacro defall [&rest symbols]
  `(setv __all__ ~(lfor sym symbols (mangle (name sym)))))
```
So the same `--all--` can be defined as
`(defall hello?)`
This seems like something Hy should be able to do by default as part of the core library.

**Comment by Kodiologist** [comment]
In my opinion, that doesn't add a lot over writing `(setv __all__ (list (map mangle […])))` every time (blame Python 3 for requiring the `list` call), since it's a construct used at most once per module. Having such a macro or function doesn't protect the programmer against needing to know about mangling, because they need to know about mangling in order to not just write `(setv __all__ […])` as a Python programmer would.

**Comment by allison-casey** [comment]
It's a behaviour that makes sense to us, but to someone new to hy this can be a very confusing issue for something they might expect to "just work". At the very least I think this is something that needs to be documented. A builtin macro would satisfy that, but so would some regular documentation.

**Comment by Kodiologist** [comment]
Sure, pointing it out as a potential newbie trap in the documentation makes sense.

**Comment by scauligi** [comment]
Alternatively, we could have the Hy compiler watch for top-level `setv`s to `__all__` and silently insert `(list (mangle [...]))`. Dunno if that's too much magic though.

**Comment by allison-casey** [comment]
I would say a macro like this belongs more in  whatever stdlib comes out of #1992 where the contribution guidlines are less strict. A lot of the refactor work going in to 1.0 involves removing layers of compiler magic that has built up over the years so adding a `__all__` magic seems less than ideal. When i rewrite the docs we can crosslink to the stdlib docs for `defall` or whatever macro ends up in that library anyways.
