### ISSUE TITLE
Document repl builtins *e, *i

### ISSUE THREAD

**Issue by jams2** [hylang/hy#1943]
The repl commands `*e, *1, *2 ...` don't seem to be documented. This became an issue when attempting to get [ob-hy](https://github.com/brantou/ob-hy) to behave (it was relying on `_` to return the result of last evaluation to emacs). It looks like this was changed in #1341. I'd like to submit a pull request for this, but would appreciate suggestions on where it should go :).

**Comment by Kodiologist** [comment]
As you may have noticed, the organization of the documentation is a bit of a mess. Without bigger changes, I'd suggest adding a section called "The Hy REPL" after "Command Line Interface".
