### ISSUE TITLE
``doc`` doesn't work with names that require mangling

### ISSUE THREAD

**Issue by peaceamongworlds** [hylang/hy#1946]
The current implementation of ``doc`` doesn't work with macro names that require mangling, like ``->``.

It seems that this would be easy to change by just adding a call to ``mangle`` in the definition of ``doc``:
```hy
(defmacro doc [symbol]
  `(help (.get __macros__ (mangle '~symbol) None)))
```
However, would it not make sense to combine ``help``, ``doc``, and ``#doc`` and have a single macro for looking up documentation? Especially as by default python's ``help`` isn't that helpful, showing the mangled names and opening up in a pager.

**Comment by Kodiologist** [comment]
It would make sense, yes. See the discussion in #1415.
