### ISSUE TITLE
Add Allie Jo Casey to core

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1949]
@allison-casey's PRs so far: #1922, #1930. I want her on our side. Any objections, @hylang/core?

**Comment by Kodiologist** [comment]
@refi64?

**Comment by paultag** [comment]
Strong plus one from me. I've been lurking and their work is great.

**Comment by Kodiologist** [comment]
Okay, let's do it. Welcome to the cabal, Allie!
