### ISSUE TITLE
Remove Botsbuildbots contrib module

### ISSUE THREAD

**Issue by allison-casey** [hylang/hy#1961]
`Bobsbuildbots` currently isn't tested or documented in the docs and I'm not sure what it even does. As of right now it doesn't actually work because it uses the old bracketed `import` syntax:
`(import [requests])`
It also doesn't really align with what the contrib module has become of late, namely a testing ground for language features and functionality. Maybe I'm just not understanding what the point of it is, but I'd vote to remove it barring some more persuasive explanation for why we should keep it.

**Comment by Kodiologist** [comment]
[I've wanted to do](https://github.com/hylang/hy/pull/1189) this [forever](https://github.com/hylang/hy/pull/1604#pullrequestreview-117866648).

@refi64 This is now officially a meme.

**Comment by allison-casey** [comment]
I would also accept moving the module to a new `hy.memes` module if so desired

**Comment by refi64** [comment]
> This is now officially a meme.

I mean, there are certainly worse things that could have ascended...

**Comment by paultag** [comment]
[shameless plug from the cobwebs in the corner](https://livefromthehyve.tumblr.com/)

**Comment by Kodiologist** [comment]
Someday I hope that Hy will have its own "Hy Memes for Homoiconic Teens" meme page on Facebook.

**Comment by allison-casey** [comment]
The true measure of a language's success
