### ISSUE TITLE
tox config doesn't match CI

### ISSUE THREAD

**Issue by jams2** [hylang/hy#1962]
It would be good to have a local testing config that matches what's happening with TravisCI. Results from running on the master branch on my machine currently are:

```
ERROR:   py27: commands failed
ERROR:   pypy: could not install deps [-rrequirements-dev.txt]; v = InvocationError('/home/joshua/build/hy-dev/.tox/pypy/bin/python -m pip install -rrequirements-dev.txt', 1)
ERROR:   py34: could not install deps [-rrequirements-dev.txt]; v = InvocationError('/home/joshua/build/hy-dev/.tox/py34/bin/python -m pip install -rrequirements-dev.txt', 1)
ERROR:   py35: commands failed
  py36: commands succeeded
ERROR:   pypy3: commands failed
ERROR:   flake8: commands failed
```

A few suggestions:
- I could start with dropping unsupported Python versions - judging from Travis this is anything < 3.6?
- Travis is running pypy3 with Python 3.6, this could potentially be updated to 3.7.
- The list of violations from flake8 is pretty long. Have you considered using an auto formatter, like black?

Another possibility to investigate would be using Docker for building testing environments, which would save on having to have each of the interpreter versions installed locally.

**Comment by allison-casey** [comment]
> I could start with dropping unsupported Python versions - judging from Travis this is anything < 3.6?

This is correct. 3.5 support was dropped in #1931. I'll open a PR tomorrow to fix that. 

> Travis is running pypy3 with Python 3.6, this could potentially be updated to 3.7.

As of right now in PyPy 7.3.3 python3.7 is still considered beta and doesn't pass all the 3.7 tests. So we could update, but I think it could lead to some unforseen consequences until it gets out of beta.

> The list of violations from flake8 is pretty long. Have you considered using an auto formatter, like black?

This has been brought up before in #1704 and something I wholly support. I was actually going to bring the issue up again and see if sentiments had changed at all so you could go voice your support over there as well.

> Another possibility to investigate would be using Docker for building testing environments, which would save on having to have each of the interpreter versions installed locally.

I like this idea and it looks like there's precedent for it https://registry.hub.docker.com/r/kiwicom/tox (this doesn't have PyPy installed :disappointed: ) I'll play around with it, thanks!
