### ISSUE TITLE
Require fails to load tags with same name as macro in same module

### ISSUE THREAD

**Issue by allison-casey** [hylang/hy#1967]
```hy
;; foo.hy
(deftag amacro [-name] `(print f"Hello {~-name}"))
(defmacro amacro [-name] `(print f"Hello {~-name}"))
```

```hy
;; bar.hy
(require [foo [amacro]])
;; (require [foo [*]]) ; This doesn't work either

(amacro "Allie") ; => (print "Hello Allie")
#amacro "Allie" ;  'amacro' is not a defined tag amcro
```

This seems unexpected since we have `#doc` and `(doc ...)` macros that work just fine. 
This seems like a pretty easy fix, changing `require` to import both just requires changing it to:
```python
if _name not in source_module.__macros__ and _name not in source_module.__tags__:
    raise HyRequireError('Could not require name {} from {}'.format(
        _name, source_module))

if _name in source_module.__macros__:
    target_macros[alias] = source_macros[_name]
if _name in source_module.__tags__:
    target_tags[alias] = source_tags[_name]
```
But is this expected behavior? It's not documented as such as far as I can tell.

**Comment by Kodiologist** [comment]
I'm inclined to think that tag macros and ordinary macros should use the same namespace. Otherwise, we'd need new `require` syntax for the user to specify which they meant in case of an overlap.

**Comment by allison-casey** [comment]
Is there an issue with importing both if there's overlap? A tag macro can't be called as a regular macro anyways. I've tried it with importing both and none of the existing tests fail :woman_shrugging:

**Comment by Kodiologist** [comment]
It's imprecise, is all. Usually each name explicitly listed in a `require` or `import` list causes an import of exactly one object. It's also confusing to have a tag macro and regular macro of the same name in the same scope, and I can't think of a case where you'd want this.

**Comment by allison-casey** [comment]
That's makes sense. Was something I ran into messing around that seemed weird to fail silently. I'll open a PR to add a note to the docs that mentions the limitation

**Comment by Kodiologist** [comment]
You don't think we should change Hy so that tag macros and ordinary macros really do use the same namespaces?

**Comment by allison-casey** [comment]
I think it would be more trouble than it's worth honestly. Maybe as a refactor down the road, but there's so much intertwined with `__macros__` & `__tags__` to change it just overlapping like this. if #1970 ends up being a huge undertaking, maybe we can do it then, but for now i'll settle for a note in the docs

**Comment by scauligi** [comment]
Would it be too much of a breaking change if we changed the syntax such that tag macros are specified by the `#` sigil in the `require`?
E.g. `(require [module [amacro #atagmacro]])`

**Comment by allison-casey** [comment]
i like that, and I don't think it would be be too difficult to implement either

**Comment by Kodiologist** [comment]
That sounds halfway reasonable. I can't help but think, though, it would be rather a simplification if tag macros and regular macros actually were the same thing, and a tag macro was just syntactic sugar for calling a macro with one argument. We wouldn't even need `deftag`. Yeah, it could be a lot of diff lines, but the result would probably be nicer and simpler than what we have.

**Comment by Kodiologist** [comment]
Maybe I'll give it a shot over the long weekend.

**Comment by allison-casey** [comment]
it would certainly be nice to simplify the monkeypatching we do to modules for sure. I just worry we lose some (maybe needed) explicitness as to which macros do what. I'd have to see how it works in practice before I come down on either side. What immedietly comes to mind is:
```hy
#-> (a b c) ;; what does something like this mean? 
```
again this might iron itself out in an actual implementation, but something to keep in mind

**Comment by Kodiologist** [comment]
I've been working on something this morning and I think it will be ready soon.
