### ISSUE TITLE
Add Sunjay Cauligi and Peter Andreev to core

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1972]
Merged PRs so far:

- @scauligi: #1950, #1951, #1957, #1969
- @peaceamongworlds: #1940, #1945, #1953

@hylang/core Any objections?

**Comment by allison-casey** [comment]
None from me! Would love to have them both on board

**Comment by asemic-horizon** [comment]
This looks like as good a space as any to praise the Hy team for maintaining this great tool. Issue boards are (necessarily) overwhelmingly negative, and they should on occasion receive feedback that their work is both impressive and very useful. I've never had a coding experience that was this close to "dump code from brain -> run correctly on the first try".

I, for one, welcome our new overlords.

**Comment by Kodiologist** [comment]
Aww, thanks, dude!

**Comment by paultag** [comment]
Plus one here. Thank you all for your work! ❤️

**Comment by Kodiologist** [comment]
Okay, let's make this happen.
