### ISSUE TITLE
`(name :under_scored)` returns `"under-scored"`... Why?

### ISSUE THREAD

**Issue by jedi2light** [hylang/hy#1974]
I have the next code:

```
(setv sample :under_scored)
(name sample)
```

Expected:
```
"under_scored"
```

Actually:
```
"under-scored"
```

At the same time, Clojure's name` returns `"under_scored"`. Please, fix it.

**Comment by Kodiologist** [comment]
`name` calls `unmangle` internally. `name` itself is of dubious value, though; we should probably just trash it.

**Comment by allison-casey** [comment]
Could we just make an exception for keywords since they should probably stay as close to their string representation as possible anyways?

**Comment by Kodiologist** [comment]
It would be better for the user to use whatever combination of `str`, `mangle`, `unmangle`, and `(. … __name__)` that they want. Again, I don't see what the value of `name` is to begin with.

**Comment by allison-casey** [comment]
because as far as i can tell none of those get you the underlying name of the keyword. 
```hy
(str :hello_world) ; =>  :hello_world
(repr :hello_world) ; =>  HyKeyword('hello_world')
(mangle :hello_world) ; =>  hyx_XcolonXhello_world
(unmangle :hello_world) ; =>  :hello-world
(name :hello_world) ; =>  hello-world
```
The closest is `str` but that doesn't remove the `:` and it's such a common operation that it doesn't seem right to make users do `(.replace (str ':hello_world) ":" "" 1)` every time or make their own function.

**Comment by Kodiologist** [comment]
You can use `sym.name` or `(cut sym 1)`.

**Comment by allison-casey** [comment]
lol didn't know that `sym.name` existed that changes things. 
@jedi2light you should probably use `(. :hello_!->world name) ; => "hello_!->world"`
instead. since hy doesn't have namespaces like clojure i think i agree with kodi now. There doesn't seem much use for `name` besides providing an alias for `(. key name)`

**Comment by allison-casey** [comment]
There is one use case I'm starting to think of and that's the ability to normalize dict keys to strings easily. 

```hy
(setv x {"a" 1  :b 2})

(dfor [k v] (x.items) [(name k) v]) ; => {"a" 1 "b" 2}
;; you could write that as
(dfor [k v] (x.items) [(if (keyword? k) k.name k) v]) ; => {"a" 1  "b" 2}
```

Don't know how valid of use case this is to keep `name` around, but something to think about

**Comment by Kodiologist** [comment]
Generally, it's a mistake to use a HyKeyword instead of a string as a dictionary key. It's too easy to confuse yourself, especially when you're looking at forms like `(dict :foo 1)`.

**Comment by allison-casey** [comment]
yeah, that's why i don't use them myself, but i'm trying to think of reasons to keep `name` around since hy doesn't have clojure style namespaces which clojure's `name` handles specially. So far i'm not comming up with much :woman_shrugging:

**Comment by scauligi** [comment]
> it's a mistake to use a HyKeyword instead of a string as a dictionary key

That seems to go against the intention of the `HyKeyword.__call__` implementation, but I agree that keywords-as-keys gets confusing with keywords-as-arguments. Should we consider removing the `(:foo mapping)` feature? Or instead, we could change it to do a string lookup instead of a HyKeyword lookup (e.g. `(:foo (dict :foo 1))` would produce `1`).

**Comment by Kodiologist** [comment]
Probably the latter.

**Comment by peaceamongworlds** [comment]
> Or instead, we could change it to do a string lookup instead of a HyKeyword lookup (e.g. `(:foo (dict :foo 1))` would produce `1`).

I think that string lookup would be the most convenient. It would actually allow for it to be used with other python objects like pandas dataframes etc. Using keywords outside of function arguments doesn't seem to mix well with the python ecosystem.

**Comment by allison-casey** [comment]
I like the string lookup idea. I pretty much never use the `(:akey adict)` type expression anyway.

so would `(:hello {:hello 1})` be a `KeyError` then?

**Comment by peaceamongworlds** [comment]
> so would `(:hello {:hello 1})` be a `KeyError` then?

I guess it would just be equal to `(get {:hello 1} (. :hello name))`, which throws a `KeyError`.

**Comment by jedi2light** [comment]
Remove `(:some col)`? Ok, will switch to another language then :/

**Comment by allison-casey** [comment]
The current proposals would still work though? it would just be a lookup for a string key.
`(:hello {"hello": 1}) ; => 1` So i'm confused?

**Comment by scauligi** [comment]
And in particular, `(:hello (dict :hello 1)) ; => 1` with the new proposal, which seems like a plus.

**Comment by scauligi** [comment]
Awesome, looks like there's enough buy-in so I'll start up a PR for this.
