### ISSUE TITLE
Bring commas back!

### ISSUE THREAD

**Issue by joehakimrahme** [hylang/hy#198]
As much as I like the idea of leaving commas out of literal constructors of lists and dictionaries, it makes it impossible to have the same for the other familiar and loved Python literals.

Sets literals are cool and useful enough to be considered. Tuples could be added in the mix too, since commas would remove any possible confusion.

The project is young enough to be break existing code. I guess what I'd like to say is that I would rather have this discussion now while we still can. What do you guys think?

**Comment by algernon** [comment]
I stand by my opinion of a year ago, and seeing that this didn't get much traffic since, I'm leaning towards closing this without changing Hy.

Added to the Grand Language Cleanup milestone nevertheless, because this'd be a breaking change.

**Comment by gilch** [comment]
>it makes it impossible to have the same for the other familiar and loved Python literals.

Python's `repr`s in general are never going to work in Hy. Adding commas to enable a few exceptions to this doesn't seem worth it.

> Sets literals are cool and useful enough to be considered. Tuples could be added in the mix too, since commas would remove any possible confusion.

We didn't before, but we have set literals now--`#{}`. We also a pretty good tuple form using `,` as the symbol.

I'm in favor of closing this issue. The original arguments don't seem to apply.

**Comment by farhaven** [comment]
Since the majority is in favor of keeping the current state of affairs and, as @algernon said there hasn't been much traffic here, I'm closing this one. If the interest comes back, we can always re-open and restart the discussion.
