### ISSUE TITLE
`eval-and-compile` is no longer documented

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1984]
This section https://docs.hylang.org/en/stable/language/api.html#eval-and-compile , and possibly also others, seems to have gotten lost in the docs overhaul. @allison-casey Do you want to check for anything else that was lost?

**Comment by allison-casey** [comment]
Likely special forms that can't be autodoc'd that I missed. I'll tae a look. let me know here, if you notice any others

**Comment by Kodiologist** [comment]
You could use regexes to collect the names in `@special` decorators in `compiler.hy` and then check that the only ones not listed in the documentation are the ones we really intend not to document, like `if*`.
