### ISSUE TITLE
eval of "(import python_module)" cannot function well inside a method

### ISSUE THREAD

**Issue by AlucardNosferatu** [hylang/hy#1990]
This is my python_module: `FUNC_STORAGE.py`:
```
def add1(a, b):
    return a + b

```
This is a python code that call hy to eval hy scripts:
```
    exp_str = '(import FUNC_STORAGE)'
    expr0 = hy.read_str(exp_str)
    hy.eval(expr0)

    exp_str = "(defn add1 [a b] (.add1 FUNC_STORAGE a b))"
    expr1 = hy.read_str(exp_str)
    hy.eval(expr1)

    exp_str = "(add1 2029 1224)"
    expr2 = hy.read_str(exp_str)
    res = hy.eval(expr2)
```
the code above only works outside any methods, when they are written in methods, the eval of `res = hy.eval(expr2)` will report a `NameError` : `name 'FUNC_STORAGE' is not defined`

How can I do `defn `and `import`(hy<-py) in different py-methods? Thanks!

**Comment by Kodiologist** [comment]
Can you simplify the example to the bare minimum necessary to reproduce your problem? You might solve it along the way.

**Comment by AlucardNosferatu** [comment]
> Can you simplify the example to the bare minimum necessary to reproduce your problem? You might solve it along the way.

Ok, I've revised it, thanks for your advice!

those code are identical inside and outside methods, but only works globally...?

**Comment by scauligi** [comment]
Eval'ing hy code will execute the equivalent python bytecode in the same environment as the calling code, not in some global context.

So your code is the equivalent of the following:

```python
```

**Comment by AlucardNosferatu** [comment]
> Eval'ing hy code will execute the equivalent python bytecode in the same environment as the calling code, not in some global context.
> 
> So your code is the equivalent of the following:
> 
> ```python
>     import FUNC_STORAGE
> 
>     def add1(a, b):
>         return FUNC_STORAGE.add1(a, b)
> 
>     add1(2029, 1224)
> ```
> 
> if you move those into their own functions, then the `import` only imports `FUNC_STORAGE` into the namespace of that function; python's import doesn't import into the global namespace when run inside of a function.

Thanks, this helped, and I am using a file-based reload mechanism to call those hy functions.
