### ISSUE TITLE
(defn test [[arg1 1] [arg2 2]] ()): Defining argument default is not working

### ISSUE THREAD

**Issue by TheCatster** [hylang/hy#2012]
Unless what I've read on the docs and what I wrote in the title is wrong, argument default (I'm not sure of the correct name in Hy) are causing errors in my projects. I just started a few days ago, and was quite ecstatic at a usable Lisp in Python, but am now quite confused.

For example, the tutorial provided this basic function:
```hy
(defn test [a b [c None] [d "x"] #* e]
  [a b c d e])
(print (test 1 2))            ; => [1, 2, None, 'x', ()]
(print (test 1 2 3 4 5 6 7))  ; => [1, 2, 3, 4, (5, 6, 7)]
```
This is simple to understand, and made perfect sense to me in comparison to the Python version. I go to run it (using Hy version 0.20.0) and get this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 267, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "/home/danya/Projects/Programming/Python/Hy/hy-playground/main.hy", line 83
    [a b c d e])
    ^
hy.errors.HySyntaxError: parse error for special form 'fn*': should have reached end of form: HyList([
  HySymbol('c'),
  HySymbol('None')]): end of form
```

This seems to be related to that default setting, `c` being `None`, but I'm not sure what I'm doing wrong. I've replicated this same exact scenario on another laptop also running Hy version 0.20.0.

I tried this with another function in the docs:
```hy
(defn format-pair [left-val [right-val None] [open-text "("] [close-text ")"]]
    (+ open-text (str left-val) ", " (str right-val) close-text))
```
which results in the error message:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 267, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "/home/danya/Projects/Programming/Python/Hy/hy-playground/main.hy", line 83
    (+ open-text (str left-val) ", " (str right-val) close-text))
    ^
hy.errors.HySyntaxError: parse error for special form 'fn*': should have reached end of form: HyList([
  HySymbol('right-val'),
  HySymbol('None')]): HyExpression([
  HySymbol('+'),
  HySymbol('open-text'),
  HyExpression([
    HySymbol('str'),
    HySymbol('left-val')]),
  HyString(', '),
  HyExpression([
    HySymbol('str'),
    HySymbol('right-val')]),
  HySymbol('close-text')])
```
Which leads me to believing my suspicions are correct. Is anyone else experiencing this? Was there a change in the API that hasn't been documented, or I simply overlooked? I saw for sure that parentheses are no longer used in a previous issue here, unless that changed.

Thank you!

**Comment by Kodiologist** [comment]
This syntax changed in #1975. Always be sure that the version of the documentation you're looking at matches the version of Hy you're running.

**Comment by TheCatster** [comment]
I'm on the docs for version 0.20.0, please take a look at them. I had no idea about this change, my apologies.

**Comment by allison-casey** [comment]
docs wise `0.20` is considered stable and the appropriate docs link is https://docs.hylang.org/en/stable/tutorial.html. What's on master contains many changes that aren't backwards compatible as we try and get to `1.0`

**Comment by Kodiologist** [comment]
> I'm on the docs for version 0.20.0

No, you're not. Look at Allison's link above.

**Comment by TheCatster** [comment]
No no, I understand now, sorry. That was just very confusing, I had the Built-Ins page open on stable, the tutorial and API open on master.

**Comment by Kodiologist** [comment]
Ah, that'll get ya. The README links to the master branch for the tutorial as a holdover from when the new tutorial hadn't made it into a release yet. That may've caught you. I'll update that.

**Comment by TheCatster** [comment]
Thank you both!
