### ISSUE TITLE
Lexing bug

### ISSUE THREAD

**Issue by jeongsoolee09** [hylang/hy#2014]
I have a function here:

```clojure
(defn repl []
  (import hw2)
  (import [importlib [reload]])
  (reload hw2)
  (import [hw2 [*]]))
```

Evaluating above in the REPL emits a `hy.lex.exceptions.PrematureEndOfInput: Premature end of input`.

**Comment by jeongsoolee09** [comment]
Oops, `(import [package [*]])` is only allowed at toplevel. My bad.

**Comment by Kodiologist** [comment]
I'm guessing this is another manifestation of #2004.
