### ISSUE TITLE
Cannot `require` module from a package

### ISSUE THREAD

**Issue by peaceamongworlds** [hylang/hy#2016]
The following are all valid:
```hy
$ > hy --spy --repl-output-fn=hy.contrib.pprint.pformat
import hy
hy 0.20.0+132.g2a6b79f1 using CPython(heads/makepkg-dirty:ba251c2ae66) 3.10.0a6+ on Linux
=> (require hy.contrib.walk)
hy.macros.require('hy.contrib.walk', None, assignments='ALL', prefix='hy.contrib.walk')
None
=> (import hy.contrib.walk)
import hy.contrib.walk
None
=> (require [hy.contrib.walk :as w])
hy.macros.require('hy.contrib.walk', None, assignments='ALL', prefix='w')
None
=> (import [hy.contrib.walk :as w])
import hy.contrib.walk as w
None
=> (import [hy.contrib [walk]])
from hy.contrib import walk
None
```
However, the following fails:
```hy
=> (require [hy.contrib [walk]])
Traceback (most recent call last):
  File "stdin-fc566da3a366533698786e10deb0bc456fb8d19e", line 1, in <module>
    (require [hy.contrib [walk]])
hy.errors.HyRequireError: The module <module 'hy.contrib' from '/home/peter/Programming/hy/hy-source/hy/hy/contrib/__init__.py'> has no macros
```
As I understand, `import` and `require` should allow for the same syntax, and given that the previous `require` forms work as expected, I think that the last one should as well.

Just to clarify, I think that `(require [hy.contrib [walk]])` should have the same effect as `(require [hy.contrib.walk :as walk])`.

**Comment by Kodiologist** [comment]
You know, I don't think I knew that `from a.b import c` is legal Python even when `a.b.c` is a module instead of an object that exists in the `a.b` module.

**Comment by allison-casey** [comment]
what should the behavior be if `hy.contrib` has a macro also named `walk`? I think python checks the module for variables first then goes to sub modules, but i'd need to double check that.

**Comment by peaceamongworlds** [comment]
Assuming that you have the following scenario:
```
foo
foo/__init__.py
foo/bar.py
```
Then `from foo import bar` will first check for any object `bar` in `foo/__init__.py` and if that fails then look `foo/bar.py`.
