### ISSUE TITLE
HyCompileError: Internal Compiler Bug 😱

### ISSUE THREAD

**Issue by TheCatster** [hylang/hy#2034]
I've been working on a rewrite of a Discord bot into Hy (it was just one of the first projects to come to mind for practice.) Everything was going great until I started working on the last cog. I am not sure how much more I can explain the issue, as this error came along (with a not very helpful stack trace):
```
HyCompileError: Internal Compiler Bug 😱
⤷ Traceback (most recent call last):
  File "/home/danya/.local/share/virtualenvs/HyDitto_-ormxuTWt/lib/python3.9/site-packages/hy/compiler.py", line 435, in compile
    ret = self.compile_atom(tree)
  File "/home/danya/.local/share/virtualenvs/HyDitto_-ormxuTWt/lib/python3.9/site-packages/hy/compiler.py", line 429, in compile_atom
    return Result() + _model_compilers[type(atom)](self, atom)
  File "/home/danya/.local/share/virtualenvs/HyDitto_-ormxuTWt/lib/python3.9/site-packages/hy/compiler.py", line 1881, in compile_string
    return self._format_string(string, str(string))
  File "/home/danya/.local/share/virtualenvs/HyDitto_-ormxuTWt/lib/python3.9/site-packages/hy/compiler.py", line 1928, in _format_string
    model, item = parse_one_thing(item)
  File "/home/danya/.local/share/virtualenvs/HyDitto_-ormxuTWt/lib/python3.9/site-packages/hy/lex/__init__.py", line 86, in parse_one_thing
    for token in lexer.lex(src_string):
  File "/home/danya/.local/share/virtualenvs/HyDitto_-ormxuTWt/lib/python3.9/site-packages/rply/lexer.py", line 62, in __next__
    return self.next()
  File "/home/danya/.local/share/virtualenvs/HyDitto_-ormxuTWt/lib/python3.9/site-packages/rply/lexer.py", line 58, in next
    raise LexingError(None, SourcePosition(
rply.errors.LexingError: (None, SourcePosition(idx=20, lineno=1, colno=17))
```
I know I'm not giving a lot to work off of, but I'm on Hy version 0.20.0, stable. Whatever more I can do to explain this, I gladly will.

My thoughts were that I messed up the syntax somehow, and ended up breaking the compiler, but I'm not sure where to start hunting.

Thank you for your time!

**Comment by allison-casey** [comment]
Hi! I haven't seen this one before. There's not much to go off of without source code however. Is there a reproducible example you could post or a gist of the file that's erroring out?

**Comment by Kodiologist** [comment]
Yeah, we need you to get a minimal example first before we can debug this.

**Comment by TheCatster** [comment]
I'm honestly not sure if I can make a minimal copy, but I do have the project on GitHub, if I'm allowed to share the link.

**Comment by Kodiologist** [comment]
Okay, I'll close this issue. If you can reproduce it with Hy master, I'll reopen it.

**Comment by TheCatster** [comment]
Alright, here is a simple way to reproduce it. Turns out, this is no bug, but rather a lack of an error for this situation. When using single quotes in Hy when you meant to use double quotes, it returns a LexException. The same does not occur in f-strings, however.

```
(setv number-list (range 10))

;; Testing single quotes instead of double in print (this should throw an error.)

;; (print 'Hello, world!')

;; Which of course, it does. The particular error is
;; hy.lex.exceptions.LexException: Could not identify the next token. This is good!

;; "Testing single quotes in a normal if statement (this should throw an error.)"

;; (if (> number 2)
;;     'Greater than two'
;;     '')

;; Which of course, it does. The particular error is
;; hy.lex.exceptions.LexException: Could not identify the next token. This is good!

;; "Testing the \"crashing\" lfor."

(print (lfor number number-list f"{(if (> number 2) 'Greater than two' '')}"))

;; This statement should also throw a LexException, but instead it has an internal compiler error!
;; Why does it not handle the error the same when in an f-string?
```
How are f-strings parsed? I wanted to attempt a PR myself, but couldn't quite understand why they are interpreted differently.

**Comment by allison-casey** [comment]
Oh! Hy has no such thing as single quote string literals. you either have to escape the double quotes inside like his
```clojure
(print (lfor number number-list f"{(if (> number 2) \"Greater than two\" \"\")}"))
```

or use bracket strings like this
```clojure
(print (lfor number number-list #[f[{(if (> number 2) "Greater than two" "")}]f]))
```

but really this should be written without the f-string like this
```clojure
(print (lfor number number-list (if (> number 2) "Greater than two" "")))
```

**Comment by TheCatster** [comment]
No no, I completely understand, since all other Lisps I've worked with use single quotes for delayed interpretation. I was just a bit surprised that a the same error wasn't thrown! Thank you for the explanation without the f-strings though, I guess I was overthinking it.

**Comment by allison-casey** [comment]
Ahhh yeah i realized what you were saying just too late. My bad, but that error was fixed on master. 1.0a1 will be released today/tomorrow if you want to try migrating to that

**Comment by TheCatster** [comment]
Will do! Thank you!
