### ISSUE TITLE
HYSTARTUP creates `__pycache__` in directory of startup file

### ISSUE THREAD

**Issue by scauligi** [hylang/hy#2043]
I noticed a `__pycache__` directory that kept appearing in my home directory &mdash; the only contents are `hystartup.cpython-39.pyc`. Incidentally, my home directory is also where my Hy startup file is.

I think we should special-case the startup execution from creating pycache artifacts, if that's possible to do &mdash; recompiling the startup file every time shouldn't be a problem.

**Comment by Kodiologist** [comment]
> recompiling the startup file every time shouldn't be a problem

I think it will create a noticeable slowdown when starting the REPL, although that depends on the size and complexity of your startup file, of course. I'd recommend just putting your startup file in a different directory.

**Comment by allison-casey** [comment]
My recommendation is `$HOME/.config/hy/hyrc.hy`
