### ISSUE TITLE
behaviour consistence between `first` and `last`?

### ISSUE THREAD

**Issue by minghu6** [hylang/hy#2045]
Env: hy 1.0a1+17.g69a23261

I found:
 `(first []) ` returns `None`,
 but `(last [])` just raise `IndexError`

**Comment by allison-casey** [comment]
Hy will be removing builtin methods that are duplicates of methods in more dedicated libraries like `Toolz` or `Funcy` for just this reason. If you're looking for implementations of common methods like this with more consistent syntax and performance profiles it's recommended to migrate your code to import from those libraries instead. Part of this migration was already done in #2042 (which removed `first` and `last` among others) which will be available in `hy 1.0a2`.
