### ISSUE TITLE
Allow macros to return `Result` objects

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2046]
I haven't thought this through, but it's probably worth mentioning. Suppose macros were allowed to return Python `ast` objects instead of Hy models (or objects to be promoted to Hy models). This would be a rarely used feature, since it would be clumsier than using models and it would require the programmer to manage `lineno` and `col_offset`. The advantage is that a lot of operators that are currently special could be implemented as macros instead of cluttering up `compiler.py`. And, users could add or alter support for Python features without having to monkey-patch the compiler.

**Comment by scauligi** [comment]
I'm in favor of this. Would it be possible to implement both types of macros under `defmacro` and handle the result in the compiler? or would we need to call it something else like `defpymacro`?
I would prefer the former but open to either.

**Comment by Kodiologist** [comment]
I think we should use `defmacro` for it, because I was already thinking of changing `defmacro` back into a special form.

**Comment by Kodiologist** [comment]
@allison-casey I'm curious what you think of this considering that you've talked about doing some deep reorganization of the compiler. It might be possible to, for example, eliminate special operators entirely and just use these macros, implementing several of them in Python rather than Hy to avoid having to self-host; with some thought and search-and-replaces, a lot of the existing compiler `@special` methods could be converted into macros.

**Comment by allison-casey** [comment]
its an interesting idea. can you mock up an example of what a macro returning a python ast object might look like?

**Comment by Kodiologist** [comment]
Allison and I have made some promising progress towards not only getting this to work, but replacing all special forms with macros, mostly written in Python rather than Hy. I'm going to keep at it and see how far I can get.
