### ISSUE TITLE
Web Console - CORS error

### ISSUE THREAD

**Issue by falonso-caa** [hylang/hy#2063]
Apologies if this is the wrong repo for this, but it looks like the web console is throwing CORS errors when you attempt to run the example:

![image](https://user-images.githubusercontent.com/37314800/117893934-2e6e6480-b270-11eb-8f44-44dfec7e68a4.png)

I'm not too familiar with CORS, but if it helps, I'm using:

Browser: Firefox 88.0.1
OS: Windows 10 Enterprise (64 bit)

**Comment by allison-casey** [comment]
Thanks for the heads up! I'm in the middle of fixing it after a lodash security advisory. Also, the correct repo would be the [hy-interpreter](https://github.com/hylang/hy-interpreter) repo. I'm going to close this issue here, but i'll open a new one over there.

**Comment by allison-casey** [comment]
should be fixed. let me know if you continue to run into issues.

**Comment by falonso-caa** [comment]
Ah, my apologies for putting it in the wrong repo; I came across the link in the README here. 

Regardless, it looks good now! Hope you have a wonderful day!

![image](https://user-images.githubusercontent.com/37314800/117900443-071e9400-b27e-11eb-8039-41deceeb8b66.png)

**Comment by allison-casey** [comment]
Oh no worries! Thank you for keeping an eye out :+1:
