### ISSUE TITLE
Run REPL using `python -m hy`

### ISSUE THREAD

**Issue by lassik** [hylang/hy#2069]
Figuring out how to get a REPL is not trivial. What do you think about making `python -m hy` do it?

**Comment by Kodiologist** [comment]
The command `hy` seems straightforward enough, and is analogous with Python. Why would you want another route to the same end?

**Comment by lassik** [comment]
I didn't realize there is a `hy` command. I installed Hy from `pip` and there isn't one in my `PATH`. I've used `import hy.cmdline` and `hy.cmdline.run_repl()`. It's a minor convention for `python -m` to do something useful, perhaps most famously `python -m SimpleHTTPServer` to serve the current directory over HTTP.

**Comment by Kodiologist** [comment]
>  I installed Hy from `pip` and there isn't one in my `PATH`

That sounds like a bug, although it's hard to guess whether the bug is in pip or Hy. Can you reproduce this issue in a virtualenv?
