### ISSUE TITLE
Recursive `hy2py`

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2079]
We could give `hy2py` a recursive mode that goes through a source tree and saves a matching Python file for each Hy file, if an up-to-date one doesn't already exist. Optionally, it could delete all such Python files and bytecode first, in order to ensure all macro expansions are fully up to date.

I'm not sure how often this would be useful in practice, but it seems like an obvious feature to have.

**Comment by dm9pZCAq** [comment]
i started implementing this, but i faced a problem:

when i pass actual module name to `hy_compile` it not just compile `hy` to `py` but also evaluates compiled `py`

**Comment by dm9pZCAq** [comment]
hmm, i think this is ok when it is part of module
