### ISSUE TITLE
anaphoric macro, "ap-if" not working with fstrings

### ISSUE THREAD

**Issue by Cloud11665** [hylang/hy#2100]
This works
```hy
(ap-if (list-tags f"{tag}*" :apikey args.api)
       (setv rec (% " Did you mean \"%s\" ?" (. it[0]['tag])))
       (setv rec ""))
```
And this doesn't
```hy
(ap-if (list-tags f"{tag}*" :apikey args.api)
       (setv rec f" Did you mean \"{(. it[0]['tag])}\" ?" )
       (setv rec ""))
;; NameError: name 'it' is not defined
```

I it something wrong with my code?
already tested this with nested `get` operators and still throws the same error

hy version: 0.20.0
cpython version: 3.8.6
OS: linux (debian)
arch: x86_64

**Comment by Kodiologist** [comment]
> If you're reporting a bug, make sure you can reproduce it with the very latest, bleeding-edge version of Hy from the `master` branch on GitHub. Bugs in stable versions of Hy are fixed on `master` before the fix makes it into a new stable release.
