### ISSUE TITLE
Macro: Undefined behaviours regarding internal symbols

### ISSUE THREAD

**Issue by m1nhtu99-hoan9** [hylang/hy#2105]
Coming from Clojure, the following REPL code failed as I expected:

```hylang
=> g
Traceback (most recent call last):
  File "stdin-54fd1711209fb1c0781092374132c66e79e2241b", line 1, in <module>
    g
NameError: name 'g' is not defined
=> (defmacro print-identity [expr]
...   (setv g None)
...   `(do
...     (setv g ~expr)
...     (print g)))
<function print_identity at 0x7f6053b979d0>
=> (print-identity 9)
9
=> g
9
```

However, when I tried to return the internal variable at the end (as in the [`->`](https://github.com/hylang/hy/blob/9cee82dc944843df951d745191b8e52a6205e736/hy/core/macros.hy#L189) and [`->>`](https://github.com/hylang/hy/blob/9cee82dc944843df951d745191b8e52a6205e736/hy/core/macros.hy#L244) macro implementations), weird behaviours occured:

```hylang
=> h
Traceback (most recent call last):
  File "stdin-27d5482eebd075de44389774fce28c69f45c8a75", line 1, in <module>
    h
NameError: name 'h' is not defined
=> (defmacro print-identity [expr]
...   (setv h None)
...   `(do
...     (setv h ~expr)
...     (print h))
...   h)
<function print_identity at 0x7f6053b075e0>
=> (print-identity 19)
=> (is (print-identity 19) None)
True
```

Why is the `do` form in the middle ignored?

**Comment by Kodiologist** [comment]
This behavior looks correct to me. You constructed the form with a backtick, but didn't return it from the macro, so it never gets executed. Other Lisps will do the same, if I'm not mistaken.

**Comment by allison-casey** [comment]
yes this is expected behaviour. if you'd like to set `h` then print it then return it, the `h` should be the last element in the `do` block
