### ISSUE TITLE
Perhaps make result macros convenient for users

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2108]
I implemented result macros chiefly for internal use (#2104), but they could have some applications by users, if users want to change what AST can be generated by Hy without forking Hy.

This will likely take code changes as well as documentation changes. It will require making a lot of previously internal compiler machinery public, for good or for ill.

**Comment by scauligi** [comment]
I don't have any immediate practical uses for this, but I do very much like the idea of letting users define result macros to extend the language in interesting ways.

**Comment by allison-casey** [comment]
If this wouldn't result in any breaking changes I think it should wait until after 1.0, but I'm partial to this as well

**Comment by Kodiologist** [comment]
It is unlikely to break much because it's more of a new feature than a change of something existing. But, it's not a priority for me, anyway.

**Comment by allison-casey** [comment]
In that case let's save this for 1.1. I think there's still a bug with result macro line numbers that I need to double check anyways

**Comment by Kodiologist** [comment]
I think this was a bad idea. Making all those internal details public would add a lot of maintenance and documentation overhead and make breaking changes an issue after 1.0.
