### ISSUE TITLE
Naming the spin-off library

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2122]
I'm finally finishing up #1992, and the next thing I'll do is make the spin-off library to hold a variety of smallish functions and macros that will no longer be part of Hy proper. This raises the critically important question of what to name it. Here are some options:

1. Hyrule
2. Hyrax
3. SkyHy
4. HyUtil

What would you vote for? (Votes from core developers count for more, but the general public's opinion is welcome as well.)

**Comment by scauligi** [comment]
![](http://fc07.deviantart.net/fs70/f/2012/185/5/f/triforce_icon_free_to_use_by_kittyzelda64-d560tnh.png)
Personally I'm a fan of Hyrule

**Comment by allison-casey** [comment]
Hyrule seems too good to pass up :1st_place_medal:

**Comment by Kodiologist** [comment]
I am also partial to "Hyrule", so we're going full Zelda.
