### ISSUE TITLE
Proposal: Make strings, maps & vectors "callable"

### ISSUE THREAD

**Issue by glyh** [hylang/hy#2154]
For example: 
```hy
; string concatenation
("a" "b" "c")
; dictionary indexing 
({:a 1 :b 2} :a)
; list indexing 
([1 2 3 4] 0)
```
just mean the these in python:
```py
# string concatenation
("a" "b" "c")
# map indexing
{"a":1, "b":2}["a"]
# list indexing 
[1,2,3,4][0]
```
This will be handy for writing codes.

**Comment by Kodiologist** [comment]
I'm don't really understand why you'd want these. `("a" "b" "c")` is better written as `"abc"`, `([1 2 3 4] 0)` as `1`, and so on.

**Comment by glyh** [comment]
> I'm don't really understand why you'd want these. `("a" "b" "c")` is better written as `"abc"`, `([1 2 3 4] 0)` as `1`, and so on.

It's just an example, there is situation when the arguments are variables: 
```hy
(setv what "string")
("a " what)

(setv key :James)
({:James :apple} {:Tom :banana} key)

(setv index :3)
([1 2 3 4] index)
```

**Comment by Kodiologist** [comment]
Okay, it makes more sense when the arguments are not not themselves literals, although it doesn't seem like much of an advantage over using `get` or `+`. Bear in mind that in general we can only implement this when the called object is a literal, because Python doesn't allow monkey-patching the `__call__` method of a built-in type.

**Comment by glyh** [comment]
Can this be done at compile time? This might be hard, if hy compiler only recognizes the syntax, rather than the semantics of the language. But I don't know details about the compiler. I'll be happy if you can tell me more about it. XD

**Comment by Kodiologist** [comment]
Only when the called object is a literal. The compiler can't know in general what the type of `col` is, because Python is dynamically typed.

**Comment by glyh** [comment]
If that is the case, I think this syntax sugar is not that important. It's nice to have, but if it can't be done easily, it's not neccessarily to put efferts into it. Thanks for your time discussing this with me. XD
