### ISSUE TITLE
Warn in documentation that `let` doesn't allow earlier frees

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2160]
This was something I thought of when reviewing #2125, but it applies to Hyrule's `let` too, so it's not new. Users might expect that restricting large objects to `let` scopes would be a way to allow Python to deallocate them earlier, but it doesn't, because the temporary variables created for the `let` are still in scope when the `let` ends. You need to use `del` or a real Python-level scope in addition to the `let` to allow such objects to be garbage-collected as early as you want.

**Comment by scauligi** [comment]
Alternatively, should we have `let` insert `del` statements for any names it binds?

**Comment by scauligi** [comment]
Actually now that I think about it, that sounds difficult to implement what with non-local control flow like `break` statements breaking out of a let. I'll just add a warning to the docs with #2125.

**Comment by Kodiologist** [comment]
> Alternatively, should we have `let` insert `del` statements for any names it binds?

I think that should be possible by wrapping the `let` result in a `try` and doing the `del` in `finally`, but ultimately this is a performance question and there are likely performance tradeoffs involved in doing this (perhaps of memory vs. speed), which might defeat the purpose. It's a difficult question and probably best pursued as its own PR if we decided it's worth doing. Let's stick with the documentation warning for now.

**Comment by gilch** [comment]
This is not about performance. Remember that `let` is supposed to be able to make *lexical* bindings. That includes closures. Deleting `let`'s dict at the end of the block would defeat that.

**Comment by Kodiologist** [comment]
Closed by #2125.
