### ISSUE TITLE
Tests are failing on Python 3.10.0rc2

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2165]
`(require tests.resources.macro-with-require)` leads to

```
…
  File "/home/hippo/Workspace/hyenv/hy/hy/macros.py", line 134, in require
    parent_frame = inspect.stack()[1][0]
  File "/home/hippo/Workspace/Python-3.10.0rc2/mybuild/lib/python3.10/inspect.py", line 1676, in stack
    return getouterframes(sys._getframe(1), context)
  File "/home/hippo/Workspace/Python-3.10.0rc2/mybuild/lib/python3.10/inspect.py", line 1653, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/home/hippo/Workspace/Python-3.10.0rc2/mybuild/lib/python3.10/inspect.py", line 1625, in getframeinfo
    start = lineno - 1 - context//2
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int
```

Evidently we failed to set a line number on a Hy model somewhere and the latest version of `inspect` needs it. I'm done fussing with this for today, but hopefully I'll find the guilty model sometime this coming week.

**Comment by scauligi** [comment]
So I was able to track this down to the `rename_function` function in `hy/macros.py`. It's probably the case that we need to something to `code_obj_args`, but... I'm also not sure what the purpose of this function really is?

I replaced the call to `rename_function` with just updating `__name__` and `__qualname__` and all the tests pass on 3.10.0rc2, so maybe the need to muck about with the `co_*` fields was a holdover from python2?

```diff
diff --git a/hy/macros.py b/hy/macros.py
index f211c737..1dcc2363 100644
--- a/hy/macros.py
+++ b/hy/macros.py
@@ -73,7 +73,8 @@ def pattern_macro(names, pattern, shadow = None):
 
 def install_macro(name, fn, module_of):
     name = mangle(name)
-    fn = rename_function(fn, name)
+    fn.__name__ = name
+    fn.__qualname__ = name
     (inspect.getmodule(module_of).__dict__
         .setdefault('__macros__', {})[name]) = fn
     return fn
```

**Comment by scauligi** [comment]
...oh, but now it's failing on python3.9. Hmm.
