### ISSUE TITLE
`flatten` not preserving the individual elements' types.

### ISSUE THREAD

**Issue by jeongsoolee09** [hylang/hy#2166]
Consider the following:

```clojure
(import [urllib.request [urlopen]])
(import [bs4 [BeautifulSoup]])

(setv java-collection "https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html")
(setv html (urlopen java-collection))
(setv bs (BeautifulSoup html "html.parser"))
(setv interesting (cut (.find-all bs "dd") 2 4))
(setv interesting! (list (map (fn [dd-tag] (.findChildren dd-tag)) interesting)))
(setv all-tags (flatten (list (map (fn [dd-tag] (.findChildren dd-tag)) interesting))))
```

`interesting!` is a list of list of `<class 'bs4.element.Tag'>`, so `all-tags` is expected to be a list of `<class 'bs4.element.Tag'>`. However, `all-tags` actually evaluates to a list of strings.

**Comment by scauligi** [comment]
`flatten` has been moved to [hylang/hyrule](https://github.com/hylang/hyrule); make sure you're using latest Hy/hyrule before opening issues, please!

Also, `bs4.element.Tag` defines `__iter__`: "Iterating over a Tag iterates over its contents."

**Comment by jeongsoolee09** [comment]
@scauligi Wow, never thought of looking into `__iter__`. Thanks!
