### ISSUE TITLE
Cannot run Keras neural networks through Hy

### ISSUE THREAD

**Issue by josephtoles** [hylang/hy#2179]
I'm trying to run [keras](https://keras.io/) through `hy`. Keras works just fine on Hy's stable release 0.20.0 but keras stops working when I attempt to run the identical code on the alpha3 located on the current master commit `1f7abd1f30c738f7160335316610d9c1d75a2d2a`. I am running  Hy version `1.0a3+155.g1f7abd1f.dirty`.

# Python vs Hy

When I run the following program through Python3 everything works fine.

```
from keras.models import Sequential
Sequential() # works fine
```

Here is a Hy port of the same code. The Hy code terminates with an error.

```
(import keras.models [Sequential])
(setv model (Sequential)) # raises an exception
```

The traceback the Hy code produces is quite long.

```
Traceback (most recent call last):
  File "/usr/local/bin/hy", line 11, in <module>
    load_entry_point('hy==1.0a3+155.g1f7abd1f.dirty', 'console_scripts', 'hy')()
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lsusr/code/pilot/bug-report/script.hy", line 3, in <module>
    (setv model (Sequential))
  File "/home/lsusr/.local/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 530, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/lsusr/.local/lib/python3.8/site-packages/keras/engine/sequential.py", line 107, in __init__
    super(functional.Functional, self).__init__(  # pylint: disable=bad-super-call
  File "/home/lsusr/.local/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 530, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/lsusr/.local/lib/python3.8/site-packages/keras/engine/training.py", line 289, in __init__
    self._init_batch_counters()
  File "/home/lsusr/.local/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 530, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/lsusr/.local/lib/python3.8/site-packages/keras/engine/training.py", line 297, in _init_batch_counters
    self._train_counter = tf.Variable(0, dtype='int64', aggregation=agg)
  File "/home/lsusr/.local/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 268, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "/home/lsusr/.local/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 250, in _variable_v2_call
    return previous_getter(
  File "/home/lsusr/.local/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 243, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "/home/lsusr/.local/lib/python3.8/site-packages/tensorflow/python/ops/variable_scope.py", line 2662, in default_variable_creator_v2
    return resource_variable_ops.ResourceVariable(
  File "/home/lsusr/.local/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 270, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/lsusr/.local/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1602, in __init__
    self._init_from_args(
  File "/home/lsusr/.local/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1756, in _init_from_args
    handle = eager_safe_variable_handle(
  File "/home/lsusr/.local/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 238, in eager_safe_variable_handle
    return _variable_handle_from_shape_and_dtype(shape, dtype, shared_name, name,
  File "/home/lsusr/.local/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 177, in _variable_handle_from_shape_and_dtype
    handle_data.shape_and_type.append(
AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'append'
```

Most of this error message is keras-specific and tensorflow-specific. I think the most important thing is the last line with the AttributeError. The `google.protobuf.pyext._message` Python library has no class named `RepeatedCompositeContainer`. I think that `RepeatedCompositeCo` is an truncation of `RepeatedCompositeContainer`. (A search through Google's [protocolbuffers repository](https://github.com/protocolbuffers/protobuf/search?q=RepeatedCompositeContainer) corroborates this.)

Other people have [solved this bug by upgrading protobuf](https://stackoverflow.com/questions/58343293/attributeerror-google-protobuf-pyext-message-repeatedcompositeco-object-has) but I don't think that's what I'm doing wrong because keras runs just fine under Python. I looked for a protobuf dependency in the Hy source code bug but there's no reference to `protobuf` or `pyext` in the Hy source code that I could fine. (Perhaps I am missing something.)

# Installing Keras

I think you can install keras with just a `pip3 install keras` and `pip3 install tensorflow` and following its other prompts (but I'm not 100% sure).

# System Information

## Operating system

Lubuntu

## Hy & Hyrule versions

I am using Hy alpha3 commit `1f7abd1f30c738f7160335316610d9c1d75a2d2a` installed from source.

I am using Hyrule commit `1a0c2d6d4cf49a5762fa9c2be71e4e8eb8f8411e`.

## Python dependencies

I have the following Python libraries installed (not exhaustive).

```
keras==2.6.0
keras-nightly==2.5.0.dev2021032900
tensorflow==2.6.0
tensorflow-estimator==2.6.0
hy==1.0a3+155.g1f7abd1f.dirty
hyrule==0.0.0
protobuf==3.19.1
```

**Comment by josephtoles** [comment]
Something really weird about this bug is that it depends on whether Python calls Hy or Hy calls Python. Suppose I create two scripts.

`pyscript.py`
```
from keras.models import Sequential
Sequential()
```

`hyscript.hy`
```
(import keras.models [Sequential])
(setv model (Sequential)) # raises an exception
```

If I use `hy` to run `hyscript.hy` then the bug apperas. If I use `Python3` to run `pyscript.py` then the bug does not appear.

But if I open a `hy` interpreter and the import `pyscript` the bug still appears whereas if I open a `Python3` interpreter and import `hyscript` then the bug does not appear.

**Comment by Kodiologist** [comment]
> Other people have solved this bug by upgrading protobuf but I don't think that's what I'm doing wrong because keras runs just fine under Python.

Have you tried upgrading protobuf, anyway? Does it resolve this?

**Comment by Kodiologist** [comment]
I suspect that what's going on is that you have Hy and Python installed such that they're picking up different versions of protobuf. So if the upgrade doesn't work, try to replicate this issue in a virtualenv.

**Comment by josephtoles** [comment]
Thank you for such a quick response.

Updating protobuf to via Pip version 3.19.1 does not fix the issue.

Using a virtualenv is a good idea too. My virtualenv works just fine when I am running Python3 but not when I am running Hy. When I am run Hy in a virtualenv, Hy accesses my system libraries and does not access the virtualenv ones. Perhaps the keras issue is just a manifestation of whatever dependency problem I have with Hy. I assume virtualenv works the same way on Hy as for Python since there is little information about virtualenvs in the Hy documentation.

I'm surprised virtualenv has no effect on Hy on my machine because it seems to me as if most of what a virtualenv does is modify the environment variable `VIRTUAL_ENV` to point to a new location. It appears that my Hy is not reading the `VIRTUAL_ENV` environment variable. (I am using my alpha3 version of `hy` installed to the default location `/usr/local/bin/hy`.)

# Warning Message

A warning message appears when I run the Hy interpreter. I do not know if it is relevant.

```
/home/lsusr/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.13.1-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/home/lsusr/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/lsusr/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Hy 1.0a3+155.g1f7abd1f.dirty using CPython(default) 3.8.10 on Linux
=> 
```

**Comment by josephtoles** [comment]
Two of the packages warned above in the above comment correspond to distutils.

```
gpg===1.13.1-unknown
distro-info===0.23ubuntu1
```

**Comment by josephtoles** [comment]
Update: I updated my `gpg`. This removed the warning messages when I run Hy.

**Comment by josephtoles** [comment]
Everything works now! Thank you so much!

**Comment by Kodiologist** [comment]
Python package management is something of a mess, isn't it? I'm glad you were able to sort things out.

**Comment by josephtoles** [comment]
Yes to both. I'm sorry to bother you about it.
