### ISSUE TITLE
`with` behaves differently in alpha3

### ISSUE THREAD

**Issue by josephtoles** [hylang/hy#2182]
I'm using the new alpha. The `with` macro behaves differently than it did on my installation of hy version 0.20.0.

I am using the following syntax for `with`.

```
(with [f (open "filename" "w")]
  (.write "text" f))
```

But when I run the same code in the alpha I get an error.

```
Hy 1.0a3+155.g1f7abd1f.dirty using CPython(default) 3.8.10 on Linux
=> (with [f (open place "w")] (.write f "text"))
Traceback (most recent call last):
  File "stdin-3355f41864ab7b8fa48648f165ba4d1b915983bf", line 1, in <module>
    (with [f (open place "w")] (.write f "text"))
hy.errors.HyMacroExpansionError: 
  File "<stdin>", line 1
    (with [f (open place "w")] (.write f "text"))
    ^-------------------------------------------^
expanding macro with
  TypeError: can only concatenate list (not "Expression") to list
```

I'm confused because I looked at the hylang unit tests [here](https://github.com/hylang/hy/blob/master/tests/native_tests/language.hy) and it appears to me like `with` is used the same way I'm using it.

Do I have the syntax wrong? Maybe I did something wrong when building and installing hy such that `with` performs wrong on my machine?

# News

I see that `with` was indeed modified in the alpha3 release.

According to `NEWS.rst`, the syntax for `with` was indeed changed. However, if I'm reading `NEWS.rst` correctly, it's just saying that the user doesn't need to create a name for the context managed function and there are no other changes.

```
* With's syntax was fixed to match the rest of the code. It's now: (PT)
    (with [name context-managed-fn] BODY)
    (with [context-managed-fn] BODY)
```

# System Specs

I am running the alpha3 located on the current master commit `1f7abd1f30c738f7160335316610d9c1d75a2d2a`. I am running Hy version `1.0a3+155.g1f7abd1f.dirty`.

**Comment by allison-casey** [comment]
I can't recreate this on that commit with either python 3.9 or 3.8. Are you using Windows? Maybe this is an issue with the python files Hy is running against related to the pip package issues you mentioned in #2179?

**Comment by josephtoles** [comment]
I'm not using Windows. (I'm running lubuntu.) I fixed the warnings in issue #2179 but not the virtualenv so there could still be something going on there. I'm using Python 3.8.10.

Fortunately, this isn't the end of the world. The nice thing about Lisps is I can just write my own version of the macro.

I appreciate all the work you folks do on this project.

**Comment by josephtoles** [comment]
If the dev team doesn't notice this problem then I'll attribute it problems on my own system. I just wrote a custom `with` macro so this is barely an inconvenience.

```
(defmacro/g! my-with [symbol-context-manager #* code]
             (setv [symbol context-manager] symbol-context-manager)
             `(do
                (setv ~g!context-manager ~context-manager)
                (setv ~symbol (.__enter__ ~g!context-manager))
                (setv ~g!output (do ~@code))
                (.__exit__ ~g!context-manager)
                ~g!output))
```

**Comment by josephtoles** [comment]
Thank you for the lightning fast response, by the way.

**Comment by allison-casey** [comment]
weird, i would still like to get to the bottom of this without you having to use a custom macro. I just can't seem to recreate it on my end. If you figure out what's going on with your virtual env be sure to update us on if it fixes the issue. Want to make sure this is a installation issue and not something on our end.

**Comment by josephtoles** [comment]
Thank you very much. I'll let you know if I can reproduce it in a clean virtual env.
