### ISSUE TITLE
kwapply doesn't translate a key '-' to '_'

### ISSUE THREAD

**Issue by Willyfrog** [hylang/hy#219]
arguments of a function are translated from '-', symbols also are translated, but strings are not, so having a key 'my-key-argument' won't be translated to 'my_key_argument' having a:
    TypeError: myfunc() got an unexpected keyword argument 'my-key-argument'

**Comment by algernon** [comment]
This should be pretty easy to implement, I believe, and also a great and easy candidate for the Grand Language Cleanup! I'll have a go at it.

**Comment by algernon** [comment]
What do y'all think about this:

```hy
(apply some-function [] {"a-b" 1})
(apply some-function [] {:a-b 1})
```

both translating to:

```python
some_function(*[], **{"a_b": 1})
```
