### ISSUE TITLE
`break` and `continue` in multidimensional `for` loops only affect the innermost generated loop

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2194]
```
=> (for [a [1 2]  b [3 4 5]] (print a b) (when (= b 4) (break)))
1 3
1 4
2 3
2 4
```

This is arguably consistent with the documentation, and it's obvious that it should happen when considering how `for` with multiple iterators is implemented, but it doesn't seem desirable. I hope we can change this without massive changes to the comprehension forms.

**Comment by Kodiologist** [comment]
Yeah, it's dicey. It might be doable with some generator trickery, but then I think `:do` clauses would no longer be in the right function scope in the case of `for`, breaking `return`. I'd have to think about it.

**Comment by allison-casey** [comment]
I'm going to add it to the `1.0` project board since this is behavior i'd like to iron out before we release (even if it does end up as a `docme`)

**Comment by Kodiologist** [comment]
Seems fair.

**Comment by allison-casey** [comment]
Can the loop iterator just compile down to a `gfor` that returns a tuple? This would preserve the `for` order of `:do`?

```clojure
=> (for [[a b] (gfor a (range 3) 
                     :do (print "A:" a)
                     b "abc" 
                     :do (print "B:" b)
                     (, a b))]
    (print a b))
```

```python
def _hy_anon_var_3():
    for a in range(3):
        print('A:', a)
        for b in 'abc':
            print('B:', b)
            yield (a, b)
for [a, b] in _hy_anon_var_3():
    print(a, b)
```

This would be less performant than the straight nested `for`s though

**Comment by Kodiologist** [comment]
That's what I was talking about [here](https://github.com/hylang/hy/issues/2194#issuecomment-998885057). `:do (return)` would return from `_hy_anon_var_3` instead of the parent function.

**Comment by allison-casey** [comment]
ahhh misread `return` in your comment. Yeah then i've got nothing besides remove `:do` from `for`

**Comment by Kodiologist** [comment]
I'm imagining something using exception-handling where `break` compiles to `raise` when appropriate. It would feel less stupid if we used the same compiler code to implement Common Lisp-style `return-from` while we were at it.

**Comment by allison-casey** [comment]
I'd be interested to see how that would interact with `for`'s `else` clause since that's dependent on `break` execution

**Comment by scauligi** [comment]
I believe wrapping the outer `for` in a `try: ... except StopIteration: pass` and using `raise StopIteration` to get out of nested loops should have analogous semantics to `break`s from single loops wrt to `else` clauses and other things

**Comment by Kodiologist** [comment]
My current thinking is that this behavior should be kept and documented, with a recommendation to use a more general `block` / `return-from` provided in Hyrule when you want to control an outer loop.
