### ISSUE TITLE
hylang.org is down although docs.hylang.org is up

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2195]
@paultag Perhaps it's a DNS issue.

**Comment by paultag** [comment]
Gah, worse than that - that's my old VPS - although I shut it down rather than turned it off. This is a good time for me to migrate it to a new website, eh. I'm going to set up a hylang org repo with the website so y'all can make unccordinated changes on it!

**Comment by Kodiologist** [comment]
Neat.

**Comment by paultag** [comment]
oh jeez, I remember now, it was a redirect via nginx on that box. I'm going to port this forward as a hotpatch, I'll get this back and stable and off that box today.

**Comment by paultag** [comment]
I lied, I forgot the state of all of this. I added an `ALIAS` for `readthedocs.io` for `hylang.org` and added it to the readthedocs custom domains. Waiting on DNS to fully expire from caches to pick up the change; no website needed since it'd be just another thing to maintain. Obv happy to reevaluate that, but I think this is a fine outcome. Objections?

**Comment by paultag** [comment]
And with that, the website's up again locally. I shut down my old VPS; would someone who's not coming from my DNS resolution chain check that in a few minutes? Happy to revise this as required @hylang/core

**Comment by Kodiologist** [comment]
The fine differences between ALIAS and CNAME are beyond me, but a DNS-level redirect seems like the right way to do it, at least until we want to put something on hylang.org other than the documentation.

**Comment by paultag** [comment]
@Kodiologist the only important difference here is you can't CNAME the root (e.g., hylang.org -- only a subdomain like docs.hylang.org; so if you wan to CNAME the root, ALIAS is your bet :) )

**Comment by paultag** [comment]
OK curl commands from a few boxes around the world are happy. Closing this isssue; please re-open if this crops up locally for anyone!

**Comment by Kodiologist** [comment]
Looks good to me. Thanks for the quick fix, Paul.

**Comment by paultag** [comment]
you got it team, a pleasure to have been able to meaningfully do a drive by contribution again :)
