### ISSUE TITLE
make dict repr more "hylish"

### ISSUE THREAD

**Issue by Willyfrog** [hylang/hy#220]
dicts are declared one way and should be **repr** the same way instead of as a python dict

```
=> {"a" 1 "b" 2}
```

is:
    {u'a': 1, u'b': 2}
and at least should be
    {u'a' 1 u'b' 2}
perfect would be:
    {"a" 1, "b"  2}
as neither ' nor u" are valid strings delimiters in Hy so it prevents a copy+paste from repl

P.D.: not sure if this should be opened as 2 issues as it also affects string representation

**Comment by algernon** [comment]
As in #198, I'd prefer this option instead of allowing pythonic syntax.

**Comment by Kodiologist** [comment]
I'm closing this in favor of the more general #351.
