### ISSUE TITLE
hy.eval crashes when evaluating macros when passed a "<...>" string to module arg 

### ISSUE THREAD

**Issue by allison-casey** [hylang/hy#2202]
Noticed this while working on the reader macro tests. 

`hy.eval` is supposed to allow passing a module name surrounded by `<` `>` to signify creating a new module to evaluate in (the value is passed directly to `compiler.get_compiler_module`).

 This works as long as you don't try to evaluate a `defmacro` call which will crash out with an `HyEvalError`. `defmacro`'s call to `macros.install_macro` attempts to inject the macro into the module's `__macros__` attribute, but since the `<module-name>` passed to `hy.eval` isn't added to `sys.modules`, `inspect.getmodule` will return `None`, immediately crashing when we try to get the module's `.__dict__` attr.
 
 ```clojure
 => (hy.eval (hy.read "(defmacro a [] 1)") :module "<test>")
hy.eval(hy.read('(defmacro a [] 1)'), module='<test>')
None
Traceback (most recent call last):
  File "stdin-0ddca9f7dc853219212315199ccdb4534920a36f", line 1, in <module>
    (hy.eval (hy.read "(defmacro a [] 1)") :module "<test>")
hy.errors.HyEvalError: 'NoneType' object has no attribute '__dict__'
 ```

I've been working around this in the tests i've been writing with a context manager to temporarily add the module to `sys.modules`:

```clojure
(with-decorator
  contextmanager
  (defn temp-module [module-name]
    (let [module (types.ModuleType module-name)
          old-module (sys.modules.get module-name)]
      (setv (get sys.modules module-name) module)
      (try
        (yield module)
        (finally
          (if old-module
              (setv (get sys.modules module-name) module)
              (sys.modules.pop module-name)))))))
```

**Comment by Kodiologist** [comment]
> `hy.eval` is supposed to allow passing a module name surrounded by `<` `>` to signify creating a new module to evaluate in

This doesn't seem to be documented, so this should be a problem only for us, and not users.

**Comment by Kodiologist** [comment]
Incidentally, `hy.eval` should perhaps take `module` first and `locals` second, so as to be more like Python's `eval`.
