### ISSUE TITLE
Distinguishing `if`, `when`, and `cond`

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2210]
Let's talk about how exactly these three similar constructs should differ.

`cond` requires brackets around each condition-result pair. Previously the idea of dropping those brackets, and thus requiring `do` when you want a multi-form result, has been floated. I've warmed up to that idea, particularly since we've been dropping brackets from other stuff (like `import`) and `if` can't be used like `cond` anymore. I feel like in most cases, I won't need the `do`.

`if` and `when` are identical when you use exactly two arguments. What if `if` was required to have exactly three arguments? Then, when you see `if`, you know that an else-clause is coming. The expectation is that you'll use `when` when you're happy with the implicit `None` in the else-case, although you can always write `(if condition then-clause None)` if you want to be explicit.

**Comment by allison-casey** [comment]
There is precedent for this as Racket does enforce this distinction. Let me try it locally and see how it feels.

**Comment by allison-casey** [comment]
I have a test passing version of a strict if on my [strict-if](https://github.com/allison-casey/hy/tree/feature/strict-if) branch if you want to take a look

**Comment by Kodiologist** [comment]
It doesn't look like it had any surprising consequences. That's good.

**Comment by allison-casey** [comment]
most the changes were for side effecting python constructs like `.append`, `break`, `continue` etc. There were a few cases where we were using the implicit `None` as a return value (mostly in `hy_repr`), but those should have either been explicitly defined as they are expected values of slices or done via `when` or as a short circuiting `and`.

**Comment by Kodiologist** [comment]
I recall using `if` in the `hy.repr` code in a lot of cases where I wanted to use `when`, because the way things were originally set up years ago, `hy.repr` had access to special forms but not any core macros.

**Comment by allison-casey** [comment]
I'm leaning in favor of this change at the moment. Using `if`'s return value with the implicit `None` is an anti pattern imo and should be discouraged. `when` does a much better job of indicating that you should be aware of the `None`  and generally leads to more easily understood code. Lets let this sit for a bit though to let the initial feeling sink in and see if anyone else wants to comment though. 

Also, you said you're warming up to bracketless `cond`. are you saying you'd be open to a PR to change that at some point? It does seem like most of our constructs are moving away from those kinds of brackets

**Comment by Kodiologist** [comment]
Yes, I think that and the change to `if` would be complementary because they help give the trio distinct roles and salve the pain of those who miss the old multi-branch `if`, although ultimately they're separate and should probably be separate PRs.

**Comment by Kodiologist** [comment]
Also, we should have a test of one-argument `when`. While not useful in and of itself, `(when CONDITION)` is something that could be generated by macros, and the desired effect is clear: evaluate `CONDITION` and return `None`, like `(do CONDITION None)`.
