### ISSUE TITLE
Account for Python's normalization of Unicode identifiers

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2216]
My friend @rebane2001 pointed out to me that thanks to the rule "All identifiers are converted into the normal form NFKC while parsing; comparison of identifiers is based on NFKC." in [PEP 3131](https://www.python.org/dev/peps/pep-3131/), two seemingly distinct Python identifiers can be understood to be the same. For example, you can spell "print" as "𝓅𝓇𝒾𝓃𝓉" or "𝖕𝖗𝖎𝖓𝖙". Reserved words, at least, still have to be in ASCII: you can't spell "if" as "𝕚𝕗".

My unawareness of this Python "feature" has led to several bugs in Hy. For example, given `PROGRAM='(setv 𝔥𝔢𝔩𝔩𝔬 1) (print hello)'`, `hy -c "$PROGRAM"` crashes with `NameError`, but `echo "$PROGRAM" | hy2py | python3` doesn't.

The situation also creates a weird opportunity. You know how we don't allow `(foo :if 3)` (#2081), because there's no equivalent Python code for `hy2py` to translate it into? Turns out there is: `foo(𝕚𝕗 = 3)`. We'll have to judge whether this is too weird to take advantage of.

Relatedly, however, a moment's thought (which is apparently more thought than was put into PEP 3131) reveals [a bug](https://bugs.python.org/issue46520) in Python's `ast.unparse`, and probably `astor` as well:

    $ python3 -c 'import ast; print(ast.unparse(ast.parse("𝕕𝕖𝕗 = 1")))' | python3
      File "<stdin>", line 1
        def = 1
            ^
    SyntaxError: invalid syntax

**Comment by allison-casey** [comment]
> You know how we don't allow (foo :if 3) (#2081), because there's no equivalent Python code for hy2py to translate it into? Turns out there is: foo(𝕚𝕗 = 3). We'll have to judge whether this is too weird to take advantage of.

I don't view this as an opportunity. just because you can doesn't mean you should and I can't think of any case where this could ever possibly be a good idea.

**Comment by Kodiologist** [comment]
You laugh, but it seems to work out very well in my PR. Variables and keyword arguments with the "reserved" names Just Work. The plain ASCII names appear unaltered in `__doc__` and error messages. The only hitch is that we need to make `hy2py` do the Unicode trick, and the only reason Hy needs to do any work for that is that CPython's `ast.unparse` has a bug. Hopefully my CPython patch will eventually make that code obsolete.

**Comment by allison-casey** [comment]
I believe i misunderstood what you were suggesting here as somehow encouraging using unicode abuse in user facing code which i still maintain is a terrible idea, but as a exclusively a way to get around python reserved words on the compiler side is very interesting and just crazy enough to work. Let me see if I can find any bugs in you PR or any reasons this might bite us in the future
