### ISSUE TITLE
[FEATURE] Backward compatibilities?

### ISSUE THREAD

**Issue by glyh** [hylang/hy#2218]
Right now Hy reaches 1.0, everything breaks. Would we consider add backward compatibilities like in perl? Or at least deprecate features rather than remove them instantly?

**Comment by glyh** [comment]
Here's an example: https://github.com/allison-casey/HyREPL
I tried to get this work on hy1.0a4 but incompatible changes happen literally everywhere.

**Comment by Kodiologist** [comment]
It's too early to think about backwards compatibility before we've released 1.0. (Well, that's a little backwards: the chief reason we haven't called any release 1.0 yet is that the language is still changing too fast for backwards compatibility to be feasible, given the manpower we have.) Probably the arrangement will be like SemVer, with 1.1 being backwards-compatible with 1.0, and 1.2 with 1.1 and 1.0, but 2.0, 3.0, etc. breaking backwards compatibility once more. Details like when stuff deprecated versus when it actually gets removed are a bridge we can cross when we get to it.

**Comment by Kodiologist** [comment]
And I don't think we'll ever have backwards compatibility on the order of Perl, which is weighted down by its commitment to the past. When I first learned Perl in 2005, `chomp` already existed, so there was no reason to use `chop`. 17 years later, `chop` is still in the latest version of Perl.
