### ISSUE TITLE
Add header notice to "stable" line documentation to point users to the alpha cycle documentation

### ISSUE THREAD

**Issue by fshabashev** [hylang/hy#2219]
I was reading documentation and noticed that hy.contrib.walk is mentioned there:
https://docs.hylang.org/en/stable/contrib/walk.html

however it appears that hy.contrib.walk file is no longer on the master branch. 
https://github.com/hylang/hy/blob/6ba90fd3f853b2ddc391aa3358f9386c41d831c4/hy/contrib/walk.hy

is it a bug in documentation or I'm missing something?

**Comment by fshabashev** [comment]
actually it looks ilke hy.contrib.walk only exists in the 0.20 version

are there any plans to support is for the version 1.0 and beyond?

**Comment by allison-casey** [comment]
you are looking at the "stable" line of the documentation. Hy is in an alpha cycle as we pilot breaking changes that will go into 1.0. In that vein contrib along with a number of other library functions were moved to [hyrule](github.com/hylang/hyrule) to facilitate a more stable, organized language

**Comment by allison-casey** [comment]
I would like to add a header to the stable branch that will point users to the up to date documentation to mitigate this in the future.

**Comment by Kodiologist** [comment]
Decent idea. People looking at the wrong documentation has perpetually been a problem, even after I added the version headers, so some more emphasis is warranted.
