### ISSUE TITLE
`let` doesn't detect assignments in loop clauses of comprehension forms

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2224]
```
=> (let [x 10] (lfor  x (range 5)  :if (> x 1)  x))
[10 10 10 10 10]
```

`hy --spy` shows this compiles to:

```
_hy_let_x_1 = 10
[_hy_let_x_1 for x in range(5) if _hy_let_x_1 > 1]
```

`let` is supposed to allow some kinds of assignments to shadow its own variables, while allowing other kinds to modify its variables, but its treatment of the loop variable seems inconsistent here.

**Comment by allison-casey** [comment]
to my understanding this should compile to 
```python
_hy_let_x_1 = 10
[x for x in range(5) if x > 1]
```
right?
the `x` fromthe `lfor` shadows the `x` from the `let`

**Comment by Kodiologist** [comment]
Maybe.  The manual says:

> Basic assignments (e.g. `setv`, `+=`) will update the local variable named by a let binding when they assign to a let-bound name. But assignments via `import` are always hoisted to normal Python scope, and likewise, `defn` or `defclass` will assign the function or class in the Python scope, even if it shares the name of a let binding. To avoid this hoisting, use `importlib.import_module`, `fn`, or `type` (or whatever metaclass) instead.

I read this as implying that this case should reassign, not shadow.

In general I feel like hoisting might've been a mistake, and it would be both simpler and more useful to always reassign whenever a `let`-variable is in scope.

**Comment by allison-casey** [comment]
I think i'm with clojure on this one. the binding of `x` in the `lfor` is essentially an entirely new binding scope that shadows the parent `let`
```clojure
user=> (let [x 10] (for [x (range 5) :when (> x 1)] x))
(2 3 4)
```
is what i would have expected from Hy as well

**Comment by allison-casey** [comment]
for what it's worth this also seems to be the case in fennel as well
```lisp
>> (let [x 10] 
     (icollect [_ x (ipairs [1 2 3 4])] 
       (when (> x 1)
         x)))
[2 3 4]
```

**Comment by Kodiologist** [comment]
I think you have to do another print outside of the loop to show how Fennel deals with this.

Anyway, the problem with not allowing comprehension forms to modify `let`-variables is that e.g. I can't change `ap-map` to use `let` instead of manual symbol replacement, because `ap-map` assigns `it` with a `gfor` loop clause.
