### ISSUE TITLE
kwargs will not work

### ISSUE THREAD

**Issue by dpavlic** [hylang/hy#2236]
I am trying a kwargs and only kwargs example:

`(defn fake-fn [&kwargs kwargs] (print 1))`

Trying to pass some keyword arguments to this fake function:

`(fake-fn :foo 1 :bar 2)`

Yields:

`fake-fn() got an unexpected keyword argument 'foo'`

Evaluating a bare function leads to:

`fake-fn() missing 2 required positional arguments: 'hyx_XampersandXkwargs' and 'kwargs'`

Hy 1.0a4 using CPython(default) 3.8.9 on Darwin

EDIT: Actually, it appears that none of the ampersand forms work.

**Comment by allison-casey** [comment]
You are looking at the wrong documentation. ampersand forms were changed to more pythonic `#*` and `#**` in the alphas. you can find the documentation for you're version [here](https://docs.hylang.org/en/alpha/index.html)

**Comment by Kodiologist** [comment]
Dang, I was really hoping #2220 would prevent this kind of thing, but evidently not entirely, even if it helps. I guess there's only so much we can do.

**Comment by dpavlic** [comment]
Sorry for wasting time, I did in fact see the warning, but I think at some point I clicked around and found myself in the old docs by accident, definite user error.

**Comment by Kodiologist** [comment]
No big deal. It happens. Let us know if you find a link in the project that should go to one version of the documentation but actually goes to a different version.
