### ISSUE TITLE
`(require hyrule *)` gives `FileNotFoundError` on Windows 10

### ISSUE THREAD

**Issue by ay0ks** [hylang/hy#2238]
### hy -v = `hy 1.0a4+46.gef7a461`

Code:
```hy
(require hyrule *)
(import hyrule [inc])

...
```
Error appears only when using `hy2py`, executing with `hy` gives no errors.

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\hy2py.exe\__main__.py", line 7, in <module>
    sys.exit(hy2py_main())
hy.errors.HyMacroExpansionError:
  File "main.hy", line 1
    (require
  hyrule *)
    ^
expanding macro require
  FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files\\Python310\\Scripts\\hy2py.exe\\__main__.py'
```

**Comment by Kodiologist** [comment]
I can't reproduce this on Linux, but it could be a Windows-specific bug.

Can you reproduce your error in a fresh virtualenv? It's not uncommon for installations of Python packages to be screwy, so that e.g. `hy2py` gets you a different Hy or even a different Python than `hy` does.

**Comment by ay0ks** [comment]
```
C:\Users\i0x\Desktop\std\>pip uninstall hy hyrule
Found existing installation: hy 1.0a4+46.gef7a461
Uninstalling hy-1.0a4+46.gef7a461:
  Would remove:
    c:\program files\python310\get_version\get_version.py
    c:\program files\python310\lib\site-packages\hy-1.0a4+46.gef7a461.dist-info\*
    c:\program files\python310\lib\site-packages\hy\*
    c:\program files\python310\scripts\hy.exe        
    c:\program files\python310\scripts\hy2py.exe     
    c:\program files\python310\scripts\hy2py3.exe    
    c:\program files\python310\scripts\hy3.exe       
    c:\program files\python310\scripts\hyc.exe       
    c:\program files\python310\scripts\hyc3.exe      
Proceed (Y/n)? y
  Successfully uninstalled hy-1.0a4+46.gef7a461
Found existing installation: hyrule 0.0.0
Uninstalling hyrule-0.0.0:
  Would remove:
    c:\program files\python310\lib\site-packages\hyrule-0.0.0.dist-info\*
    c:\program files\python310\lib\site-packages\hyrule\*
Proceed (Y/n)? y 
  Successfully uninstalled hyrule-0.0.0
```
then install it back
```
C:\Users\i0x\Desktop\std>pip install git+https://github.com/hylang/hy                                     
Collecting git+https://github.com/hylang/hy
  Cloning https://github.com/hylang/hy to c:\users\i0x\appdata\local\temp\pip-req-build-q8awipjh
  Running command git clone --filter=blob:none --quiet https://github.com/hylang/hy 'C:\Users\i0x\AppData\Local\Temp\pip-req-build-q8awipjh'
  Resolved https://github.com/hylang/hy to commit ef7a461719c1800022ab016c75f6a81ea7c9f351
  Preparing metadata (setup.py) ... done
Requirement already satisfied: rply>=0.7.7 in c:\program files\python310\lib\site-packages (from hy==1.0a4+46.gef7a461) (0.7.8)
Requirement already satisfied: funcparserlib>=1.0.0a0 in c:\program files\python310\lib\site-packages (from hy==1.0a4+46.gef7a461) (1.0.0a0)
Requirement already satisfied: colorama in c:\program files\python310\lib\site-packages (from hy==1.0a4+46.gef7a461) (0.4.4)
Requirement already satisfied: appdirs in c:\program files\python310\lib\site-packages (from rply>=0.7.7->hy==1.0a4+46.gef7a461) (1.4.4)
Building wheels for collected packages: hy
  Building wheel for hy (setup.py) ... done
  Created wheel for hy: filename=hy-1.0a4+46.gef7a461-py3-none-any.whl size=76430 sha256=715082f8b50c7176ce686dd631fc99e1c617097a5405c6357439548e3eccc493
  Stored in directory: C:\Users\i0x\AppData\Local\Temp\pip-ephem-wheel-cache-b6gojw3l\wheels\15\e0\4c\c9e5417621f8676ea484376806edfbadca81fa1632acaca86a
Successfully built hy
Installing collected packages: hy
Successfully installed hy-1.0a4+46.gef7a461

C:\Users\i0x\Desktop\std>pip install git+https://github.com/hylang/hyrule
Collecting git+https://github.com/hylang/hyrule
  Cloning https://github.com/hylang/hyrule to c:\users\i0x\appdata\local\temp\pip-req-build-hh8isebv
  Running command git clone --filter=blob:none --quiet https://github.com/hylang/hyrule 'C:\Users\i0x\AppData\Local\Temp\pip-req-build-hh8isebv'
  Resolved https://github.com/hylang/hyrule to commit e1fc30e89a1a3a9204fcfbf2b2d03f0a2be11ccb
  Preparing metadata (setup.py) ... done
Collecting hy@ git+https://github.com/hylang/hy@master#egg=hy-1.0
  Cloning https://github.com/hylang/hy (to revision master) to c:\users\i0x\appdata\local\temp\pip-install-890r857t\hy_2f8943d94bfc484a8ac6af4daedd6490
  Running command git clone --filter=blob:none --quiet https://github.com/hylang/hy 'C:\Users\i0x\AppData\Local\Temp\pip-install-890r857t\hy_2f8943d94bfc484a8ac6af4daedd6490'
  Resolved https://github.com/hylang/hy to commit ef7a461719c1800022ab016c75f6a81ea7c9f351
  Preparing metadata (setup.py) ... done
Requirement already satisfied: rply>=0.7.7 in c:\program files\python310\lib\site-packages (from hy@ git+https://github.com/hylang/hy@master#egg=hy-1.0->hyrule==0.0.0) (0.7.8)
Requirement already satisfied: funcparserlib>=1.0.0a0 in c:\program files\python310\lib\site-packages (from hy@ git+https://github.com/hylang/hy@master#egg=hy-1.0->hyrule==0.0.0) (1.0.0a0)
Requirement already satisfied: colorama in c:\program files\python310\lib\site-packages (from hy@ git+https://github.com/hylang/hy@master#egg=hy-1.0->hyrule==0.0.0) (0.4.4)
Requirement already satisfied: appdirs in c:\program files\python310\lib\site-packages (from rply>=0.7.7->hy@ git+https://github.com/hylang/hy@master#egg=hy-1.0->hyrule==0.0.0) (1.4.4)
Building wheels for collected packages: hyrule
  Building wheel for hyrule (setup.py) ... done
  Created wheel for hyrule: filename=hyrule-0.0.0-py3-none-any.whl size=35592 sha256=c7c941532d5317326800f403b5529ce105e188979c892b41dbc5811648fb4d8c
  Stored in directory: C:\Users\i0x\AppData\Local\Temp\pip-ephem-wheel-cache-_9czsgzj\wheels\af\ec\52\198048ef2c45de23b32a4f6de7f77d719c668714c445b208e3
Successfully built hyrule
Installing collected packages: hyrule
Successfully installed hyrule-0.0.0
```

finally
```
C:\Users\i0x\Desktop\std>hy2py main.hy > test.py
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\hy2py.exe\__main__.py", line 7, in <module>
    sys.exit(hy2py_main())
hy.errors.HyMacroExpansionError:
  File "main.hy", line 1
    (require
  hyrule *)
    ^
expanding macro require
  FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files\\Python310\\Scripts\\hy2py.exe\\__main__.py'
```

so the problem only appears on windows, because it works normally on linux (Arch and Android 11)

**Comment by Kodiologist** [comment]
Uninstalling and then installing again doesn't necessarily get you the same thing as a virtualenv, though. I think.

**Comment by ay0ks** [comment]
> Uninstalling and then installing again doesn't necessarily get you the same thing as a virtualenv, though. I think.

okay, i'll try to create virtual env now

**Comment by ay0ks** [comment]
> ```
> C:\Users\i0x\Desktop\std\>pip uninstall hy hyrule
> Found existing installation: hy 1.0a4+46.gef7a461
> Uninstalling hy-1.0a4+46.gef7a461:
>   Would remove:
>     c:\program files\python310\get_version\get_version.py
>     c:\program files\python310\lib\site-packages\hy-1.0a4+46.gef7a461.dist-info\*
>     c:\program files\python310\lib\site-packages\hy\*
>     c:\program files\python310\scripts\hy.exe        
>     c:\program files\python310\scripts\hy2py.exe     
>     c:\program files\python310\scripts\hy2py3.exe    
>     c:\program files\python310\scripts\hy3.exe       
>     c:\program files\python310\scripts\hyc.exe       
>     c:\program files\python310\scripts\hyc3.exe      
> Proceed (Y/n)? y
>   Successfully uninstalled hy-1.0a4+46.gef7a461
> Found existing installation: hyrule 0.0.0
> Uninstalling hyrule-0.0.0:
>   Would remove:
>     c:\program files\python310\lib\site-packages\hyrule-0.0.0.dist-info\*
>     c:\program files\python310\lib\site-packages\hyrule\*
> Proceed (Y/n)? y 
>   Successfully uninstalled hyrule-0.0.0
> ```
> 
> then install it back
> 
> ```
> C:\Users\i0x\Desktop\std>pip install git+https://github.com/hylang/hy                                     
> Collecting git+https://github.com/hylang/hy
>   Cloning https://github.com/hylang/hy to c:\users\i0x\appdata\local\temp\pip-req-build-q8awipjh
>   Running command git clone --filter=blob:none --quiet https://github.com/hylang/hy 'C:\Users\i0x\AppData\Local\Temp\pip-req-build-q8awipjh'
>   Resolved https://github.com/hylang/hy to commit ef7a461719c1800022ab016c75f6a81ea7c9f351
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: rply>=0.7.7 in c:\program files\python310\lib\site-packages (from hy==1.0a4+46.gef7a461) (0.7.8)
> Requirement already satisfied: funcparserlib>=1.0.0a0 in c:\program files\python310\lib\site-packages (from hy==1.0a4+46.gef7a461) (1.0.0a0)
> Requirement already satisfied: colorama in c:\program files\python310\lib\site-packages (from hy==1.0a4+46.gef7a461) (0.4.4)
> Requirement already satisfied: appdirs in c:\program files\python310\lib\site-packages (from rply>=0.7.7->hy==1.0a4+46.gef7a461) (1.4.4)
> Building wheels for collected packages: hy
>   Building wheel for hy (setup.py) ... done
>   Created wheel for hy: filename=hy-1.0a4+46.gef7a461-py3-none-any.whl size=76430 sha256=715082f8b50c7176ce686dd631fc99e1c617097a5405c6357439548e3eccc493
>   Stored in directory: C:\Users\i0x\AppData\Local\Temp\pip-ephem-wheel-cache-b6gojw3l\wheels\15\e0\4c\c9e5417621f8676ea484376806edfbadca81fa1632acaca86a
> Successfully built hy
> Installing collected packages: hy
> Successfully installed hy-1.0a4+46.gef7a461
> 
> C:\Users\i0x\Desktop\std>pip install git+https://github.com/hylang/hyrule
> Collecting git+https://github.com/hylang/hyrule
>   Cloning https://github.com/hylang/hyrule to c:\users\i0x\appdata\local\temp\pip-req-build-hh8isebv
>   Running command git clone --filter=blob:none --quiet https://github.com/hylang/hyrule 'C:\Users\i0x\AppData\Local\Temp\pip-req-build-hh8isebv'
>   Resolved https://github.com/hylang/hyrule to commit e1fc30e89a1a3a9204fcfbf2b2d03f0a2be11ccb
>   Preparing metadata (setup.py) ... done
> Collecting hy@ git+https://github.com/hylang/hy@master#egg=hy-1.0
>   Cloning https://github.com/hylang/hy (to revision master) to c:\users\i0x\appdata\local\temp\pip-install-890r857t\hy_2f8943d94bfc484a8ac6af4daedd6490
>   Running command git clone --filter=blob:none --quiet https://github.com/hylang/hy 'C:\Users\i0x\AppData\Local\Temp\pip-install-890r857t\hy_2f8943d94bfc484a8ac6af4daedd6490'
>   Resolved https://github.com/hylang/hy to commit ef7a461719c1800022ab016c75f6a81ea7c9f351
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: rply>=0.7.7 in c:\program files\python310\lib\site-packages (from hy@ git+https://github.com/hylang/hy@master#egg=hy-1.0->hyrule==0.0.0) (0.7.8)
> Requirement already satisfied: funcparserlib>=1.0.0a0 in c:\program files\python310\lib\site-packages (from hy@ git+https://github.com/hylang/hy@master#egg=hy-1.0->hyrule==0.0.0) (1.0.0a0)
> Requirement already satisfied: colorama in c:\program files\python310\lib\site-packages (from hy@ git+https://github.com/hylang/hy@master#egg=hy-1.0->hyrule==0.0.0) (0.4.4)
> Requirement already satisfied: appdirs in c:\program files\python310\lib\site-packages (from rply>=0.7.7->hy@ git+https://github.com/hylang/hy@master#egg=hy-1.0->hyrule==0.0.0) (1.4.4)
> Building wheels for collected packages: hyrule
>   Building wheel for hyrule (setup.py) ... done
>   Created wheel for hyrule: filename=hyrule-0.0.0-py3-none-any.whl size=35592 sha256=c7c941532d5317326800f403b5529ce105e188979c892b41dbc5811648fb4d8c
>   Stored in directory: C:\Users\i0x\AppData\Local\Temp\pip-ephem-wheel-cache-_9czsgzj\wheels\af\ec\52\198048ef2c45de23b32a4f6de7f77d719c668714c445b208e3
> Successfully built hyrule
> Installing collected packages: hyrule
> Successfully installed hyrule-0.0.0
> ```
> 
> finally
> 
> ```
> C:\Users\i0x\Desktop\std>hy2py main.hy > test.py
> Traceback (most recent call last):
>   File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Program Files\Python310\Scripts\hy2py.exe\__main__.py", line 7, in <module>
>     sys.exit(hy2py_main())
> hy.errors.HyMacroExpansionError:
>   File "main.hy", line 1
>     (require
>   hyrule *)
>     ^
> expanding macro require
>   FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files\\Python310\\Scripts\\hy2py.exe\\__main__.py'
> ```
> 
> so the problem only appears on windows, because it works normally on linux (Arch and Android 11)

arch:
```py
❯ hy2py main.hy
import hy
hy.macros.require('hyrule', None, assignments='ALL', prefix='')
from hyrule import inc

/home/i0x/std/ ············································· 4s
❯```
android 11:
```
❯ hy2py main.hy
import hy
hy.macros.require('hyrule', None, assignments='ALL', prefix='')
from hyrule import inc

~/storage/emulated/0/Download/std/ ························· 4s
❯```
output is identical

**Comment by ay0ks** [comment]
@Kodiologist created virutalenv, same error
```
(venv) C:\Users\i0x\Desktop\std>hy2py main.hy > test.py
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\i0x\Desktop\std\AceAttorney\venv\Scripts\hy2py.exe\__main__.py", line 7, in <module>
    sys.exit(hy2py_main())
hy.errors.HyMacroExpansionError:
  File "main.hy", line 1
    (require
  hyrule *)
    ^
expanding macro require
  FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\i0x\\Desktop\\std\\venv\\Scripts\\hy2py.exe\\__main__.py'
  ``
[venv.zip](https://github.com/hylang/hy/files/8141607/venv.zip)
`

**Comment by Kodiologist** [comment]
Okay, thanks for helping to debug this. I hope to look into it soon.

**Comment by Kodiologist** [comment]
Unfortunately, I failed to reproduce this on a Windows runner for GitHub Actions. My patch to Hyrule is below. You can see the result at https://github.com/Kodiologist/hyrule/actions/runs/1900723341 for however long the artifacts stay up.

Try seeing if you can reproduce the problem with a trivial or simple Hy file that you require, instead of Hyrule. That could at least help eliminate Hyrule as the problem.

```patch
From 3dc978fbcbc56d7077b31cd84a37b5bc4b769ccf Mon Sep 17 00:00:00 2001
From: Kodi Arfer <Kodiologist@users.noreply.github.com>
Date: Fri, 25 Feb 2022 15:47:35 -0500
Subject: [PATCH] win req testing

---
 .github/workflows/tests.yml | 11 ++++++-----
 example.hy                  |  4 ++++
 2 files changed, 10 insertions(+), 5 deletions(-)
 create mode 100644 example.hy

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
index e254baa..1e60e08 100644
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -8,10 +8,11 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python: [3.7, 3.8, 3.9, '3.10', pypy-3.7]
+        os: [windows-latest, ubuntu-latest]
+        python: ['3.10']
 
-    name: ${{ matrix.python }}
-    runs-on: ubuntu-latest
+    name: ${{ format('{0}-{1}', matrix.os, matrix.python) }}
+    runs-on: ${{ matrix.os }}
     env:
       TERM: xterm-256color
         # This is needed to avoid a terminfo-related crash when
@@ -25,5 +26,5 @@ jobs:
     - run: pip install . && rm -r hyrule
         # We want to be sure we're testing the installed version,
         # instead of running from the source tree.
-    - run: pip install pytest
-    - run: pytest
+    - run: hy example.hy
+    - run: hy2py example.hy
diff --git a/example.hy b/example.hy
new file mode 100644
index 0000000..5326c2c
--- /dev/null
+++ b/example.hy
@@ -0,0 +1,4 @@
+(require hyrule *)
+(import hyrule [inc])
+
+(print "Everything's A-OK!")
-- 
2.32.0
```

**Comment by ay0ks** [comment]
> Unfortunately, I failed to reproduce this on a Windows runner for GitHub Actions. My patch to Hyrule is below. You can see the result at https://github.com/Kodiologist/hyrule/actions/runs/1900723341 for however long the artifacts stay up.
> 
> Try seeing if you can reproduce the problem with a trivial or simple Hy file that you require, instead of Hyrule. That could at least help eliminate Hyrule as the problem.
> 
> ```diff
> From 3dc978fbcbc56d7077b31cd84a37b5bc4b769ccf Mon Sep 17 00:00:00 2001
> From: Kodi Arfer <Kodiologist@users.noreply.github.com>
> Date: Fri, 25 Feb 2022 15:47:35 -0500
> Subject: [PATCH] win req testing
> 
> ---
>  .github/workflows/tests.yml | 11 ++++++-----
>  example.hy                  |  4 ++++
>  2 files changed, 10 insertions(+), 5 deletions(-)
>  create mode 100644 example.hy
> 
> diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
> index e254baa..1e60e08 100644
> --- a/.github/workflows/tests.yml
> +++ b/.github/workflows/tests.yml
> @@ -8,10 +8,11 @@ jobs:
>      strategy:
>        fail-fast: false
>        matrix:
> -        python: [3.7, 3.8, 3.9, '3.10', pypy-3.7]
> +        os: [windows-latest, ubuntu-latest]
> +        python: ['3.10']
>  
> -    name: ${{ matrix.python }}
> -    runs-on: ubuntu-latest
> +    name: ${{ format('{0}-{1}', matrix.os, matrix.python) }}
> +    runs-on: ${{ matrix.os }}
>      env:
>        TERM: xterm-256color
>          # This is needed to avoid a terminfo-related crash when
> @@ -25,5 +26,5 @@ jobs:
>      - run: pip install . && rm -r hyrule
>          # We want to be sure we're testing the installed version,
>          # instead of running from the source tree.
> -    - run: pip install pytest
> -    - run: pytest
> +    - run: hy example.hy
> +    - run: hy2py example.hy
> diff --git a/example.hy b/example.hy
> new file mode 100644
> index 0000000..5326c2c
> --- /dev/null
> +++ b/example.hy
> @@ -0,0 +1,4 @@
> +(require hyrule *)
> +(import hyrule [inc])
> +
> +(print "Everything's A-OK!")
> -- 
> 2.32.0
> ```

Already tried `hy2py` on files without `require` and its working, problem appears only when trying to require something

**Comment by Kodiologist** [comment]
Try seeing if you can reproduce the problem with a trivial or simple Hy file that you require, instead of Hyrule. That could at least help eliminate Hyrule as the problem.

**Comment by Kodiologist** [comment]
Since I can't reproduce this, there's no way for debugging to proceed without your continued involvement.
