### ISSUE TITLE
Add support for nix-shell interpreter multiline shebangs?

### ISSUE THREAD

**Issue by shadowrylander** [hylang/hy#2260]
Hello!

This may be useless to a lot of `hy` users, but would it be possible to add support for [nix-shell interpreter multiline shebangs](https://nixos.org/manual/nix/stable/command-ref/nix-shell.html#use-as-a--interpreter)? Such as for the following click script:
```hy
#! /usr/bin/env nix-shell
#! nix-shell -i hy -p python310Packages.hy python310Packages.click
#! nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-21.11.tar.gz

(import click)
#@((.option click "-n" "--name" :help "Your name")
(defn main [name] (print (+ "Hello, " (or name "User") "!")))

(if (= __name__ "__main__") (main))
```

Currently the following error occurs:
```
Traceback (most recent call last):
  File "/nix/store/bv2z3s4zajm452rq0nqlvdqcwmgfqzxs-python3.10-hy-1.0a4/bin/.hy-wrapped", line 9, in <module>
    sys.exit(hy_main())
  File "/nix/store/443qk9752l44kfp8pzsrp0m9jyq6jz2p-python3-3.10.3/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/nix/store/443qk9752l44kfp8pzsrp0m9jyq6jz2p-python3-3.10.3/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/nix/store/443qk9752l44kfp8pzsrp0m9jyq6jz2p-python3-3.10.3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/shadowrylander/test.hy", line 1, in <module>
    #! /usr/bin/env nix-shell
NameError: name 'hyx_Xnumber_signXXexclamation_markX' is not defined
```

Thank you kindly for your consideration on the matter, and sorry for wasting your time if you decide not to!

**Comment by Kodiologist** [comment]
I'm never seen a multiline shebang before. Is it understood by anything other than Nix?

**Comment by shadowrylander** [comment]
As in, are there any other examples of multiline shebangs, or any other programs that can use this format? Because what is happening is that `nix-shell` uses any following lines prefixed with `#!nix-shell` or `#! nix-shell` (note the space in the latter) and uses them as settings; the thing is that since a lot of languages use `#` as the comment syntax, lines prefixed with it are usually ignored. In python this isn't an issue, but `hy` doesn't know what to do with these lines. Would it be possible to create an exception for lines starting with the aforementioned shebangs? So treat `#! nix-shell` or similar as a comment, as well as `#_` and `;`?

**Comment by shadowrylander** [comment]
Sorry if I misunderstood your question, though!

**Comment by Kodiologist** [comment]
> As in, are there any other examples of multiline shebangs

That one.

When I think of how programs try to embed out-of-band information in the source code of other programs, I think of Emacs and Vim settings. Both editors use syntax that can be embedded in whatever the comment syntax of the host program is. Nix seems to have made itself dependent on `#!` being a valid comment, beyond the usual exception for a (single) shebang line. If Nix can recognize its multiline shebangs with other lines intervening, you could at least embed them in a multiline string literal.

**Comment by shadowrylander** [comment]
Hmm... I don't know of any others, no; I also don't think nix can read any other comment syntax... I could theoretically open an issue on their repo, but it seems like a high effort, low reward kind of scenario. Would there be any problems in particular implementing an exception in `hy` itself?

**Comment by Kodiologist** [comment]
No, I think it would be an easy change. You would just remove any number of shebang lines at the beginning instead of only one.

**Comment by shadowrylander** [comment]
Cool! How can I help, if at all? I know nothing of `hy's` internals. 😅

**Comment by Kodiologist** [comment]
I would say wait until #2242 is merged, try changing it, and submit a PR.

**Comment by Kodiologist** [comment]
> I could theoretically open an issue on their repo, but it seems like a high effort, low reward kind of scenario for them

Still, I think you should do this if you use Nix. Hy isn't the only programming language that doesn't use `#` as a comment character, so every language would need to go out of its way to support Nix unless Nix chooses a syntax that can be embedded in the host language's comments.

**Comment by shadowrylander** [comment]
Fair enough; in the meantime, could you point me towards some resources mentioning embedding vim and emacs settings in different languages? What should I search for? "Embedding vim and emacs settings in different languages" seems a little vague.

**Comment by shadowrylander** [comment]
Actually, in the pull request, where `hy/lex/__init__.py` states `# skip shebang`, does it already take care of the issue? Or does that line only skip the first shebang line?

**Comment by Kodiologist** [comment]
For Emacs, see https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html

For Vim, see http://vimdoc.sourceforge.net/htmldoc/options.html#modeline

> Or does that line only skip the first shebang line?

That's right, only the first.

**Comment by allison-casey** [comment]
That only does the first

**Comment by Kodiologist** [comment]
Jinx!

**Comment by shadowrylander** [comment]
@allison-casey @Kodiologist Bah hah hah hah! 😹 So would that technically have to be the only line to change? And would I ignore all lines starting with `#!`, or just lines starting with some variation of `#! nix-shell`? Or do I just tack on something after skipping the first shebang line, without modifying it?

Also, thanks for the references, @Kodiologist! I'll do some reading and get to opening the issue on Nix's repo!

**Comment by allison-casey** [comment]
You would change that to strip out the first consecutive `#!` lines. It should stop as soon as it sees any non shebang line

**Comment by shadowrylander** [comment]
So maybe the following?
```python
while stream.read(2) == "#!":
    stream.readline()
else:
    stream.seek(0)
```

**Comment by allison-casey** [comment]
You would need to track where in the stream you are so that once the condition isn't true anymore you seek backward only those two chars and not go back to the beginning of the stream.

**Comment by shadowrylander** [comment]
But then how does the following work? Are you going back here?
```python
if stream.read(2) == "#!":
    stream.readline()
else:
    stream.seek(0)
```

**Comment by allison-casey** [comment]
Because it's working off the assumption that there's only one shebang at the top of the file so we can just jump back to the beginning if that's not true.

**Comment by shadowrylander** [comment]
Oh, I see; that makes sense. But even then, my example goes back to the beginning of the line the moment it doesn't find a `#!`, with the `else` statement, doesn't it? `stream.readline()` skips the lines if it does, then searches for the next `#!`.

**Comment by shadowrylander** [comment]
Could the following be used, then?
```python
pos = 0
while stream.read(2) == "#!":
    stream.readline()
    pos = stream.tell()
else:
    stream.seek(pos)
```

Then `pos` would be overridden later by the original `pos = stream.tell()`.

**Comment by shadowrylander** [comment]
Ah, quick note: I modified my example to account for the changes in #2242, i.e. ensuring `if` has a second argument, and changing `#@` to `with-decorator`, but the latter doesn't seem to work, giving me the following error:
```
Traceback (most recent call last):
  File "/nix/store/bv2z3s4zajm452rq0nqlvdqcwmgfqzxs-python3.10-hy-1.0a4/bin/.hy-wrapped", line 9, in <module>
    sys.exit(hy_main())
  File "/nix/store/443qk9752l44kfp8pzsrp0m9jyq6jz2p-python3-3.10.3/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/nix/store/443qk9752l44kfp8pzsrp0m9jyq6jz2p-python3-3.10.3/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/nix/store/443qk9752l44kfp8pzsrp0m9jyq6jz2p-python3-3.10.3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/shadowrylander/test-hy/test.hy", line 7, in <module>
    (.option click "-n" "--name" :help "Your name")
TypeError: main() missing 1 required positional argument: 'name'
```

Here's the modified example:
```hy
#! /usr/bin/env nix-shell
#! nix-shell -i hy -p python310Packages.hy python310Packages.click
#! nix-shell -I nixpkgs=/home/shadowrylander/nixpkgs

(import click)
(with-decorator
    (.option click "-n" "--name" :help "Your name")
    (defn main [name] (print (+ "Hello, " (or name "User") "!"))))

(if (= __name__ "__main__") (main) None)
```

**Comment by Kodiologist** [comment]
That doesn't look related to this issue.

**Comment by shadowrylander** [comment]
> Could the following be used, then?
> 
> ```python
> pos = 0
> while stream.read(2) == "#!":
>     stream.readline()
>     pos = stream.tell()
> else:
>     stream.seek(pos)
> ```
> 
> Then `pos` would be overridden later by the original `pos = stream.tell()`.

Right; I tried out the snippet above, and it works perfectly when used with this new test script:
```hy
#! /usr/bin/env nix-shell
#! nix-shell -i hy -p python310Packages.bakery
#! nix-shell -I nixpkgs=/home/shadowrylander/nixpkgs

(import sys [argv])
(del (get argv 0))
(print argv)
```

**Comment by shadowrylander** [comment]
Oh, but related to this, you can use a multiline comment with #!, as nix-shell does not require subsequent shebangs to be right after the first: https://www.reddit.com/r/NixOS/comments/q7ns3l/comment/hgjzr65/?utm_source=share&utm_medium=web2x&context=3

Does this make my changes kinda useless?

**Comment by Kodiologist** [comment]
Hy doesn't have multi-line comments, but string literals (both the double-quoted kind and the bracketed kind) can span multiple lines, so they should suffice for the purpose, if I understand correctly.

**Comment by shadowrylander** [comment]
Fair enough; thanks for all the help! ... Ah, should I still mention the `with-decorator` issue on the pull-request...?

**Comment by allison-casey** [comment]
the `with-decorator` thing is because you forgot to add `click.command` to the decorator. It should be

```clojure
(import click)
(with-decorator
    (click.command)
    (click.option "-n" "--name" :help "Your name")
    (defn main [name]
      (print (+ "Hello, " (or name "User") "!"))))

(when (= __name__ "__main__")
  (main))
```

**Comment by shadowrylander** [comment]
Well that'll teach me not to trust my memory... Thanks for the tip, and sorry for the trouble! 😅

**Comment by allison-casey** [comment]
No worries! Hope you're enjoying Hy! Feel free to ask more questions in discussions if you need anything

**Comment by shadowrylander** [comment]
Will do, and thanks again! 😸
