### ISSUE TITLE
Decorating anonymous functions is inconsistent

### ISSUE THREAD

**Issue by allison-casey** [hylang/hy#2271]
Attempting to decorate an `fn` that can compile down to a `lambda` fails, but it won't fail if the `fn` contains statements that force compilation to an anonymous `def`

```clojure
=> (with-decorator cache (fn [x] x))
Traceback (most recent call last):
  File "stdin-ecb69bbf92e18e5e87b4bc8c6fd3222c5969d4a8", line 1, in <module>
    (with-decorator cache (fn [x] x))
  File "<stdin>", line 1
    (with-decorator cache (fn [x] x))
                          ^
hy.errors.HySyntaxError: Decorated a non-function
```

```clojure
=> (with-decorator cache (fn [x] (print 1) x))
@cache
def _hy_anon_var_2(x):
    print(1)
    return x
_hy_anon_var_2
```

I think it makes the most sense to force the anon `def` when an `fn` uses a decorator like it already does when it contains statements or type annotations.

**Comment by Kodiologist** [comment]
This should be immediately closed by #2270, since there will no longer be a way to decorate a `fn`.

**Comment by allison-casey** [comment]
then it should be noted in NEWS as a breaking change probably

**Comment by Kodiologist** [comment]
I think that's implied by "`with-decorator` and `#@` have been removed in favor of decorator lists (see below)" and the description of decorator lists only mentioning `defn` and `defclass`.
