### ISSUE TITLE
Parsing `^` is weird

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2278]
A wart in the syntax is that `^` marks an annotation unless it's followed by whitespace or `=`. The `^` and `^=` macros are rarely used, so I think it's safe to rename them. Then `^` will only be for annotations. Another option is to use some other syntax for annotation, like `#^`, and let `^` be a regular character.

**Comment by scauligi** [comment]
I'd prefer the `#^` option of the two, so that all the Python operators still translate 1:1.

Alternatively, would it be possible to (ab)use keywords to represent annotations somehow? Since it would map nicely with the Python colon syntax.

**Comment by Kodiologist** [comment]
> so that all the Python operators still translate 1:1

We're still stuck with `=` for `==` and `setv` for `=`. ;_;

> Alternatively, would it be possible to (ab)use keywords to represent annotations somehow?

Not that I can think of. What do you have in mind?

**Comment by scauligi** [comment]
I was thinking something along the lines of `:int` etc, but now that I'm typing this I'm realizing it wouldn't work for anything more complicated (eg `(of list int)`).

I think `#^` works well, since our annotation syntax already works like a reader macro.

**Comment by allison-casey** [comment]
I'd be good with `#^`
