### ISSUE TITLE
Use HyExpressions as shortcut to (get dict "key")

### ISSUE THREAD

**Issue by nicszerman** [hylang/hy#2289]
Right now, you can use symbols to get from dictionaries if the key is a symbol:

```
(setv d {:a 5 "b" 8})
(print (:a d))
```
Prints 5.

But if we want to access "b", we need the longer and super annoying form `(get d "b")`.

```
(print (get d "b"))
```
This is a huge detractor from using Hy vs Python because in python we can easily use
```
print(d["b"])
```
If doing data intensive operations with Panda, for example, calling (get) becomes a pain. A big PAIN. I end up using (pys) frequently when doing data intensive operations.

So I thought, how about we can shortcut (get) similarly to getting symbols from dictionaries:
```
(print (:"a" d))
```

Seems fantastic to me.

**Comment by nicszerman** [comment]
I realized that sometimes you can just use d["b"] in Hy. It would be great to have documentation on when is this acceptable.

**Comment by Kodiologist** [comment]
> ```
> (setv d {:a 5 "b" 8})
> (print (:a d))
> ```
> Prints 5.

No, it doesn't. It's a `KeyError`. `(:a d)` already does `(get d "a")`, which sounds like just what you want.

**Comment by Kodiologist** [comment]
In fact, you'll probably like #2287, which should get merged within a few days.

**Comment by Kodiologist** [comment]
Sorry, I missed this:

> I realized that sometimes you can just use d["b"] in Hy.

`d["b"]` is syntactically legal, but it's not an indexing operation; it's two forms, one of the symbol `d` and one of a singleton list.

**Comment by nicszerman** [comment]
> > ```
> > (setv d {:a 5 "b" 8})
> > (print (:a d))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Prints 5.
> 
> No, it doesn't. It's a `KeyError`. `(:a d)` already does `(get d "a")`, which sounds like just what you want.

In my computer the example works as indicated and your example throws KeyError.

![image](https://user-images.githubusercontent.com/14032356/170288089-a210ff15-f7e3-4f26-a0d6-9d355445d829.png)

**Comment by Kodiologist** [comment]
Then you're running a previous version of Hy, unless something is dreadfully wrong.

**Comment by Kodiologist** [comment]
Yes.

**Comment by Kodiologist** [comment]
Always happy to be of service. ;)
