### ISSUE TITLE
Code read with `hy.read` can't define a reader macro

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2291]
```
=> (hy.eval (hy.read "(defreader r 5)"))
Traceback (most recent call last):
  File "stdin-27f203d5d830092f5be52fd45c79e54c119e57b6", line 1, in <module>
    (hy.eval (hy.read "(defreader r 5)"))
hy.errors.HyEvalError: module 'hy' has no attribute 'hyx_XampersandXreader'
```

#2290 creates a more detailed traceback, but doesn't fix this.

**Comment by scauligi** [comment]
Should we have `hy.&reader` persist through execution then? We can have `hy.eval`/`hy.read` use the current value of `hy.&reader` by default, similar to how they will use the current `global()` dict unless otherwise specified.

Examples of proposed change:
```hy
(hy.eval '(defreader x '4))
#x  ; => yields 4
```
```hy
(hy.eval '(defreader x 4))
(hy.read "#x")  ; => yields '4
```
```hy
(defreader x 4)
(hy.read "#x")  ; => yields '4
```
```hy
(let [my-reader (hy.reader.HyReader)]
  (hy.eval :reader my-reader (hy.read "(defreader x '4)"))
  (hy.eval :reader my-reader (hy.read "#x"))  ; => yields 4
  (hy.eval (hy.read "#x")))  ; => error

**Comment by Kodiologist** [comment]
I think so, but I'm not sure how well that will work when executing a file from bytecode.

**Comment by scauligi** [comment]
Oh hmm, I forgot about that.
I would want something like the third example above to continue working even when run with bytecode, but I'm not sure how to do that without getting hacky (like instantiating a default reader per module). Although it may not be too bad in practice if we do it lazily?

**Comment by Kodiologist** [comment]
@scauligi Could I trouble you to take a crack at this and the related issues #2292 and #2303? I'd like to have these things tied up before Hy 1.0. If you don't have time, I'll probably get to them eventually.

**Comment by scauligi** [comment]
Sure thing, I'll take a crack at it 👍
