### ISSUE TITLE
Threading macro

### ISSUE THREAD

**Issue by ihavenonickname** [hylang/hy#2296]
I was reading [the docs for the `->` macro](https://docs.hylang.org/en/stable/language/api.html#id3). 

When I tried executing the snippet, Hy complained that `->` does not exist.

    Hy 1.0a4 using CPython(tags/v3.10.2:a58ebcc) 3.10.2 on Windows
    => (defn output [a b] (print a b))
    => (-> (+ 4 6) (output 5))
    Traceback (most recent call last):
    File "stdin-d87512cca1bf3201f51e31407536b2d6127abaaf", line 1, in <module>
        (-> (+ 4 6) (output 5))
    NameError: name 'hyx_XhyphenHminusXXgreaterHthan_signX' is not defined

Then, after scratching my head **for quite a while**, I realized that I was reading outdated docs.

I switched to [the docs of alpha version](https://docs.hylang.org/en/alpha/api.html#core-macros) and, to my surprise, I didn't find the `->` macro anymore.

Was the `->` removed? If so, what should I use instead?

**Comment by allison-casey** [comment]
Much of Hy's standard library were moved to their own library, [hyrule](https://hyrule.readthedocs.io/en/master/#hyrule.argmove.-%3E). You can require all of them with `(require hyrule * :readers *)`

**Comment by ihavenonickname** [comment]
@allison-casey 

Sorry, but it doesn't seem to work.

```none
Hy 1.0a4 using CPython(tags/v3.10.2:a58ebcc) 3.10.2 on Windows
=> (require hyrule * :readers *)
Traceback (most recent call last):
  File "stdin-c253313cd27e7967867b9a6d93f88c129090081a", line 1, in <module>
    (require hyrule * :readers *)
  File "<stdin>", line 1
    (require hyrule * :readers *)
                      ^
hy.errors.HySyntaxError: parse error for pattern macro 'require': got unexpected token: :readers, expected: end of input
```


I also tried [`(require hyrule [->])` as suggested in the docs](https://docs.hylang.org/en/alpha/api.html#hy.macroexpand) but it doesn't seem to work too. 

```none
Hy 1.0a4 using CPython(tags/v3.10.2:a58ebcc) 3.10.2 on Windows
=> (require hyrule [->])
Traceback (most recent call last):
  File "stdin-04be959dd8bc7927058278eba9f817a8428d82eb", line 1, in <module>
    (require hyrule [->])
hy.errors.HyRequireError: No module named 'hyrule'
```
