### ISSUE TITLE
Write, the inverse of read

### ISSUE THREAD

**Issue by Zambito1** [hylang/hy#2297]
Sorry if I'm missing something, I really tried searching for this and I couldn't find what I needed. I'm looking for a `write` procedure, which acts as the inverse to `read`.

Here is the behavior I am looking for:

```Lisp
=> (setv x (read))
(+ 2 4)
=> ;; At this point, x is the quoted expression (+ 2 4)
=> (eval x)
6
=> (write x) ;; This will print the exact expression that was previously read.
(+ 2 4)
```

The closest thing that I have found is this:

```Lisp
=> (hy.contrib.pprint.pprint x)
'(+ 2 4)
```

which is not the same of course. The expression is quoted, and if it is directed to `(read)` in another process, it will be doubly quoted. When applying `(eval ''(+ 2 4))` you get a list of `+`, `2`, and `4`. In this case, one could just `eval` again. In other cases where there are intermixed quasiquote and unquotes though, simply evaling again doesn't work as one would want.

Most other Lisp implementations that I have used have this feature (mostly Scheme implementations, but also the few Common Lisp implementations that I have tested). It would be great to have this in Hy.

**Comment by Kodiologist** [comment]
Already implemented as `hy.repr`.

**Comment by Kodiologist** [comment]
`hy.repr` is a different function from `repr`.
