### ISSUE TITLE
Error in `lfor` docs, using `if` instead of `when`.

### ISSUE THREAD

**Issue by nicszerman** [hylang/hy#2313]
The lfor docs contain the following code sample using `if` instead of `when`:

> `:if CONDITION`, which is equivalent to `:do (if (not CONDITION) (continue))`.

![image](https://user-images.githubusercontent.com/14032356/176905967-049d388a-25ff-4d24-bef2-17476454dfb4.png)

**Comment by nicszerman** [comment]
Sounds good, sorry! I'm dyslexic and my special font makes it hard to type code in forms. I'll edit the post to add the text.

**Comment by Kodiologist** [comment]
I often find it more convenient to type in my text editor and paste into a web form than to type into the form.
