### ISSUE TITLE
`__file__` is sometimes missing the directory

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2318]
```sh
$ cd /tmp
$ echo 'print(__file__)' >a.py ; python3 a.py
/tmp/a.py
$ echo '(print __file__)' >b.hy ; hy b.hy
b.hy
```

The variable seems to be set correctly when the file is imported rather than run directly:

```sh
$ hy -c '(import a b) (print a.__file__ b.__file__)'
/tmp/a.py
/tmp/b.hy
/tmp/a.py /tmp/b.hy
```

**Comment by Kodiologist** [comment]
> So theoretically, using it from a pytest fixture, or a hook like `pytest_sessionstart`, should be fine, right?

I don't know, because I don't know how those things are implemented.

> And on another note, would `py / pys` work as a temporary workaround?

I don't think so, but perhaps I misunderstand what you have in mind. Try it and see.

**Comment by shadowrylander** [comment]
Got it.

And also, nope; you're right. Didn't work:
```hy
$ cd /tmp

$ echo '(print __file__)' >a.hy ; hy a.hy

a.hy

$ echo '(print (py "__file__"))' >b.hy ; hy b.hy

b.hy

$ echo '(print (pys "__file__"))' >b.hy ; hy b.hy

None
```

Damnit; thought I was on to something there...
