### ISSUE TITLE
Statements pulled out of `assert` still execute under `python3 -O`

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2319]
```sh
$ echo '(assert (do (print "hi") 1))' >ex.hy
$ python3 -Oc 'import hy, ex'
hi
```

The cause is pretty straightforward: after statements are pulled out of the `assert`, Python doesn't know it's supposed to remove them. This can probably be fixed by guarding the statements with `if __debug__: …`.

**Comment by scauligi** [comment]
Interestingly:
```sh
$ echo '(assert (do (print "hi") 1) "assert message")' >ex.hy
$ python3 -Oc 'import hy, ex'
<no output>
$ python3 -c 'import hy, ex'
hi
```
Running hy2py:
```python
import hy
_hy_anon_var_2 = __debug__
if _hy_anon_var_2:
    print('hi')
    _hy_anon_var_2 = not 1
if _hy_anon_var_2:
    _hy_anon_var_1 = 'assert message'
    assert False, _hy_anon_var_1
    _hy_anon_var_3 = None
else:
    _hy_anon_var_3 = None
```

So we're already (manually) gating on `__debug__` when there's an assert message, but we're not properly encapsulating a message-less `assert`.
