### ISSUE TITLE
`hyc` doesn't require an argument

### ISSUE THREAD

**Issue by rpaulo** [hylang/hy#2322]
Compiling from stdin results in a weird error which seems like hyc is trying to read the file from the disk.

```
% cat > tmp.hy
(import os sys)

% hy tmp.hy

% hyc tmp.hy
Compiling tmp.hy

% hyc - < tmp.hy
[Errno 2] No such file or directory: '(import os sys)'

% hyc < tmp.hy  
[Errno 2] No such file or directory: '(import os sys)'
```

**Comment by rpaulo** [comment]
I guess you're trying to follow the style of python -m py_compile, but the usage string is not clear on what to expect.  Different compilers do different things, for example, C compilers produce `a.out` from stdin when `-o` isn't specified.

**Comment by rpaulo** [comment]
I was expecting it to generate Python code from Hy code.  That said, I don't even know how this is supposed to work because running `hyc myfile.hy` doesn't seem to generate anything at all.

**Comment by Kodiologist** [comment]
Sounds like you actually want `hy2py`, then.

`hyc` should probably just require an argument.

**Comment by Kodiologist** [comment]
The intended behavior for STDIN is indeed to treat each line as a filepath, but that's not too useful (especially since filepaths can theoretically contain newlines). Better just to remove it.
