### ISSUE TITLE
Off-by-1 error in tutorial comment

### ISSUE THREAD

**Issue by Masynchin** [hylang/hy#2323]
https://github.com/hylang/hy/blob/d175c5c7655b6f9343e5e27260d8db5e7b1e2865/docs/tutorial.rst#L77

There is overflow in comment :)

**Comment by Kodiologist** [comment]
That's a pedantic complaint seeing as Python integers are arbitrary-size anyway, but I see your point. This was my line and I should know better.

**Comment by Masynchin** [comment]
> That's a pedantic complaint seeing as Python integers are arbitrary-size anyway, but I see your point. This was my line and I should know better.

Nah, I just nerding here 🤓. Example will loose its simplicity if will be changed.
