### ISSUE TITLE
Python statements are executed unconditionally

### ISSUE THREAD

**Issue by joehakimrahme** [hylang/hy#233]
When translating a Hy expression into a Python statement (`print`, `yield`, ...), it gets executed unconditionally. For instance:

``` clj
=> (and False (do (print "hello") True))
hello
False
```

More info can be found in [this discussion](https://github.com/hylang/hy/pull/222#discussion_r5041876).

**Comment by kirbyfan64** [comment]
How the heck did this get closed? @Kodiologist showed other manifestations of this issue that #824 did NOT solve. :(

**Comment by Kodiologist** [comment]
Yep, it should stay open, in my opinion. Or maybe we should make new issues for each operator or function that exhibits this problem, if they're going to have to be dealt with piecemeal.

**Comment by kirbyfan64** [comment]
@Kodiologist Well, your second example isn't really an issue; you're supposed to use `(setv y (assoc l (f 0) "A"))`.

**Comment by kirbyfan64** [comment]
So I think the main issue remaining is just that the mutating operators (`+=`, `-=`, etc.) need to return a value.

**Comment by Foxboron** [comment]
I got no idea how this was closed. I believe github auto-closed this when i merged the PR

**Comment by gilch** [comment]
Even if `assoc` is a better alternative, double-calling the function *is* unexpected. I wonder if this can happen in other cases.

**Comment by gilch** [comment]
@kirbyfan64 the mutating operators returning values seems like a separate issue from unexpected execution of statements in this issue. If you want to open a new issue for that we can all discuss it, but I think implementing this correctly is going to be more trouble than it's worth.

**Comment by Kodiologist** [comment]
Now that `setv` returns `None`, we probably don't want the mutating operators to be any different, anyway.
