### ISSUE TITLE
GUI based internals debugger

### ISSUE THREAD

**Issue by paultag** [hylang/hy#234]
Allow for a curses base debugger that allows debugging of Hy code via an interactive pane-based explorer -- allow "stepping" through Hy code, and highlighting portions of HST, AST and Python that relate to the segment. Perhaps also show macros that've touched the code.

I plan to replace hy2py with this. Branch @ paultag/hy/paultag/refactor/debugging

**Comment by Kodiologist** [comment]
This is probably outside the scope of Hy itself at this point. Maybe if someone decides to make it, they can add any necessary support code to Hy.
