### ISSUE TITLE
Hy code formatter

### ISSUE THREAD

**Issue by James4Ever0** [hylang/hy#2357]
The default code formatter for hy is missing.

Extract ast from hy code then reconstruct expressions in place seems to be feasible?

**Comment by James4Ever0** [comment]
Or use hy parser to verify its legitimacy then use my modified version of nelean to format the code?

**Comment by James4Ever0** [comment]
I'm not sure whether it works on all cases. It's just a temporary workaround.

**Comment by James4Ever0** [comment]
Hyrule works for objects, but it does not work on hy expressions, nor against raw hy source code.

**Comment by Kodiologist** [comment]
You need to call `hy.read` first on source-code text to get `hy.model.Object`s out of it.

**Comment by James4Ever0** [comment]
```hy
(setv source #[[(try (+ 1 1) (except [SystemExit] (raise)) (except [] "mySignature" (import traceback) (traceback.print_exc) (print "just some error let's keep going") "USE THIS VALUE INSTEAD"))]])
(setv expression (hy.read source))
(import hyrule)
(print (hyrule.pprint expression))
```

**Comment by Kodiologist** [comment]
If you want help, you need to be more specific than "it does not work".

**Comment by James4Ever0** [comment]
There will be more to be concerned about to build such a formatter for hy. String literals may need to be checked if containing some unquoted double quote signs before converting back to source code if using the "ast -> source" approach.

**Comment by Kodiologist** [comment]
Already implemented:

```
=> (import hyrule)
=> (hyrule.pprint #[[hello " world]])
"hello \" world"
```

**Comment by James4Ever0** [comment]
This pretty print module is useful for string quoting and reconstruction.
My "nelean" formatter is for formatting raw hy source code. It is currently patched and able to handle more cases including `#[[hello " world]]` within source code.

**Comment by Kodiologist** [comment]
Well, since you have no specific limitations of `pprint` to report, and you're already working on something else that you feel will better meet your needs, I don't think there's anything for Hy to do here.

**Comment by James4Ever0** [comment]
Maybe there's something hy can do. My formatter is not taking the ast approach. May fail on some cases.

**Comment by James4Ever0** [comment]
Lisp-like languages generally lack good source code formatters, not as good as black for python.

**Comment by James4Ever0** [comment]
Use `hy.reader.HyReader` for extracting comments from source code, better than regular expression alone.

**Comment by James4Ever0** [comment]
I notice that hy source code files in hy like `hy/core_repl.hy` are formatted in some way. I also fail to find a proper source code formatter for hy since this is a lisp dialect, not common lisp.

I wonder if formatting for these files are done by hand or by some tool or emacs plugin?

**Comment by Kodiologist** [comment]
I've already said why I think there's nothing to do here.
