### ISSUE TITLE
Small docstring mismatch in multiplication

### ISSUE THREAD

**Issue by nagy** [hylang/hy#2359]
In `pyops.hy` it reads:

```hy
(defop * [#* args]
  ["multiplication"
    :nullary "0"
    :unary "x"]
...
```

I am sure, it is supposed to read:

```hy
(defop * [#* args]
  ["multiplication"
    :nullary "1"
    :unary "x"]
...
```

**Comment by Kodiologist** [comment]
Quite so. I also notice that the module docstring is missing from the Read the Docs version even though it appears when I build the documentation locally.
