### ISSUE TITLE
f() got an unexpected keyword argument / not possible to pass keywords as arguments rather than a key

### ISSUE THREAD

**Issue by jleonard-r7** [hylang/hy#2364]
```
=> (defn f [#* args] (print args))
def f(*args):
    return print(args)
None
=> (f "a" "b")
f('a', 'b')
('a', 'b')
=> (f :a "b")
f(a='b')
Traceback (most recent call last):
  File "stdin-5404a66b2035f16881a04eb448f8c6092581159d", line 1, in <module>
    (f :a "b")
TypeError: f() got an unexpected keyword argument 'a'
=> 
=> 
=> (f :a :b)
f(a=hy.models.Keyword('b'))
Traceback (most recent call last):
  File "stdin-560f1d6781f7a14e3c73d89efc49924482d5b6c3", line 1, in <module>
    (f :a :b)
TypeError: f() got an unexpected keyword argument 'a'
```

**Comment by Kodiologist** [comment]
This is the intended behavior. See https://docs.hylang.org/en/master/syntax.html#keywords

**Comment by jleonard-r7** [comment]
Oh, I was under no delusion that it was unintentional. However, it is a pretty clear blemish on the language no? Doesn't it deserve a nice, elegant treatment somehow? Perhaps thinking more deeply and clearly about unintended consequences of language design choices?

**Comment by jleonard-r7** [comment]
FWIW if the argument is "but Python uses strings for keywords" (which it seems to be), one could always have the equivalent of clj->js & js->clj as in clojurescript to do the conversions back and forth when interoperating with the host language.

**Comment by Kodiologist** [comment]
It doesn't seem like a blemish to me. Like, I think the design here is fine. Do you have any specific changes to propose? Perhaps you're thinking that Hy should be able to autodetect how to call `f`, but Python is a dynamic langauge and so Hy can't tell what `f`'s signature is at compile-time.

**Comment by jleonard-r7** [comment]
No, my preference would be to follow the example of ClojureScript. Allow liberal use of keywords (anywhere, as values, keys, etc etc) inside Hy itself but provide the conversion macros for interop with the host language.

**Comment by Kodiologist** [comment]
I don't speak Clojure(Script), but I can tell you that Hy already allows using keywords all over the place. It's just usually not going to make your life easier than using a string. You can convert a keyword to a string, but you use the attribute `.name` to do it instead of a macro.

**Comment by jleonard-r7** [comment]
The whole point of this bug is that Hy does not actually allow keywords as positional arguments to a function-- only as keys to keyword arguments to such. If one were going to implement `dissoc` for example and was using internally all keyword keys, it would not work.

See: https://clojuredocs.org/clojure.core/dissoc

[`cljs->js`](https://cljs.github.io/api/cljs.core/clj-GTjs) does not convert a single key but rather stringifies all keyword keys (recursively throughout an arbitrarily deep nested map of maps). [`js->clj`](https://cljs.github.io/api/cljs.core/js-GTclj) the opposite when its `:keywordize-keys` optional argument is set to true.

This is my implementation of `dissoc` in Hy:
```
(defn dissoc [d #* keys]
  (dict
    (mapcat
      (fn [i]
        (if (in (get i 0) keys) [] [i]))
      (.items d))))
```

And the argument for using keywords in Lisps and Clojure is the same as the argument for using symbols in Ruby (quote below from chat.openai.com, but proofread and fact-checked by myself):

"Ruby uses symbols to represent unique, immutable objects. This means that each time a symbol is used in a program, it refers to the same object, rather than creating a new one. This can be useful for things like keys in a hash, where you want to use the same object every time a specific value is needed. Symbols are also often used as names for methods, since they are more efficient than strings in this context. Overall, symbols can help make Ruby programs more efficient and easy to read."

I would add to this explanation that editors typically color them differently so they stand out visually (in addition to the leading colons being easier on the eyes than double quotes).

**Comment by jleonard-r7** [comment]
And another explanation specifically in regards to Common Lisp:

"There are a few reasons why it is generally preferable to use keywords instead of strings in Common Lisp:

Keywords are more concise and easier to read than strings. Because keywords are denoted using a colon (:) followed by the keyword itself, they take up less space in the code and are more immediately recognizable as special forms or functions.

Keywords are evaluated more efficiently than strings. When the Common Lisp interpreter encounters a keyword, it can immediately identify it as a special form or function and evaluate it accordingly. In contrast, if a string is used instead of a keyword, the interpreter would need to first parse the string and then determine what it represents, which is a more computationally expensive operation.

Keywords provide a more predictable and consistent way to identify special forms and functions. Because keywords are standardized and have well-defined meanings, using them makes it easier to write code that is predictable and easy to understand. In contrast, using strings for this purpose can lead to confusion and errors, because the meaning of a particular string may not be immediately clear to the reader of the code."

**Comment by Kodiologist** [comment]
> Hy does not actually allow keywords as positional arguments to a function

It does, provided you quote the keyword. Otherwise Hy thinks you're trying to set a keyword argument.

I still don't understand what change to Hy you're proposing, if any. You gotta be specific if you want me to help you.

**Comment by jleonard-r7** [comment]
Oh, well there you go. I guess quoting the keyword argument is my fix. No change to the language is necessary. Thanks!

**Comment by jleonard-r7** [comment]
(sorry I didn't gather that from the documentation you linked previously). 

Works like a charm:
```
=> (dissoc {:a :b :c :d} ':a)
dissoc({hy.models.Keyword('a'): hy.models.Keyword('b'), hy.models.Keyword('c'): hy.models.Keyword('d')}, hy.models.Keyword('a'))
{:c :d}
```
