### ISSUE TITLE
consider the following implementations of useful clojure functions for inclusion in the hy std library

### ISSUE THREAD

**Issue by jleonard-r7** [hylang/hy#2365]
I can create a PR for these if there is interest. 

```
(defn identity [x] x)

(defn concat [seqs]
  (itertools.chain.from_iterable seqs))

(defn mapcat [f seq]
  (concat (map f seq)))

(defn first [seq]
  (if (> (len seq) 0)
    (get seq 0)
    None))

(defn rest [seq]
  (cut seq 1 (len seq)))

(defn apply [f args]
  (if (= 0 (len args))
      (f)
      (apply (functools.partial f (first args)) (rest args))))

(defn merge [#* dicts]
  (dict (mapcat (fn [d] (.items d)) dicts)))

(defn dissoc [d #* keys]
  (dict
    (mapcat
      (fn [i]
        (if (in (get i 0) keys) [] [i]))
      (.items d))))
```

**Comment by Kodiologist** [comment]
Many of these functions used to be in this repository, but were either moved to Hyrule or deleted because they were already available in other libraries, like `toolz`. See NEWS.

**Comment by jleonard-r7** [comment]
Yea, I pulled concat and mapcat from toolz. It was just easier for me to reimplement them for my purposes in this simple script rather than having to figure out how to deal with dependencies, pip, setup.py, virtualenv, or whatever the latest and greatest jazz is in the world of python dependencies.

**Comment by Kodiologist** [comment]
I feel you—Python packaging is a mess—but the road to Hy 1.0 has been long enough without trying to keep extra stuff not needed for the core language in the same package. That's why I made Hyrule.

**Comment by jleonard-r7** [comment]
Is there any guide or best practices for using dependencies with hy (or would it just be whatever the state of the art is for Python proper)?

**Comment by Kodiologist** [comment]
> or would it just be whatever the state of the art is for Python proper

Yeah, there isn't really anything that Hy changes in how Python manages dependencies.
