### ISSUE TITLE
[FR] Implement equivalence of `(in-package)` in Common Lisp

### ISSUE THREAD

**Issue by glyh** [hylang/hy#2393]
Implement equivalence of `(in-package)` in Common Lisp, so it's easier for downstream IDE writer to integrate hy to their IDE.
`in-package` cause the environment be aware that it's in some package, when called from REPL. Hy is not capable of this because Python is not capable of this. But it's definitely useful for debugging purpose/integration.

**Comment by Kodiologist** [comment]
You mean like this?

```
(setv outer 5)
(.run (hy.REPL :locals (globals)))
Hy 0.25.0+116.g70f549b4 using CPython(main) 3.10.7 on Linux
=> outer
5
```

**Comment by glyh** [comment]
So this is a thing when I try this with a interactive development envrionment:
```hy
(import abc.def [d])
```
where `abc` is the current package I am working on. But it seems like hy is unaware that I'm in a package, it tells me there's no such module as `abc`.

**Comment by Kodiologist** [comment]
Give a complete, minimal, reproducible example.

**Comment by glyh** [comment]
Well, this have to be the way, if you read a bit on [how hy client is implemented](https://github.com/Olical/conjure/blob/master/fnl/conjure/client/hy/stdio.fnl) in conjure. 

To reproduce this, install neovim with conjure, and create any hy package(e.g. with [my template](https://github.com/glyh/new-hy-package) ), and then create two source file where one import stuff from another. Evaluate the work in the importer, the imported will be treated as non-exist.

That is a thing because we're using stdio and it's unaware of the existence of any package. So I said it would be good if there's any kind of facility like common-lisp's `in-package`

**Comment by Kodiologist** [comment]
If you can't reproduce your problem without Neovim and Clojure, you need concrete evidence that Hy is the problem and not Neovim or Clojure or the Hy client for Clojure or whatever if you want me to help you. I'm not familiar with any of those things.

**Comment by glyh** [comment]
This is an FR, I'm talking about something is missing. Not really a bug. Sorry if my explanation is unclear.

**Comment by Kodiologist** [comment]
Python has a lot of flexibility in how variable search happens, which Hy inherits, so I'm reasonably sure that whatever thing you want to do is already possible with Hy, but without a concrete example of what you want Hy to do, I can't show you how.

**Comment by glyh** [comment]
Okay, I want to change __module__ and __file__, how do you do that?

**Comment by Kodiologist** [comment]
```
(setv __file__ "my file")
(setv function.__module__ "my module")
```

**Comment by glyh** [comment]
I don't think that's gonna work, but I think I found an workaround by setting sys.path. Thank you anyway.
Also my description is a bit vague, setting the file and module by it own can't actually make a program behave as if it's in the file...

**Comment by glyh** [comment]
I'm gonna close this cause I found a workaround.
