### ISSUE TITLE
Remove color

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2396]
Does anybody actually use colored models or colored error messages? I bet not. They've been disabled by default for a bit over 4 years now, and they're the sole reason for having one of our dependencies, `colorama`. If nobody objects, let's remove these slightly silly features.

**Comment by Kodiologist** [comment]
If we end up keeping them after all, then at least we should remove `colorama` as a hard dependency, and only import it when color is enabled.

**Comment by danieltanfh95** [comment]
We can just remove it and point people to https://github.com/staticshock/colored-traceback.py instead

**Comment by Kodiologist** [comment]
But that colors Python syntax, not Hy syntax, right?

**Comment by danieltanfh95** [comment]
> But that colors Python syntax, not Hy syntax, right?

It colors Python Tracebacks, which should function similarly for Hy?
