### ISSUE TITLE
Tracebacks in a file with a shebang point to the wrong line

### ISSUE THREAD

**Issue by glyh** [hylang/hy#2405]
```hy
#!/usr/bin/env hy
;; wow
(raise Exception)
;; nothing
```

```
$ hy test.hy
Traceback (most recent call last):
  File "/home/lyh/.local/bin/hy", line 8, in <module>
    sys.exit(hy_main())
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/a.hy", line 2, in <module>
    ;; wow
Exception
```

**Comment by glyh** [comment]
I can't reproduce this in python so it has to be a hy bug.

**Comment by Kodiologist** [comment]
Good catch. You're getting better.

**Comment by Kodiologist** [comment]
The best way to fix this may be to change how `self._pos` is initialized in `hy.reader.reader.Reader._set_source`. It's [currently](https://github.com/hylang/hy/blob/ca9db459b1a8d04a878d48d4e79ddd6e12a43233/hy/reader/reader.py#L81) set to `(1, 0)` unconditionally. It ought to account for when `stream` isn't actually positioned at the start of the file, as in the case of a shebang.
