### ISSUE TITLE
`hy.M` sugar for import on demand

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2416]
It's annoying to have to import to a gensym when you want to use a function from another module in a macro expansion. Suppose you could say `(hy.M.math.sqrt 2)` to call `math.sqrt` without actually binding `math` or `math.sqrt` to some name in the local scope. In addition to making macros neater, this could be convenient as a general shorthand for using something from a module, particularly a module with a long name, without having to add a separate `import` form.

To get a module whose name itself has dots, one could use `/` instead of the dots, so `(hy.M.foo/bar/baz.bing)` would work like `(import foo.bar.baz) (foo.bar.baz.bing)`.

Here's a simple implementation:

```python
import hy

class M:
    def __call__(self, module_name):
        import importlib
        return importlib.import_module(module_name)
    def __getattr__(self, s):
        return self('.'.join(hy.unmangle(s).split('/')))

hy.M = M()
hy.eval(hy.read_many('''
(print hy.M.sklearn/neighbors.KNeighborsRegressor)
'''))
```

The nice thing about this feature is that it can be added without changing Hy's syntax or touching the set of core macros.

`__call__` is provided so you can also say `(hy.M "foo.bar.baz")` to get the module `foo.bar.baz`, which may be more convenient when the module name isn't known until runtime.

This sort of feature could probably be provided for requiring macros, too.

**Comment by scauligi** [comment]
Ooh I like this idea, but the syntax feels clunky; perhaps we could instead have it as a reader macro?

For example:
```hy
(#module:math/sqrt 2)
(#module:foo.bar.baz/bing)
(print #module:some.submod/CONSTANT)
(type #module:re) ; -> ModuleType
```

We could swap `.` and `/` and `:` with other things; these were just my personal preferences (and we should be able to use `.` like this in a reader macro).
Probably also want to call `#module` something else.

As an aside, wouldn't `(hy.M module-name)` be the same thing as `(importlib.import-module module-name)`?
