### ISSUE TITLE
Use pyproject.toml instead of setup.py

### ISSUE THREAD

**Issue by jbutcher5** [hylang/hy#2432]
The 'setup.py install' method is deprecated. It would be nice to use the more modern 'pyproject.toml' approach however I am unsure if there is some kind of requirement that Hy uses this method or some reason it hasn't already been updated. This PEP details the reasons for the shift in how packaging is done. https://peps.python.org/pep-0517/

**Comment by Kodiologist** [comment]
Sorry, I forgot this:

> The 'setup.py install' method is deprecated.

I think `python setup.py install` may be deprecated, but there are no plans to remove `pip install .` with a `setup.py`. Please correct me if not.

**Comment by jbutcher5** [comment]
> Sorry, I forgot this:
> 
> > The 'setup.py install' method is deprecated.
> 
> I think `python setup.py install` may be deprecated, but there are no plans to remove `pip install .` with a `setup.py`. Please correct me if not.

You are correct by the looks of it. I was just asking about this because I received the following when I installed Hy.
```
$ pip install hy
Defaulting to user installation because normal site-packages is not writeable
Collecting hy
  Using cached hy-0.26.0.tar.gz (99 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: funcparserlib~=1.0 in ./.local/lib/python3.11/site-packages (from hy) (1.0.1)
Installing collected packages: hy
  DEPRECATION: hy is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for hy ... done
Successfully installed hy-0.26.0
```

**Comment by Kodiologist** [comment]
I guess the `wheel` package is required to get the expected behavior, strictly speaking? Weird.

**Comment by Kodiologist** [comment]
I tried changing the `pip install .` in the GitHub Action workflow to `pip install . --use-pep517`. All tests pass except for some cases of `test_bin.py` on Windows. It sounds like pip 23.1 is supposed to be released this month, and is going to make something like `--use-pep517` the default, but some details are yet to be decided. Let's just wait and see what happens.

**Comment by Kodiologist** [comment]
All tests pass with pip 23.1.2, so you should no longer see the warning with the latest pip and everything should be good.
