### ISSUE TITLE
Execute scripts provided through standard input

### ISSUE THREAD

**Issue by nagy** [hylang/hy#2438]
In Python, we get a very clean output when we pass commands via stdin/shell redirection:

```sh
$ python <<< 'print(123)'
123
$
```

In Hy, it is a bit more cluttered:

```sh
$ hy <<< '(print 123)'
Hy 0.26.0 using CPython(main) 3.10.11 on Linux
=> 123
=>
now exiting REPL...
$
```

I would argue, that we should clean up the output to be equal to the one of python.

Maybe this can help with that:

https://docs.python.org/3/library/os.html#os.isatty

**Comment by Kodiologist** [comment]
I'm actually not sure what Python is doing here. For example, `echo '1\n2\n3\n' | python3` prints nothing. I guess Python doesn't launch its own REPL in some circumstances even when it's called without arguments, perhaps from checking whether standard input is a TTY, as you suggest.

**Comment by nagy** [comment]
> I'm actually not sure what Python is doing here. For example, echo '1\n2\n3\n' | python3 prints nothing.

If you wrap the values in a print call it prints something: 

```sh
$ echo -e 'print(1)\nprint(2)\nprint(3)\n' | python3
1
2
3
$
```
So it just does not print every evaluated value.

**Comment by nagy** [comment]
Just as a side note, if you want to run these short python snippets without having to wrap them in print calls, you can use something like this: https://github.com/hauntsaninja/pyp

**Comment by Kodiologist** [comment]
Yeah, [here it is](https://docs.python.org/3/using/cmdline.html#interface-options):

> - When called with standard input connected to a tty device, it prompts for commands and executes them until an EOF (an end-of-file character, you can produce that with `Ctrl-D` on UNIX or `Ctrl-Z, Enter` on Windows) is read.
> - When called with a file name argument or with a file as standard input, it reads and executes a script from that file.

So to get CPython-like behavior, we need to check that standard input is a TTY and only then start the REPL, otherwise executing the input as a script in the fashion of `hy scriptname.hy`.

This page also calls my attention to a feature I'd never heard of but that we should perhaps check we support, too, namely, using a directory or ZIP file as a script argument:

> `<script>` - Execute the Python code contained in *script*, which must be a filesystem path (absolute or relative) referring to either a Python file, a directory containing a `__main__.py` file, or a zipfile containing a `__main__.py` file.
