### ISSUE TITLE
Support Python 3.12's new features for type parameters

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2446]
See [PEP 695](https://peps.python.org/pep-0695/).

**Comment by Kodiologist** [comment]
[At the AST level](https://peps.python.org/pep-0695/#ast-changes), there are three changes we need to support:

- The `type_params` attribute of `FunctionDef` (Hy core macros `defn`, `defn/a`, `fn`, `fn/a`)
- The `type_params` attribute of `ClassDef` (Hy core macro `defclass`)
- The node type `TypeAlias` (probably requires a new Hy core macro)

I propose the following syntax:

```
(defn [Decorator1 Decorator2] #^ int fun-name (tp T1 T2) [p1 p2 …]
  body…)
(fn #^ int (tp T1 T2) [p1 p2 …]
  body…)
(defclass [Decorator1 Decorator2] ClassName (tp T1 T2) [Base1 Base2]
  body…)
(deftype AliasName (tp T1 T2) rvalue)
```

A more complex `tp` form would look like:

```
(tp A B #* C #** D #* E F)
```

I chose the name `tp` to be short yet mnemonic; it stands for "type parameter". Other options in place of `(tp T1 T2)` include `(T1 T2)`, `#(T1 T2)`, and `{T1 T2}`, but a more legible syntax for an obscure feature like this one seems appropriate to me. We don't actually need a macro named `tp`, although we do need a macro `deftype`. We probably don't want to name that macro `type` because then it would shadow the built-in Python function `type`.

Any objections?

**Comment by scauligi** [comment]
Hmm, if we use a macro form, I think we should use a more verbose name than `tp`, since it fits with names such as `annotate` and `unpack-iterable`; then (like `annotate`) we could have a reader macro for convenience if it makes sense.

I'm not totally clear how your `tp` examples translate to Python. Do your examples include type constraints? Or would those be handled using  `annotate`/`#^` within the `tp` form?

I also think the name being parametrized should be inside the macro form as well, since conceptually we're parametrizing that type name (c.f. `annotate`, `of`).

**Comment by Kodiologist** [comment]
You keep saying "the macro form", but I'm saying that `tp` doesn't need to be a macro. It would only be recognized in these specific positions in calls to certain core macros, where no macro calls are allowed. That's why it might as well be short: it won't pollute any namespaces.

> I'm not totally clear how your `tp` examples translate to Python.

Like this:

```
@Decorator1
@Decorator2
def fun_name[T1, T2](p1, p2, …) -> int:
   body…

@Decorator1
@Decorator2
class ClassName[T1, T2](Base1, Base2):
    body…

type AliasName[T1, T2] = rvalue
```

> Do your examples include type constraints?

No.

> Or would those be handled using `annotate`/`#^` within the `tp` form?

Right, that should work without any explicit support. I think.

> I also think the name being parametrized should be inside the macro form as well, since conceptually we're parametrizing that type name (c.f. `annotate`, `of`).

You mean like this?

```
(defn [Decorator1 Decorator2] #^ int (tp fun-name T1 T2) [p1 p2 …]
  body…)
```

To me it seems both less visually clear and harder to write a model pattern for (because of it will compete with the nesting of `annotate`), but I can probably do it if you're sure.

**Comment by scauligi** [comment]
Ahh ok, I understand what you mean now about not making it a macro form. Yeah in that case we don't need the name inside the form as well.
So if it's a form that's only found in these specific cases, then maybe we could make it a keyword? Kind of like how we have keyword parameters for `require`:
```hy
(defn [Dec1 Dec2] :tp [T1 T2] #^ int fun-name [p1 p2]
  body...)
```
This also lets us put the type parameters before the return type annotation for functions, which makes things like this make more sense:
```hy
;; def foo[T](...) -> T: ...
(defn :tp [T] #^ T foo [...] ...)
```

Correspondingly,
```hy
(fn :tp [T1 T2] #^ int [p1 p2 …]
  body…)
(defclass [Decorator1 Decorator2] :tp [T1 T2] ClassName [Base1 Base2]
  body…)
(deftype :tp [T1 T2] AliasName rvalue)
```

```hy
```

**Comment by Kodiologist** [comment]
That seems reasonable.

**Comment by Kodiologist** [comment]
I'm working on this. It's just been slow going.
