### ISSUE TITLE
`hy.exe` is not found

### ISSUE THREAD

**Issue by goyalyashpal** [hylang/hy#2460]
1. On installing `hy` via `pip install hy` or `pip install hy --user`, it seems that the binary `hy.exe` is nowhere there. 
2. And hence running `hy` in the commandline gives error of `hy: command not found`
3. It should have been present in the directory of `Python\Python311\Scripts\`

And as there's no executable in the first place, it's not an issue of not belonging in paths.

```console
> hy
'hy' is not recognized as an internal or external command, operable program or batch file.
```

```console
> pip install -U hy
Requirement already satisfied: hy in d:\programfiles\python\python311\lib\site-packages (0.26.0)
Requirement already satisfied: funcparserlib~=1.0 in d:\programfiles\python\python311\lib\site-packages (from hy) (1.0.1)
```

### Reproduction records:

* This issue was earlier also reported in 2023.02.26 by GiorgosCham with Python 3.11.2 at https://github.com/hylang/hy/discussions/2418#discussioncomment-5114252
* Though people did report having `hy.exe` upto atleast as far back as 2017.03.12 in https://github.com/hylang/hy/issues/1251#issuecomment-285897182 with `python 2.7`  and `hy 0.12.1`

### Environment

* OS: windows 10 22H2
* python: 3.11.2
* pip: 23.1.2
* hy: 0.26.0

**Comment by goyalyashpal** [comment]
Maybe check (for myself:) 
* #1022

**Comment by Kodiologist** [comment]
I couldn't reproduce this. Today I updated my Windows 11 installation (to 10.0.22621 Build 22621), installed Python 3.11.4 via python.org's Windows installer (64-bit; https://www.python.org/ftp/python/3.11.4/python-3.11.4-amd64.exe), and ran `pip3 install --user hy` in `cmd.exe`. The output included `WARNING: The scripts hy.exe, hy2py.exe and hyc.exe are installed in 'C:\Users\Kodi\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.` Sure enough, calling `C:\Users\Kodi\AppData\Roaming\Python\Python311\Scripts\hy.exe` in `cmd.exe` works.

Are you sure that it's not the case that `hy.exe` was correctly installed on your system, but isn't in your `PATH`? Try `pip show -f hy`.

**Comment by goyalyashpal** [comment]
> Try `pip show -f hy`

<details><summary>Here:</summary>

<br/>

```console
$ pip show -f hy
Name: hy
Version: 0.26.0
Summary: A Lisp dialect embedded in Python
Home-page: http://hylang.org/
Author: Paul Tagliamonte
Author-email: tag@pault.ag
License: Expat
Location: D:\ProgramFiles\Python\Python311\Lib\site-packages
Requires: funcparserlib
Required-by: 
Files:
  hy-0.26.0.data\data\get_version\get_version.py
  hy-0.26.0.dist-info\AUTHORS
  hy-0.26.0.dist-info\LICENSE
  hy-0.26.0.dist-info\METADATA
  hy-0.26.0.dist-info\RECORD
  hy-0.26.0.dist-info\WHEEL
  hy-0.26.0.dist-info\entry_points.txt
  hy-0.26.0.dist-info\top_level.txt
  hy\__init__.py
  hy\__main__.py
  hy\__pycache__\pyops.cpython-311.pyc       
  hy\__pycache__\reserved.cpython-311.pyc    
  hy\_compat.py
  hy\cmdline.py
  hy\compiler.py
  hy\completer.py
  hy\core\__init__.py
  hy\core\__pycache__\hy_repr.cpython-311.pyc
  hy\core\__pycache__\macros.cpython-311.pyc 
  hy\core\__pycache__\util.cpython-311.pyc
  hy\core\hy_repr.hy
  hy\core\macros.hy
  hy\core\result_macros.py
  hy\core\util.hy
  hy\errors.py
  hy\importer.py
  hy\macros.py
  hy\model_patterns.py
  hy\models.py
  hy\pyops.hy
  hy\reader\__init__.py
  hy\reader\exceptions.py
  hy\reader\hy_reader.py
  hy\reader\mangling.py
  hy\reader\reader.py
  hy\repl.py
  hy\reserved.hy
  hy\scoping.py
  hy\version.py
```

</details> 

wait, it's fixed on installing with `--user` . 
But don't close the issue just yet - continue reading - i think there still can be something tangible here.

<details>
<summary>Console Log</summary>

_Note: this bash syntax comes from using msys2 - rest stay assured; it doesn't affect python in any way _(i think)__

```console
$ pip show -f hy | grep -E *.exe

$ pip uninstall hy -y
   ... MORE ...

$ pip install hy
   ... MORE ...
Installing collected packages: hy
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\ProgramFiles\\Python\\Python311\\get_version'
Consider using the `--user` option or check the permissions.

$ pip uninstall hy -y
   ... MORE ...

$ pip install --user hy
   ... MORE ...
Installing collected packages: hy
  WARNING: The scripts hy.exe, hy2py.exe and hyc.exe are installed in '%APPDATA%\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed hy-0.26.0

$ pip show -f hy | grep -E *.exe
  ..\Scripts\hy.exe
  ..\Scripts\hy2py.exe
  ..\Scripts\hyc.exe
```

</details> 

----

As can be seen from above, without the `--user` flag, i.e. for normal install; it shows this highly unusual error:

`OSError: [WinError 5] Access is denied: 'D:\\ProgramFiles\\Python\\Python311\\get_version'`

and w.r.t. this error; i don't understand:
1. why it needs permission for "get_version",
i have not seen this required with any other module install so far 🤔 ? and also
2. how installing in `user`-space satisfies that requirement?
3. Rechecking again, there is _no "D:/ProgramFiles/Python/Python311/get_version"_ in my system in first place - how can anything access it 😅

**Comment by Kodiologist** [comment]
Looks like a simple permissions issue to me. If you want to install it without `--user`, you need administrator permissions, not unlike many *nix setups. Try it from `cmd.exe` running as an administrator.

**Comment by goyalyashpal** [comment]
aaahhh!!

like i said, 

> there is no "D:/ProgramFiles/Python/Python311/get_version" in my system in first place - how can anything access it

**Comment by Kodiologist** [comment]
> If you want to install it without `--user`, you need administrator permissions, not unlike many *nix setups. Try it from `cmd.exe` running as an administrator.

**Comment by scauligi** [comment]
Just to make things clear, the Hy `setup.py` script is trying to _create_ `get_version/get_version.py` in the site directory. Without `--user`, it tries to do this in the global site dir. The global site dir is only modifiable (e.g., creating new directories) with admin permissions -- hence, `[WinError 5] Access is denied: 'D:\\ProgramFiles\\Python\\Python311\\get_version'`.

**Comment by goyalyashpal** [comment]
> the Hy `setup.py` script is trying to _create_ ... in the site directory.

ahw, ohkay ohkayh. now i get it. thanks a lot.
