### ISSUE TITLE
Weirdness with result macros and `.` access

### ISSUE THREAD

**Issue by scauligi** [hylang/hy#2475]
Invoking some of the result macros with an unnecessary attribute access somehow gets hy to make them async:

```python
# (defn normal [])
def normal():
    pass

# ((. defn) weird [])
async def weird():
    pass


# (with [normal])
_hy_anon_var_1 = None
with normal:
    _hy_anon_var_1 = None

# ((. with) [weird])
_hy_anon_var_2 = None
async with weird:
    _hy_anon_var_2 = None


# (fn/a [] (do 0 normal))
async def _hy_anon_var_3():
    0
    return normal

# ((. fn/a) [] (do 0 weird))
def _hy_anon_var_4():
    0
    return weird

# ((. fn) [] (do 0 weirdly-normal))
def _hy_anon_var_5():
    0
    return weirdly_normal
```

It's even more strange to me that `fn` has the _opposite_ behavior of `defn` and `with`.
There might be other examples as well, these are just the ones I stumbled across.

**Comment by Kodiologist** [comment]
It boils down to e.g. `with` saying

```python
node = asty.With if root == "with" else asty.AsyncWith
```

and `root` being `(. with)` instead of `with`. `fn` being the odd one out is because I wrote the conditional the other way in that case.

I would say the underlying bug is that `((. foo) a)` can call a macro `foo`, instead of only treating `foo` as a Python object, as would be more reasonable.

**Comment by Kodiologist** [comment]
Ah, but we need `((. foo bar) x)` to be able to call a macro named `foo.bar`, because that's how `(foo.bar x)` is parsed. So it does indeed seem correct that `((. foo) x)` should be exactly equivalent to `(foo x)`. In that case, I think I just need to ensure `root` is set correctly.
