### ISSUE TITLE
old click script no longer works

### ISSUE THREAD

**Issue by hhamud** [hylang/hy#2480]
(import click)

#@((.option click "-n" "--name" :help "Your name")
(defn main [name] (print (+ "Hello, " (or name "User") "!")))

(if (= __name__ "__main__") (main))

Error
`Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Users/user/Documents/projects/dasy/dasy/cli/commands.hy", line 5
    #@((.option click "-n" "--name" :help "Your name")
     ^
hy.reader.exceptions.LexException: reader macro '#@' is not defined`

**Comment by Kodiologist** [comment]
Hy releases are in general not compatible with each other. See NEWS for each breaking change and how to address it, or downgrade to your preferred version of Hy.

**Comment by hhamud** [comment]
can you at least tell me what I am doing wrong and how i can correct this?
The docs aren't clear

**Comment by Kodiologist** [comment]
No. You posted a non-issue in the issues list, and now you're asking a maintainer for help without expending minimal effort. Start in NEWS, look at the manual, and if the manual isn't clear, tell me what's unclear.

**Comment by hhamud** [comment]
> Start in NEWS, look at the manual, and if the manual isn't clear, tell me what's unclear.

I originally looked in the docs and found nothing and so I posted this issue. I wouldn't have bothered with this project if i knew that I would have encountered incredible hostility to pointing the complete lack of docs. Breaking changes should be the front page of the main manual. 

If you want the language to be used then developer experience should be number one.

**Comment by Kodiologist** [comment]
> Breaking changes should be the front page of the main manual.

I disagree. That would be a huge wall of text to scroll past to get to the table to contents. NEWS is a more appropriate place.

**Comment by wrobell** [comment]
@hhamud It seems you need to put contents of `#@` between `defn` and `main` as list.

@Kodiologist While this was easy to find, the contents of the NEWS file is not helping. And `#@` is a good example. The file says:

> with-decorator and #@ have been removed in favor of decorator lists (see below)

Then you need to scroll down to find

> defn and defclass now allow a decorator list as their first argument

It is not easy find on a phone even if you know it is there. 

In second sentence I would repeat `#@` and `with-decorator`, and an example would help immensely, especially beginners like me. 

@Kodiologist Would you accept a patch?

**Comment by Kodiologist** [comment]
1. Programming on a phone is asking to be miserable.
2. You can search for "decorator" and the second portion will indeed show up.
3. Scrolling down is exactly what is indicated by "see below", which you quoted.
4. NEWS isn't the place to recapitulate the manual.
5. Editing release notes for a release that's already been released, and furthermore is several releases behind by this point, is not a great use of your time.

All this said, if you want to submit a patch, you can, but bear in mind that we don't change previous releases retroactively. Only the version of NEWS in `master` will be changed.
