### ISSUE TITLE
Macro documentation

### ISSUE THREAD

**Issue by wrobell** [hylang/hy#2484]
As newcomer to Lisp and Hylang, I am finding Macros section in the documentation quite confusing.

This is https://docs.hylang.org/en/stable/macros.html.

After few weeks of dealing with Hylang and few other Lisp related things, if I may suggest, it would be great if there was

- quick introduction/example
- differences between usual Lisp notation and Hylang, i.e. `,` vs `~`
- link to a Lisp macro tutorial/book (i.e. On Lisp by Paul Graham is available for free online)
- link to the API

Not bad information is in the API section, but hard to find it there, especially on a smartphone.

**Comment by Kodiologist** [comment]
Yeah, the chapter is long overdue for a rewrite. I'm procrastinating because I first want to be reasonably sure no additional changes to macros or reader macros are coming up.
