### ISSUE TITLE
setv on tuple returns the tuple?

### ISSUE THREAD

**Issue by rwtolbert** [hylang/hy#249]
Seems like odd behavior since in general, setv returns None. The assignment works, the return is unexpected. 

```
=> (setv x 1)
=> (setv l [1 2])
=> (setv ll (list [1 2]))
=> (setv (, a b) [1 2])
(1, 2)
=> (print a)
1
=> (print b)
2
```

**Comment by algernon** [comment]
This behaviour is *very* confusing, especially when combined with `hy --spy`. Adding it to  the Grand Language Cleanup.

Not sure how best to fix it, though, or if there's any code relying on this behaviour...
