### ISSUE TITLE
Surprising behavior when `return` form is used inside an undefined macro

### ISSUE THREAD

**Issue by mcejp** [hylang/hy#2492]
At first this looks like an obvious Hy bug, on second thought I see why this might be tricky to fix.

Consider:

```hy
(defn wtf []
  (unless foobar    ;; oops, forgot to import the 'unless' macro
    (return "this should not happen")))

(print (wtf))
```

This, in fact, prints "this should not happen" instead of raising an error complaining about `unless` or `foobar` being undefined.

`hy.disassemble` reveals that this is because the `return` gets lifted out of what Hy thinks to be a function call.

```hy
(print (hy.disassemble '(defn wtf []
    (unless foobar
        (return "this should not happen")))
    True))
```

=>

```python
def wtf():
    return 'this should not happen'
    return unless(foobar, None)
```

Admittedly this is with Hy 0.27.0 (Python 3.11.4) -- if it could make a difference, I will re-test on Hy master.

**Comment by Kodiologist** [comment]
But this is exactly the right behavior, isn't it? `unless` isn't defined as a macro, so it's taken to be the name of a Python object. Statements pulled out of function arguments get evaluated before the function name itself, as usual. Since one of those statements is `return`, `wtf` is exited before `unless` is ever evaluated to raise a `NameError`.

**Comment by mcejp** [comment]
> Statements pulled out of function arguments get evaluated before the function name itself, as usual.

I thought that this was an implementation detail, rather than intentional design. With it in mind, the behavior makes sense indeed.

**Comment by Kodiologist** [comment]
It is an implementation detail: in general, [you shouldn't rely on order of evaluation within a sequential model](https://docs.hylang.org/en/master/semantics.html#order-of-evaluation).
