### ISSUE TITLE
`hy.M` for macros

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2512]
I like the one-shot import syntax `hy.M` a lot, but it would be nice to have an equivalent for macros, too. Perhaps we should use the name `hy.M` for that and rename the existing feature to `hy.I`, with the "I" standing for "import".

**Comment by scauligi** [comment]
I'd like to keep `hy.M` for modules, as that clicks a lot better in my head.
Would you be opposed to `hy.Ma` for macros? Or `hy.R` for "require" could work as well.

**Comment by Kodiologist** [comment]
Hmm, I'd go with `hy.R` over `hy.Ma`. Perhaps it's too confusing to have `hy.M` be the one that isn't about macros, but perhaps not. I'm not sure.

**Comment by Kodiologist** [comment]
Yeah, I think if there's two of these and the one that *doesn't* use macros is called `hy.M`, that's too counterintuitive. The mnemonic about modules doesn't really work, either, because macros are associated with modules no less than regular Python objects.

I'm thinking we should use `hy.I` for regular objects, which are "I"mported, and `hy.R` for macros, which are "R"equired. That's the most mnemonic single-letter scheme I can think of. As a bonus, old uses of `hy.M` will just raise `NameError` instead of trying to get a macro in place of a regular Python object. Users who are either very foolish or very brave (it's often hard to tell the difference) can still set `hy.M = hy.I` or whatever.

I have no plans to add a reader-macro equivalent, because, as the kids say, umm, *yikes*, sweaty. My one reservation about the above is that the "R" might too readily be assumed to refer to "R"eader macros.

@scauligi What say you?

**Comment by scauligi** [comment]
Yeah what you say makes sense, I think `I`mport and `R`equire are good mnemonics.

Agreed on no magic for readers (even thinking about how to implement it makes me shudder); I don't think it'll be too much of a problem considering the mnemonics work nicely.
