### ISSUE TITLE
Any capitalization of `NaN` and `Inf` are parsed as imaginary numbers with uppercase suffix `J`

### ISSUE THREAD

**Issue by kwshi** [hylang/hy#2521]
This issue seems related to #1288 and #1294. Floating-point special values such as `NaN` and `Inf` are required to be capitalized exactly as such, but when used in imaginary number literals with _uppercase_ `J` suffix, any capitalization is allowed. In the same spirit as #1288, I believe this is unintended/undesired behavior.

```hy
NaNj ; valid (good)
NANj ; invalid (good)
Infj ; valid (good)
iNfj ; invalid (good)

NaNJ ; valid (good)
NANJ ; valid (should not be!)
InfJ ; valid (good)
iNfJ ; valid (should not be!)
```

Interestingly enough, this behavior only occurs in pure-imaginary literals; it doesn't surface in "compound" complex literals, which seem to have the correct behavior:

```hy
1+NaNj ; valid (good)
1+NANJ ; invalid (good)
```

**Comment by Kodiologist** [comment]
Yeah, this is a bug. Thanks for catching it.
