### ISSUE TITLE
Hy produces an illegal implicit `return` in async generators

### ISSUE THREAD

**Issue by linnik** [hylang/hy#2523]
This bug looks almost the same as #691 

```lisp
(defn/a naysayer []
  (yield "nope"))
```

raises `SyntaxError: 'return' with value in async generator`. The output of `hy2py` is

```python
async def naysayer():
    return (yield 'nope')
```

The current workaround is to use `assert` 

```lisp
(defn/a naysayer []
  (yield "nope")
  (assert True))
```

**Comment by Kodiologist** [comment]
This is nasty. Either the compiler needs to look at each function definition to check whether it's an async generator, which could be messy, or the user needs to be warned to make sure each async generator doesn't end with `return`. Frustratingly, Python even forbids `return None` at the end of the function in this case, even though it should be a no-op.

**Comment by linnik** [comment]
Apparently you can make an async generator which returns.
The code in CPython responsible for this [compile.c@3f84a19e62#L3200](https://github.com/python/cpython/blob/3f84a19e6291db682fc9a570e7612e80e2ffbbb5/Python/compile.c#L3200) 

```python
>>> async def naysayer():
...     yield 'nope'
...     return
...
>>> async def naysayer():
...     yield 'nope'
...     return None
...
  File "<stdin>", line 3
SyntaxError: 'return' with value in async generator
````

Therefore for the more clean looks of temporary fix we may use an explicit `return` instead of the `assert`:
```lisp
(defn/a naysayer []
  (yield "nope")
  (return))
```

**Comment by Kodiologist** [comment]
Oh dang, that's even weirder. But good to know.

**Comment by scauligi** [comment]
I think adding a little bit of tracking to `ScopeFn` should be able to let us solve this, I'm testing it out right now

**Comment by linnik** [comment]
> Oh dang, that's even weirder. But good to know.

Furthemore, PyPy considers this a valid code

```
Python 3.10.13 (f1607341da97ff5a1e93430b6e8c4af0ad1aa019, Oct 09 2023, 18:49:30)
[PyPy 7.3.13 with GCC Apple LLVM 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> async def naysayer():
....     return (yield 'nope')
....
>>>> naysayer()
<async generator object naysayer at 0x00000001083dda60>
```

 I wonder if this issue is a bug in the CPython itself considering all the inconsistency between valid return inside classing generator and SyntaxError exception in async version.

```
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def test():
...     yield 1
...     return
...
>>> def test():
...     yield 1
...     return 2
...
>>> async def test():
...     yield 1
...     return
...
>>> async def test():
...     yield 1
...     return 2
...
  File "<stdin>", line 3
SyntaxError: 'return' with value in async generator
```

**Comment by scauligi** [comment]
Interesting that PyPy allows it; according to [PEP 525](https://peps.python.org/pep-0525/#asynchronous-generators):

> It is a `SyntaxError` to have a non-empty return statement in an asynchronous generator.

So CPython is in the right here, at least according to the spec.

**Comment by scauligi** [comment]
Oh, that's actually a bug in PyPy:

```python
Python 3.10.12 (af44d0b8114cb82c40a07bb9ee9c1ca8a1b3688c, Jun 15 2023, 12:39:27)
[PyPy 7.3.12 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>>> async def f(): yield 3; return 4
  File "<stdin>", line 1
    async def f(): yield 3; return 4
                            ^^^^^^^
SyntaxError: 'return' with value in async generator

>>>> async def f(): yield 3; return None
  File "<stdin>", line 1
    async def f(): yield 3; return None
                            ^^^^^^^^^^
SyntaxError: 'return' with value in async generator

>>>> async def f(): return (yield 3)

>>>> import asyncio
>>>> x = f()
>>>> asyncio.run(x.asend(None))
3
>>>> asyncio.run(x.asend("uh oh"))
RPython traceback:
  File "pypy_interpreter_1.c", line 63911, in AsyncGenASend_do_send
  File "pypy_interpreter_2.c", line 26126, in GeneratorOrCoroutine__send_ex
Fatal RPython error: AssertionError
/home/scauligi/bin/py: line 33: 351338 Aborted                 (core dumped) python3
```

**Comment by scauligi** [comment]
I submitted the bug to PyPy's issue tracker: https://foss.heptapod.net/pypy/pypy/-/issues/4023

**Comment by linnik** [comment]
Fantastic! Thank you for your work!
