### ISSUE TITLE
async for?

### ISSUE THREAD

**Issue by kovan** [hylang/hy#2541]
How to write an async for in Hy?

**Comment by Kodiologist** [comment]
> Hy's issue list is for bugs, complaints, and feature requests.

**Comment by kovan** [comment]
I request async for support

**Comment by Kodiologist** [comment]
But it's already implemented. We've had it since 2019 at the latest.

**Comment by kovan** [comment]
And where can I find some documentation on it?, I have searched the docs with no luck.

**Comment by Kodiologist** [comment]
`for` itself is documented on the API page under the entry `for`, whereas asynchronous loop clauses are documented under `lfor` on the same page. I should add the phrase "async for" to the bullet point that mentions it.

**Comment by kovan** [comment]
Ok yes, I think it is `gfor :async LVALUE ITERABLE ` what I am looking for, thanks.  
Yeah, that would be nice.
