### ISSUE TITLE
Collapse some similar core macros

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2545]
Consider the following substitutions:

| Old syntax       | New syntax            |
| ---------------- | --------------------- |
| `(fn/a …)`       | `(fn :async …)`       |
| `(defn/a …)`     | `(defn :async …)`     |
| `(with/a […] …)` | `(with [:async …] …)` |
| `(yield-from …)` | `(yield :from …)`     |

The purpose is to cut down a bit on the number of distinct core macros. There are a lot of them.

For consistency with `for`, notice that the new `with` applies `async` per context manager, not to all context managers in the same `with`.

@scauligi What do you think of this?

**Comment by scauligi** [comment]
Ooh I like these! I may want to play around a little with the placement of `:async` for `with`, since we usually don't have keywords as the first element of a list, but everything else looks great to me (particularly `yield :from` which feels much more natural now)

**Comment by Kodiologist** [comment]
I see what you mean. I think `:async row (db)` is a little better than `row :async (db)` because it's more consistent with the other uses of keywords in the comprehension macros, where the keyword heads the clause.
