### ISSUE TITLE
Documentation website is not rendering properly

### ISSUE THREAD

**Issue by nkabir** [hylang/hy#2585]
Please take a look at 

https://hylang.org/hy/doc/v0.28.0

![hylang-docs](https://github.com/hylang/hy/assets/92801/42b278f8-150c-418a-9a10-3df2a1d50d32)

**Comment by Kodiologist** [comment]
Looks good to me. What problem do you see?

**Comment by nkabir** [comment]
Here's a link to the original rendering. The search box is gone and the central content column has disappeared.

https://web.archive.org/web/20240104083643/https://docs.hylang.org/en/stable/

**Comment by Kodiologist** [comment]
The layout is different because I changed it on purpose, silly.

Mistaking a restyled web page for a rendering bug has got to be one of the weirdest issues I've gotten on this repository, and that's saying a lot.

**Comment by nkabir** [comment]
Apologies! I have muscle memory for the original search box...
