### ISSUE TITLE
Macro scope evaluating Hy source from Python function

### ISSUE THREAD

**Issue by mcarpenter** [hylang/hy#2589]
Hi,

I'm trying to evaluate some Hy source code (from a string) in a Python program. The source contains one macro and one function. I invoke the macro with the name of the function, and immediately call the returned lambda (`fn`). This works fine if I'm at the top level of the Python script. However if I put the calls to `hy.read_many` and `hy.eval` inside a Python function then `eval` complains that the Hy function name cannot be found.

I thought this might have something to do with the `:macros` key but it's not the macro that cannot be found but the function. I get multiple models back from `read_many` but my understanding is that `eval` groks that. I tried iterating over the `models` and evaluating each in turn, same error. If I paste `HY_SRC` into the Hy REPL this works fine too.

Is this a bug or am I missing a nuance?

Ubuntu 22, Python 3.10, Hy 0.29.0 (current head).

```python
import hy

HY_SRC = '''
(defn head [arr]
  (if (= 0 (len arr)) None
    (get arr 0)))

(defmacro anon-lambda [#* argv]
  (let [argc (len argv)]
    (let [args (cut argv 0 (- argc 1))
          expr (get argv -1)]
      `(fn [~@args] ~expr))))

((anon-lambda (head [1 2 3])))
'''

def eval_hy_src(hy_src):
    models = hy.read_many(hy_src)
    return hy.eval(models)

# This works
models = hy.read_many(HY_SRC)
print(hy.eval(models))

## This fails "name 'head' is not defined"
#print(eval_hy_src(HY_SRC))
```

Output:
```
Traceback (most recent call last):
  File "/tmp/wat.py", line 28, in <module>
    print(eval_hy_src(HY_SRC))
  File "/tmp/wat.py", line 21, in eval_hy_src
    return hy.eval(models)
  File "/tmp/venv/lib/python3.10/site-packages/hy/compiler.py", line 805, in hy_eval_user
    value = hy_eval(
  File "/tmp/venv/lib/python3.10/site-packages/hy/compiler.py", line 769, in hy_eval
    return eval(ast_compile(expr, filename, "eval"), globals, locals)
  File "<string>", line 12, in <module>
  File "<string>", line 12, in <lambda>
NameError: name 'head' is not defined
```

**Comment by Kodiologist** [comment]
A simpler pure Hy program reproducing the error is:

```hy
(defn eval-hy-src []
  (hy.eval '(do
    (defn head [] 1)
    (print ((fn [] (head)))))))
(eval-hy-src)
```

The Python equivalent is:

```python
def eval_py_src():
    exec(
        'def head(): return 1\n'
        'print((lambda: head())())')
eval_py_src()
```

The Python version raises the same error. Hence, not a Hy bug. You'll probably need to give more arguments to `hy.eval`.

**Comment by mcarpenter** [comment]
Aha! `globals={}`, thanks for the nudge.
