### ISSUE TITLE
Cannot import Hy package installed as editable

### ISSUE THREAD

**Issue by mcejp** [hylang/hy#2591]
This might be just my misunderstanding of how Hy or pip or setuptools or (...) works. I apologize in advance.

I have created a sample project to demonstrate the issue: https://github.com/mcejp/hy-example-package

Repro:
```
$ pip install --user .
$ hy demo/demo.hy
Hello from my Hy package

$ pip install --user --editable .
$ hy demo/demo.hy
Traceback (most recent call last):
  File "/home/codespace/.python/current/bin/hy", line 8, in <module>
    sys.exit(hy_main())
  File "/usr/local/python/3.10.13/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/python/3.10.13/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/python/3.10.13/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspaces/hy-example-package/demo/demo.hy", line 1, in <module>
    (import my-package [say-hello])
ImportError: cannot import name 'say_hello' from 'my_package' (unknown location)
```
Tested with Hy 0.29 as well as Git master.

**Comment by Kodiologist** [comment]
> This might be just my misunderstanding of how Hy or pip or setuptools or (...) works.

It's possible. The first thing to try is whether you can reproduce the issue with plain Python instead of Hy. If you can, it's not a Hy issue.

I would also try reproducing your issue with a `setup.py` in place of `pyproject.toml`.

**Comment by mcejp** [comment]
It does work if the package is implemented in Python (`__init__.py` instead of `__init__.hy`)

Editable installations depend on a mechanism called _path configuration files_ (https://docs.python.org/3.12/library/site.html). Does Hy take those into account when importing Hy packages?

I have looked at the code in hy/importer.py, but I don't really understand how it hijacks the standard import mechanism (I would expect it to append itself either to `sys.meta_path` or `sys.path_hooks`, but it does neither)

**Comment by Kodiologist** [comment]
Using `__init__.hy` at the top level of a package isn't really supported. The fundamental problem with it is that it could interfere with trying to import the package when Hy itself isn't already imported. Instead, rename your `__init__.hy` to `foo.hy` or so and make an `__init__.py` that just star-imports from `foo`. This seems to resolve your issue:

```sh
$ mv my_package/__init__.hy my_package/foo.hy
$ echo 'from my_package.foo import *' >my_package/__init__.py
$ pip install -e .
…
$ hy demo/demo.hy
Hello from my Hy package
```

**Comment by mcejp** [comment]
Fair enough, this works. Is there any hack to re-export also macros?

**Comment by Kodiologist** [comment]
I think the easiest way is with something like `hy.eval(hy.read('(require mymodule.mymacros *)'))`.

**Comment by mcejp** [comment]
Excellent, thank you very much ❤️
