### ISSUE TITLE
The behavior of symbols in `match`

### ISSUE THREAD

**Issue by wrobell** [hylang/hy#2597]
Please consider a simulation of Hy's `Symbol` class
```
class Object:
    def __eq__(self, other):
        print('self: other: {}'.format(type(self), type(other)))
        return type(self) is type(other) and super().__eq__(other)

class Symbol(Object, str):
    def __new__(cls, s, **kw):
        return super().__new__(cls, s, **kw)

match Symbol('a'):
    case Symbol('b') as a:
        print('hey b', a)
    case Symbol('a') as a:
        print('hey a', a)
    case _:
        print('not ok')

```
Above prints
```
$ python m.py
self: <class '__main__.Symbol'>, other: <class 'str'>
self: <class '__main__.Symbol'>, other: <class 'str'>
not ok
```
Remove `Object.__eq__` method and the match statement works as expected. I am not sure why `other` becomes string (I would still expect symbol).

Or redefine `Symbol` as
```
class Symbol(Object, str):
    __match_args__ = ("__match_self_prop__",)

    @property
    def __match_self_prop__(self):
        return str(self)

    def __new__(cls, s, **kw):
        return super().__new__(cls, s, **kw)
```

**Comment by Kodiologist** [comment]
[As I said where you brought this up originally](https://github.com/hylang/hy/discussions/2366#discussioncomment-10533892), it's not clear to me what should happen. Therefore, it's not clear that the current behavior is a bug. I'm open to adding `Symbol.__match_args__` if you like that behavior better, but go through the other model types to see if you want analogous changes there, too. Removing `Object.__eq__` entirely is out of the question; it will cause a lot of tests to fail. Also, be sure that the symbol `'a` doesn't start matching the string `"a"`.

**Comment by wrobell** [comment]
Just to clarify. I have no solution at the moment, just providing observations.

The code below outputs `True`, `True`, and `False`. I would expect it to print `True` three times.
```
print(Symbol('a') == Symbol('a'))

match Symbol('a'):
    case Symbol(a) if a == Symbol('a'):
        print(True)
    case _:
        print(False)

match Symbol('a'):
    case Symbol('a') as a:
        print(True)
    case _:
        print(False)
```
IMHO, *inconsistent* behaviour for the two match statements indicates a bug.

**Comment by wrobell** [comment]
What could be considered, is use of metaclasses.

The following code works as expected (3 x `True` is printed)
```
class Object(type):
    def __eq__(self, other):
        return type(self) is type(other) and super().__eq__(other)

class Symbol(str, metaclass=Object):
    def __new__(cls, s, **kw):
        return super().__new__(cls, s, **kw)

print(Symbol('a') == Symbol('a'))

match Symbol('a'):
    case Symbol(a) if a == Symbol('a'):
        print(True)
    case _:
        print(False)

match Symbol('a'):
    case Symbol('a') as a:
        print(True)
    case _:
        print(False)
```

**Comment by wrobell** [comment]
Let's focus on non-working match statement:
```
match Symbol('a'):
    case Symbol('a') as a:   # Symbol('a') specified in case statement is converted to string here
        print(True)
    case _:
        print(False)
```
From Python docs (https://peps.python.org/pep-0634/#class-patterns, one of them is `str`)
> For a number of built-in types (specified below), a single positional subpattern is accepted which will match the entire subject.

`Symbol('a')` is not the `a` string, but is a string
```
(issubclass Symbol str) ; True
(isinstance (Symbol "a") Symbol) ; True

(type (+ 'a "")) ; <class 'str'>
(< 'a "b") ; True
(< "b" 'b) ; False
```

I am not sure what are the benefits of treating symbols as strings, but maybe it should revisited. Especially, that:
```
(= (Symbol "a") "a") ; False

(= ('a "a")) ; True
(type 'a) ; <class 'hy.models.Symbol'>
```

**Comment by Kodiologist** [comment]
> I am not sure what are the benefits of treating symbols as strings

It adds a lot of useful operations. You can concatenate them, index and slice them, use the many defined string methods, etc.

**Comment by wrobell** [comment]
Could the operations be provided by implementing base classes from `collections.abc`? The current semantics, where Symbol is becoming a string sometimes is worrying.

**Comment by Kodiologist** [comment]
What's the worrying part? Sure the behavior of `match` here is crazy, but that's `match` for you. I'm pretty happy with the semantics of symbols elsewhere.

**Comment by Kodiologist** [comment]
> `(= (Symbol "a") "a") ; False`

I went out of my way to implement non-equality of models to corresponding base types. There's a bit in the manual that talks about this and how to convert back and forth. They used to be equal, and it was a total mess for writing macros; you could say `(= x 'foo)` and accidentally match a string literal `"foo"`.

> `(= ('a "a"))`

The form `('a "a")` isn't even evaluated here. It crashes if you do. 

> `(type 'a) ; <class 'hy.models.Symbol'>`

Clearly correct.

> `(<= (Symbol "a") "a")`

Seems unobjectionable. What did you expect here?

**Comment by Kodiologist** [comment]
To be clear: my plan is to release Hy 1.0 fairly soon. The time to make major overhauls to semantics to make a corner case somewhat neater is long gone. So even if I liked this proposal to make `Symbol` no longer a `str`, which I don't, you'd have to convince me it was a really necessary change.

**Comment by wrobell** [comment]
> > `(= (Symbol "a") "a") ; False`
> 
> I went out of my way to implement non-equality of models to corresponding base types. There's a bit in the manual that talks about this and how to convert back and forth. They used to be equal, and it was a total mess for writing macros; you could say `(= x 'foo)` and accidentally match a string literal `"foo"`.
> 
> > `(= ('a "a"))`
> 
> The form `('a "a")` isn't even evaluated here. It crashes if you do.

Sorry a typo above. Please ignore.
 
> > `(<= (Symbol "a") "a")`
> 
> Seems unobjectionable. What did you expect here?

Type error would be better
```
(= (Symbol "a") "a") ; False
(<= (Symbol "a") "a") ; True

(= 1 "a") ; False
(<= 1 "a") ; TypeError: '<=' not supported between instances of 'int' and 'str'
```

**Comment by wrobell** [comment]
> To be clear: my plan is to release Hy 1.0 fairly soon. The time to make major overhauls to semantics to make a corner case somewhat neater is long gone. So even if I liked this proposal to make `Symbol` no longer a `str`, which I don't, you'd have to convince me it was a really necessary change.

I believe Symbol has very bad design/implementation. This causes issues with `match`, and I can bet there are more undefined behaviours because of this.

**Comment by wrobell** [comment]
> > Type error would be better
> 
> Eh, a `TypeError` would've been a reasonable option, but I think being allowed to order symbols and strings is also fine. It's not clear whether the string `"a"` should be regarded as coming before or after the integer `1`. That's why Python chokes on `"a" < 1`. In the case of symbols and strings, by contrast, the order is obvious.

Does this make sense though?
```
(= (Symbol "a") "a") ; False
(and (<= (Symbol "a") "a") (>= (Symbol "a") "a")) ; True
```

**Comment by Kodiologist** [comment]
Yes, actually, that's a good example of how [preorders](https://en.wikipedia.org/wiki/Preorder) work. You can have two elements *a* and *b* with *a* ≤ *b* and *b* ≤ *a* and yet *a* ≠ *b*. I implemented a general preorder class as part of [Artiruno](https://github.com/Kodiologist/Artiruno).

**Comment by Kodiologist** [comment]
I'll readily admit to being unsure how many of the fine details of the semantics of model objects should be written out. I'm open to additions if you're interested in writing them.

**Comment by Kodiologist** [comment]
This issue doesn't look like it's going anywhere.

**Comment by wrobell** [comment]
IMHO, this issue deserves at least better documentation for symbol objects, and even then this minefield will not go away.

**Comment by Kodiologist** [comment]
I'm open to documentation additions on this subject if you're interested in writing them.
