### ISSUE TITLE
str vs unicode and int vs long

### ISSUE THREAD

**Issue by Willyfrog** [hylang/hy#283]
I'm curently going through the overflow int issue (#276) which is going fine except for a test that is failing:

`(instance? int 3)` => `False`

This is False on my current implementation of HyInt, which would use long on python 2.x But it would be the same problem if we try to do

`(instance? str "abc")` => `False`

While I can mimic the way the test is used for strings (and my current branch does thsi) I wonder if it will be confusing for someone that `(instance? int 3)` and `(instance? str "abc")` performs differently on py2 and py3

**Comment by Kodiologist** [comment]
We have `string?` and `integer?`, which do the job.
