### ISSUE TITLE
defn has no tests

### ISSUE THREAD

**Issue by Willyfrog** [hylang/hy#302]
I can't seem to fin any tests of defn. I have found some defn behaviour that is at least weird:

I should not be able to use anything but a HySymbol as name for a function. I can currently use:
* a string (defn "hy" [] 1) (this at least can later be called withouth quotes, which might be seem as inconsistent)
* a lambda list. (defn &hy [] 1) This can't later be called.
* any other new HyType I define that is a string (see my keywords pr #295, it can be used too) e.g.: (defn %hy [] 1)
* keywords. (defn :hy [] 1) Although this one fails due to other reasons.

Insonsistent behaviour:
* (defn if [] 1) should either fail or override if macro? currently it doesn't fail but behavior is the one from "if" macro.

I was planning to add some tests, but I'm not sure where should be added and if any of those is a non-issue

**Comment by algernon** [comment]
For the record:

* `(defn "hy" [] 1)` raises a `HyTypeError`
* `(defn &hy [] 1)` works, and is callable later.
* `(defn :hy [] 1)` raises a `HyMacroExpansionError`
* `(defn if [] 1)` raieses a `HyTypeError`

Didn't test the new HyType case, though. I'll add tests for these cases.
