### ISSUE TITLE
bpython-like REPL

### ISSUE THREAD

**Issue by rcarmo** [hylang/hy#324]
[bpython](http://bpython-interpreter.org/screenshots/) provides an awesome standard Python shell, and would likely form a good basis for a fully interactive REPL.

**Comment by weakish** [comment]
Here is a repository:

https://github.com/thomasballinger/bphython

But I [failed to install it](https://github.com/thomasballinger/bphython/issues/1).

**Comment by Kodiologist** [comment]
I don't think this is in scope for this repository. Whoever wants to write it should develop it as its own project.
