### ISSUE TITLE
running a flask server in debug mode breaks hy and drops to Python

### ISSUE THREAD

**Issue by Willyfrog** [hylang/hy#329]
Setting a Flask app to run in debug mode breaks hy and drops to python.

Steps to reproduce:
    $ hy
    hy 0.9.11
    => (import [flask [Flask]])
    => (setv app (Flask "**main**"))
    => (setv app.debug True)
    True
    => (.run app)
     \* Running on http://127.0.0.1:5000/
     \* Restarting with reloader
    Python 2.7.5 (default, Sep  6 2013, 09:55:21) 
    [GCC 4.8.1 20130725 (prerelease)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> 

using kwapply give the same result and running directly without setting debug makes the server run

**Comment by Kodiologist** [comment]
This still doesn't work in 2017 with Python 3, but it just crashes now:

    hy 0.12.1+50.g741b9b9 using CPython(default) 3.6.0 on Linux
    => (import [flask [Flask]])
    => (setv app (Flask "main"))
    => (setv app.debug True)
    => (.run app)
     * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
     * Restarting with stat
    /usr/local/bin/python3.6: can't find '__main__' module in '

**Comment by Beluki** [comment]
Hello

 

I am Marisa, Beluki's wife. I'm sorry but I have to tell you that he died last year.

 

Sent: Monday, March 27, 2017 at 1:51 AM

**Comment by kirbyfan64** [comment]
:(

**Comment by Kodiologist** [comment]
Thanks for letting us know, Marisa, and sorry if I bothered you. Feel free to mute this thread, as mentioned in the email you got from GitHub.

**Comment by Beluki** [comment]
He loved his work and one important part of him still lives in the things he made, so thank you to all people that keep that part of him alive.
 

Sent: Tuesday, March 28, 2017 at 5:20 PM

**Comment by Kodiologist** [comment]
Actually, the same sequence of calls fails with the same error in Python's own REPL. I'm going to close this until somebody can show an example that works in Python but not a recent version of Hy.

**Comment by Beluki** [comment]
Hello

 

Carlos (Beluki) died last year, he had cancer, so I cant help you with his work and commentaries. Sorry.

 

Marisa


Sent: Friday, April 28, 2017 at 12:55 AM
