### ISSUE TITLE
Hy handles *some-variable* incorrectly

### ISSUE THREAD

**Issue by Coaldust** [hylang/hy#378]
Proper Lisp code uses `+some-variable+` for non-local constants, and `*some-variable*` for non-local mutables.  See http://google-styleguide.googlecode.com/svn/trunk/lispguide.xml#Global_variables_and_constants or any other Lisp style guide that covers the issue.

Hy converts `*some-variable*` to `SOME_VARIABLE` which is what proper Python code uses for constants.  In other words, this is exactly the opposite of the expected behavior.  This will confuse programmers trying to use Hy code from Python.

I suggest changing Hy to behave as Lisp and Python programmers would expect it, by having `*some-variable*` in Hy become `some_variable` (what proper Python code uses for global mutables; see http://google-styleguide.googlecode.com/svn/trunk/pyguide.html?showone=Naming#Naming ) in Python, and `+some-variable+` in Hy become `SOME_VARIABLE` in Python.  This would prevent unnecessary confusion and bugs.

You may also want to consider making Hy automatically do the right thing with `*some-variable*`, so Hy programmers don't have to write `(global *some-variable*)` manually.  This will not be necessary for `+some-variable+` since the global annotation in Python is only necessary for mutation, not reading (see http://docs.python.org/3/reference/simple_stmts.html#global ).  It would also enforce proper naming.

Being able to view the emitted Python code is invaluable to finding bugs like this, and to Hy programmers making the transition from Python.  I hope it will be maintained.

**Comment by algernon** [comment]
See the discussion in #383: we saw no compelling reason to change the earmuffs. For Hy, earmuffs are some minor sugar, and they do not - and should not - work like in other lisps. We're not other lisps.

**Comment by agentultra** [comment]
Ear muffs are just a convention in CL and don’t mean anything…
