### ISSUE TITLE
"apropos" for Hy

### ISSUE THREAD

**Issue by Coaldust** [hylang/hy#409]
Common Lisp and Emacs Lisp can search all identifiers, docstrings, and arguments to procedures that have been loaded and report the identifier of anything that matches a pattern.

It's more useful than Google, since you don't have to leave your programming environment for the web browser, the code you're working with may not be visible to Google, and you're likely to get less irrelevant results.

Using it can encourage code reuse.  If I don't know something exists, I'm likely to reinvent the wheel, but if finding out if it exists is easy, I'm likely to search to see if it exists before I start coding.

It would be really nice to be able to restrict the results various ways, such as only showing variables, procedures, classes, modules, etc. or only matching identifiers instead of identifiers, docstrings, and arguments.

It would also be really nice to be able to use "fancy" patterns, like a regular expression, instead of literal strings.  At the very least having the option to say "case doesn't matter" would be very helpful.

I've longed for something like this in Python.  Third parties have implemented it before, but due to constant API changes, they tend to not stay working for long.

I thought that since Hy was already wrapping the AST API to force a stable representation of it, that it might be possible to implement and keep working without much extra labor.

Here are links to some implementations.  They probably no longer work, but might make figuring out how to implement it easier.
http://stackoverflow.com/questions/16886679/python-apropos-command
https://github.com/philippp/apropos.py
http://www.pymolwiki.org/index.php/Apropos
http://ttic.uchicago.edu/~nati/Python/apropos.py

**Comment by Kodiologist** [comment]
I don't think it will be any easier to implement this for Hy specifically than for Python in general. Hy provides only a thin layer over Python that's mostly gone by the time the program is running and you're doing introspection like this. The upside of this is that any such apropos function that works for Python should work for Hy, too, without issues. If not, the problem can be addressed by patching Hy, patching the apropos library, or writing a new library that depends on the old one, as appropriate. I'm closing this issue in lieu of these approaches.
