### ISSUE TITLE
__main__ is not handled correctly when a program is run with hy program.hy

### ISSUE THREAD

**Issue by podhmo** [hylang/hy#418]
Maybe, the diferrence between hy and hyc is existed treating "**main**" module.  perhaps, this behavior is bug, but, I can't judge about it.

when i try below code.

``` lisp
(import unittest)

(defclass Tests [unittest.TestCase]
  [[testIt (fn [self] (raise (Exception "")))]])

(when (= --name-- "__main__")
  (import sys)
  (print (dir (get sys.modules "__main__")))

  (.main unittest)
  )
```
## Execution with hyc

this is expected behavior (Exception is raised).

``` bash
$ hyc assert-sample.hy
$ python assert-sample.pyc

E
======================================================================
ERROR: testIt (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "assert-sample.hy", line 4, in testIt
    [[testIt (fn [self] (raise (Exception "")))]])
Exception

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
['Tests', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', 'sys', 'unittest']
```
## Execution with hy

Exception is not raised.

``` bash
$ hy assert-sample.hy
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__requires__', 'load_entry_point', 'sys']

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by Kodiologist** [comment]
It's still around. Here's a slightly simpler example. Create this file and call it `test1.hy`:

    (import sys)
    (setv foobar 15)
    (when (= --name-- "__main__")
      (print foobar)
      (print (hasattr (get sys.modules "__main__") "foobar")))

`hy test1.hy` will print `False`, but `hyc test1.hy && python3 test1.hy` will print `True`. You also get `True` if you write the file in Python to start with:

    import sys
    foobar = 15
    if __name__ == "__main__":
      print(foobar)
      print(hasattr(sys.modules["__main__"], "foobar"))

**Comment by Kodiologist** [comment]
Oh, wait, this is described better in #459. I'll close this, then.
