### ISSUE TITLE
[wishlist] add a cython code generator

### ISSUE THREAD

**Issue by benwbooth** [hylang/hy#464]
It would be cool if hy could produce cython output. Cython lets you write python-like code that compiles to c code, so it's useful for writing code where performance or c-interop is important. I guess this would mean writing a code generator that produced cython code, and extending the parser to support cython constructs, or writing a new parser for cython. After writing this, it actually sounds like this might be enough work to warrant breaking it out into a separate project :-/ oh well, I just figured I'd throw it out there in case anyone else thinks it's a good idea.

**Comment by Kodiologist** [comment]
I'm closing this in favor of the more general issue #934.
