### ISSUE TITLE
add recursive-replace to core

### ISSUE THREAD

**Issue by paultag** [hylang/hy#465]
Add @cndreisbach 's `recursive-replace` into core.

It's ruddy brilliant.

**Comment by algernon** [comment]
Ping @hylang/core. Not related to the Grand Cleanup, but I'm going through all bugs, and this one seems straightforward.

**Comment by farhaven** [comment]
:+1:, I really like it.

**Comment by algernon** [comment]
@farhaven, care to turn this into a PR? :)
