### ISSUE TITLE
Fix loop/recur documentation

### ISSUE THREAD

**Issue by agentultra** [hylang/hy#467]
http://docs.hylang.org/en/latest/contrib/loop.html

Remove the quoted TCO section and references to TCO from that page. It's misleading. Anyone who looks at the implementation of loop/recur can see that it's not actually optimizing away stack frames.

If it's necessary this document should describe the actual implementation.

**Comment by chr15m** [comment]
@agentultra I ran the following two variations of test code:

Regular recursive function call:
```
(defn fib [n s]
  (if (< n 1)
    s
    (fib (- n 1) (+ s n))))
```

Using loop instead:
```
(defn fib2 [t]
  (loop [[n t] [s 0]]
    (if (< n 1)
      s
      (recur (- n 1) (+ s n)))))
```

The first one triggers Python's maximum recursion depth when run with e.g. `2000`.

I can't get the second one to exceed recursion depth - I run out of CPU first.

Can you explain the nuance of why this is not "optimizing away stack frames"?

**Comment by Kodiologist** [comment]
Closing in lieu of an explanation.
