### ISSUE TITLE
Find a way to ruin our glorious unicode future with regular bytes / ascii for ${THINGS}

### ISSUE THREAD

**Issue by paultag** [hylang/hy#495]
FSVO `${THINGS}` such as setuptools, which requires `package_data` to use regular ascii strings as package names. Annoying.

Thanks to @oubiwann for the bug

it'd be good to get something like `b"foo"` working (since we already have `u"foo"` and `r"foo"`)

Damnit, setuptools.

**Comment by wbolster** [comment]
fwiw, issue #732 has comments worth reading

**Comment by wbolster** [comment]
woohoo :)
