### ISSUE TITLE
&rest does not work correctly with macros

### ISSUE THREAD

**Issue by JacobGood1** [hylang/hy#497]
(defmacro a
    [&rest b]
    b)

This will result in an error if it is invoked.  In the mean time, for anyone who reads this, there is a solution...

-quote-

macro-expander does not know how to handle tuples as return values (yet)..but something like (defmacro foo [&rest a] (for [args a] (print args))) should work

 -theanalyst

**Comment by Kodiologist** [comment]
This issue can be closed now. `(defmacro a [&rest b]) (a 1 2)` returns `[1 2]`.
