### ISSUE TITLE
Exclamation mark ! is not mangled

### ISSUE THREAD

**Issue by ivan** [hylang/hy#536]
I noticed that https://github.com/hylang/hyway/blob/master/conway.hy uses "!" in `set!` and `get!`, but Hy doesn't mangle "!" into something else.  The variable is added to the module as-is.  That means it'll be hard to reach it from normal Python code.  Also, hy2py on Hy code with `set!` returns invalid syntax: `def set!(`.

**Comment by algernon** [comment]
My opinion here is that this is not a bug. There are symbols that Python can't handle, but Hy can, and symbols that end with a bang are such. There's also `^`, and a couple of others that do not get mangled.

On the other hand, the `foo!` syntax is reasonably common, so... how about mangling that to `foo_bang` ?

**Comment by farhaven** [comment]
IIRC that's what Clojure does as well. LGTM :+1:
