### ISSUE TITLE
Confusing HyMacroExpansionError when unquoting is followed by attribute

### ISSUE THREAD

**Issue by ivan** [hylang/hy#542]
Expanding this (incorrect?) macro results in a rather confusing error:

```
=> (defmacro m [] (with-gensyms [sys] `(do (import [sys :as ~sys]) (print ~sys.stdout))))
=> (m)
  File "<input>", line 1, column 1

  (m)
  ^-^
HyMacroExpansionError: `m' object has no attribute 'stdout'
```

(Why is it complaining about the lack of the attribute on the macro itself?)

This works as expected:

```
=> (defmacro m [] (with-gensyms [sys] `(do (import [sys :as ~sys]) (print (. ~sys stdout)))))
=> (m)
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
```

**Comment by algernon** [comment]
This is a bit better on Hy master now:

```
=> (defmacro m [] (with-gensyms [sys] `(do (import [sys :as ~sys]) (print ~sys.stdout))))
=> (m)
  File "<input>", line 1, column 1

  (m)
  ^-^
HyMacroExpansionError: expanding `m': AttributeError("'HySymbol' object has no attribute 'stdout'",)
```

At least it tells you that a HySymbol doesn't have that attribute, which is somewhat better than the previous error. Not sure if we can/want do better. I can add a rule to hydiomatic that'd catch this, though. I'll see what I can do, but if improving hy master's behaviour is too complicated, I'm inclined to close this issue, as we already saw improvement.

**Comment by algernon** [comment]
Aight. So `~sys.stdout` gets translated to `(unquote sys.stdout)`, and we can't teach `unquote` to warn when it sees a dot, because `(defmacro m [] `(do (print ~butlast.--doc--)))` is entirely valid too.

So I believe the current error message is a reasonable one, and therefore, I'm closing this issue.
