### ISSUE TITLE
scope of for loop

### ISSUE THREAD

**Issue by andrewchambers** [hylang/hy#543]
The code here prints the values 9 then 5.  This is following pythons for binding,
imo its more appropriate to get rid of the local binding to x after the loop and have it print 5 5. Opinions?

```
(def x 5)
(defn foobar []
  (for [x (range 10)] "foobar")
  (print x))
(foobar)
(print x)
```

**Comment by Kodiologist** [comment]
In my opinion, this is one of several imperfections in Python's scoping rules, but trying to paper over it in Hy is a Bad Idea: we don't want to change Python's semantics more than we have to in order for the idea of Python-as-a-Lisp to work. After all, this leakage does have an advantage—namely, that you can tell where the loop stopped—so it's not as if we would be unconditionally better off without it.

I'm closing this issue, but anyone who disagrees should feel free to reopen (or, better, open a pull request with a proposed implementation and tests).

**Comment by andrewchambers** [comment]
"After all, this leakage does have an advantage—namely, that you can tell where the loop stopped—so it's not as if we would be unconditionally better off without it."

My original suggestion was to make the value of the for expression this value so its still avaliable. If nobody else complains i don't mind this being closed though.
