### ISSUE TITLE
HyDicts not turned into dicts inside a quote

### ISSUE THREAD

**Issue by dbohdan** [hylang/hy#552]
When you have a structure like

```
'(html
  (head)
  (body
    (p {"align" "right"} "Hello, " (b "'90s HTML!"))))
```

the type of the `{"align" "right"}` part is `HyDict`; it doesn't get turned into a `dict`. Since a `HyDict` is internally represented as a `list` this means that unless you manually do something like `(dict (.items x))` on your `HyDict` you can't retrieve its items with `(get x y)`.

**Comment by Kodiologist** [comment]
This isn't a bug. Quoting a form preserves the literal syntax, without evaluating anything. `'{"a" 1 "b" 2}` doesn't equal `'{"b" 2 "a" 1}` even though they evaluate to equal objects, because they're not equal as s-expressions.
