### ISSUE TITLE
Ship a magic coverage module

### ISSUE THREAD

**Issue by paultag** [hylang/hy#559]
@nedbat mentioned something about coverage plugins so we can get pretty html reports by writing functions to do line alignment and a pygments lexer def. (not looked into it)

This was apparently designed for jinja/mako/django templates, but we can shamelessly abuse it for the greater good.

**Comment by timmartin** [comment]
I've written a very simple coverage module [here](https://github.com/timmartin/hy-coverage) that does line coverage of Hy files. There's no integration with pygments yet, but the output HTML seems usable anyway.

**Comment by Kodiologist** [comment]
This is probably outside the scope of Hy itself.
