### ISSUE TITLE
`gensym` makes impossible variables

### ISSUE THREAD

**Issue by xcthulhu** [hylang/hy#597]
Here are some ways I've discovered to make impossible variables with `gensym` (both of these will throw exceptions):

``` hy
(setv (gensym "blah.blah") 1)
(setv (gensym "(+ 1 1)") 9)
```

To quote Paul: _what do?_

**Comment by xcthulhu** [comment]
Hi hylang/hy,
A message from Matthew Wampler-Doty was left on IQ Elite for you. 
Click here a.iqelite.com/j/0JmRlo/ml6/?hg=PoO4syC8qA to read your message 


The IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: a.iqelite.com/common/unsubscribe/?code=702826fa&email=reply@reply.github.com&hg=PoO4syC8qA
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------

**Comment by xcthulhu** [comment]
Bonjour,

Matthew  vient de s'inscrire sur IQ Elite. Il vous a écrit un message. 

Pour lire ce message avant qu'il n'expire, il suffit de cliquer sur le lien suivant : a.iqelite.com/entry/new_message/304c5d3a9b82edb35f6db34c2d3fda9e1f544b80bfb/320c612f7502fe03c666666899058907b3c897b6eccbeccbd67a867b667cb5852a9cb6eaf8abd82745f8275a867b6905f67af7452a85f897b513c587b897b8274c320c612f75044d3e22edb35af44b80bfb/?hg=FiIHr9n0lG

Lisez votre message avant qu'il ne disparaisse !            

Cordialement, 
L'équipe IQ Elite 



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=702826fa&email=reply@reply.github.com.&hg=FiIHr9n0lG
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by xcthulhu** [comment]
Bonjour,

Votre ami Matthew vous a envoyé un message il y a 36h jours, mais vous ne l'avez toujours pas lu. 

Le message sera supprimé dans 24 heures. 

Pour savoir ce que Matthew vous a écrit, cliquez ici : a.iqelite.com/entry/new_message/304c5d3a9b82edb35f6db34c2d3fda9e1f544b80bfb/320c612f7502fe03c666666899058907b3c897b6eccbeccbd67a867b667cb5852a9cb6eaf8abd82745f8275a867b6905f67af7452a85f897b513c587b897b8274c320c612f75044d3e22edb35af44b80bfb/?hg=tPeY08oD5i            

Cordialement, 
L'équipe IQ Elite 



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=702826fa&email=reply@reply.github.com.&hg=tPeY08oD5i
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by Kodiologist** [comment]
I agree with Paul. This isn't a bug. It could lead to a bug once we try to make hy2py create runnable Python code, but that's a separate, larger issue.
