### ISSUE TITLE
editor setup/etc

### ISSUE THREAD

**Issue by joefromct** [hylang/hy#605]
Paul, based on things i've come across you work in vim from what i can tell.

Is there any chance you can talk about your hy workflow and potentially lend some insight into how users could leverage the full power of a lisp-like-repl embedded in their editor? 

I'm very much use to clojure + vim + fireplace, and would love python interop with a hy type system.  I'm trying to research if there is anyway to link fireplace to a  hy repl... any tips appreciated.

Not sure if this is an issue, but i couldn't find a discussion board. If anything it's a documentation request on how to best do interactive development with hy.

Thanks, -Joe

**Comment by Kodiologist** [comment]
Now that support for both Emacs and Vim exists as separate repositories, we probably don't need this issue anymore.
