### ISSUE TITLE
More Explicit TCO instead of loop/recur?

### ISSUE THREAD

**Issue by mseri** [hylang/hy#609]
I just happened to read [New Tail Recursion Decorator (Python recipe)](http://code.activestate.com/recipes/496691/). 

I am very new to hy and cannot help/answer by myself yet, but I wonder if it would be possible to incorporate the idea in hy and get a more explicit form of TCO.

**Comment by allison-casey** [comment]
`loop/recur` has used a decorator implementation since 5a64f187264eef2ef9a8bcffac6ad3adc0ca5a3d and the link/website in question no longer works. closing
