### ISSUE TITLE
apply doesn't use shadowed operators

### ISSUE THREAD

**Issue by ccfontes** [hylang/hy#647]
Now this is possible:

``` clj
(let [[op +]] (apply op ["a" "b" "c"]))
```

and also this:

``` clj
(reduce + ["a" "b" "c"])
```

However this is not:

``` clj
(apply + ["a" "b" "c"])
```

which yields `HyTypeError: compiling the application of`+' didn't return a function call, but `BinOp'`

@paultag <b>says</b>:

Since it defers back to compile expression, it'll defer to @builds("+"), which means we get a BinOp back. Which is *hilarious&. At the top there should be a self.compile call since it'll actually treat the first argument as the argument in the call position when it needs to be an  ast.Call.

**Comment by Kodiologist** [comment]
Tested in [`test-apply-op `](https://github.com/hylang/hy/blob/eeb0be8fb0bdbd9d7d23dc908be2d24d4e475d0a/tests/native_tests/operators.hy#L289).
