### ISSUE TITLE
The lexer needs to be more informative

### ISSUE THREAD

**Issue by rcarmo** [hylang/hy#657]
I've just spent a long while trying to debug the following situation:
- `a.hy` had a single-quoted string (yeah, I know...)
- `b.hy` imported `a`

When trying to run `b.hy`, I got:

```
LexException: Could not identify the next token.
```

...without a single clue as to the file or line the error was actually in. So a little more information might save a lot of time...

**Comment by philiparvidsson** [comment]
This needs to be fixed as it is still an issue. I did some manual "binary search" by deleting chunks of code in a source file until finding the issue, but that is not always viable either. How about at least outputting the file, row and column of the previous token!?
