### ISSUE TITLE
Yield does not work inside nested `let` and `if`

### ISSUE THREAD

**Issue by svetlyak40wt** [hylang/hy#663]
Such code:

``` lisp
(let [[var 1]]
     (if var
         (yield "Hello")))
```

Compiles into:

``` python
def _hy_anon_fn_1():
    var = 1L
    return (yield u'Hello' if var else None)
_hy_anon_fn_1()
```

And return inside a generator leads to `SyntaxError: 'return' with argument inside generator` error.

**Comment by rcarmo** [comment]
Guys, this is starting to be a bit of a pain... Same issue, same kind of logic. Can we get a fix for this?

```hy
(defn map-coords [seq &optional[width 11] [height 11] [spacing 3]]
    (let [[x-inc (+ width spacing)]
          [y-inc (+ height spacing)]
          [x spacing]
          [y spacing]
          [month-offsets []]]
        (for [d seq]
             (let [[wday (% (+ 1 ( .weekday d)) 7)]]
                (if (= wday 6)
                    (do
                        (setv y spacing)
                        (setv x (+ x x-inc))))
                (print x y)
                (yield {:date d :x x :y y :width width :height height})
                (setv y (+ y y-inc))))))
```

**Comment by kirbyfan64** [comment]
@rcarmo You could always use `setv` as a workaround. Or:

```hy
(defmacro multi-setv [&rest args]
  `(do
    ~@(map (fn [[a b]] `(setv ~a ~b)) (zip (slice args nil nil 2) (slice args 1 nil 2)))))
```

Which would let you do:

```
(multi-setv [x-inc (+ width spacing)
                   y-inc (+ height spacing)
                   ...])
(continue work here)
```

**Comment by paultag** [comment]
or (yield-from (let )) - I had a PR for some of this before

On Wed, Jul 15, 2015 at 3:45 PM, Ryan Gonzalez <notifications@github.com>
wrote:

> @rcarmo <https://github.com/rcarmo> You could always use setv as a
> workaround. Or:
>
> (defmacro multi-setv [&rest args]
>   `(do
>     ~@(map (fn [[a b]] `(setv ~a ~b)) (zip (slice args nil nil 2) (slice args 1 nil 2)))))
>
> Which would let you do:
>
> (multi-setv [x-inc (+ width spacing)
>                    y-inc (+ height spacing)
>                    ...])
> (continue work here)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/663#issuecomment-121724682>.
>



-- 
:wq

**Comment by paultag** [comment]
The issue was (IIRC) figuring out when to trigger the yield-from

On Wed, Jul 15, 2015 at 3:46 PM, Paul R. Tagliamonte <paultag@gmail.com>
wrote:

> or (yield-from (let )) - I had a PR for some of this before
>
> On Wed, Jul 15, 2015 at 3:45 PM, Ryan Gonzalez <notifications@github.com>
> wrote:
>
>> @rcarmo <https://github.com/rcarmo> You could always use setv as a
>> workaround. Or:
>>
>> (defmacro multi-setv [&rest args]
>>   `(do
>>     ~@(map (fn [[a b]] `(setv ~a ~b)) (zip (slice args nil nil 2) (slice args 1 nil 2)))))
>>
>> Which would let you do:
>>
>> (multi-setv [x-inc (+ width spacing)
>>                    y-inc (+ height spacing)
>>                    ...])
>> (continue work here)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hylang/hy/issues/663#issuecomment-121724682>.
>>
>
>
>
> --
> :wq
>



-- 
:wq

**Comment by rcarmo** [comment]
Yeah, I ended up using setv instead. It's just that this is a very common pattern when you're building pipelines of infinite sequences - I get bitten by this bug every other week or so.

**Comment by gilch** [comment]
I think a fairly straightforward extension of my proposal in #664 would also work for `yield` inside `let`. Here's a possible Python translation for a contrived example.
```Python
(def test-yield []
  (setv foo 2)
  (setv bar 3)
  (let [[baz 5]]
    (yield foo)
    (yield bar)
    (yield baz)
    (setv foo (* 10 foo))
    (setv bar (* 100 bar))
    (yield foo))
  (yield foo)
  (yield bar))
def test_yield():
    foo = 2
    bar = 3
    _hy_anon_fn_1(foo=foo,bar=bar)
        baz = 5
        yield foo, (foo, bar)
        yield bar, (foo, bar)
        yield baz, (foo, bar)
        foo = 10 * foo
        bar = 100 * bar
        yield foo, (foo, bar)
    for _hy_anon_var_1, _hy_anon_var_2 in _hy_anon_fn_1():
        foo, bar = _hy_anon_var_2
        yield _hy_anon_var_1
    yield foo
    yield bar


```
A generator is not like a normal function. You don't just call it. Here when a `yield` is detected, Hy would invoke it with a for loop which updates the simulated nonlocals, then yields the intended value from outside the let. Notice that compiling it this way could also work for `yield` inside nested lets. Nonlocals and yield values will propagate out.

**Comment by zackmdavis** [comment]
@gilch clever!

**Comment by paultag** [comment]
That won't work for macro'd yields or coroutines that send values out. I
have half a PR using yield-from.

Perhaps I can hack on that again

**Comment by paultag** [comment]
This is tragically broken in like 3 ways, since we need to figure out if the yield is inside another function.

https://github.com/paultag/hy/commit/aa4dd40c46dc010e6145919f171e2d5f6e3b7823

I couldn't find my old code. I think it's what was behind the AST Macro bug

**Comment by paultag** [comment]
(this breaks in the following 5000 cases:)

  * `(let [[x 1]] (fn [] (yield 1)))`
  * `(let [[x [1 2]]] (yield-from x))`

**Comment by kirbyfan64** [comment]
I'm seriously saying: just dump this form of `let` and compile down to a `try...finally` block.

**Comment by paultag** [comment]
@kirbyfan64 Out of curiosity, why is this better than `(setv)` plain?

**Comment by paultag** [comment]
It'll still leak

```python
[tag@cassiel:~][⌚ 12:32 PM] ♥  python
Python 2.7.10 (default, Jul  1 2015, 10:54:53) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> try:
...     x = 1
... finally:
...     pass
... 
>>> print(x)
1
```

**Comment by kirbyfan64** [comment]
@paultag Try putting `del x` in the `finally` block.

**Comment by kirbyfan64** [comment]
@paultag Like:

```python
try:
    a = 5
finally:
    del a
print a
```

**Comment by paultag** [comment]
@kirbyfan64 I see what you're saying now --

so, what about things like `x` where you'd shadow the outer scope -- or if you try to do Let over Lambda (it'll silently fail in a kinda nasty way)

I think that what you're saying is a totally valid approach, I'm just not quite convinced using `del` on things in the `let` will work quite right. I'm open to examples of why i'm wrong, though!

**Comment by kirbyfan64** [comment]
@paultag Well, one could do something like:

```python
try:
    try:
       _some_magic_symbol = a
    except:
        _a_present = False
        _some_magic_symbol = None
    else:
        _a_present = True
    a = 123
finally:
    if _a_present: a = _some_magic_symbol
    else: del a
    del _some_magic_symbol
    del _a_present
```

**Comment by kirbyfan64** [comment]
There are a bunch of `let`-related issues open right now. I think we should probably make a new issue that condenses a TL;DR of each of these in order to clean up the issue tracker a bit.
