### ISSUE TITLE
implement return for generators

### ISSUE THREAD

**Issue by paultag** [hylang/hy#674]
including on python 2 via manual iteration munging -- we can avoid ast.Return for Py 2 - perhaps more macro work. 

``` hy
(defmacro/g! greturn [value]
  `(do
    (setv ~g!ex (StopIteration))
    (setv (. ~g!ex value) ~value)
    (raise ~g!ex)))
```

**Comment by allison-casey** [comment]
Obsolete since python2 is no longer supported and `return <value>` is syntactic sugar for `StopIteration(<value>)` since [PEP380](https://www.python.org/dev/peps/pep-0380/#use-of-stopiteration-to-return-values).

> return expr in a generator causes StopIteration(expr) to be raised upon exit from the generator.
