### ISSUE TITLE
disassemble utility for bytecode

### ISSUE THREAD

**Issue by theanalyst** [hylang/hy#676]
let's have a contrib for various stages of disassemble

```
<paultag> [21:09:45] Foxboron: what do you think of: (disassemble/ast
    '(1 2 3)) (disassemble/bytecode '(1 2 3))
<paultag> [21:09:54] Foxboron: where we do an ast pretty print or a
    dis.dis
<paultag> [21:10:11] perhaps a matching compile/ast and
    compile/bytecode
<Foxboron> [21:11:33] hurm
```

**Comment by Kodiologist** [comment]
This need is probably best addressed by compiling the Hy code into Python AST and then applying Python tools like the standard library `dis`. I don't think much is to be gained by adding wrappers for a simple and uncommon task such as that.
