### ISSUE TITLE
py2 `yield-from` fails to compile if the last item in a function is an expression.

### ISSUE THREAD

**Issue by pyos** [hylang/hy#691]
For example, this code:

``` hy
(defn g []
    (yield-from (f)))
```

gives a

```
SyntaxError: 'return' with argument inside generator (<input>, line 1)
```

Similarly, any function that has a return value (does not end with a statement that is not an expression?) does not work either:

``` hy
=> (defn g []
...   (raise a)
...   (if b (c "a" "b") d)
...   (yield-from e)
...   (h 1 2 3))
Traceback (most recent call last):
...
SyntaxError: 'return' with argument inside generator (<input>, line 1)
```

An example of a function that does compile:

``` hy
=> (defn g []
...   (yield-from (f))
...   (assert true))  ; note that assert does not have a return value
=> (g)
<generator object g at 0x7ff9dbfecc30>
```

**Comment by Kodiologist** [comment]
This one's still around as of 5bf9ecfc5a40821eb15e2ac7f218ae276f81fa60. That said, I'm inclined to think `yield-from` on Python 2 isn't worth supporting, so we should remove it rather than fix it.

**Comment by tuturto** [comment]
While it was really neat thing to support yield-from on Python 2, I think it's too much effort to keep supporting it now. I think we should stop supporting yield-from on Python 2.
