### ISSUE TITLE
Release 0.10.2

### ISSUE THREAD

**Issue by Foxboron** [hylang/hy#709]
Blockers:
- [ ] #707
- [x] #691 `yield-from` edge case
- [x] #692  `yield-from` edge case

Things we want:
So...what do we want?

Things we should consider:
- [ ] #676 
- [ ] #683 

Bring our yer bugs!
![](http://images.fanpop.com/images/image_uploads/Bring-Out-Your-Dead--monty-python-and-the-holy-grail-591430_800_441.jpg)

**Comment by berkerpeksag** [comment]
+1 for a new release. Already merged changes:

* #795
* #773 
* #762
* #763
* #756
* #795 
* #753

etc.

**Comment by paultag** [comment]
+1 for a release. I'll do it tonight.

On Sun, Apr 26, 2015 at 5:26 AM, Berker Peksag <notifications@github.com>
wrote:

> +1 for a new release. Already merged changes:
>
>    - #795 <https://github.com/hylang/hy/pull/795>
>    - #773 <https://github.com/hylang/hy/pull/773>
>    - #762 <https://github.com/hylang/hy/pull/762>
>    - #763 <https://github.com/hylang/hy/pull/763>
>    - #756 <https://github.com/hylang/hy/pull/756>
>    - #795 <https://github.com/hylang/hy/pull/795>
>    - #753 <https://github.com/hylang/hy/pull/753>
>
> etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/709#issuecomment-96352503>.
>



-- 
:wq

**Comment by Foxboron** [comment]
I think we need those `yield-from` bugs fixed before a release *looks at paultag*

**Comment by paultag** [comment]
Ach. OK, I'll look at work I need to do an PR them. Sorrrrryyyyy.

On Mon, Apr 27, 2015 at 11:26 AM, Morten Linderud <notifications@github.com>
wrote:

> I think we need those `yield-from` bugs fixed before a release *looks at
> paultag*
>
>
> On 04/27/2015 04:59 PM, Paul‮etnomailgaT‭ wrote:
> > +1 for a release. I'll do it tonight.
> >
> > On Sun, Apr 26, 2015 at 5:26 AM, Berker Peksag <notifications@github.com
> >
> > wrote:
> >
> > > +1 for a new release. Already merged changes:
> > >
> > > - #795 <https://github.com/hylang/hy/pull/795>
> > > - #773 <https://github.com/hylang/hy/pull/773>
> > > - #762 <https://github.com/hylang/hy/pull/762>
> > > - #763 <https://github.com/hylang/hy/pull/763>
> > > - #756 <https://github.com/hylang/hy/pull/756>
> > > - #795 <https://github.com/hylang/hy/pull/795>
> > > - #753 <https://github.com/hylang/hy/pull/753>
> > >
> > > etc.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/hylang/hy/issues/709#issuecomment-96352503>.
> > >
> >
> >
> >
> > --
> > :wq
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/hylang/hy/issues/709#issuecomment-96687927>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/709#issuecomment-96707659>.
>



-- 
:wq

**Comment by paultag** [comment]
I'm calling a punt on https://github.com/hylang/hy/issues/691 for this release

**Comment by paultag** [comment]
and punting on https://github.com/hylang/hy/issues/692 for this release too. Both are non-trivial at the moment.

**Comment by paultag** [comment]
Where we at on #707 ?

**Comment by zackmdavis** [comment]
(If I may be so bold, I would like to suggest merging #796 before a release&mdash;passing anonymous functions as arguments is the sort of thing that one would expect to work in a Lisp, and the three-line patch probably isn't very expensive to review.)

**Comment by paultag** [comment]
Let's add that as a blocker

**Comment by berkerpeksag** [comment]
Added and reviewed #796. Zack's patch LGTM.

**Comment by kirbyfan64** [comment]
If I may be crazy...what's the status of something like #740? I'd implement it, but no one said anything...

It would be nice to have before any breaking changes/more additions!

**Comment by paultag** [comment]
We can do https://github.com/hylang/hy/issues/740 on the next cycle, I'm doing a release now :)

**Comment by paultag** [comment]
Oh wait, we don't have NEWS. Can someone send up a NEWS? We're good to release once that's in master.
