### ISSUE TITLE
Hy command line swallows uncaught IOErrors

### ISSUE THREAD

**Issue by slimetree** [hylang/hy#714]
In `cmdline.py` we have

    # User did "hy <filename>"
    try:
        return run_file(options.args[0])
    except IOError as x:
        sys.stderr.write("hy: Can't open file '%s': [Errno %d] %s\n" %
                         (x.filename, x.errno, x.strerror))
        sys.exit(x.errno)

If a Hy program throws an uncaught `IOError`, the interpreter will print a mysterious `hy:
Can't open file...` instead of the usual traceback, which is confusing.

The only IO that `run_file` seems to do is call `importer.import_file_to_hst`. Maybe we could catch it there, and raise/catch a separate `HyIOError`?

**Comment by berkerpeksag** [comment]
Fixed in #763.
