### ISSUE TITLE
Can't use names of builtins as class variables

### ISSUE THREAD

**Issue by ALSchwalm** [hylang/hy#721]
Currently, the following code fails

    (defclass MyClass []
      [[eval 1]])

    HyTypeError: Can't assign to a builtin: `eval'

Note that adding the class variable with `setv` works as expected. So

    (setv MyClass.eval 1)

does not fail. The issue here is really that hy doesn't distinguish between builtin names and keywords. Python will disallow:

    class MyClass:
      True=10

But it would allow this with 'eval' or any other builtin.

**Comment by Foxboron** [comment]
closing this in favor for #783
