### ISSUE TITLE
Assignment to builtins and keywords

### ISSUE THREAD

**Issue by ALSchwalm** [hylang/hy#723]
Currently, hy disallows assignment to any builtin function/macro or keyword in any context. This can cause problems like issue #721  preventing 'eval' as a class variable. Python allows assignment to all builtins in any context. So

    # this works
    class MyClass:
      eval = 10
    
    # this too
    int = 100
    
There are a few possible solutions to this problem:

1. Allow assignment to any non-python keyword in any context. This creates the problem that 

        (defclass MyClass [] [[for 1]])  ; fails because 'for' is a python keyword
        (defclass MyClass [] [[for* 1]]) ; works because 'for*' isn't

2. Allow assignment to anything within a class body, but keep the current rules everywhere else. This creates the problem that

        (defclass MyClass [] [[True 1]]) ; Works, as anything goes inside a class body
        
        # But in python
        class MyClass: True=1 # cannot assign to a keyword

3. Allow assignment to builtins within class bodies, but keep the current rules everywhere else. This creates the same problem as in 1.

4. Maintain a list of those macros which are more like keywords, (let, with, etc) but not those that are like functions (list, eval). Call this the hy keyword list and prevent assignment to these in any context, but allow assignment to anything else in any context.

Personally, I don't think we can adopt any solution that causes special behavior for the builtins which happen to not be python keywords (i.e., 'for*'). This would be a pretty surprising behavior. Looking at the builtin macros, I don't really see anything except eval, list, eval_and_compile and maybe a few others that would belong in the 'builtin' list. So I'm thinking option 4 is probably the best bet. Of course, any other possible solutions are welcome.

**Comment by Foxboron** [comment]
closing this in favor for #783
