### ISSUE TITLE
apply does not work for assoc

### ISSUE THREAD

**Issue by JDaance** [hylang/hy#724]
So I was a bit naive and tried to write a function to help with dictionaries. In that process I discovered I cannot apply assoc at all. For example
```
=> (apply assoc [{} "a" 1])
File "<input>", line 1, column 8

(apply assoc [{} "a" 1])
^----^
HyTypeError: `assoc' needs at least 3 arguments, got 0.
```

On IRC I got the impression that this was expected since assoc is a special form. But the syntax for assoc is not very special and I think more people will run into stuff like this. It would be great if we could just apply it - if it can be solved implementation wise. Otherwise maybe it should print a better error like "You cant apply assoc because it is a special form". Or document apply to say that it does not work for the built ins.

**Comment by Foxboron** [comment]
closing in favor for #725
