### ISSUE TITLE
keyword? needs docs

### ISSUE THREAD

**Issue by tianon** [hylang/hy#730]
I can't seem to find anywhere that `keyword?` is documented to exist (sans the code itself, of course), but it definitely does. :+1:

**Comment by timmartin** [comment]
I'm not sure how I close this ticket, or if I even can.

**Comment by Foxboron** [comment]
You can't, but i will \o/

**Comment by tianon** [comment]
:+1: (sorry, honestly forgot this was my own issue, or I would've closed it myself :confounded:)
