### ISSUE TITLE
Nicer class definitions (defclassy?)

### ISSUE THREAD

**Issue by cwebber** [hylang/hy#731]
I find classes really hard to read in Hy... I'm sure I can't be the only one.  I'd like something that looks a bit more Python-like.  It would be fine if this was a macro.  It would be nice if there was an official one, so we don't have One Class Sugar Macro Per Package (TM).

How about something like this:

```clojure
(defclassy FooFighter [Fighter]
  "Everyone was Kung Foo Fighting"
  (class-arg fighter-type "Kung Foo Fighter")

  (class-method frobbed-instance [cls frobbed-args]
    (apply cls [] (defrob-args frobbed-args)))

  ;; This version uses basic --init-- construction with defmethod
  ;; Might be nice to have a special init form that takes care of
  ;; some of the redundant assignment stuff
  (defmethod --init-- [self hp kick-power]
    (setv self.hp hp)
    (setv self.kick-power kick-power)
    nil)

  (defmethod kick [self person-to-kick]
    "Kick that other person's butt"
    (person-to-kick.kicked self.kick-power)))
```

**Comment by algernon** [comment]
@cwebber, what do you think of the syntax in #875? Is that better, good enough?

If so, we may be able to close this issue.

**Comment by kirbyfan64** [comment]
Pretty sure this can be closed now.
