### ISSUE TITLE
Docs for interop: working with OO libraries

### ISSUE THREAD

**Issue by gknapp** [hylang/hy#735]
I think the documentation is sparse on examples of how to consume OO libraries. Common operations like passing constructor arguments, calling methods with args on the instance that was just instantiated.

Maybe include an example of using `argparse` or similar, the concepts can be translated by the reader to the particular library they're using.

**Comment by cwebber** [comment]
Now that we have keyword argument passing, maybe we could do some Django ORM examples?  That's something a lot of people are familiar with, and is very "OO-looking".

**Comment by justuswilhelm** [comment]
For the sake of brevity: How does a sample Flask project look like? For ORM it could use SQLAlchemy et al. The advantage is that it will fit in one module, whereas with Django it would typically be spread out over many modules.

**Comment by gilch** [comment]
Don't we have one of those? https://github.com/hylang/hy/blob/master/eg/flask/meth_example.hy

**Comment by paultag** [comment]
Yeah, but its ugly :) - I'll have to clean that up soon

**Comment by Kodiologist** [comment]
The new tutorial (#1811) has examples of working with objects, so I think we're good now.
