### ISSUE TITLE
Feature macros

### ISSUE THREAD

**Issue by refi64** [hylang/hy#740]
Reading #738 brought up an old idea I had lurking in my brain. The idea is for checking for Hy features. In short, you'd be able to write code like this:

``` clojure
(check-features some-hy-feature) ; throws FeatureError if some-hy-feature isn't present

(if (has-features some-other-feature) something something-else)

(check-features-msg "error message here" yet-another-feature)
```

Each Hy version would have a list of _features_ that it supports. That way, projects can easily check for needed features or use workarounds on older Hy versions.

This could also be used to retain compatibility if/when #652 gets merged:

``` clojure
(defmacro my-cut [&rest args]
    `(~(if (has-features slice-now-cut) `cut `slice) ~@args))
```

**Comment by calben** [comment]
Any work done on this?
Thinking I might raise this sucker from the dead and implement- seems like a really good idea.

**Comment by kirbyfan64** [comment]
I'm probably just going to implement this and open a PR, then you guys can discuss it there, considering the fact that I opened this 7 months ago and there's only 1 comment...

**Comment by Kodiologist** [comment]
This probably isn't worth implementing before 1.0 is out and we've added major features since then, which aren't in 1.0.

**Comment by minghu6** [comment]
en, I wonder how long before 1.0, do you have some plan about it. (it takes more than 5 years from initial project to v0.13.1 :anguished: , I  guess it should have v0.2 v0.3 ...)

**Comment by Kodiologist** [comment]
No, unfortunately we don't. Our developers are too unpredictably available for such a plan to be realistic.

**Comment by minghu6** [comment]
All rights, seems that I should write some monkey patch myself for new feature.

**Comment by Kodiologist** [comment]
At this point, I think that checking the version of Hy is a much better idea than trying to check for specific Hy features or bugfixes, and the best way to do this is probably in your package's dependency declarations (probably in `setup.py`) rather in the real code (although you can always check `hy.__version__` manually if you want to).
