### ISSUE TITLE
Line numbers can get lost for no apparent reason

### ISSUE THREAD

**Issue by kirbyfan64** [hylang/hy#742]
Example: putting an `(assert 0)` at the end of HyTest's main function yields this traceback:

```
Traceback (most recent call last):
  File "./hytest", line 9, in <module>
    res = main(*sys.argv)
  File "/media/ryan/stuff/hytest/hytest.hy", line 1603, in main

AssertionError
```

Line 1603? The entire file is only 347 lines? Why the heck does it say this?

**Comment by cwebber** [comment]
@kirbyfan64 What was the surrounding context?

Also see #741 which I just filed... which either you saw, or we have serious zeitgeist going on here.

**Comment by kirbyfan64** [comment]
@cwebber I put the `(assert 0)` in [this file](https://github.com/kirbyfan64/hytest/blob/master/hytest.hy) right before line 323.

**Comment by kirbyfan64** [comment]
HA! FIGURED IT OUT! (Not really, but close.) Here's a simple shell script that can be used to figure out line numbers. See [here](https://gist.github.com/kirbyfan64/7c8a2a65552108c76b7c). Basically, if you get a crazy ridiculous line number, the *real* line number can be found using:

```
crazy_line - (crazy_line / 256 * 256)
```

with integer division. Then find:


```
crazy_line + 256*0
crazy_line + 256*1
crazy_line + 256*2
...
```

until the number being added to `crazy_line` is greater than the number of lines in the file.

**Comment by Kodiologist** [comment]
I can't reproduce this, but reopen if you can.
