### ISSUE TITLE
Add hy-mode and vim-hy links to quick start and tutorial documentations

### ISSUE THREAD

**Issue by berkerpeksag** [hylang/hy#743]
- hy-mode: https://github.com/hylang/hy-mode
- vim-hy: https://github.com/hylang/vim-hy

**Comment by cwebber** [comment]
It seems hy-mode is in [melpa](http://melpa.org/), so that might make describing how to install with emacs easier.

**Comment by theanalyst** [comment]
Yep probably we can give links to both hy-mode: <githbub> <melpa>  sort of

**Comment by shrayasr** [comment]
This probably makes most sense to be in the [Protips](http://docs.hylang.org/en/latest/tutorial.html#protips) section?

**Comment by berkerpeksag** [comment]
We can create a new section "Editor plugins" in tutorial, or better we can create a new page "Tools" and add our editor plugins, IPython kernels, HyREPL, Sublime plugins etc. and then we can add cross references to http://docs.hylang.org/en/latest/tutorial.html and http://docs.hylang.org/en/latest/quickstart.html (see item 7)

**Comment by shrayasr** [comment]
> We can create a new section "Editor plugins" in tutorial, or better we can create a new page "Tools" and add our editor plugins, IPython kernels, HyREPL, Sublime plugins etc. 

If there are these many things to add, I think a "Tools" page makes sense.

>and then we can add cross references to http://docs.hylang.org/en/latest/tutorial.html and http://docs.hylang.org/en/latest/quickstart.html (see item 7)

Cross reference from where to these pages? "Tools", you mean?

**Comment by berkerpeksag** [comment]
> Cross reference from where to these pages? "Tools", you mean?

Sorry, yes I meant "tools" :)

**Comment by Kodiologist** [comment]
I'm closing this in favor of #605.
