### ISSUE TITLE
Move hylang/hy-style-guide to docs.hylang.org

### ISSUE THREAD

**Issue by berkerpeksag** [hylang/hy#744]
I saw a couple of questions about writing idiomatic Hy code on #hy. So it would be great to move hylang/hy-style-guide to our main repo to make it more visible and up-to-date.

**Comment by iKevinY** [comment]
I agree with migrating the style guide to the main Hy documentation; it seems a little strange to have a separate repository just for the style guide. I can work on this migration if no one has already started doing so.

**Comment by berkerpeksag** [comment]
@iKevinY please go ahead and a PR :)

**Comment by iKevinY** [comment]
Done! Having strange issues with some code block formatting, though.

**Comment by paultag** [comment]
:+1: thanks! :dancer:

**Comment by theanalyst** [comment]
Thanks @iKevinY :)
