### ISSUE TITLE
Using coll? on list in macro causes internal compiler error

### ISSUE THREAD

**Issue by Tritlo** [hylang/hy#758]
Example of code that fails:

    (import [flask [Flask render_template]])

    (def app  (Flask "__main__"))

    (defmacro defroute [route function]
      `(with-decorator ((. app route) ~route)
        ~function
        )
      )

    (defmacro/g! defroutes [routes function]
      (setv g!a [])
      (for [route routes]
        ((. g!a append) `((. app route) ~route)))
      `(with-decorator ~@g!a
        ~function
        )
      )

    (defmacro/g! endpoint [routes template &optional [args []] [opargs []] handler]
      (if (coll? routes)
          (setv g!b [routes])
          (setv g!b routes))
      `(defroutes  [~@g!b]
         (defn ~g!a [~@args &optional ~@opargs]
           (apply render-template [~template] (locals)))))

    (endpoint ["/<name>/" "/<name>/<phone>"] "yatta.html" ["name"] ["phone"])
    (endpoint "/" "yatta.html" )

results in:

    hy.errors.HyCompileError: Internal Compiler Bug 😱
    ⤷ TypeError: replace() takes at least 2 arguments (1 given)
    Compilation traceback:
    File "/home/tritlo/yatta-py/venv/lib/python3.4/site-packages/hy/compiler.py", line 420, in compile
        ret = self.compile_atom(_type, tree)
      File "/home/tritlo/yatta-py/venv/lib/python3.4/site-packages/hy/compiler.py", line 412, in compile_atom
        ret = _compile_table[atom_type](self, atom)
      File "/home/tritlo/yatta-py/venv/lib/python3.4/site-packages/hy/compiler.py", line 1723, in compile_expression
        expression = macroexpand(expression, self.module_name)
      File "/home/tritlo/yatta-py/venv/lib/python3.4/site-packages/hy/macros.py", line 173, in macroexpand
        tree = macroexpand_1(tree, module_name)
      File "/home/tritlo/yatta-py/venv/lib/python3.4/site-packages/hy/macros.py", line 205, in macroexpand_1
    obj.replace(tree)
      File "/home/tritlo/yatta-py/venv/lib/python3.4/site-packages/hy/models/list.py", line 31, in replace
    x.replace(other)
      File "/home/tritlo/yatta-py/venv/lib/python3.4/site-packages/hy/models/list.py", line 31, in replace
    x.replace(other)

**Comment by Tritlo** [comment]
Larme on irc seems to have a solution though.

**Comment by Tritlo** [comment]
Simpler example of failure:

    (defmacro/g! collf2 [liorstring]
      (if (coll? liorstring)
        (setv g!a liorstring)
        (setv g!a [liorstring]))
        `(print ~g!a))
(collf2 "str")

**Comment by larme** [comment]
I think 
```
  (if (coll? routes)
      (setv g!b [routes])
      (setv g!b routes))
```
should be
```
  (if (coll? routes)
      (setv g!b routes)
      (setv g!b [routes]))
```

**Comment by Tritlo** [comment]
yes, I'm starting to suspect that myself

**Comment by Kodiologist** [comment]
The "simpler example" above now works. I believe the underlying bug is covered by the `a-list` test in `native_macros.hy`. Could you close this, @gilch?

**Comment by gilch** [comment]
@Tritlo, @larme: @Kodiologist claims this has been resolved, so I'll close this for now, but if it's not resolved, I can re-open it.
