### ISSUE TITLE
and/or doesn't always short-circuit

### ISSUE THREAD

**Issue by kirbyfan64** [hylang/hy#766]
Example:

```
ryan@DevPC-LX:~$ hy --spy
hy 0.10.1 using CPython(default) 2.7.6 on Linux
=> (and 0 (assert 0))
assert 0L
(0L and None)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AssertionError
=> (or 1 (assert 0))
assert 0L
(1L or None)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AssertionError
=> 
```

I have a potential fix [here](https://github.com/kirbyfan64/hy/commit/d640f5e4a86f3ea1a18b7b8376794fb423df7612) that wraps the expression sides in lambdas, but it makes `defmacro/g!` and therefore 2.7's `yield-from` crash...

**Comment by zackmdavis** [comment]
Seems to be a manifestation of #233?
