### ISSUE TITLE
Message for asserts

### ISSUE THREAD

**Issue by thomasballinger** [hylang/hy#767]
It would be neat if asserts could have messages, as in

    (assert (= "a, b" (respace "a,b")) "should transform commas without spaces")

like Python has.

**Comment by thomasballinger** [comment]
@Foxboron points out this wouldn't be that complicated a change if it's desirable: https://github.com/hylang/hy/blob/master/hy/compiler.py#L1030

**Comment by paultag** [comment]
:+1: let's do this! Let's get a PR lined up and land it -- it's a widely used feature and I miss it too :)

**Comment by Foxboron** [comment]
@paultag Might have someone doing it already :D
