### ISSUE TITLE
Using < and > as first-class functions

### ISSUE THREAD

**Issue by nicolas-p** [hylang/hy#775]
Hello. While playing with Hy I found that I could do :
```hy
=> (list (map + [4 7 5 9] [1 9 4 2]))
[5, 16, 9, 11]
```
but not :
```hy
=> (list (map < [4 7 5 9] [1 9 4 2]))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name '<' is not defined
```
I was expecting :
```hy
[False, True, False, False]
```

hy 0.10.1 using CPython(default) 3.4.2 on Darwin

**Comment by paultag** [comment]
Yeah; we need a shaddow entry for these guys

**Comment by tianon** [comment]
I'm totally interested in tackling this if nobody else beats me to it. :innocent:

**Comment by tianon** [comment]
Got a working patch:
```console
hy 0.10.1 using CPython(default) 3.4.2 on Linux
=> (list (map < [4 7 5 9] [1 9 4 9]))
[False, True, False, False]
=> (list (map <= [4 7 5 9] [1 9 4 9]))
[False, True, False, True]
=> (list (map > [4 7 5 9] [1 9 4 9]))
[True, False, True, False]
=> (list (map >= [4 7 5 9] [1 9 4 9]))
[True, False, True, True]
```

On to tests!

**Comment by paultag** [comment]
\o/

On Wed, Mar 11, 2015 at 7:24 PM, Tianon Gravi <notifications@github.com>
wrote:

> Got a working patch:
>
> hy 0.10.1 using CPython(default) 3.4.2 on Linux=> (list (map < [4 7 5 9] [1 9 4 9]))[False, True, False, False]=> (list (map <= [4 7 5 9] [1 9 4 9]))[False, True, False, True]=> (list (map > [4 7 5 9] [1 9 4 9]))[True, False, True, False]=> (list (map >= [4 7 5 9] [1 9 4 9]))[True, False, True, True]
>
> On to tests!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/775#issuecomment-78394827>.
>



-- 
:wq
