### ISSUE TITLE
can't compile with RPython

### ISSUE THREAD

**Issue by yawnt** [hylang/hy#780]
I tried the example in the `eg/` folder and I get

```
[translation:ERROR] Exception: object with a __call__ is not RPython: <built-in function print>
[translation:ERROR] Processing block:
[translation:ERROR]  block@46 is a <class 'rpython.flowspace.flowcontext.SpamBlock'>
[translation:ERROR]  in (test:9)main
[translation:ERROR]  containing the following operations:
[translation:ERROR]        v1 = simple_call((function fib), v0)
[translation:ERROR]        v2 = simple_call((builtin_function_or_method print), v1)
[translation:ERROR]  --end--
```

ideas?
thanks!

PS: i'm using python2 on ArchLinux, the PyPy source I have is 3-2.4.0

**Comment by yawnt** [comment]
looks like the `print` call isn't python's standard print..

**Comment by Foxboron** [comment]
Rpython is a subset of python. It will probably never run on rpython alone.

**Comment by yawnt** [comment]
I talked to @paultag on Twitter and, to his knowledge, the RPy backend was still working.. as long as Hy doesn't do particular translation magic, it should work just fine..

**Comment by paultag** [comment]
Could you post the hy2py of your rhy script?

**Comment by yawnt** [comment]
here it is, might it be that I have python3 installed so it defaults to `print()` instead of `print`? How can I choose the python backend?
```
┌(yawnt@ehecatl) (iojs 1.2.0)
╰─(~/Code/hy/test/rpython)> hy2py test.hy
def fib(n):
    return (n if (n <= 2L) else (fib((n - 1L)) + fib((n - 2L))))

def main(argv):
    for x in [1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L]:
        print(fib(x))
    return 0L
```

I've currently fixed it with a workaround, anyway

```hy
(defn main [argv]
  (for [x [1 2 3 4 5 6 7 8]]
    (.pp target (fib x)))
  0)
```
in target.py
```python
...
def pp(what):
    print what
...
```

**Comment by kirbyfan64** [comment]
RPython doesn't support the print function; it only supports the print statement.

Also, I would just advise you don't use Hy with RPython. There are so many restrictions that there's bound to be other conflicts, probably with Hy's aggressive iterator usage (e.g. using itertools' `i*` functions.

I don't think RPython would play nicely with Hy's use-anything-as-an-identifier ability, either.

**Comment by yawnt** [comment]
yes, I'm playing a bit with it .. `map` doesn't seem to be working, although `for` compiles fine.. I wonder if it would make sense to write a contrib.rpyhon package with alternative implementations of core fns

**Comment by kirbyfan64** [comment]
Idea: add a `print2` function. It would only compile under Python 2 and would represent an actual `print` statement.

**Comment by Kodiologist** [comment]
I'm closing this in favor of the more general issue linked to above.
