### ISSUE TITLE
ap-each-while docstring is confusing

### ISSUE THREAD

**Issue by acron0** [hylang/hy#784]
[code - anaphoric.hy](https://github.com/hylang/hy/blob/master/hy/contrib/anaphoric.hy)

`Evalutate the body form for each element in the list while the predicate form evaluates to True.`

I believe that this should be amended to

`Evaluate the body form for each element in the list until the predicate form evaluates to False.`

I am happy to PR the amendment if people agree. I'd also pencil an addition to the ap macros - perhaps `ap-each-where` which fulfils the original docstring? i.e. `(ap-each-where [1 2 3 4] (% it 2) (print it)) => "1", "3"`

**Comment by theanalyst** [comment]
patches welcome :-)

**Comment by Kodiologist** [comment]
I don't think the original is any less correct than your proposal.
