### ISSUE TITLE
Hy in Hy

### ISSUE THREAD

**Issue by ntrifunovic** [hylang/hy#786]
Why not using **Hy** to develop **Hy** instead of **Python** :smiley: ?

Python sources could be generated for packaging and distribution.

**Comment by kirbyfan64** [comment]
Because the Python version of Hy code isn't always syntactically valid.

**Comment by agentultra** [comment]
You'd have to ship a Hy interpreter or ask the user have one in order to bootstrap it. 

If I ever finish my parser-combinator I can implement READ in Hy and we wouldn't need our present parser generator. 

But you'd still have to bootstrap it with Hy. :)

**Comment by Foxboron** [comment]
We have discussed if it's possible to generate a .pyc file with everything hy needs.
That would be interesting.

**Comment by Tritlo** [comment]
If we can ensure the correctness (at least for the compiler itself) of the
generated python code, this could be done. We'd just ship the generated
code, and use that to bootstrap the system.

**Comment by cwebber** [comment]
Would we lose out on interoperability with Python's wonderful world of libraries (arguably Hy's biggest selling point as a lisp?)

**Comment by agentultra** [comment]
No, since the output of the interpreter is still a Python AST; you’d still need a Python interpreter to consume it.

The fundamental difference would be that the artifact of bootstrapping a Hy interpreter is a Python module that is a Hy interpreter. All Hy-in-Hy is proposing is that we write Hy’s core in Hy instead of Python.

**Comment by kirbyfan64** [comment]
What about writing it in a subset of Hy that compiles down to normal Python code? For instance, this:

```hy
(def + 1)
```

would generate wrong Python code when given to hy2py but this:

```hy
(def x 1)
```

would work. Then the Python source files

**Comment by cwebber** [comment]
@agentultra :+1: then!  Thanks for the explaination.

**Comment by kirbyfan64** [comment]
Should this be closed now?

**Comment by Kodiologist** [comment]
I say yes; it would be a huge amount of work for almost no benefit.
