### ISSUE TITLE
Anaphoric threading macro

### ISSUE THREAD

**Issue by nicolas-p** [hylang/hy#787]
The threading macros `->`and `->>` are great but I encountered a case where the invisible argument had to be the fist argument in one function and the last one in other functions.

So I had to do it like this :
```hy
(-> filename 
    (loadmat :squeeze_me true) 
    (->> (keyfilter (fn [k] (not (in "__" k))))
         (valfilter (fn [v] (> (len v) 0)))
         DataFrame)))
```
I think this could be improved with an anaphoric threading macro modelled on `ap-map`, `ap-filter`, etc.
```hy
(ap-> filename 
      (loadmat it :squeeze_me true) 
      (keyfilter (fn [k] (not (in "__" k))) it)
      (valfilter (fn [v] (> (len v) 0)) it)
      DataFrame))
```
The name `ap->` is a bit ugly but it's the best I could think of.

**Comment by emidln** [comment]
In the Clojure Prismatic library, there is a function that converts --> to -> for individual elements: https://github.com/Prismatic/plumbing/blob/master/src/plumbing/core.cljx#L319

That said, an anaphoric version would probably read cleaner.

**Comment by nicolas-p** [comment]
Interesting... but you're right, it's quite hard to understand :

```hy
(->> filename 
    (<- (loadmat :squeeze_me true))
    (keyfilter (fn [k] (not (in "__" k))))
    (valfilter (fn [v] (> (len v) 0)))
    DataFrame))
```

**Comment by nicolas-p** [comment]
Actually, I think it would be better to name the macro `ap-pipe` and to have `ap-compose` as well :
```hy
(defn load [filename]
  (ap-pipe filename 
           (loadmat it :squeeze_me true) 
           (keyfilter (fn [key] (not (in "__" key))) it)
           (valfilter (fn [values] (> (len values) 0)) it)
           DataFrame)))
```
```hy
(def load
  (ap-compose (loadmat it :squeeze_me true) 
              (keyfilter (fn [key] (not (in "__" key))) it)
              (valfilter (fn [values] (> (len values) 0)) it)
              DataFrame)))
```

**Comment by emidln** [comment]
Why do you need two macros if you specify positioning with `'it`?

**Comment by nicolas-p** [comment]
The second one is for function composition. It takes only functions as arguments.

**Comment by emidln** [comment]
Right. That makes sense.

**Comment by jaredly** [comment]
The original example works fine as

```
(->> 
     (loadmat filename :squeeze_me true)
     (keyfilter (fn [k] (not (in "__" k))))
     (valfilter (fn [v] (> (len v) 0)))
     DataFrame))
```

But, if this anaphoric macro is going forward, it might be clearer if some sigil were used instead of the variable-looking `it`. Something like `@`

**Comment by paultag** [comment]
PR from @nicolas-p was merged, closing this ticket! Thank you!
