### ISSUE TITLE
how to multiline comment ?

### ISSUE THREAD

**Issue by acekingke** [hylang/hy#789]
# just single comment?
; as comment
but I enjoy the multiline comment like C languange /**/

**Comment by paultag** [comment]
You can use a bare quote, and use a string, like many python people do :)

**Comment by emidln** [comment]
```hy
(defmacro comment [& body] nil)
```

**Comment by paultag** [comment]
(while fun, this also requires valid syntax inside the comment)

On Tue, Apr 7, 2015 at 9:39 AM, Brandon Adams <notifications@github.com>
wrote:

> (defmacro comment [& body] nil)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/789#issuecomment-90557073>.
>



-- 
:wq

**Comment by emidln** [comment]
Well, yes. To be fair, most things ar valid syntax if they're not being evaluated.

**Comment by paultag** [comment]
Sure :)

On Tue, Apr 7, 2015 at 9:43 AM, Brandon Adams <notifications@github.com>
wrote:

> Well, yes. To be fair, most things ar valid syntax if they're not being
> evaluated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/789#issuecomment-90557768>.
>



-- 
:wq

**Comment by theanalyst** [comment]
This works as a reader macro as well, which ignores the form supplied  :-)
```
=> (defreader _ [&rest body] nil)
=> #_(foo bar)
```

**Comment by acekingke** [comment]
thank you very much ,the macro can work well

**Comment by theanalyst** [comment]
Hope your issue is solved. Feel free to ask if not the case
