### ISSUE TITLE
Trying to use single quotes for a string gives obscure error (UnboundLocalError)

### ISSUE THREAD

**Issue by jaredly** [hylang/hy#790]
Doing this:
```clojure
(print 'hi')
```

Results in:
```
LexException: Could not identify the next token.
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
UnboundLocalError: local variable 'tokens' referenced before assignment
```

Which is confusing...

**Comment by paultag** [comment]
because ' is quote, use " :)


On Tue, Apr 7, 2015 at 11:54 AM, Jared Forsyth <notifications@github.com>
wrote:

> Doing this:
>
> (print 'hi')
>
> Results in:
>
> LexException: Could not identify the next token.
> ---------------------------------------------------------------------------
> UnboundLocalError                         Traceback (most recent call last)
> UnboundLocalError: local variable 'tokens' referenced before assignment
>
> Which is confusing...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/790>.
>



-- 
:wq

**Comment by paultag** [comment]
to be clear, quote as in a quoted form, which is to say - 'foo is valid
syntax

On Tue, Apr 7, 2015 at 11:54 AM, Paul R. Tagliamonte <paultag@gmail.com>
wrote:

> because ' is quote, use " :)
>
>
> On Tue, Apr 7, 2015 at 11:54 AM, Jared Forsyth <notifications@github.com>
> wrote:
>
>> Doing this:
>>
>> (print 'hi')
>>
>> Results in:
>>
>> LexException: Could not identify the next token.
>> ---------------------------------------------------------------------------
>> UnboundLocalError                         Traceback (most recent call last)
>> UnboundLocalError: local variable 'tokens' referenced before assignment
>>
>> Which is confusing...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hylang/hy/issues/790>.
>>
>
>
>
> --
> :wq
>



-- 
:wq

**Comment by jaredly** [comment]
Right, I know this is wrong syntax. The error message is confusing though. Why an `UnboundLocalError`?

**Comment by paultag** [comment]
I don't get that, funny :)

```
[tag@helios:~/dev/sunlight/moxie-jobs][⎇  master] ♥  hy
hy 0.10.1 using CPython(default) 3.4.2 on Linux
=> (print 'foo')
LexException: Could not identify the next token.

=>
```

Which is the "right" error, I guess. We could make it better, I guess, have
a patch in mind?



On Tue, Apr 7, 2015 at 2:48 PM, Jared Forsyth <notifications@github.com>
wrote:

> Right, I know this is wrong syntax. The error message is confusing though.
> Why an UnboundLocalError?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/790#issuecomment-90695645>.
>



-- 
:wq
