### ISSUE TITLE
(feature request) function argument destructuring

### ISSUE THREAD

**Issue by jaredly** [hylang/hy#792]
In clojure, I can do
```clojure
(defn awe [[x y]] (+ x y))
(awe [2 3]) ; => 5
```
But not in hy :( destructuring within a `let` works just fine though.

Why is this useful? A larger example
```clojure
(map
  (fn [[x y]] (, (int x) y)))
  (.items my-dictionary))
```

Which otherwise needs to be one of
```clojure
(map
  (fn [args] (let [[[x y] args]] (, (int x) y))))
  (.items my-dictionary))
```
or
```clojure
(map
  (fn [args] (, (int (. args [0]) (. args[1]))))
  (.items my-dictionary))
```

**Comment by kirbyfan64** [comment]
This is pretty simple to implement yourself:

```hy
(import [hy.models.symbol [HySymbol]] [hy.models.list [HyList]])

(defmacro fnd-base [inv ext args body]
  (setv skipx false)
  (setv argr [])
  (for [arg args]
    (argr.append arg)
    (when skipx
      (setv skipx false)
      (continue))
    (when (isinstance arg HySymbol)
      (setv skipx true)
      (continue))
    (when (isinstance arg HyList)
      (setv oldarg arg)
      (setv arg (gensym))
      (assoc argr (dec (len argr)) arg)
      (setv body (+ [`(setv ~oldarg ~arg)] body))))
  `(~inv ~@ext [~@argr] ~@body))

(defmacro fnd [args &rest body]
  `(fnd-base fn [] [~@args] [~@body]))

(defmacro defnd [name args &rest body]
  `(fnd-base defn [~name] [~@args] [~@body]))
```

Pop it into a file named `fnd.hy` and use it like so:

```hy
(require fnd)

; fnd instead of fn
((fnd [[x y]] (print x y)) [1 2])

; defnd instead of defn
(defnd myfunc [[x y]]
  (print x y))

(myfunc [1 2])
```

**Comment by jaredly** [comment]
but why not have it be a language feature? Python already has function argument destructuring built-in

**Comment by paultag** [comment]
That's Python 2 only - and I think we can make it work by fixing the
argument compiles --

with hy --spy:

```
=> (defn x [(, a b)])
def x((u',' u'a' u'b')):
    pass
=>
```

appears to be buggy

On Tue, Apr 7, 2015 at 3:23 PM, Jared Forsyth <notifications@github.com>
wrote:

> but why not have it be a language feature? Python already has function
> argument destructuring built-in
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/792#issuecomment-90705742>.
>



-- 
:wq

**Comment by kirbyfan64** [comment]
#793

**Comment by jaredly** [comment]
@kirbyfan64 that was fast! :+1:
