### ISSUE TITLE
Why & cannot work?

### ISSUE THREAD

**Issue by acekingke** [hylang/hy#794]
#  Why & cannot work?
=> (defn count-args [& args]
...   (str "You passed " (count args) " args: " args))
=> (count-args 1 2 3)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: count_args() takes exactly 2 arguments (3 given)

**Comment by berkerpeksag** [comment]
Hi! You can use `&rest`:

```hy
=> (defn count-args [&rest args]
...  (print "You passed" (len args) "args:" args))
=> (count-args 1 2 3)
You passed 3 args: (1L, 2L, 3L)
```

**Comment by berkerpeksag** [comment]
And see also http://docs.hylang.org/en/latest/language/api.html#defn-defun

**Comment by paultag** [comment]
I'm going to close this since @berkerpeksag points out the clojure `& foo` is `&rest foo` here :)
