### ISSUE TITLE
about range

### ISSUE THREAD

**Issue by acekingke** [hylang/hy#797]
In clojure , It can use

(take 4 range)
but in hy It can make it so easy ?

**Comment by kirbyfan64** [comment]
???

If you're referring to getting the numbers from 0 to 4, just use `(range 4)`...

**Comment by paultag** [comment]
Let's keep it productive, things like "???" aren't helpful.

I think this is talking about range being a generator of infinate numbers - perhaps itertools.count?

```hy
=> (import itertools)
=> (take 4 (itertools.count))
<itertools.islice object at 0x7f69d8dcb4a8>
=> (list (take 4 (itertools.count)))
[0, 1, 2, 3]
```

**Comment by kirbyfan64** [comment]
@paultag Yeah, you're right; [Clojure's range is an infinite stream of numbers](https://clojuredocs.org/clojure.core/range). I've never used Clojure, so I misunderstood the statement.

**Comment by algernon** [comment]
Since this is doable in Hy, using `itertools.count`, I'm closing this issue. Our range is python's range, which works the way it does.
