### ISSUE TITLE
Provide mechanism for redefining/extending builtins

### ISSUE THREAD

**Issue by kitsu** [hylang/hy#804]
I want to use Pyrsistent with Hy. Ideally I would replace all data literals with versions that create immutable versions. In reality I planned to create reader macros to get close. I also want to replace data manipulation functions with Pyrsistent analogs. This seems impossible:

    hy 0.11.0 using CPython(default) 2.7.8 on Windows
    => (defn assoc [d k v] (print "redef!"))
      File "<input>", line 1, column 7

      (defn assoc [d k v] (print "redef!"))
            ^----^
    HyTypeError: Can't assign to a builtin: `assoc'

I would really like something like Clojure's protocols where interfaces could be extended to existing types. Then the assoc could be extended to work on arbitrary data types by the user at run time...

Here is a good SO post explaining why protocols: http://stackoverflow.com/questions/5986120/clojure-defprotocol-as-a-solution-to-the-expression-problem

(Having written no code) it seems trivial to implement something like protocols in Python/Hy. Even if I did implement something I wouldn't be able to modify assoc though because, as per another issue, assoc isn't a function but emits AST for the Python statement `d[key]=value`.

I might have a go at implementing protocols in Hy anyway. Here is a link mainly for my own reference: https://github.com/clojure/clojure/blob/master/src/clj/clojure/core_deftype.clj#L508

**Comment by Foxboron** [comment]
I'd say go for it. The limitations with built-ins could very well be worked around.

**Comment by agentultra** [comment]
Why not just sub-class the types you’re interested in and make them quack for assoc? “Duck typing,” is a kind of protocol. :)

**Comment by kitsu** [comment]
You could maybe implement __getitem__ and __setitem__ in this case and get the built-in assoc working, but protocols are a more general solution. Protocols are about open extension, adding features to someone else's objects without modifying its code or monkey patching.

Here is a gist where I've sketched part of a protocol implementation: https://gist.github.com/kitsu/83d0120b5ef3ba783940

It still needs a lot of machinery for grouping functions in actual protocols and extending those sets over existing types. Then all that machinery can be hidden on the Hy side with some nice macros.

**Comment by agentultra** [comment]
This isn't the first time someone has tried these ideas in Python and I've never been convinced of their utility. 

It seems like a YAGNI for me without some hard evidence. 

Try it out in your project and give us some concrete examples of how it has improved your code!

**Comment by kitsu** [comment]
It seems the author of [PEP0443](https://www.python.org/dev/peps/pep-0443/) and the python devs that included it in [Python 3.4](https://docs.python.org/3/library/functools.html#functools.singledispatch) disagree with you. Also, I'm proposing adding this to Hy, not Python. Just because you are not enamored of an idea in an imperitive/OOP setting doesn't mean it has no use.

**Comment by algernon** [comment]
Protocols would be lovely to have. That would make a lot of things in adderall a lot easier, and a number of features that I'd love, possible.
