### ISSUE TITLE
Does hy Has lazier ?

### ISSUE THREAD

**Issue by acekingke** [hylang/hy#808]
In clojure , It can write like here
```
(defn lazy-seq-fibo 
    ([] 
        (concat [0 1] (lazy-seq-fibo 0 1))) 
    ([a b] 
        (let [n (+ a b)] 
            (lazy-seq 
                (cons n (lazy-seq-fibo b n))))))
```

But how to make it in Hy?

**Comment by theanalyst** [comment]
Not lazy seq as such.. though you can achieve partly using generator
expressions.. an example in the core docs
http://docs.hylang.org/en/latest/language/core.html#sequence-functions

**Comment by acekingke** [comment]
Thank you very much
