### ISSUE TITLE
using "numb" module with Hy : "with-decorator" fails.

### ISSUE THREAD

**Issue by youngsu999** [hylang/hy#811]
Numba is JIT compiler with LLVM.

http://numba.pydata.org/numba-doc/0.13/index.html

It provides easy way to writing efficient code and i thought that it will be awesome if hy can use this module.

I just tried convert following python code into hy code

> from numba import jit
> 
> @jit
> def sum(x, y):
>    return x + y

and get following results.

=> (import [numba [jit]])
=> (with-decorator jit (defn sum [x y](+ x y)))
=> (sum 1 2)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\numba\dispatcher.py", line 162, in _compile_for_args
    return self.compile(sig)
  File "C:\Anaconda\lib\site-packages\numba\dispatcher.py", line 305, in compile
    flags=flags, locals=self.locals)
  File "C:\Anaconda\lib\site-packages\numba\compiler.py", line 563, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Anaconda\lib\site-packages\numba\compiler.py", line 301, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "C:\Anaconda\lib\site-packages\numba\compiler.py", line 310, in compile_bytecode
    return self._compile_bytecode()
  File "C:\Anaconda\lib\site-packages\numba\compiler.py", line 550, in _compile_bytecode
    return pm.run(self.status)
  File "C:\Anaconda\lib\site-packages\numba\compiler.py", line 199, in run
    raise patched_exception
KeyError: "Failed at object (object mode backend)\n'__console__'"

Is there any way to apply the "jit" decorators to the hy functions objects?

**Comment by berkerpeksag** [comment]
I don't have numba installed, so didn't tried, but looks like:
```
(with-decorator jit (defn sum x y))
```
should be
```clj
(with-decorator jit (defn sum [x y] (+ x y)))
````

**Comment by wuxianliang** [comment]
it works.
```hy
(import [numba [jit]])
(with-decorator jit (defn sum [x y] (+ x y)))
```

Should we make a new keyword "defn-jit" for defining functions with numba ( JIT )  as default? @berkerpeksag 

```hy
(defn-jit sum [x y] (+ x y))
```
or "defnj" for short
```hy
(defnj sum [x y] (+ x y))
```

**Comment by berkerpeksag** [comment]
I think it's easy enough to implement in your code via using decorator syntax or macros :)

**Comment by kirbyfan64** [comment]
@wuxianliang It doesn't need to be a keyword:

```hy
(defmacro defn-jit [&rest args]
  `(with-decorator jit (defn ~@args)))
```

**Comment by wuxianliang** [comment]
@kirbyfan64 Thank you! This is my first day with Hy! Macros!

**Comment by Kodiologist** [comment]
Looks like everybody's happy here.
