### ISSUE TITLE
Generated code using shadow isn't valid python?

### ISSUE THREAD

**Issue by bollwyvl** [hylang/hy#812]
Over on https://github.com/bollwyvl/hy_kernel/issues/5 it has been noted that trying to use the shadowed forms of operators as functions fails. 

Upstream, it seems unlikely that `from hy.core.shadow import *` is ever going to behave as expected.

**Comment by paultag** [comment]
Yeah, a lot of code Python creates isn't valid Python --

from `hy --spy`

```hy
=> (defn foo! [] (print "Hi!"))
```

```python
def foo!():
    return print('Hi!')
```

Because we never write out Python, it works, since we write AST, not Python source :)

There are bunches of things hy2py won't get right, and I don't think anyone's pushed for it to be more than a debugging mode -- is there a reason you're using the source and not the AST?

**Comment by bollwyvl** [comment]
Thanks for the response.

Seems like this makes it hard to write things in hy which normal py users could use... from the whole JS/Coffee/Typescript debacle, it's at least usually the case that one can use the output of a transpiler in the upstream language.

I've taken the approach out of defensive laziness, I suppose. By handing over generated python code, I can reuse everything in the upstream IPythonKernel. History, magics, widgets, tracebacks, documentation, autocomplete, etc. Some of them are lies, as they are text-based and therefore based on python and not hy, but I'm handling them as I figure out sane ways to wrap them,

Of course, deep down, [IPython's shell](https://github.com/ipython/ipython/blob/3.x/IPython/core/interactiveshell.py#L2870) is generating and executing AST nodes, just from python source, but only after (potentially) doing quite a bit of other hackery to it.

I explored monkeypatching the Kernel's shell, (and _m_ of its _n_ super/sub classes, and users along the way), but haven't figured out how to preserve the text-based features... and even if I was able to achieve feature parity, I would be able to keep up with the upstream in terms of re-implementing features... the very features a user would be using Jupyter for in the first place. As it is, I have to give up a good number of features as some are line-and-whitespace sensitive.

**Comment by Foxboron** [comment]
```Seems like this makes it hard to write things in hy which normal py users could use... from the whole JS/Coffee/Typescript debacle, it's at least usually the case that one can use the output of a transpiler in the upstream language.```

Well no. Python never see the "literal Python" we can generate from the "invalid" AST. Python only see the AST. So the AST we generate is valid Python AST, but not really valid "literal Python". We also generate variables like `:something = 123` which can't be parsed. But the AST is actually more flexible then Python itself.

**Comment by paultag** [comment]
@bollwyvl and just to expand on @Foxboron - we interop in both directions, 100% - the issue is we only target the AST, not code - we don't output templated Python, we construct Python AST -- stuff like `pdb` works on Hy, and it works because of how careful we are -- we just don't target the Python *source*, we target the Python *runtime*

**Comment by paultag** [comment]
Just to drive the point home a bit more::

```
(hy)[tag@sol:~][⌚ 04:13 PM] ♥  cat foo.hy 
(defn square [x] (* x x))
(hy)[tag@sol:~][⌚ 04:13 PM] ♥  cat bar.py 
import hy
import foo

print(foo.square(8))
(hy)[tag@sol:~][⌚ 04:14 PM] ♥  python bar.py 
64
(hy)[tag@sol:~][⌚ 04:14 PM] ♥  
```

**Comment by paultag** [comment]
As for `*`, after thinking about it and looking at the AST, you're both right and it still works, since it imports everything from shadow (perhaps not the best idea, I wonder if we should change up how we handle bar names to do an attr lookup rather) :)

**Comment by paultag** [comment]
```
=> (let [[x *]])
<function * at 0x7eff419772f0>
=> (get (locals) "*")
<function * at 0x7eff419772f0>
=> (get (locals) "+")
<function + at 0x7eff419771e0>
=> 
```

**Comment by bollwyvl** [comment]
With respect to publishing, I was referring to the example just given where a potentially useful thing would not be importable through standard means due to the developer's choice of naming:

```py
#some.py
from some_hy import foo!
```

I suppose it might be possible to use importlib with the module.

The star joke was a pun: if you're trying to import multiplication, you call it `*`: if you want to implement everything you call it... `*`. So "expected" depends on how you see the world.

I am certainly not arguing anything about the value of AST vs. source, I just was fishing for an The Decision. If the stance is, "generating valid python utf-8 source is never going to be a concern," that's great and fine, and my caveat that hy_kernel for the time being can't do some hy stuff will stand, and I'll keep looking for some way to keep the text-based features of IPython, while exposing successively more of the Truth of Hy!

**Comment by Foxboron** [comment]
@bollwyvl Not at all trying to sound harsh. Just trying to explain how Hy interacts with the Python world ^^

**Comment by paultag** [comment]
@bollwyvl Yeah, I think the team here largely considers the generation of Python source code largely a byproduct of our debugging techniques, and not as a first-class target -- I'm open to work making it more supported, but I'm not sure how much work that'd be

We provide nearly identical interface(s) as Python's internals, so if the Python kernel can do X, I'm positive we can land support for a modified X that also works with Hy, but just talks AST, or shims out (e.g. our PEP302 loader, etc)

BTW; I love your work on hy_kernel, thanks so much for working on it :)

**Comment by paultag** [comment]
@hylang/core - if anyone disagrees, please speak up :) :+1:

**Comment by Kodiologist** [comment]
Seems like everybody's happy here.
