### ISSUE TITLE
Unary divide

### ISSUE THREAD

**Issue by gilch** [hylang/hy#825]
My understanding of the design goals of Hy is to be homoiconic Python. I think Python libraries + Lisp macros = awesome. From reading the Hy Style guide, the design guidelines seem to be defer to Python3, to Clojure, to Common Lisp, in that order. I think that's a great plan. Clojure seems to be very well designed.

So where's the unary divide?
```Lisp
;;; Clojure
user=> (/ 2)
1/2

;;; Common Lisp
* (/ 2)
1/2

;;; Hy
;; Guesses anyone? Sadly, Python doesn't have a ratio type and neither does Hy.
;; But at least you'd expect (/ 1 2) to equal (/ 2), right?
=> (/ 1 2)
0.5
;; Wrong.
=> (/ 2)
  File "<input>", line 1, column 1

  (/ 2)
  ^---^
HyTypeError: `/' needs at least 2 arguments, got 1.
```
Yeah, I was surprised too. Is this a bug? Or a design oversight?

Python doesn't have a unary divide, so I have to assume this was on purpose and plead my case. But you know, it doesn't have a ternary divide either, and yet this seems to work fine:
```Lisp
=> (/ 6 3 2)
1.0
```
One might argue that this changes the semantics of divide. The first number should be the dividend, and the rest divisors. Now you're dividing an implicit 1. Well, yeah, you need a divisor, or it's not division. But you have to realize that unary minus already works the same way:
```Lisp
=> (- 0 2)
-2
=> (- 2)
-2
```
You're subtracting from an implicit 0. Why break the symmetry?

We can't defer exactly to Python in all cases, or Hy would still be Python. There is sufficient reasonable doubt about designing it Python's way. We should defer to our fallback guides of Clojure and Common Lisp, which both agree on this point. Unary minus means additive inverse; unary divide means multiplicative inverse. I have yet to meet another lisp with Hy's problem. Even Scheme does it this way.
```Scheme
;;; R5RS
> (/ 2)
1/2
```
It should be the same in Hy:
```Lisp
;;; doesn't actually work in Hy yet.
=> (/ 2)
0.5
```

I could be wrong here, but it doesn't *seem* like a particularly difficult fix. I could almost write a macro to insert the implicit 1 in case of one argument, but I don't think I can override the built-in symbols. 

This change also shouldn't break any existing Hy code.

Objections?

Actually Python DOES have a ratio type:
```Python
# Python3
>>> from fractions import Fraction
>>> Fraction(16, -10)
Fraction(-8, 5)
```
Hy could definitely make Fraction prettier with ratio literals like all the other Lisps. It's something to think about, but I think it's a separate issue from the strangely lacking unary division. I must concede that integer division returning floats is more consistent with the way Python3 works.

**Comment by paultag** [comment]
@gilch let's break this into two - first is lack of `(/ 2)` support. I think that's not bad. Let's add it. 

Here's how it was added for plus - https://github.com/hylang/hy/blob/master/hy/compiler.py#L1725

Also let's double check on the shadow opers

**Comment by paultag** [comment]
Second: the fraction type. Interesting idea. Can we file a second bug on that and see what we can do there?

**Comment by gilch** [comment]
I'll submit another one for the ratio literals.

**Comment by kirbyfan64** [comment]
What I'm envisioning (here I'm going to use `\` for a fraction literal):

```hy
(/ x) => (/ 1 x) ; reciprocal, like K
(\ x y) => (Fraction x y)
(\ y) => (Fraction 1 y)
```

**Comment by paultag** [comment]
Good gut, but I'm thinking that might be a bit confusing.

I'm mostly worried about how this interacts with code that expect a Long or
something.

Explicitly doing this won't be the end of the world (esp. with macros), but
some sort of contrib addon would be interesting.



On Fri, Jun 26, 2015 at 3:34 PM, Ryan Gonzalez <notifications@github.com>
wrote:

> What I'm envisioning (here I'm going to use \ for a fraction literal):
>
> (/ x) => (/ 1 x) ; reciprocal, like K
> (\ x y) => (Fraction x y)
> (\ y) => (Fraction 1 y)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/825#issuecomment-115849202>.
>



-- 
:wq

**Comment by kirbyfan64** [comment]
@paultag 

> I'm mostly worried about how this interacts with code that expect a Long or
something.

?? I'm not quite sure why `(= (/ 2) 0.5)` would cause any more trouble with longs than Python 3's float division. Or are you referring to something else?

**Comment by gilch** [comment]
I opened #826 Ratio Literals.
@kirbyfan64 I don't think we need a new divide operator, since Python's fractions aren't exactly the same as Lisp ratios anyway:
```Clojure
;;; Clojure
user=>(/ 3 1/2 )
6N
```
Notice it was coerced into an integral type (I think that's a Java BigInt, I'm still learning Clojure).
```Python
# Python
>>> 3 / Fraction("1/2")
Fraction(6, 1)
```
Notice it's still a Fraction.

I think it should work like this:
```
=> 1/1
Fraction(1, 1)
=> (/ 1/1 2)
Fraction(1, 2)
=> (/ 1 2)
0.5
```
The 1/1 is an "atom" not an operation.

**Comment by kirbyfan64** [comment]
@gilch @paultag Ah! I personally do not like `\`; I was just using as an example. :)
