### ISSUE TITLE
Ratio Literals

### ISSUE THREAD

**Issue by gilch** [hylang/hy#826]
Lisps typically have a built in ratio type with corresponding literal syntax:
```Clojure
;;; Clojure
user=> (+ 1/6 1/3)
1/2
```
Python does have a near-equivalent fraction type, but the syntax is awkward:
```Python
# Python3
>>> from fractions import Fraction
>>> Fraction(1, 6) + Fraction("1/3")
Fraction(1, 2)
```
Hy could definitely make Fraction prettier with ratio literals like all the other Lisps.

**Comment by gilch** [comment]
I would suggest a literal syntax for Fraction "atoms" (oxymoron?). Like so:
```
; >>> # Python equivalents
; >>> Fraction("1/1")
=> 1/1
Fraction(1, 1)
; >>> Fraction("1/2")
=> 1/2
Fraction(1, 2)
; >>> Fraction("2/4")
=> 2/4
Fraction(1, 2)
; >>> 2 * Fraction("-1/2")
=> (* 2 -1/2)
Fraction(-1, 1)
```
Any symbol with an included `/` that has valid integers on either side would be passed to the Fraction constructor as a string behind the scenes. Fraction will have to be automatically imported if used.

**Comment by kirbyfan64** [comment]
Taking a stab at this: do you guys want a model for this (e.g. `HyFraction`) or just return a `HyExpression` that constructs a fraction from `t_identifier`?

**Comment by gilch** [comment]
I believe #828 addresses this. I'm closing it.
