### ISSUE TITLE
Set literals

### ISSUE THREAD

**Issue by gilch** [hylang/hy#827]
I'm not sure if this has be discussed before. "Set" is not a good search term.
Python has set literal syntax:
```Python
# Python3
>>> {3, 2, 2, 1}
{1, 2, 3}
# Python2.7
>>> {3, 2, 2, 1}
set([1, 2, 3])
```
Let's try that in Hy.
```
=> {3 2 2 1}
{2: 1, 3: 2}
```
Ah I see, that's a dictionary. Clojure does it the same way:
```Clojure
user=> {3 2 2 1}
{3 2, 2 1}
```
I noticed the comma between pairs. To Clojure this is mere whitespace. Maybe we could pair things this way in Hy? That way we would have both dictionary and set syntax. But the `,` is used for tuples now. I *like* Hy's `(, "I'm" "a" "tuple")` syntax and don't want to break it.

Remembering the design guide, when in doubt defer to Python3, then to Clojure, then to Common Lisp. Python has a set syntax. Hy should also be able to do this. We should be able to do anything Python can do in Hy. I don't like giving up power! Clearly dictionaries are more important, since earlier Python2 versions had that and not set syntax, also `{}` is an empty dictionary in Python, not an empty set. So dictionary gets priority on the curly braces. I'm still in doubt, how does Clojure handle this?
```Clojure
user=>#{3 2 1}
#{1 3 2}
```
This works pretty well, and we don't have to sacrifice commas. Does this work in Hy?
```
=> #{3 2 1}
  File "<input>", line 1, column 8

  #{3 2 1}
         ^
LexException: Ran into a RCURLY where it wasn't expected.
```
It does not. But it could.
Maybe it should.

At the moment the best we can do seems to be old-school Python 2:
```
=>(set [3 2 1])
{1, 2, 3}
```
Ugh. Wasted square brackets. I couldn't find any better syntax in Hy's documentation. Well I'm up for suggestions, but Clojure's seems like a good solution, and it's fairly well-known.

**Comment by Foxboron** [comment]
```hy
=> (defreader s [x] `(set ~x))
=> #s[1 2 2 3]
{1, 2, 3}
=> 
```

We do have "reader macros" (not proper by any means) that uses # as a dispatch character. But having `{` as en exception to this rule could work. Won't be hard to implement really.

**Comment by kirbyfan64** [comment]
Done. #829.

**Comment by danceasarxx** [comment]
This issue is reoccuring in version 0.11.1 for Cython 3.5.2

**Comment by kirbyfan64** [comment]
@danceasarxx You need to install the development version from Git in order to use set literals:

```
$ pip install git+https://github.com/hylang/hy.git
```

**Comment by Kodiologist** [comment]
I don't think we support Cython, anyway.

**Comment by danceasarxx** [comment]
So can I or can I not use hy on Cython

**Comment by Kodiologist** [comment]
You can try whatever you want. I just can't guarantee it will work, and we probably won't fix Cython-specific bugs.
