### ISSUE TITLE
hy2py in the repl

### ISSUE THREAD

**Issue by gilch** [hylang/hy#833]
Is there a way to invoke hy2py in the repl on individual forms? Looking at hy2py output I realize that sometimes what I think I said is not what Hy thinks I said. Python's scoping rules aren't quite the same as Lisp's. Sometimes Hy does strange things to turn statements into expressions. A quick printout of nearly-python code in the repl would help immensely with debugging Hy programs (and Hy itself for that matter).

**Comment by paultag** [comment]
I think you want `(disassemble)`

**Comment by paultag** [comment]
```
=> (print (disassemble '(fn [] (print "hi!")) true))
def _hy_anon_fn_1():
    return print('hi!')
```

Or run `hy --spy`

**Comment by gilch** [comment]
Thanks, that's exactly what I was looking for. My inferior-lisp is now using `hy --spy`. 

I didn't realize github can't render .rst files or I might have seen it before.
![capture](https://cloud.githubusercontent.com/assets/3346292/8418395/24914454-1e70-11e5-938c-9cc82e3e3507.PNG)

**Comment by berkerpeksag** [comment]
You can also use the web version at http://docs.hylang.org/en/latest/language/cli.html#hy

**Comment by gilch** [comment]
Yes I see it now. I have some reading to do.
