### ISSUE TITLE
(string? :keyword) raises exception.

### ISSUE THREAD

**Issue by gilch** [hylang/hy#836]
If this is intentional, it should be documented. It does not appear to be documented behavior, thus I suspect this is a bug in Hy. Since `HyKeyword` inherits `HyString`, I think `(string? :keyword)` should return `True` as with `(string? 'symbol)`

**Comment by kirbyfan64** [comment]
I think the issue stems from the fact that `string?` is just a normal function:

```
ryan@DevPC-LX:~$ hy
hy 0.10.1 using CPython(default) 2.7.6 on Linux
=> string?
<function is_string at 0x7fc6555f0de8>
=> 
```

And `HyKeyword`s are converted to Unicode:

```
=> :abc
u'\ufdd0:abc'
=> 
```

So you're really calling `string?` on a string with a technically invalid Unicode character.

**Comment by gilch** [comment]
Or it could return false. I'm not sure if that's better, but I do think crashing the `string?` predicate on such a common datatype is the wrong answer. Python is duck-typed; no static type checking. Sometimes you have to check these things at runtime to avoid causing errors. Therefore the act of checking should not itself cause errors. It's also not at all unusual when writing Lisp macros to step through a list and do different things depending on what type of element you find.

**Comment by algernon** [comment]
This is a toughie. I think that `(string? 'symbol)` returning true is wrong. On the other hand, `(string? :keyword)` throwing an exception ain't exactly friendly, either. I'd propose both should return false.

Opinions?

**Comment by agentultra** [comment]
Shouldn’t keywords be their own type, perhaps sub-classed from str?

(issubclass :keyword HyKeyword) => True

**Comment by paultag** [comment]
from IRC:

```
14:09 < paultag> we should perhaps make keywords actual objects
14:09 < paultag> rather then utf-8 strings
14:09 < paultag> I think we long lost the hy import thing
14:10 < paultag> we did it that way (you did it that way :) ) because it
didn't add hy dep on runtime
14:10 < paultag> now we nearly always have one
14:10 < paultag> so might as well just make it an object
14:10 < paultag> which we can also make __call__'able
14:10 < paultag> without having a compiler special case
14:10 < algernon> was thinking along the same lines.
14:10 < paultag> which also makes it map'able
14:11 < algernon> I'll add that to the milestone, to collect more input
14:11 < paultag> ++
14:11 < paultag> ♥
```

On Fri, Jul 24, 2015 at 10:13 AM, J Kenneth King <notifications@github.com>
wrote:

> Shouldn’t keywords be their own type, perhaps sub-classed from str?
>
> (issubclass :keyword HyKeyword) => True
>
> > On Jul 24, 2015, at 10:06 AM, Gergely Nagy <notifications@github.com>
> wrote:
> >
> > This is a toughie. I think that (string? 'symbol) returning true is
> wrong. On the other hand, (string? :keyword) throwing an exception ain't
> exactly friendly, either. I'd propose both should return false.
> >
> > Opinions?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/836#issuecomment-124536283>.
>



-- 
:wq

**Comment by algernon** [comment]
See #846

**Comment by Kodiologist** [comment]
I think this is correct behavior. `(string? :keyword)` is interpreted as trying to calling the function `string?` with a keyword argument `keyword`, but you didn't provide a value for it, hence the exception `Keyword argument :keyword needs a value`. You can still do `(setv x :keyword) (string? x)`; that works fine, and returns `True`. Is it really worth making `string?` into a macro to cover the specific and not-very-useful case of trying to call it on a literal keyword?

**Comment by gilch** [comment]
@Kodiologist yup, you've convinced me. Keywords in Hy function calls behave differently than in other Lisps, since it gets translated into a keyword argument. If you actually want to pass a keyword as data to a function in Hy (unlike other Lisps) you have to quote it.
```Hy
=> (string? ':keyword)
from hy.core.language import is_string
from hy import HyKeyword
is_string(HyKeyword('\ufdd0:keyword'))
True
```
This behavior of keywords is in function calls what needs to be documented more clearly, since in other Lisps keywords always evaluate to themselves and thus are self-quoting. The `string?` function is fine as-is.
