### ISSUE TITLE
How to change vector to form

### ISSUE THREAD

**Issue by acekingke** [hylang/hy#837]
I have an question:
the list 
![image](https://cloud.githubusercontent.com/assets/7586502/8543062/cb1b2120-24cc-11e5-82e3-7b4d1b4ed45a.png)

but how to list result like 
(1L, 2L, 3L)
?

**Comment by berkerpeksag** [comment]
Hi @acekingke, you can use the `tuple` builtin:

```
=> (tuple [1 2 3])
(1L, 2L, 3L)
```

or

```
=> (, 1 2 3)
(1L, 2L, 3L)
```

**Comment by acekingke** [comment]
Thank you very much

**Comment by zackmdavis** [comment]
(The title of the issue makes me suspect @acekingke meant a list like those in classical Lisps, which might be better analogized to a HyExpression or the chain of cons cells given by `list*`, rather than to a tuple, depending on the intended usage.
```
=> '(1 2 3)
(1 2 3)
=> (type '(1 2 3))
<class 'hy.models.expression.HyExpression'>
=> (list* 1 2 3)
(1 2 . 3)
=> (type (list* 1 2 3))
<class 'hy.models.cons.HyCons'>
```
)

**Comment by acekingke** [comment]
Thank you, yes,  I mean the (1 2 3)  like lisp
