### ISSUE TITLE
How to join two list ?

### ISSUE THREAD

**Issue by acekingke** [hylang/hy#839]
In common lisp, It can do this:

 ```
(append '(3 3) '(4 4))
```

but how do it make in Hy similar?

**Comment by algernon** [comment]
```hy
(+ '(3 3) '(4 4))
```

**Comment by agentultra** [comment]
(.extend [1 2] [3 4])

Hy is just Python. (3 4) isn't a linked list. ;)

**Comment by acekingke** [comment]
@agentultra 
 ```
=> (setv a (.extend [1 2] [3 4]))
=> a
=> (setv a [1 2])
=> (.extend a [3 4])
=> a
[1L, 2L, 3L, 4L]
```
and the way algernon afford can work well:
```
=> (+ '(3 3) '(4 4))
(3L 3L 4L 4L)
```

**Comment by rajkrish** [comment]
The `+` operator fails for `None` items - 
```hy
=> (+ [1 2]  None [3 4])
  Traceback (most recent call last):
    File "stdin-b041eb053c9d062d8ea88189d2b4fa2851468a91", line 1, in <module>
      (+ [1 2]  None [3 4])
       ^^^^^^^^^^^^^^^^^^^^
  TypeError: can only concatenate list (not "NoneType") to list
``` 
Ideally I would expect `None` to be ignored in this case, as certain intermediate list generation logic might return a `None` value.

**Comment by Kodiologist** [comment]
That's how Python semantics works. If you don't like that, you'll have to take it up with the Python guys.
