### ISSUE TITLE
(reduce + [1 2 3]) works but (apply + [1 2 3]) doesn't?

### ISSUE THREAD

**Issue by gilch** [hylang/hy#840]
```
hy --spy
```
```
=> (reduce + [1 2 3])
from hy.core.language import reduce
from hy.core.shadow import +
reduce(+, [1, 2, 3])
6
=> (apply + [1 2 3])
  File "<input>", line 1, column 8

  (apply + [1 2 3])
         ^^
HyTypeError: compiling the application of `+' didn't return a function call, but
 `BinOp'

=>
```
In Lisp `+` is just another function. In Python, `+` is a binary operator. In Hy, I don't know anymore. Sometimes it's a function. If if feels like it.

**Comment by kirbyfan64** [comment]
#725 should fix this; I need to figure out why the tests were failing.

**Comment by Foxboron** [comment]
I'll just close this since we do have an issue on the topic

**Comment by gilch** [comment]
Duplicate of #647
