### ISSUE TITLE
Make assoc a function instead of a special form

### ISSUE THREAD

**Issue by hcarvalhoalves** [hylang/hy#841]
Even though Hy implements `assoc`, somehow it's not a valid function in the local scope:

```
$ hy --spy
hy 0.11.0 using CPython(default) 2.7.10 on Darwin
=> assoc
assoc
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'assoc' is not defined
```

Strange. Let's import `toolz` version:

```
=> (import [toolz.dicttoolz [assoc]])
from toolz.dicttoolz import assoc
=> assoc
assoc
<function assoc at 0x1022af140>
```

Good. Let's try:

```
=> (= (assoc {} "Say" "Hy") {"Say" "Hy"})
{}[u'Say'] = u'Hy'
(None == {u'Say': u'Hy', })
False
=> 
```

Double WTF.
1. Hy's `assoc` implementation is weird since it mutates instead of returning a new dict.
2. I can't shadow with a saner version of `assoc`.

:crying_cat_face:

**Comment by kirbyfan64** [comment]
Well...

1. If `assoc` returned a new dict, I would be mad. Issue is that Hy <=> Python.
2. I believe this would be partly fixed by #725?

**Comment by paultag** [comment]
So, unfortunately, it won't fix it, due to the compiler being a bit dumb
about some of this stuff

Namely, if the compiler sees a form with a name, and that name is a
builtin, it'll generate the AST for it. Since `assoc` turns into index
assignment, it'll
always do that, without turning it into an `ast.Call`.

I would be open to a patch removing `assoc` from builtins *entrirely*, and
turn it into a function, though!

**Comment by kirbyfan64** [comment]
@paultag I have a fix "ready" [here](https://github.com/kirbyfan64/hy/commit/7eb1353e09aca6db78223e828b741bbe8b293e01), but it's giving a really weird error:

```
ryan@DevPC-LX:~/stuff/hy$ ./run
hy 0.11.0 using CPython(default) 2.7.6 on Linux
=> (setv x {})
=> (assoc x 2 2)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/media/ryan/stuff/hy/hy/core/language.hy", line 301, in assoc
    (is x None))
NameError: global name 'v' is not defined
=> 
ryan@DevPC-LX:~/stuff/hy$ 
```

This is what `hy2py` outputs for `hy/core/language.hy`:

```hy
def assoc(tgt, *args):
    if (not is_even(len(args))):
        raise TypeError(u'expected an even number of key-value pairs')
        _hy_anon_var_2 = None
    else:
        _hy_anon_var_2 = None
    it = iter(args)
    for [k, v] in zip(it, it):
        tgt[k] = v
    return tgt
```

It looks like it should work. What's wrong?

**Comment by agentultra** [comment]
for k, v = zip(it, it) ?

**Comment by paultag** [comment]
Yeah, hunh. What's the hy function look like?

**Comment by kirbyfan64** [comment]
@paultag https://github.com/kirbyfan64/hy/commit/7eb1353e09aca6db78223e828b741bbe8b293e01#diff-0596550c57598e9e162e09fa94572868R40:

```hy
(defn assoc [tgt &rest args]
  (if (not (even? (len args)))
    (raise (TypeError "expected an even number of key-value pairs")))
  (setv it (iter args))
  (for [[k v] (zip it it)]
    (assoc* tgt k v))
  tgt)
```
