### ISSUE TITLE
Get rid of let

### ISSUE THREAD

**Issue by gilch** [hylang/hy#844]
We all know `let` is broken. There have been many proposed solutions, but one option that no-one has offered--or perhaps actually thought of, but never dared to say--is to get rid of `let` altogether.

I understand this may be controversial. If at least a couple of core members feel strongly that Hy *must* have a `let`, then feel free to close this issue and I'll not mention it again. But do hear me out first.

Remember the main selling point of Hy: "We're still Python(TM). Most of the internals translate 1:1 to Python internals." Hy is not Clojure, nor Common Lisp, but homoiconic Python. Do we really need `let`?

In the older Lisps, usually `let` is just used to create a local variable. Hy can do this more simply with the `setv` form. Python has no block scope. Creating and calling a new function just for a local or two is pretty inefficient in Python. Shouldn't we encourage users to use `setv` anyway in such cases? This approach also breaks `break` `continue` `yield` and would break `return` if we had it (we should). There may be other problems I haven't thought of.

Now I'm confident that, in time, we could fix all of these issues, perhaps with an alternative approach. But all of these alternatives will expand into something *complicated* especially compared to `setv`. There will likely be overhead or other nasty surprises.

If someone really needs a new scope block (perhaps to control variable lifetime in a macro), then there's nothing stopping them from explicitly doing it the same way as they would in Python. Perhaps with a class, function or dictionary. Then those familiar with Python would not be surprised by their expectations about how `let` is supposed to work and we wouldn't have to port `nonlocal` to Python 2.

**Comment by kirbyfan64** [comment]
> we wouldn't have to port nonlocal to Python 2.

I feel like that'll end up being necessary regardless...

**Comment by gilch** [comment]
Actually there's a really easy way to make that unnecessary: Drop support for Python 2. Not saying we should necessarily, but Python2 is supposed to go away eventually anyway.

**Comment by Foxboron** [comment]
You are in a camp where we all dream of a day without Python2. We have
partially started dropping support for Python26 tho, so progress \o/

**Comment by cwebber** [comment]
One alternative is to provide let to preserve backwards compatibility, but fully document that it's mostly broken and *why* it is unlikely that a real let will never exist, and not use it in any example code.

**Comment by agentultra** [comment]
Or just implement it as a convenience macro for setv'ing a bunch of variables. It's just Python under the hood.

**Comment by gilch** [comment]
>One alternative is to provide let to preserve backwards compatibility, but fully document that it's mostly broken and why it is unlikely that a real let will never exist, and not use it in any example code.

A major failure mode for design-by-committee (historically) has been cruft. That's why C is a pretty good language, but C++ is crazy scary. Also compare Common Lisp to Clojure. Languages with a single designer or benevolent dictator don't have such a cruft problem. Compromise leads to compromised language. I think the move to Python 3 was a good thing because it got rid of cruft. But it did cause some other problems (putting it mildly). Mainly because there was so much software written in Python 2 already. That means the best time to clean up cruft in Hy is as soon as possible. While we're still in alpha and not too much depends on the current version of the language. (We are still in alpha, right?)

It already bothers me that Hy has so much duplication polluting the default namespace because it's trying to be Clojure and Common Lisp (and Python) at the same time. We don't need both `do` and `progn` etc. `do` alone will do. We don't need both `True` and `true`. We can put Python first, it's `True`. Hy does not need to be compatible with Clojure or Common Lisp, and certainly not both.

If we want to take the route of deprecating `let` as you suggest, can we at least move it out of Hy's core, and into a contrib. library or something? It would take a simple import statement to fix the old scripts. We could do the same for the other duplication and keep Hy's core simpler.

>Or just implement it as a convenience macro for setv'ing a bunch of variables. It's just Python under the hood.

Better yet, just extend `setv` to work on multiple pairs simultaneously. In Common Lisp, `setf` already does this. (quoting from the hyperspec)
```Lisp
(setf place-1 newvalue-1
       place-2 newvalue-2
       ...
       place-N newvalue-N)
```
is precisely equivalent to
```Lisp
 (progn (setf place-1 newvalue-1)
        (setf place-2 newvalue-2)
        ...
        (setf place-N newvalue-N))
```
We could make `setv` work the same way:
```
(setv spam 1
      eggs 2
      bacon 3)
spam = 1
eggs = 2
bacon = 3
bacon
```
Python can already do simultaneous assignment using tuples. So we can already do something similar to `psetf` like this:
```
(setv (, spam eggs bacon) (, 1 2 3))
(spam, eggs, bacon) = (1, 2, 3)
(spam, eggs, bacon)
```
In many cases it makes no difference though.

**Comment by agentultra** [comment]
Design by committee diatribe aside, I agree 100%. 

ANSI specifications are useful so that your language isn't dictated by implementation. Python would be better off with one so that PyPy, Jython, et al wouldn't have to duplicate CPython bug for bug.

**Comment by kirbyfan64** [comment]
First, can I try implementing a better version. If that fails, *then* deprecation is an option. How does that sound?

**Comment by gilch** [comment]
I was (and am) honestly not certain if getting rid of `let` is a good idea to begin with. But I'm also not certain it's a bad one. I have proposed some fixes, after all. I do think we have a better chance of creating a *sane* `let` implementation if we keep in mind the viable alternative of not having one at all. Especially the costs of using any kind of let as compared to the more natural (for Python) `setv`. 

Costs include implementation/maintenance work, user confusion, and performance issues from making Python do extra things to simulate simple things it was never designed for.

**Comment by algernon** [comment]
In favour of `let`, I'd like to say that working primarily in Clojure, my fingers remember `let`. It would feel strange and alien without it. Nevertheless, a macro that translates it to `setv`s would be fine with my finger memory.

**Comment by paultag** [comment]
I prefer `let` as well, but it's pretty broken, and my attempts over the last two days to fix the `yield` behavior turn out to be *really* hard.

In particular, you have to know if `let` is in a function or not (which makes it double-hard), and I'm thinking we either need AST macros (ugh, I kinda hate this idea) or bail on `let`. I'm starting to think we need to do a serious cleaning.

I say we prune out a bunch of stuff, get things into a one-true-way thing, and fix things like double square brackets. Throughout the language. I'd rather see this breakage once.

**Comment by paultag** [comment]
Fact is, our semantics are tied to Python, and our efforts to wrap that away are, well, basically endless.

The semantics of scoping and stuff are pretty annoying (no Let-over-lambda), so I'd rather clean out everything broken and start to re-add things as we get them correct. This will piss off anyone with existing Hy code.

**Comment by paultag** [comment]
Thinking further, we could move those functions and macros we're pulling out into a contrib shim for the next release to give folks migration time.

**Comment by algernon** [comment]
Can we do the cleanup before ~september? I'd rather go into production with "modern" Hy.

(The contrib shim sounds like a reasonable idea.)

**Comment by paultag** [comment]
Yeah. No problem. Let's get a ticket open with a TODO of things to fix. We
shouldl appoint someone from core to BDFL this.

On Fri, Jul 24, 2015 at 9:47 AM, Gergely Nagy <notifications@github.com>
wrote:

> Can we do the cleanup before ~september? I'd rather go into production
> with "modern" Hy.
>
> (The contrib shim sounds like a reasonable idea.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/844#issuecomment-124526741>.
>



-- 
:wq

**Comment by agentultra** [comment]
:D

**Comment by paultag** [comment]
@algernon is cleanup BDFL, he's on the job!

On Fri, Jul 24, 2015 at 10:04 AM, J Kenneth King <notifications@github.com>
wrote:

> :D
>
> > On Jul 24, 2015, at 9:49 AM, Paul‮etnomailgaT‭ <notifications@github.com>
> wrote:
> >
> > Yeah. No problem. Let's get a ticket open with a TODO of things to fix.
> We
> > shouldl appoint someone from core to BDFL this.
> >
> > On Fri, Jul 24, 2015 at 9:47 AM, Gergely Nagy <notifications@github.com>
> > wrote:
> >
> > > Can we do the cleanup before ~september? I'd rather go into production
> > > with "modern" Hy.
> > >
> > > (The contrib shim sounds like a reasonable idea.)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/hylang/hy/issues/844#issuecomment-124526741>.
> > >
> >
> >
> >
> > --
> > :wq
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/844#issuecomment-124533216>.
>



-- 
:wq

**Comment by rwtolbert** [comment]
Been a bit quiet here lately, but I agree with this one-true-way cleanup.

I think I've unknowingly run into these `let` issues and so I have code that already just uses a bunch of `setv`. 

While I like the Lisp philosophy of `let`, if we can do it right, we shouldn't do it at all. 

Getting rid of things like the double brackets is just extra goodness that we can deal with since we are making a big change.

**Comment by rcarmo** [comment]
*sigh* seeing as I'm doing Clojure again and `let` is kind of... inevitable, I'm torn. I just know I'm going to have to hack [sushy](http://github.com/rcarmo/sushy) to bits once the new release is out, but if you _really_ have to break Hy, then...

**Comment by paultag** [comment]
@rcarmo anything we do remove will be moved into a contrib module with its current behavior exactly - so we can have some time to figure out how (or if) we reintroduce them. I prefer `(let)`, too, and nearly all my code will break if we remove it, but I see the point that it's really horrifically broken because of Python scoping.

What are your thoughts?

**Comment by agentultra** [comment]
Python is not the JVM. Hy is not Clojure for Python. It's apples to oranges. 

The problem, as I understand it, is that Python only implements lexical scopes using functions. We don't have a real progn and we'd have to eval with the lexical envs

**Comment by rcarmo** [comment]
Just do it (TM)

**Comment by rcarmo** [comment]
> On 24 Jul 2015, at 17:18, J Kenneth King <notifications@github.com> wrote:
> 
> Python is not the JVM. Hy is not Clojure for Python. It's apples to oranges. 

Yeah, well, I am quite aware of that. That is not the comparison I had in mind.

Rather painfully so, since I’ve been using Hy for a fairly extensive set of little things. It’s just that it will be annoying to code some things without let, just like it is to have it partially broken like it is today - and being close to Clojure helps a lot when you’re switching contexts frequently.

**Comment by algernon** [comment]
I'd keep *some* kind of let. A macro that expands to a set of `setv`s, to at least seem familiar. But then, calling that `let` may not be the best idea...

**Comment by agentultra** [comment]
The context switch is always hard but they are separate things and should not be conflated.

I really like having `let` but we don’t have the facilities in Python to really support it, just hacks.

If we come up with a `progn` implementation we could do it but I suspect we’ll have to eval code in the enclosing lexical scope and that might make some Python programmers uncomfortable (even though we use eval in some of the builtin libs…). It also might make us uncomfortable since Python’s eval takes strings… :(

**Comment by paultag** [comment]
Or let setv take multiple pairs

**Comment by agentultra** [comment]
It should, regardless. :)

**Comment by theanalyst** [comment]
like {e,c}lisp's setq

**Comment by paultag** [comment]
Let's get a bug and PR on that

**Comment by algernon** [comment]
This'll do for a bug. I'll prep a PR tomorrow, unless someone beats me to it.

**Comment by gilch** [comment]
>If we come up with a `progn` implementation we could do it but I suspect we’ll have to eval code in the enclosing lexical scope and that might make some Python programmers uncomfortable (even though we use eval in some of the builtin libs…). It also might make us uncomfortable since Python’s eval takes strings… :(

Python's `eval` doesn't cut it. It only does expressions, not statements. You need `exec`. Also, these don't *have* to take strings. They work on code objects, which we can `compile()` from AST.

**Comment by agentultra** [comment]
Derp, forgot you can give eval code objects… my point either way is that we can’t evaluate arbitrary lexical environments; or we could if we could actually compile an arbitrary `let` body into an expression code object we pass to eval.

**Comment by kirbyfan64** [comment]
I think you guys keep forgetting that you can implement `let` via a `try...finally` block with completely normal, not-crazy semantics. I've been working on it. The reason people using Python don't do that is simply because it would take more typing than it's worth. But, this is Hy. Which means there are macros!

**Comment by rcarmo** [comment]
> On 24 Jul 2015, at 20:59, Ryan Gonzalez <notifications@github.com> wrote:
> 
> I think you guys keep forgetting that you can implement let via a try...finally block with completely normal, not-crazy semantics. I've been working on it. The reason people using Python don't do that is simply because it would take more typing than it's worth. But, this is Hy. Which means there are macros!
> 
Hey _that_ is a neat concept I can completely get behind. But would it work properly with `yield`? I _think_ it should, but...

**Comment by gilch** [comment]
Clever, but no. A `finally`/`del` is nowhere near a proper let, because it breaks closures. For example:
```Lisp
; Common Lisp
* (defvar foo
    (let ((counter 0))
      (lambda () (incf counter))))
* (funcall foo)

1
* (funcall foo)

2
* (funcall foo)

3
*
```
Now let's try that with `finally`/`del` in Python.
```Python
>>> try:
	counter = 0
	def _hy_anon_fn_1():
		global counter
		counter = counter + 1
		return counter
	_hy_anon_var_1 = _hy_anon_fn_1
finally:
	del counter

	
>>> foo = _hy_anon_var_1
>>> foo()
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    foo()
  File "<pyshell#7>", line 5, in _hy_anon_fn_1
    counter = counter + 1
NameError: name 'counter' is not defined
>>> 
```
You see the problem? If this were in a function we could use `nonlocal` instead of `global`, but it still wouldn't work. And `let` **is** allowed outside of functions.

**Comment by agentultra** [comment]
You also have to be clever to not bash outer scopes.

Not sure if our statement-mangling eval can compile a code object we can pass to eval with the lexical environment defined by the `let` but that’d be the only way I can see it happening.

**Comment by kirbyfan64** [comment]
@gilch I got around that, too. Just requires a little more boilderplate.

**Comment by zackmdavis** [comment]
> Can we do the cleanup before ~september?

September 13 might be appropriate, to match the [Python 3.5 release](https://www.python.org/dev/peps/pep-0478/#release-schedule)?

**Comment by eigenhombre** [comment]
It looks like this is still up for discussion...?  As a full-time Clojurian coming back to Hy after a few years away, I'm still playing catch-up as to how `let` is broken in Hy (Python); but after getting over my initial visceral reaction ("you'll have to pry `let` from my cold, dead hands"), I would like to +1 what @algernon wrote in favor of `let`, above.  Almost every Lisp I've used has a `let`, or several.  Aside from providing a certain kind of scoping behavior, `let`, especially in Clojure, usually signals the following intentions:

1. I'm going to take a value and bind it to a name;
2. I'm not going to change its value (generally; OK Clojure is immutable by default, but generally I'll program that way in Python too if I can help it); 
3. I only care about this binding in the scope of this form.
(I could also add:
4. My binding might shadow another binding in the outer scope
but this seems less critical to me.)

I'll be a little sad if Hy loses a shared (very Lisp-y) idiom for this most common of patterns.  If one can work around Python's strange scoping, all the better.

**Comment by agentultra** [comment]
It’s not that Python has strange scoping; it just doesn’t have delimiters for arbitrary scope. All scoping is function-scope. Even bindings (at least used to, pretty sure they fixed it in 3.3+) in comprehensions leaked to the outer scope because of this limitation.

`let` in the lispy form is typically implemented by an implicit progn in an eval with the specified environment defined by the bindings (at least that’s what we’d expect the naive transformation to be… implementations often do some tricks to generate better code). We have been able to mimic that in Hy by generating nested functions but that has it’s own problems when interacting with other parts of the language since the programmer doesn’t have any control over the generated code there.

If Python was purely defined by expressions then it would be arbitrary to eval an expression with the enclosing environment defined by the `let`. We might be able to still do that with some hackery to convert the (Hy) body to a valid Python expression, compile the code object and pass it to eval with the let bindings shadowing over the local environment. However the usual caveats of eval in Python would apply: it’s slow as molasses. That cost might not be a big deal in practice depending on where the let is located but you’d have to be awfully careful not to call a function in a tight loop with a `let` inside (which is generally good practice anyway even in a Lisp world where this sort of structure is basically free).

`let` in the Python sense is the same as a variadic `setv`. We can bind names all we want given the normal Python rules. However we can’t generate new scopes without generating hacks and work-arounds.

The eval route might still work; but it would take some investigation to see how we can limit the generated Hy body to only, ever output a valid Python expression code object to pass to Python’s eval.

**Comment by algernon** [comment]
I have a proposal: while @kirbyfan64 is working on the try/except-based `let`, I'd implement the other, fallback option: a `let` macro that translates to setv.

Something like this:

```hy
(defmacro let [bindings &rest body]
  `(do
    (setv ~@bindings)
    ~@body))
```

That'd also address #713.

**Comment by algernon** [comment]
I started working on the let change proposed above. Turns out it is much more involved than initially thought. WIP code available on the [f/let-to-setv-based-macro](https://github.com/algernon/hy/tree/f/let-to-setv-based-macro) branch in my repo. Tests fail, with cryptic errors, and some of the translations are likely buggy too.

Unfortunately, my timebox for this task today is used up, feel free to take what I have and run with it, or ignore and start from scratch.

**Comment by gilch** [comment]
The documentation indicates that `with-gensyms` depends on `let`, should we rework this to use `setv` instead, or should we remove `with-gensyms` to the contrib. shim as well?

**Comment by algernon** [comment]
My plan is to have a `let`, that follows python scoping rules. See the short macro I posted earlier. So `with-gensyms` would still use let underneath (or setv, doesn't matter much, although I find the let form more familiar).

**Comment by gilch** [comment]
>My plan is to have a let, that follows python scoping rules.

Wouldn't redefining `let` like that collide with the same name in the planned contrib shim?

**Comment by algernon** [comment]
Yes, it would. But the contrib shim would need to be imported explicitly, and would shadow the other one.

**Comment by gilch** [comment]
Which would mean any macro expecting the old `let` now expands to the shadowed version in any context where the shim has been imported. Clojure has symbol namespaces and fully qualifies quasiquoted symbols to avoid this sort of problem, but to my knowledge Hy has no such protection.

**Comment by algernon** [comment]
Well, the shim should only be imported if all lets in that context need to follow the old ways. I'll make sure that the hy built-in macros won't be affected (they'll likely use setv directly). So I don't think this'll be a huge issue.

Or, we can just drop the idea of an old-let shim: while changes too, and there'll be plenty of other breaking changes. I suggest we try to improve the tooling instead. HyREPL + hydiomatic + vim/emacs/lighttable integration would mean that one can press a combo, and get a hint at what the form should be replaced with. Or run hydiomatic on a piece of code, and get a diff back.

**Comment by algernon** [comment]
I'll be closing this one. We pretty much agreed that we want to reimplement let, one way or the other, but we'll be keeping *some* kind of let.

See #688 and #713 for various options.
