### ISSUE TITLE
Multiple predicates in list-comp

### ISSUE THREAD

**Issue by gilch** [hylang/hy#848]
Extend `list-comp` and related forms to accept multiple predicates like Python does. I am aware that one could use Boolean logic to combine them, but in general this is error prone. I am also aware that one could filter after the fact, but that's extra complexity.

This is valid Python:

``` Python
[x for x in range(100) if x%3==0 if x%5==0]
```

This should work in Hy, but doesn't:

```
(list-comp x [x (range 100)] (= (% x 3) 0) (= (% x 5) 0))
```

**Comment by paultag** [comment]
Great! Let's get a PR together for this :) :+1:

**Comment by algernon** [comment]
Sounds like it shouldn't be too hard to implement!

**Comment by gilch** [comment]
Sorry guys, but I've mislead you. After further research I'm going to have to revise my recommendation. It's actually harder than I thought.
```Python
>>> def expensive_generator():
	print('churn!')
	yield 1
	print('chug!')
	yield 2

	
>>> [(x,y) for x in range(10) if x%5==0 for y in expensive_generator()]
churn!
chug!
churn!
chug!
[(0, 1), (0, 2), (5, 1), (5, 2)]
>>> [(x,y) for x in range(10) for y in expensive_generator() if x%5 == 0]
churn!
chug!
churn!
chug!
churn!
chug!
churn!
chug!
churn!
chug!
churn!
chug!
churn!
chug!
churn!
chug!
churn!
chug!
churn!
chug!
[(0, 1), (0, 2), (5, 1), (5, 2)]
```
Same answer, but so much less efficient. The programmer *must* be allowed to insert the predicates as soon as possible in comprehensions. As Hy is now, the predicate is always at the end, even if there are multiple `for` terms. With my original proposal, multiple predicates are allowed, but all the predicates have to be at the end. This is unacceptable.

Some possibilities:
```
; look ma, no brackets!
(list-comp (, x y) 
           x (range 10) :if (= 0 (% x 5))  ; one :if per predicate. Kinda like Python.
           y (expensive_generator))
```
```
; we'll just be explicit. Really looks like Python.
(list-comp (, x y) 
           :for x :in (range 10) :if (= 0 (% x 5))  ; the :in seems so pointless.
           :for y :in (expensive_generator))
```
```
; a la Clojure?
(for-list  ; also for-set, for-dict and for-each?
  [x (range 10) :when (= 0 (% x 5))  ; can we do a :while by raising StopIteration or something?
  y (expensive_generator)]
  (, x y))
```

**Comment by algernon** [comment]
```hy
(list-comp (, x y) [x (range 10) :if (= 0 (% x 5))]
                   [y (expensive_generator)])
```

This is a variant of 1 & 2: each predicate is in a vector, which makes it straightforward to parse. (The no-brackets option would be a pain to parse and highlight, imo).

**Comment by gilch** [comment]
The `:if` isn't really necessary, is it?
```Hy
(list-comp (, x y) [x (range 10) (= 0 (% x 5))]  ; [target iterable &rest predicates]
                   [y (expensive_generator)])
```
I think the above is not bad, but something more like Clojure, except with Python ordering and words seems better:
```Hy
(list-comp (, x y)
  [x (range 10) :if (= 0 (% x 5))
   y (expensive_generator)])
```
But then, what are those brackets even doing? There's no implicit `do` in comprehensions; it's just one expression. And we're back to my first option:
```Hy
; look ma, no brackets!
(list-comp (, x y)
  x (range 10) :if (= 0 (% x 5))
  y (expensive_generator))
```
After you trivially pop the `(, x y)` off the front of the arguments list, you're parsing exactly the same structure Clojure does. Clearly this is doable, because Clojure does it. The arguments are the same order as the Python, and I assume the AST. Just step through the list. I don't know what more highlighting you expect than what's already showing in this comment.

**Comment by algernon** [comment]
On argument in support for braces: they make it easier to quickly select, move, rearrange, kill, etc a particular part of the expression. Also makes it easier for stuff like hydiomatic to make sense of the expression.

For example, if we have this:

```hy
(list-comp (, x y)
  x (some-expression-that-makes-the-line-long-enough-to-wrap 10) 
    :if (= 0 (% x 5))
  y (expensive_generator))
```

In Emacs, I can't easily cut the first predicate: it spans two lines, and I'd have to teach `hy-mode` to recognise the form to be able to support selecting it. If it is in brackets, paredit already handles it for me. One of the reasons I prefer brackets & parens around distinct parts of an expression is because it makes it easier to navigate the source programmatically.

When you do a lot of work that involves walking the code (hello hydiomatic!), you'd like to be able to walk it easily, without reimplementing half of the compiler.

**Comment by gilch** [comment]
You *can* easily cut the first clause with paredit: (the `|` is the cursor)
```Hy
x (some-expression-that-makes-the-line-long-enough-t
o-wra|p 10) 
; slurp backward (C-(), now paredit handles it just the same.
(x some-expression-that-makes-the-line-long-enough-t
o-wra|p 10)
; backward-up-list (C-M-u)
|(x some-expression-that-makes-the-line-long-enough-t
o-wra|p 10)
; kill-sexp (C-M-k)
|
; move, then yank (C-y)
(x some-expression-that-makes-the-line-long-enough-t
o-wrap 10)|
; left, barf backward (C-{)
x (some-expression-that-makes-the-line-long-enough-t
o-wrap 10|) 
```
Wasn't hard. `hy-mode` not required. This is even easier with `evil-mode` when you can just `da(` to kill the sexp without moving the cursor.

The first predicate works the same way:
```Hy
:if (= 0 (% x 5))
; backslurp
(:if = 0 (% x 5))
; etc
```
>One of the reasons I prefer brackets & parens around distinct parts of an expression is because it makes it easier to navigate the source programmatically.

You're not the first to tell me that, but the community seems to prefer Clojure-like forms over Common-Lisp-like forms. There are a lot of other places in the language we could add (or keep) the extra `[]`. I don't like the visual clutter, and it's harder to remember how to produce a nested form than a flat one.

The ideal `[]` form by the programmatic argument seems to be:
```Hy
(list-comp (, x y)
  [x (range 10)]
  [:if (= 0 (% x 5))]
  [y (expensive_generator)])
```
The `:if` is required to distinguish the predicates from the for clauses. Now it's just pairs.

But if we write it like this:
```Hy
(list-comp (, x y)
  x (range 10)
  :if (= 0 (% x 5))
  y (expensive_generator))
```
Then it's trivial to transform it back into the `[]` pairs with `(partition 2 coll)` whenever you have to manipulate it programmatically.

What? Hy doesn't have `partition`?
```Hy
(defn partition [n coll]
  (->> coll (iter) (,) (* n) (apply zip)))
```
Does now.

The reverse operation, flattening one layer, is also trivial with `itertools.chain`.

**Comment by Kodiologist** [comment]
Fulfilled by #1626.
