### ISSUE TITLE
Remove redundant braces in defclass

### ISSUE THREAD

**Issue by gilch** [hylang/hy#850]
For example, (from Hy's docs)
from this
```
=> (defclass Cat []
...  [[age None]
...   [colour "white"]
...   [speak (fn [self] (print "Meow"))]])
```
to this
```
=> (defclass Cat []
...   age None
...   colour "white"
...   speak (fn [self] (print "Meow")))
```

**Comment by algernon** [comment]
No strong opinion on this, but I'd keep one of the braces:

```
(defclass Cat []
   [age None
    colour "white"
    speak (fn [self] (print "Meow"))])
```

This would make it a tiny bit easier and more straightforward to add docstring support (if we want / can):

```
(defclass Cat []
   "Kitty kat says Meow"
   [age None
    ...])
```

**Comment by gilch** [comment]
```
(defclass Cat []
  --doc-- "Kitty kat says Meow"
  age None
...)
```
Just pointing out that the brackets are not required for docstrings. 

Which is better? I don't know. 

`--doc--` is five whole characters longer than the `[]` we just got rid of. It's arguably the more common case to have docstrings in classes than not. It's also more consistent with functions to have an implicit --doc-- instead of an explicit assignment.

On the other hand, 
    Explicit is better than implicit.
    Simple is better than complex.
    Flat is better than nested.
    Special cases aren't special enough to break the rules.
Once you start using macros to define classes anyway, isn't it just easier not to deal with the special cases?

I honestly hadn't thought of the docstrings when I made that simplification. I wonder if I'm missing anything else. Do class declarations in Python do anything else special (i.e. that isn't like an assignment)?

**Comment by algernon** [comment]
Yuck, `--doc--` looks terrible, sorry. We *could* do without an explicit docstring marker, and without brackets, but that'd be even more confusing. Just a hunch, but I'm for only removing one level of brackets. But, as I said earlier, I have no strong arguments for or against either way.

**Comment by gilch** [comment]
Doesn't `--init--` look equally terrible? We're not getting around that one, are we? I don't think it looks that bad though.

**Comment by gilch** [comment]
I'm beginning to think that the entire `defclass` form is flawed. It's too different from the way Python does it to fit well.
```Python
>>> # class definitions can have side effects
>>> class C:
	print('side effect!')

	
side effect!
>>> # can contain loops
>>> class C:
	for i in range(3):
		print(i)

		
0
1
2
>>> C.i
2
>>> # can clean up with del
>>> class C:
	for i in range(3):
		print(i)
	del i

	
0
1
2
>>> C.i
Traceback (most recent call last):
  File "<pyshell#16>", line 1, in <module>
    C.i
AttributeError: type object 'C' has no attribute 'i'
>>> # can refer to outer scope
>>> def foo():
	spam = 42
	class C:
		nonlocal spam
		print(spam)

		
>>> foo()
42
>>> eggs = 3
>>> class C:
	global eggs
	print(eggs)

	
3
>>> # can catch exceptions without failing
>>> 1/0
Traceback (most recent call last):
  File "<pyshell#44>", line 1, in <module>
    1/0
ZeroDivisionError: division by zero
>>> class C:
	try:
		1/0
	except ZeroDivisionError:
		pass
	msg = "still good!"

	
>>> C.msg
'still good!'
>>> # can build differently on conditions
>>> def makeC():
	class C:
		if raining:
			__umbrella = True
		else:
			__sunglasses = True
	return C

>>> raining = True
>>> dir(makeC())
['_C__umbrella', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
>>> raining = False
>>> dir(makeC())
['_C__sunglasses', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
>>> # can do internal imports
>>> class C:
	import re

	
>>> re
Traceback (most recent call last):
  File "<pyshell#72>", line 1, in <module>
    re
NameError: name 're' is not defined
>>> C.re
<module 're' from 'C:\\Python34\\lib\\re.py'>
>>> # can contain nested inner classes
>>> class C:
	class D:
		spam = 42

		
>>> C.D.spam
42
```
Basically, a lot of what we miss for want of proper `let`, we *could* do with Python classes. But I can't do ANY of this with `defclass`!

We don't need special square bracket syntax for setting attributes. `setv` can do multiple pairs now. Just use one of those.
```
(defclass Cat []
  "docstring"
  (setv age None
        colour "white")
  (defn speak [self] 
    (print "meow"))
```

**Comment by algernon** [comment]
The last proposed syntax looks fine to me. A noticable improvement over the current one, :+1: for that!

**Comment by algernon** [comment]
Ping @hylang/core, any other opinions?

I was also toying with this idea:

```hy
(defclass Cat []
  "docstring"
  [age None
   colour "white"]
  (for [x (range 10)]
    (print "side effect #" x))
  (defn speak [self]
    (print "meow"))
```

That is, we'd have an optional property list, because that looks nicer than `(setv ...)`. Parsing would go like this:

* Is the first arg a string? Yes? Docstring! If no, continue.
* Is the next arg a HyList? Yes? Property list! If no, continue.
* Everything else translates to stuff within the class's scope.

**Comment by Foxboron** [comment]
I enjoy the last example a lot. Should give enough flexibility while also supporting the python features

**Comment by algernon** [comment]
Another idea: have a `class` that doesn't do much sugar:

```hy
(class Cat []
  "optional docstring"
  (setv ...)
  (defn ...))
```

And build a `(defclass)` macro on top of that.

**Comment by gilch** [comment]
Typically, the only shared class attributes are the methods. While it's common for Python classes to have instance variables assigned in `__init__`, it's relatively rare to have class variables shared by all instances (shared variables are not particularly object-oriented).

Is it really worthwhile to have a special syntax for such an uncommon case? My vote would be for the `class` that doesn't do much sugar, and forget about the macro on top of that.

**Comment by algernon** [comment]
I'm ok with either. The difference is about 5-6 lines of code (and updates to docs / tests). I'm slightly happier with the special case, but if others in @hylang/core prefer the bare-bones approach, I'll update the patch.
