### ISSUE TITLE
@ for decorators

### ISSUE THREAD

**Issue by zackmdavis** [hylang/hy#856]
As long as we're considering a [grand language cleanup](https://github.com/hylang/hy/milestones/Grand%20Language%20Cleanup), `with-decorator` is an awful lot of characters. [What if](https://github.com/zackmdavis/HyTimer/commit/776d638b) we just used `@`? 

It would superficially collide with (the much, *much* less frequently used) [matrix multiplication](https://github.com/hylang/hy/commit/0dbf2126c) (maybe I should have thought to bring this idea up before implementing matrix multiplication, sorry!), but we could get around that by inspecting whether the second argument is a `FunctionDef` or `ClassDef` to decide whether to produce a decorator or `MatMul`.

* Advantages: very Pythonic
* Disadvantages: not very Lisp-like (for a form to mean completely different things depending on one of its arguments; Python has the excuse that the grammar doesn't permit confusion between `@` in decorators and as a binary operator, but that doesn't fly when everything is an S-expression).

**Comment by tuturto** [comment]
We could even do with something as simple as a reader macro #@. That wouldn't conflict with matrix multiplication and would be pretty simple to implement.

**Comment by algernon** [comment]
:+1: for `#@`
