### ISSUE TITLE
document literal syntax

### ISSUE THREAD

**Issue by gilch** [hylang/hy#858]
Strings, numbers, sets, dictionaries, True, False, None, etc. In one place. The rules for how it should work, even if it's just "The same as Python". This is certainly not the case for strings, which are broken (#831), by the way. There's a little of this in the tutorial, which makes a good introduction, but not a good reference.

**Comment by Ealhad** [comment]
I’ll do it. Where should it go ? In [Hy (the language)](http://docs.hylang.org/en/latest/language/api.html) ?

I am glad strings seem not to be broken anymore.

**Comment by Kodiologist** [comment]
Seems as good a place as any. The documentation is poorly organized, anyway. You could rename the section "Notes on Syntax" to "Literals" and go from there.

**Comment by jyn514** [comment]
I found sets and dictionaries very confusing starting out, it looks like `{1: 2}` is treated as a dictionary mapping `1:` to `2`? It gives a traceback:

```
Traceback (most recent call last):
  File "stdin-0b487aaf927306af720b1ae9624e06f12a2dd2aa", line 1, in <module>
    {1: 2}
NameError: name 'hyx_1XcolonX' is not defined
```

Set literals also don't seem to be supported, they're parsed as dictionaries:

```
=> {1, 2, 3}
Traceback (most recent call last):
  File "/usr/lib/python3.7/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "/usr/lib/python3.7/codeop.py", line 168, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "/usr/lib/python3.7/codeop.py", line 133, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)
ValueError: Dict doesn't have the same number of keys as values
```

I did find that `(set [1 2 3 4])` works fine instead, but it's not what I expected.

**Comment by Kodiologist** [comment]
@jyn514 Read the tutorial. We now have reference documentation on some literals (https://hy.readthedocs.io/en/master/language/syntax.html) but e.g. dictionary and set literals are currently described only in the tutorial.
