### ISSUE TITLE
add farhaven into core

### ISSUE THREAD

**Issue by Foxboron** [hylang/hy#865]
Based on his work here: https://github.com/hylang/hy/commits?author=farhaven
and vim-hy (https://github.com/hylang/vim-hy/commits?author=farhaven)

+1
:shipit: :dancer:

**Comment by algernon** [comment]
:+1:

**Comment by paultag** [comment]
I'm +1! Really great work, @farhaven!


On Tue, Jul 28, 2015 at 11:13:48PM -0700, Morten Linderud wrote:
>    Based on his work here:
>    [1]https://github.com/hylang/hy/commits?author=farhaven
>    and vim-hy ([2]https://github.com/hylang/vim-hy/commits?author=farhaven)
> 
>    +1
>    [3]:shipit: [4]:dancer:
> 
>    —
>    Reply to this email directly or [5]view it on GitHub.
> 
>    Reverse link: [6]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/hylang/hy/commits?author=farhaven
>    2. https://github.com/hylang/vim-hy/commits?author=farhaven
>    5. https://github.com/hylang/hy/issues/865
>    6. https://github.com/hylang/hy/issues/865

-- 
 .''`.   Paul Tagliamonte <paultag@debian.org>    |   Proud Debian Developer
: :'  :  https://people.debian.org/~paultag       |   https://pault.ag/
`. `'`               Debian - the Universal Operating System
 `-        4096R / 8F04 9AD8 2C92 066C 7352  D28A 7B58 5B30 807C 2A87

**Comment by farhaven** [comment]
I'm obviously in favor of this, but I might be a tiny bit biased :smile:

**Comment by berkerpeksag** [comment]
+1

**Comment by algernon** [comment]
Done, welcome @farhaven!

**Comment by paultag** [comment]
Thanks, @algernon ! Beat me to it :) :heart:
