### ISSUE TITLE
Remove redundant braces in for and add implicit do

### ISSUE THREAD

**Issue by gilch** [hylang/hy#866]
from this
```
(for [x collection]
  (do
    (side-effect1 x)
    (if (% x 2)
      (continue))
    (side-effect2 x)))
```
to this
```
(for x collection
    (side-effect1 x)
    (if (% x 2)
      (continue))
    (side-effect2 x))
```

**Comment by kirbyfan64** [comment]
But right now `for` let's you do the Cartesian product:

```hy
(for [a x b y]
    ...)
```

I totally agree with the implicit `do`, though. Drives me nuts.

Also: is there a reason we need `do` notation for `cond`:

```hy
(cond
    [b (do ...)])
```

I mean, is there a reason why I can't put more than one expression in a branch body without `do`? That also drives me crazy, and, after looking through Hy's code, I see no reason why.

**Comment by algernon** [comment]
I too, prefer the current syntax. Braces aren't necessarily evil, we do not need to purge as many of them as possible. And in case of for, they serve a desirable purpose.

On the other hand, I agree that an implicit do would be a blessing - same goes for cond, that drived me nuts a couple of times too. Can you open a separate bug about that @kirbyfan64?

**Comment by gilch** [comment]
>But right now for let's you do the Cartesian product:

That's news to me, is that in the docs anywhere? How does the `else` part work with that?

**Comment by algernon** [comment]
Closing this one, #874 is where the fate of `for` is discussed further, while #868 takes care of the implicit `do`.
