### ISSUE TITLE
Ok, I have written the regular expression demo in Hy and python

### ISSUE THREAD

**Issue by acekingke** [hylang/hy#873]
Thank to hylang for help. 
I have written a regular expression matcher in hy and python,

<https://github.com/acekingke/regular-expression-in-hy>

**Comment by theanalyst** [comment]
@acekingke you could probably announce/start the discussions in the hylang mailing list https://groups.google.com/forum/#!forum/hylang-discuss  since anyone browsing in the future could probably see the link etc.. as a github issue once it is closed, the links tend to be forgotten

**Comment by acekingke** [comment]
Thank you very much
