### ISSUE TITLE
get rid of for macro

### ISSUE THREAD

**Issue by gilch** [hylang/hy#874]
The only purpose of the `for` macro over the `for*` loop that it is based on seems to be Cartesian products (nesting) support. Python can already do this with `itertools.product`. `for` creates a generator expression that looks exactly like the form `product` was designed to replace. This is pointless redundancy cluttering Hy. Let's get rid of the `for` macro, rename `for*` to `for`, and maybe auto-import `from itertools import product`.

From this:

``` Hy
=> (for [x (range 3) y (range 2) z (range 1)](print [x y z]))
from hy.core.language import range
for (x, y, z) in ((x, y, z) for x in range(3) for y in range(2) for z in range(1)):
    print([x, y, z])
[0, 0, 0]
[0, 1, 0]
[1, 0, 0]
[1, 1, 0]
[2, 0, 0]
[2, 1, 0]
```

To this:

``` Hy
=> (for [(, x y z) (product (range 3)(range 2)(range 1))](print [x y z]))
from hy.core.language import range
for (x, y, z) in product(range(3), range(2), range(1)):
    print([x, y, z])
[0, 0, 0]
[0, 1, 0]
[1, 0, 0]
[1, 1, 0]
[2, 0, 0]
[2, 1, 0]
```

Now we don't need the `[]` anymore either. `for*` could be simplified to:

``` Hy
(for (, x y z) (product (range 3)(range 2)(range 1))
  (print [x y z]))
```

**Comment by zackmdavis** [comment]
A counterargument is that there's precedent for the existing behavior in, say, Clojure&mdash;
```
user=> (doseq [x (range 3) y (range 2) z (range 1)] (println [x y z]))
[0 0 0]
[0 1 0]
[1 0 0]
[1 1 0]
[2 0 0]
[2 1 0]
nil
```

> Now we don't need the [] anymore either

The cause of readability isn't necessarily best served by removing every possible delimiter. The Cartesian-product behavior of `for` is strictly analogous to the ability to declare more than one binding in a `let` form; there's an appeal in being able to say that `(for [x a-sequence y another-sequence] ... )` should mean the same thing as the nested loops `(for [x a-sequence] (for [y another-sequence] ...))` for the same reason that `(let [a value1 b value2] ...)` means the same thing as the nested lets `(let [a value1] (let [b value2] ...))`.

(Okay, #713 is still open, so the latter example isn't valid present-day Hy, but you get the idea.)

**Comment by algernon** [comment]
:-1:, the current `for` syntax is not only more readable than having to use `product`, but the bindings are easier to see at a glance. Compare this two:

```hy
(for [x (range 3)
      y (range 2)
      z (range 1)]
  (println [x y z]))
```

vs

```hy
(for (, x y z) (product (range 3) (range 2) (range 1))
  (println [x y z]))
```

At a glance, I can see that `y` is `(range 2)` from the first: variable and value are right next to each other. In the second case, I have to scan through the entire line. Even if I reformat it a bit:

```hy
(for (,        x         y         z)
     (product (range 3) (range 2) (range 1))
  (println [x y z]))
```

This is easier to see, but the formatting becomes more work too.

On the other hand, teaching the `for` macro to use `product` underneath instead of nested `for*` loops may worth a try. We'd need some approximate numbers though, to see if its worth it.

**Comment by gilch** [comment]
I'll admit the `[]` version is prettier than `,`/`product`, however, the same readability complaint applies whenever assigning to tuples, such as `(setv (, x y z) (, 3 2 1))`, or `(for [(k,v) (some-dict.items)] ...)`. Why are these OK? I don't think we should change all of these to use `[]` and pairs, do you? 

Using `product` is much more consistent with the rest of the language. We could `import itertools.product as` something shorter, if you prefer, like `prod`, `cart`, or `nest`.

It's FAR more common to iterate over two collections in parallel, than over their Cartesian product. That's why `zip` is a builtin, but you have to `import itertools.product`. If you insist on retaining a macro with `[]` syntax, a much better translation is from:
```Hy
(for [x it1
      y it2]
  (print [x y]))
```
to
```Python
for x,y in zip(it1,it2):
    print([x,y])
```

Yet we have to write it as
```
(for [(, x y) (zip it1, it2)]
  (println [x y])
```
Which presents *exactly* the same readability issue. And this is the more common case!

But still, this is consistent with the way you iterate over dictionaries:
```
(for [(, k v) (some-dict.items)]
  (println [k v]
```
I don't even know *how* to fix that one with `[]`, do you?

Even with `[]` for `product`, you can't get away from tuples in the more complex cases:
```Hy
(for [(, x y) (zip it1 it2)
      (, z w t) (product it3 it4 it5)  # same readability issue here!
      (, k v) (some-dict.items)]
...)
```
And, of course, assignments to tuples can nest:
```Hy
(setv (, a (, b c) d) (, 1 (, 2 3) 4)
```
Same readability issue, but you can't fix it with `[]`. Tuples are valid assignment targets in many places, not just `setv` and `for` loops.

**Comment by paultag** [comment]
https://github.com/hylang/hy/issues/573 might shed some light on why we don't use product

**Comment by paultag** [comment]
(My initial code did)

**Comment by paultag** [comment]
https://github.com/hylang/hy/commit/2167c211203fc1d43cb3a9d8c0d10598f7c55388 was my changeset adding product to for - https://github.com/hylang/hy/issues/573 was a bug that it introduced

**Comment by paultag** [comment]
and https://github.com/hylang/hy/pull/574 was when we reintroduced the current semantics

**Comment by paultag** [comment]
(Basically, they're similar (`for` and `product`) except when they're not because they can't be :) )

**Comment by kirbyfan64** [comment]
But list comprehensions already have the Cartesian product:

```python
>>> [(x, y) for x in [1,2,3] for y in [4,5,6]]
[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]
```

Having a multi-argument `for` that does the same thing seems more consistent, and having it use `zip` is just confusing.

**Comment by gilch** [comment]
>On the other hand, teaching the for macro to use product underneath instead of nested for* loops may worth a try. We'd need some approximate numbers though, to see if its worth it.

@algernon It looks like the current implementation uses a genexpr, not nested `for*`, and actually used to use `itertools.product`. This is so `break`/`continue`/`else` work properly on the whole loop instead of just the inner part. 

@kirbyfan64 The Python example doesn't really apply here, since it uses muliple `for` keywords. That makes it analogous to
```Python
result = []
for x in [1,2,3]:
    for y in [4,5,6]:
        result.append((x, y))
```
and not analogous to
```Python
result = []
for x,y in product([1,2,3],[4,5,6]):
    result.append((x,y))
```
Which is what we were actually talking about.
The equivalent list comp in Python is actually:
```Python
[pair for pair in product([1,2,3],[4,5,6])]
```

On the other hand, if you meant that `for` should be consistent with *Hy*'s `list-comp` form, that is a much better argument. Clearly `(list-comp (x,y) [x [1,2,3] y [4,5,5]])` looks a lot more like the current `for`.

But I don't buy this either, because we're changing the comprehension syntax anyway for #848. We have to change it because we have to be able to put the predicates in between the for clauses. This will break the symmetry anyway. 

Therefore, I don't think that translating to `zip` will remain confusing with the new comprehension syntax (except for inertia from existing users, same as any language change). Those coming from Python rather than Clojure will find the `zip` form more intuitive than the current `product`-like behavior. But this is not my first choice anyway, which is just to get rid of the `[]` altogether, and use `zip`, `product`, `dict.items` etc. explicitly as we do in Python.

**Comment by gilch** [comment]
Ah, I see @paultag's point referencing #573. The `for` bindings, as implemented with a `genexpr`, are sequential, not parallel as they would be using `product`, thus arg2 of `product` can't depend on a variable bound from the result of arg1, because it hasn't happened yet, but this is possible with a genexpr, which, unlike `product`, is not a function.

So, @algernon teaching the `for` macro to use `product` underneath instead of the `genexpr` it uses now will break anything that depends on sequential assignments working. Maybe it's worth a try if it's significantly more efficient, but understand it does change the current behavior.

**Comment by algernon** [comment]
> I'll admit the `[]` version is prettier than `,`/`product`, however, the same readability complaint applies whenever assigning to tuples, such as `(setv (, x y z) (, 3 2 1))`, or `(for [(k,v) (some-dict.items)] ...)`. Why are these OK? I don't think we should change all of these to use `[]` and pairs, do you? 

In case of `(setv)`, it only has one kind of arguments: symbol-value pairs to associate. You could write the `(setv (, x y z) (, 3 2 1))` like this:

```hy
(setv x 3
      y 2
      z 1)
```

Already more readable. Mind you, it doesn't cover the case where you want to destructure the return value of a function, that will always be done with tuples, everywhere, consistently. The reason I don't think a `[]` makes sense for `(setv)`, but does for `(for)` is because - as hinted above - the former only has one kind of arguments, while `(for)` has a list of bindings and a body at least. The `[]` is a visual aid. Could we get rid of it? Yes. We could get rid of all brackets and parens, too.

Yes, there will be cases - may even be most cases - where you'll have to use a tuple anyway. That's fine, I have nothing against tuples. But if there's a case where we can make it simpler, while not making the other cases terrible, I think we should add that bit of sugar.

As for calling a Python Python: Hy is Hy, not Python-with-parens.

(Mind you, I've yet to deal with #848, I haven't taken those changes in consideration yet.)

**Comment by Kodiologist** [comment]
`for` is a special form and `for*` is gone as of #1626.
