### ISSUE TITLE
Improving partition

### ISSUE THREAD

**Issue by gilch** [hylang/hy#878]
Ref #877.
Good news, guys. I figured out how to make overlapping partitions like Clojure's using `islice`s instead of just `iter`.
```Python
from itertools import islice, zip_longest
_sentinel = object()
def partition(n,coll,step=None,fillvalue=_sentinel):
    step = step or n
    slices = [islice(coll,start,None,step) for start in range(n)]
    if fillvalue is _sentinel:
        return zip(*slices)
    else:
        return zip_longest(*slices,fillvalue=fillvalue)
```
```Python
>>> list(partition(3,range(6)))
[(0, 1, 2), (3, 4, 5)]
>>> list(partition(3,range(6),2))
[(0, 1, 2), (2, 3, 4)]
>>> list(partition(3,range(6),1))
[(0, 1, 2), (1, 2, 3), (2, 3, 4), (3, 4, 5)]
>>> list(partition(3,range(6),1,'x'))
[(0, 1, 2), (1, 2, 3), (2, 3, 4), (3, 4, 5), (4, 5, 'x'), (5, 'x', 'x')]
>>> list(partition(3,range(7),fillvalue=None))  # None is a valid fillvalue, but not the default
[(0, 1, 2), (3, 4, 5), (6, None, None)]
```
@kirbyfan64 I also added an optional `fillvalue` argument so we can keep remainders. (This isn't quite as versatile as the `pad` collection Clojure uses.)

Now, I can easily translate this into Hy, but I wonder if this is the best order for the arguments. Clojure uses a multimethod with the following signatures: `[n coll]``[n step coll]``[n step pad coll]`. The `coll` is always last. This makes `partition` easier to use with the `->>` tail threading macro, which Hy also has.

On the other hand, Hy does support arbitrary argument order using keywords, same as Python:
```Hy
=> (defn test [a b c] (print a b c))
def test(a, b, c):
    return print(a, b, c)
=> (->> "b" (test 1 :c 2 :b))
test(1, c=2, b='b')
1 b 2
```
But then every out-of-order argument must have a keyword.

@Foxboron pointed out on IRC last night that Hy does, in fact, support multimethods. 

But it's in contrib, and so wouldn't be available in core. I couldn't even use `->>` for my first implementation of `partition`. 

Maybe I could override the current `partition` as a multimethod in a contrib import only, while keeping the core version as-is. Maybe the above signature is good enough and we'd prefer the full version in core. Maybe we should put the `coll` argument first so we can at least use the `->` macro. Hy's `partition` doesn't *have* to use the same ordering as Clojure, but it could cause confusion if it doesn't. Maybe we could have more than one function with different names. Give me some direction here.

**Comment by algernon** [comment]
There's a difference between multimethods (`defmulti`) and arity overloading (same function, different number of arguments). What you want is the latter, not the former.

In hy, this is a bit awkward to do, but entirely doable:

```hy
(defn partition [n &rest args]
  "Bla bla bla"

  (setv argc (len args)
        coll (last args)
        step 1
        with-fillvalue false)
  (cond
    [(< argc 2) (throw "some error")]
    [(= argc 3) (setv step (first args))]
    [(= argc 4) (setv step (first args)
                      fillvalue (second args)
                      with-fillvalue true)]
    [(> argc 4) (throw "some other error")])

    ;; Here, step and coll are already set. If we have a fillvalue, then 
    ;; with-fillvalue is true and fillvalue is set. Otherwise with-fillvalue is false.

    ...)

**Comment by Foxboron** [comment]
Also note `defmulti` i hy isnt multi-methods, but arity-overloading. I
have realized in later time its horrible naming. But going to try and
throw multimethods into hy.contrib.multi when i can work it out.

But i do wonder if we should move it out of contrib and give it a better
name. That would be neat

**Comment by algernon** [comment]
If moved out of contrib, it should be baked into `defn`, I believe. Or call it `defn-arity`... or perhaps make it a macro + decorator monster? (not sure if that'd work)

**Comment by gilch** [comment]
>There's a difference between multimethods (`defmulti`) and arity overloading (same function, different number of arguments). What you want is the latter, not the former.

I thought of using `&rest`. I think I do want the former though.
```Hy
(require hy.contrib.multi)
(import [itertools [islice]])
(defmulti multi-partition
  ([n coll]
   (->> coll (iter) (,) (* n) (apply zip)))
  ([n step coll]
   (apply zip (list-comp (islice coll start nil step)
                         [start (range n)])))
  ([n step fillvalue coll]
   (apply zip-longest
          (list-comp (islice coll start nil step)
                     [start (range n)])
          {"fillvalue" fillvalue})))
```
This way it keeps the ordering we want, and we're still free to change that order using keywords:
```Hy
=> (list (multi-partition 3 2 "x" (range 6)))
from hy.core.language import range
list(multi_partition(3, 2, 'x', range(6)))
[(0, 1, 2), (2, 3, 4), (4, 5, 'x')]
=> (list (multi-partition 3 2 :coll (range 6) :fillvalue "x"))
from hy.core.language import range
list(multi_partition(3, 2, coll=range(6), fillvalue='x'))
[(0, 1, 2), (2, 3, 4), (4, 5, 'x')]
=> 
```
But with `&rest` this isn't possible.

**Comment by algernon** [comment]
Fair point. We should get `defmulti` into core then, preferably with a better name.

**Comment by Foxboron** [comment]
The problem is that the decrorator is written in python, so i gotta do a
rewrite there before anything gets moved.

**Comment by gilch** [comment]
We can't import Python yet in core?
