### ISSUE TITLE
How do I access macro docstrings in the repl?

### ISSUE THREAD

**Issue by gilch** [hylang/hy#892]
The macros defined in Hy all seem to have docstrings, but I looked through the docs and can't figure out how to access them in the repl.

**Comment by algernon** [comment]
See #356, which is related.

**Comment by jkitchin** [comment]
See https://github.com/jkitchin/hy/blob/hydoc/hy/core/hylp.hy#L154 For one approach to getting the doc string.

=> (. (get hy.macros._hy_macros nil "with") __doc__)
u'shorthand for nested with* loops:\n  (with [x foo y bar] baz) ->\n  (with* [x foo]\n    (with* [y bar]\n      baz))'
=>

**Comment by Kodiologist** [comment]
I'm going to close this since #356 is about the same thing.
