### ISSUE TITLE
Separate nil from None

### ISSUE THREAD

**Issue by gilch** [hylang/hy#896]
I'm proposing we redefine `nil` to be `'()`, instead of `None`. Empty containers are already falsey in Python, so anything depending on that behavior still works. There can be only one `None`, and the same would have to apply to `'()`. It doesn't currently:

```
=> (id '())
54381928
=> (id '())
54252712
```

But I think that could be corrected.

Besides removing a duplicate keyword, this has the advantage of nicer behavior for macro definitions. Sometimes when you do an unquote splice, you don't want to add anything on some condition, but do on others.

```
(defmacro foo [x]
  `(, 1 2
      ~@(if x
          ["the x was true!"]
          '())
      3 4))
```

If nil already meant `'()`, then it could be shortened to:

```
(defmacro foo [x]
  `(, 1 2 ~@(if x ["the x was true!"]) 3 4))
```

This is just one example, but in Common Lisp, you take advantage of `nil`==`'()` a lot.

**Comment by kirbyfan64** [comment]
You know both examples are invalid, right? (Try running them through hy2py.) ;)

Although the idea is neat, `'()` doesn't go nicely with most Python libs, and I don't really like `if` now returning `'()`. Feels kind of out-of-place.

The main thing I love about Hy is that it's ultimately Python, not Lisp. This doesn't really feel too Pythonic...

**Comment by gilch** [comment]
String's an iterable and it spliced the characters... edit/fixed with `[]`. Usually, you're splicing in code, not strings into macros, so I think the point stands.

**Comment by Kodiologist** [comment]
`nil` is gone as of #1159. Are you interested in resurrecting it as some kind of empty iterable object? Or do you just want to change the default "else" value of `if`?

**Comment by Kodiologist** [comment]
Pinging @glich.
