### ISSUE TITLE
Documenting transformations

### ISSUE THREAD

**Issue by cbbrowne** [hylang/hy#90]
One of the things I'd most like for hy to be good for is to allow me to write unambiguous Python code; I'm always futzing over the indentation handling.

Is there an easy way to take a .py file and transform it into a .hy file?  And vice-versa?

There is some indication that this is possible; it would be real nice if there were a command line example.

**Comment by Kodiologist** [comment]
We have hy2py, and we now have a separate issue for py2hy, so I'm closing this.
