### ISSUE TITLE
Add a pretty print function to compose with macroexpand

### ISSUE THREAD

**Issue by gilch** [hylang/hy#914]
`macroexpand` and `macroexpand-1` are essential for the development of macros with non-trivial complexity, but the output must be readable to be useable. In Common Lisp you would use the `pprint` function for this purpose. In Hy I have to count parentheses or paste into Vim for cleanup.

I wonder if it would be easier to adapt an existing `pprint` implementation (or something similar) for Hy than to write it from scratch.

**Comment by algernon** [comment]
There's already a [pretty printer in Hydiomatic][1], which would be reasonably easy to move over to Hy (as `hy.contrib.pprint` or somesuch - I wouldn't put it in core just yet).

 [1]: https://github.com/hylang/hydiomatic/blob/master/hydiomatic/utils.hy#L17-L60

**Comment by Kodiologist** [comment]
Is `hy-repr` sufficient for this? It uses Hy syntax, but doesn't generate indents or newlines.

**Comment by kirbyfan64** [comment]
Would it really help that much? IIRC the result of macroexpand is already formatted correctly, it's just a pain in the ass to read.

**Comment by Kodiologist** [comment]
> IIRC the result of macroexpand is already formatted correctly

Not with `repr`, since `HySymbol.__repr__` quotes the symbol like a Python string:

    => (macroexpand '(+ 1 2))
    ('+' 1 2)

**Comment by tuturto** [comment]
I like the ```hy-repr``` but it's not enough when expanding complex macro. I end up counting parentheses or copy/pasting the result into somewhere where I can format it into readable format.

**Comment by Kodiologist** [comment]
Perhaps `hy-repr` should have an option for adding appropriate whitespace. Or Hy could have a separate pretty-printer that takes code as a string. Hydiomatic's last commit was over a year ago, so any code stolen from it would probably need updates.
