### ISSUE TITLE
embedding Hy in .py files

### ISSUE THREAD

**Issue by tmbdev** [hylang/hy#921]
In order to build Hy with a rather pedantic build system, I need to embed the .hy files in the distribution inside .py files, but I'm not having much luck. Can anybody help make this work, or suggest an alternative?

Apparently, I don't understand import_buffer_to_module; it would seem to me that if it does what it says it does, the following should work.

Here is how I'm replacing macros.hy with macros.py:

```
import hy
import hy.core
import hy.importer
hy.core.macros = hy.importer.import_buffer_to_module('hy.core', """
;;; Hy core macros
... rest of macros.hy ...
""")
```

Actually, "hy" starts up after building, but "(print 3)" fails with:

```
hy 0.11.0 using CPython(default) 2.7.6 on Linux
=> (print 3)
  File "<stdin>", line 41, column 1

  (defn _numeric-check [x]
  ^-----------------------
    (if (not (numeric? x))
  ------------------------
      (raise (TypeError (.format "{0!r} is not a number" x)))))
  ------------------------------------------------------------^
HyMacroExpansionError: expanding `defn': AttributeError("'NoneType' object has no attribute 'errors'",)

=> (print)
Traceback (most recent call last):
  File "repo/third_party/py/hy/compiler.py", line 2478, in hy_compile
    compiler = HyASTCompiler(module_name)
  File "repo/third_party/py/hy/compiler.py", line 379, in __init__
    load_stdlib()
  File "repo/third_party/py/hy/compiler.py", line 75, in load_stdlib
    for e in mod.EXPORTS:
AttributeError: 'module' object has no attribute 'EXPORTS'
=>
```

**Comment by kirbyfan64** [comment]
I think the first error is referring to:

```hy
(defmacro macro-error [location reason]
  "error out properly within a macro"
  `(raise (hy.errors.HyMacroExpansionError ~location ~reason)))
```

`hy` is ending up as `None` for some reason...I think...

**Comment by Kodiologist** [comment]
I don't think it makes sense for us to try to make this sort of thing (importing a core module as a string) work. In your case, it's probably the build system that needs patching.
