### ISSUE TITLE
hy2py generates invalid Python

### ISSUE THREAD

**Issue by tmbdev** [hylang/hy#923]
Running hy2py generates invalid Python output:

```
$ cat test.hy
(defn test.+ [] 0)
$ hy2py test.hy
def _hy_anon_fn_1():
    return 0L
test.+ = _hy_anon_fn_1
test.+
$
```

I think this should either quote or give an error at compilation time.

**Comment by kirbyfan64** [comment]
@tmbdev This is known and intentional. `hy2py` is really just a debugging tool (which is really handy when writing macros).

**Comment by gilch** [comment]
`hy2py` would certainly be more useful if the output was valid Python. With that we could use Hy with things that expect Python code instead of compiled Python. (Cython?) 

I wonder if we could add a switch to the tool to make it convert all the identifiers to their punycode equivalents? Would that be enough to make all the output valid Python?

**Comment by ailijic** [comment]
@gilch 
Hi, can you elaborate on possible/potential use cases for such a feature?
I am not aware of any libraries that take python code as an argument. If you have a situation where you need to pass in python code directly could you just create a python program, call your hy program, and then just return to python when needed?

**Comment by gilch** [comment]
In #934 @kirbyfan64 pointed out that Cython uses a custom parser, so it needs source code, not just a compiled module. Hy doesn't support Cython's type annotations, but you supposedly get considerable speedup even without them. If you just imported a Hy module from a Cython program, there wouldn't be any speedup for the Hy module, but if hy2py could generate valid Python, then you could compile that output with Cython and get the speedup.

I also wonder about Pyjamas, which lets you run Python in the browser. It's supposed to generate JavaScript from Python AST, but they're probably making assumptions about it containing valid Python identifiers. I haven't actually tried it, but I don't think Hy would work. But if hy2py could generate *valid* Python, then you could translate that output to JavaScript using Pyjamas.

**Comment by Foxboron** [comment]
Closing this. @gilch feel free to make a new issue about the switch idea \o/
