### ISSUE TITLE
Multiple implementations overwrite each others' entrypoint hooks

### ISSUE THREAD

**Issue by Ketsuban** [hylang/hy#931]
It's not uncommon to find Python 2 and Python 3 coexisting on the same system, and it's not unreasonable for the user to also want Hy for both Pythons. However, where Python handles this gracefully by providing separate executables (`python2` and `python3` alongside `python`, `pip2` and `pip3` alongside `pip` etc) Hy simply bulldozes an existing `hy`, `hyc` etc.

Sorry if this has already been reported; I tried to look for previous issues but nothing much came to mind when I was trying to play guess-the-keyword.

**Comment by Foxboron** [comment]
closing this as we have the PR!
