### ISSUE TITLE
nonlocal for Hy in Python2

### ISSUE THREAD

**Issue by gilch** [hylang/hy#933]
There might be better ways of doing this, but it's possible if we use our own call stack. We could have a global stack object that all local assignments happen inside of. This way we can access locals of deeper stack frames if required.

But between threading and generators we might need more than one stack. So it might be easier to just piggyback on Python's. First we need a stack frame class, maybe something like this:

``` Python
class HyStackFrame:
    def __init__(self, parent):
        self.parent = parent
        self.vars = {}
        self.nonlocals = set()
    def __getitem__(self, name):
        try:
            return self.vars[name]
        except KeyError:
            return self.parent[name]
    def __setitem__(self, name, val):
        if name in self.nonlocals:
            self.parent[name] = val
        else:
            self.vars[name] = val
    def nonlocal(self, *names):
        self.nonlocals |= set(names)
```

Let's try to emulate this simple Python3 example with that:

``` Python
def spam():
    foo = 7
    def eggs():
        nonlocal foo
        foo = 42
    eggs()
    print(foo)
spam()
#42
```

Redefine `def`/`setv` and functions to use our new stack frames by declaring a `_hy_local` variable at the top of each function like so:

``` Python
def spam():
    _hy_local = HyStackFrame(_hy_local)
    _hy_local['foo'] = 7
    def eggs():
        _hy_local = HyStackFrame(_hy_local)
        _hy_local.nonlocal('foo')
        _hy_local['foo'] = 42
    eggs()
    print(_hy_local['foo'])
spam()
#42
```

The astute reader will notice that the line `_hy_local = HyStackFrame(_hy_local)` is an error. Python cannot both read a nonlocal and assign to a local of the same name. We can fix this using a technique similar to the `let` form.

``` Python
_hy_nonlocal = HyStackFrame(globals())

def spam():
    _hy_local = HyStackFrame(_hy_nonlocal)
    _hy_local['foo'] = 7
    def _hy_anon_fn_1(_hy_nonlocal = _hy_local):
        def eggs():
            _hy_local = HyStackFrame(_hy_nonlocal)
            _hy_local.nonlocal('foo')
            _hy_local['foo'] = 42
        return eggs
    eggs = _hy_anon_fn_1()
    eggs()
    print(_hy_local['foo'])
spam()
#42
```

The above code works. The astute reader will also notice the line `eggs = _hy_anon_fn_1` creates a local outside of our `HyStackFrame` object. This is easily corrected.

``` Python
_hy_nonlocal = HyStackFrame(globals())

def spam():
    _hy_local = HyStackFrame(_hy_nonlocal)
    _hy_local['foo'] = 7
    def _hy_anon_fn_1(_hy_nonlocal = _hy_local):
        def _hy_anon_fn_2():
            _hy_local = HyStackFrame(_hy_nonlocal)
            _hy_local.nonlocal('foo')
            _hy_local['foo'] = 42
        return _hy_anon_fn_2
    _hy_local['eggs'] = _hy_anon_fn_1()
    _hy_local['eggs']()
    print(_hy_local['foo'])
spam()
#42
```

We also need to set any parameters at the top, so this variation,

``` Python
def spam(foo):
    def eggs():
        nonlocal foo
        foo = 42
    eggs()
    print(foo)
spam(7)
#42
```

turns into this:

``` Python
_hy_nonlocal = HyStackFrame(globals())

def spam(foo):
    _hy_local = HyStackFrame(_hy_nonlocal)
    _hy_local['foo'] = foo
    def _hy_anon_fn_1(_hy_nonlocal = _hy_local):
        def _hy_anon_fn_2():
            _hy_local = HyStackFrame(_hy_nonlocal)
            _hy_local.nonlocal('foo')
            _hy_local['foo'] = 42
        return _hy_anon_fn_2
    _hy_local['eggs'] = _hy_anon_fn_1()
    _hy_local['eggs']()
    print(_hy_local['foo'])
spam(7)
#42
```

It's kind of ugly, but it's still readable, and appears to be well within the proven capabilities of AST manipulation. Of course Hy in Python3 should simply use the `nonlocal` keyword instead.

This hack need only apply to variables that `nonlocal` could apply to, that is, in a function or method. It won't affect variables in class definitions outside of methods nor indirect assignments like `a.foo = 7`, which might become `_hy_local['a'].foo = 7` but never `_hy_local['a']._hy_local['foo'] = 7`, since `.foo` is an attr, not a local.

Using a custom stack frame like this will have some overhead, but I'm not sure how bad. It might be worth it to get a consistent `let` implementation, since the lack of `nonlocal` in Python2 seems to be the main obstacle.

**Comment by kirbyfan64** [comment]
There are other ways to have nonlocal on Python 2: http://code.activestate.com/recipes/578965-python-2-nonlocal/.

**Comment by gilch** [comment]
Understanding that link will take some more study, but it looks like those decorators are rewriting the Python bytecode. It also looks like the functions could run faster with the bytecode approach, though it might take longer to create them than with my AST approach.

Will the bytecode approach still work in PyPy? I thought one of the main advantages of generating AST over writing bytecode was better compatibility with other Python implementations and versions numbers.

IronPython's and Jython's bytecodes are supposed to be very different from CPython's. (Does Hy's AST approach even work on those?) If it does, you'd have to rewrite the nonlocal decorators for each implementation of Python2. The alternative Python implementations are slower to adopt Python3 and thus stand to benefit the most form a Hy nonlocal implementation.

**Comment by kirbyfan64** [comment]
@gilch 

> Understanding that link will take some more study, but it looks like those decorators are rewriting the Python bytecode.

...did you even read the description? :D

> Will the bytecode approach still work in PyPy?

Yes.

**Comment by gilch** [comment]
I was away today and trying to read the Python on a tiny phone screen. I'm afraid I didn't quite get that far. Re-read description:
> This module is a nonlocal patch for Python 2.7 and PyPy. 
> ...
> This is very hackish and plays with CPython internal implementation stuff that PyPy just happens to be compatible with. YOU WERE WARNED!!!

It looks like our tox isn't set up to test IronPython nor Jython. If Hy wasn't compatible with them in the first place, perhaps it's a moot point, but it looks like rewriting bytecode won't work with them. (Or at least not in the same way.)

Do the bytecode decorators work if you skip over a nested function?
```Python
@export_nonlocals('var')
def outer():
    var = 0
    def middle():
        @nonlocals('var')
        def inner():
            print var
            var = 1
            print var
        inner()
    middle()
outer()
```
```
Traceback (most recent call last):
  File "<pyshell#162>", line 1, in <module>
    outer()
  File "<pyshell#161>", line 11, in outer
    middle()
  File "<pyshell#161>", line 5, in middle
    @nonlocals('var')
  File "nonlocals.py", line 104, in func
    freevars[freec:])))
KeyError: 'var'
```
Nope. That's a problem. The equivalent Python3 works.
```Python
def outer():
    var = 0
    def middle():
        def inner():
            nonlocal var
            print(var)
            var = 1
            print(var)
        inner()
    middle()
outer()
```
```
0
1
```

Is it possible to use both the `@nonlocals` and `@export_nonlocals` decorators on the same function?
```Python
@export_nonlocals('var')
def outer():
    var = 0
    @nonlocals('var')
    @export_nonlocals('var')
    def middle():
        @nonlocals('var')
        def inner():
            print var
            var = 1
            print var
        inner()
    middle()
outer()
```
```
Traceback (most recent call last):
  File "<pyshell#165>", line 1, in <module>
    outer()
  File "<pyshell#164>", line 13, in outer
    middle()
  File "<pyshell#164>", line 7, in middle
    @nonlocals('var')
  File "nonlocals.py", line 104, in func
    freevars[freec:])))
KeyError: 'var'
```
That doesn't work either. The AST approach can do this though.

**Comment by Kodiologist** [comment]
`nonlocal` is important, but I don't think new features for Python 2 are worth the maintenance overhead, let alone the effort needed to implement them to begin with. People should be switching to Python 3.
