### ISSUE TITLE
Clearer github project description

### ISSUE THREAD

**Issue by ALSchwalm** [hylang/hy#935]
Currently, the hy project description is 'ὑμήνπτερόν', which is apparently (ancient?) greek for Hymenoptera from which the project derives its name. I only found this out because when you google that word you can find @paultag mentioning it on twitter. This is more of a riddle than a description of the project. I appreciate that the description also links to [hylang.org](hylang.org), but I think something more descriptive would be nice to have (for github search results, etc).

I propose it be changed to something like "A dialect of Lisp that's embedded in Python", taken from [http://docs.hylang.org/en/latest/](http://docs.hylang.org/en/latest/)

**Comment by paultag** [comment]
Fair enough! Thanks!
