### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by gilch** [hylang/hy#939]
Somehow github and our .rst docs can use highlighting for Hy syntax. I don't know where the code for this is, but it seems to be getting out of date.

``` Hy
;; some core words aren't highlighted, but some are
(, range partition fraction last read-str symbol zip-longest)
```

Also, the new integers from #938 

``` Hy
(, 0x123 0o123 0b011011)
```

**Comment by kirbyfan64** [comment]
GitHub's Linguist uses a submodule pointing to [language-hy](https://github.com/rwtolbert/language-hy)...which hasn't been updated in almost a year...

**Comment by tuturto** [comment]
I added the ones mentioned here (except the integer thing) and created a pull request. Should probably go through all the keywords and such and check if they're mentioned in language-hy or not.

**Comment by kirbyfan64** [comment]
Maybe hylang could maintain a custom fork of language-hy?

**Comment by Kodiologist** [comment]
GitHub no longer supports this, so at least it's not broken anymore!
