### ISSUE TITLE
intern from common lisp

### ISSUE THREAD

**Issue by gilch** [hylang/hy#941]
(For the record, from an IRC conversation.)

Hy lacks the capability to create unquoted symbols.

``` Hy
(defmacro intern [name] (HySymbol name))
```

What I just came up with over IRC. 

"clambers" says he'll submit a patch. @Foxboron suggests a different name, maybe `symbol`?

**Comment by paultag** [comment]
`(HySymbol)` creates a quoted symbol

**Comment by paultag** [comment]
```hy
(import inspect)

(defn resolve-var-scope [stack symbol]
  (setv scope (get stack 0))
  (for [(, frame file line func lines index) (get stack (slice 1 nil))]
    (if (in symbol (. frame f-locals))
      (do (setv scope (. frame f-locals))
          (break))))
  scope)

(defn intern [symbol]
  (setv stack (get (inspect.stack) (slice 1 nil)))
  (setv scope (resolve-var-scope stack symbol))
  (if (in symbol scope)
    (get scope symbol)
    nil))

(defn foo []
  (setv x 1)
  ((defn bar []
    (print (intern "x")))))

(foo)
```

**Comment by paultag** [comment]
I wonder if something like this could solve Let over Lambda concerns - cc @olasd

**Comment by gilch** [comment]
`locals()` is effectively read-only due to optimizations. I don't think this helps with that. Perhaps if we combined it with the piggyback stack from #933.

**Comment by paultag** [comment]
Yeah, true. This might (at least) work for read

**Comment by gilch** [comment]
:open_mouth: I found a way to make `locals()` writable:
```Python
>>> def foo():
...   locals()['spam'] = 42
...   return spam
...
>>> foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in foo
NameError: global name 'spam' is not defined
>>> def bar():
...   exec "pass"
...   locals()['spam'] = 42
...   return spam
...
>>> bar()
42
```
This doesn't work in Python 3, but we do have `nonlocal` there. Is this enough to make `let` work!?

**Comment by kirbyfan64** [comment]
Is this really worth it? Python has some pretty scoping rules, and there are half-a-dozen *wrong* ways to do this.

**Comment by gilch** [comment]
I was referring to @Foxboron's insufficient coffee idea: #664.
>This isn't really hard. We could just pass along `**locals()` into the function.
`def _hy_anon_fn_1(**locals()):`

I don't think this would fix `let`'s `yield` issues though. At best we could use it to backport `nonlocal` to Python2, and maybe only CPython2. `let` is still dead to me.

**Comment by kirbyfan64** [comment]
@gilch Well...I was referring to the idea of an `intern` function, not what you had posted above. ;)

Does checking the caller's scope like @paultag showed work with `nonlocal`s? Otherwise, this is pretty much dead. Note that @paultag's approach would probably cause issues with globals and things like:

```hy
(defn f []
  (setv a 1)
  (g))

(def a 2)

(defn g []
  (intern :a)) ; Will pull f's `a` instead of the global one!
```

A simpler solution could potentially be:

```
(defn intern [sym]
  (setv frame (-> (inspect.stack) (cut 1) (get 0)))
  (setv scope (frame.f-globals.copy))
  (scope.update frame.f-locals)
  (-> sym str (scope.get)))
```

Not sure how this works with nonlocals.

**Comment by Kodiologist** [comment]
[Common Lisp's `intern` function](http://clhs.lisp.se/Body/f_intern.htm) is about package variables, not local variables. The Python equivalent of a package variable is a module global variable, which is set or get with `getattr(module, "variable")` or `globals()["variable"]`. I don't think a shortcut for one of these one-liners would be of much use, but reopen this issue if you disagree.
