### ISSUE TITLE
update pypi

### ISSUE THREAD

**Issue by gilch** [hylang/hy#942]
The change in API is confusing the new people. Have we made enough improvements to release a new version on PyPI? I don't think we're done with the Grand Language Cleanup. Perhaps it's best to only break it once.

If we can't update yet, we should at least add a link to the *stable* docs in README.md with a note about the change, since people tend to find the old version first, but read the current docs, which doesn't work.

**Comment by Foxboron** [comment]
I kinda think this is partially tied with the Grand Cleanup (still going on). The stable docs have been added so yeah, i'll just close this to unclutter the logg.
