### ISSUE TITLE
Add gilch into core

### ISSUE THREAD

**Issue by Foxboron** [hylang/hy#947]
:fireworks: 
Based on the work here https://github.com/hylang/hy/commits?author=gilch along with current pending PR's. Also been great with opinions on past and current PR's.

cc @gilch 
cc @hylang/core

**Comment by algernon** [comment]
:+1:

**Comment by berkerpeksag** [comment]
+1

**Comment by paultag** [comment]
:+1: totally. I'll add @gilch in a few days  :)

**Comment by gilch** [comment]
Waiting for my approval?
:+1:

**Comment by paultag** [comment]
Invited!

**Comment by paultag** [comment]
Welcome to core, @gilch , and thank you so much for all you've done so far!
