### ISSUE TITLE
Comparison operators should accept more arities

### ISSUE THREAD

**Issue by gilch** [hylang/hy#949]
In Clojure:
```Clojure
user=> (< 1)
true
```
Common Lisp:
```Lisp
* (< 1)

T
```
Hy:
```Hy
=> (< 1)
  File "<input>", line 1, column 1

  (< 1)
  ^---^
HyTypeError: `<' needs at least 2 arguments, got 1.
```
It also works like this for the other comparison operators, `<, <=, >, >=, <>, !=, ==`. (Perhaps we should even consider the remaining "comparisions" `in, not in, is, is not`.)

Again I am surprised. Why is Hy different? Judging from past issues like this (for `and, or, +, -, /` etc.) I think it's just because nobody thought of it. 

Perhaps it would not be an invalid choice if this were actually a conscious choice, because we have the precedent of Scheme requiring at least two arguments in its comparison functions.

So let's make it a conscious choice.  What's the rationale for a minimum of two arguments vs. one? Is it a good enough reason to make Hy work like Scheme in this regard, instead of more like Clojure and Common Lisp like we've done for most everything else?

**Comment by tuturto** [comment]
Interesting. Why would one want to compare if 1 is smaller than? I can understand comparing more than two: ```(< 1 5 7)``` to check that they're in ascending order. What would be the actual usage of this?

**Comment by algernon** [comment]
Macros:

```hy
(defmacro blah [&rest args]
  `(< ~@args))
(blah 1)
(blah 1 2)
```

Much simpler than if you'd have to check the length of args for each similar macro.

**Comment by tuturto** [comment]
Right, makes sense then. What would value be for each of them, ```true``` for all? ```true``` for some and ```false``` for others?

```in, not in, is, is not``` I would leave as they are now, unless there's some good reason to do it otherwise.

**Comment by algernon** [comment]
`true` for all but `!=`, which would be false, and the collection-related comparators (`in`, `not-in`, etc) I wouldn't touch, either.

I have a patch in the works, btw, just finishing up the tests.

**Comment by gilch** [comment]
>true for all but !=, which would be false

Strange, Clojure and Common Lisp seem to disagree on this point.

```Lisp
* (/= 1)

T
```
```Clojure
user=> (not= 1)
false
```
