### ISSUE TITLE
RTD build failures

### ISSUE THREAD

**Issue by berkerpeksag** [hylang/hy#953]
```py
python /home/docs/checkouts/readthedocs.org/user_builds/hy/envs/latest/bin/pip install --exists-action=w -rrequirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

https://readthedocs.org/projects/hy/builds/3372772/

**Comment by berkerpeksag** [comment]
Last successful build: https://readthedocs.org/projects/hy/builds/3255318/

**Comment by kirbyfan64** [comment]
The same error was occurring before, but [it was beung ignored for some reason](https://readthedocs.org/projects/hy/builds/3255318/).

**Comment by kirbyfan64** [comment]
@paultag or another organization member can go to the Admin tab of the Hy RTD page and, in Advanced Settings, change the path to `requirements.txt`.

**Comment by paultag** [comment]
Change made on RTD; looks good, thanks for the ping!

**Comment by huckl3b3rry87** [comment]
I am running into this issue as well:
```
Could not open requirements file: [Errno 2] No such file or directory: 'pip install -r requirements.txt'
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
https://readthedocs.org/projects/nloptcontroljl/builds/4810061/

Where the requirements.txt file in my main directory has:
```
upgrade pip
sphinxcontrib-bibtex
```
Any thoughts?

**Comment by Kodiologist** [comment]
@huckl3b3rry87 It doesn't look like you're using Hy. This is the GitHub repository for Hy, so it's not the place for your question.
