### ISSUE TITLE
document &key

### ISSUE THREAD

**Issue by gilch** [hylang/hy#961]
The docs for `defn` seem to say `&key` exists, but there are no examples. If it's a just a misprint and doesn't actually exist, it should be removed. Otherwise, it needs examples.

**Comment by kirbyfan64** [comment]
> there are no examples

Uhhh...

http://docs.hylang.org/en/latest/tutorial.html

Basically:

```hy
(defn func [&key {"a" "b" "c" "d"}] (+ a c))
```

is the same thing as:

```hy
(defn func [&optional [a "b"] [c "d"]] (+ a c))
```

**Comment by gilch** [comment]
Okay, so it's a little bit documented. The tutorial is not a reference. There's nothing under the **&key** heading in the reference for `defn`.

**Comment by kirbyfan64** [comment]
Outside of the realm of documentation: is there a reason `&key` allows anything other than identifiers in the mapping? For instance:

```
ryan@DevPC-LX:/media/ryan/stuff/hy$ hy --spy
hy 0.11.0 using CPython(default) 2.7.6 on Linux
=> (defn func [&key {1 "b"}] (+ 1 2))
def func(1=u'b'):
    return (1L + 2L)
=> (defn func [&key {a "b"}] (+ 1 2))
def func(a=u'b'):
    return (1L + 2L)
=> 
ryan@DevPC-LX:/media/ryan/stuff/hy$ hy --spy
hy 0.11.0 using CPython(default) 2.7.6 on Linux
=> (defn func [&key {a "b"}] (+ 1 2)) ; ok
def func(a=u'b'):
    return (1L + 2L)
=> (defn func [&key {"a" "b"}] (+ 1 2)) ; quotes work but are useless
def func(a=u'b'):
    return (1L + 2L)
=> (defn func [&key {1 "b"}] (+ 1 2)) ; why the hell would I want to do this
def func(1=u'b'):
    return (1L + 2L)
=> (defn func [&key {True "b"}] true) ; uh oh
def func(True=u'b'):
    return True
=> (defn func [&key {[1 2] "b"}] true) ; this doesn't even work
  File "<input>", line 1, column 19

  (defn func [&key {[1 2] "b"}] true) ; this doesn't even work
                    ^---^
HyTypeError: Can't assign or delete a HyList

=> (defn func [&key {# "b"}] true) ; this doesn't work either
def func():
    return True
=> (defn func [&key {` "b"}] true) ; useless again
def func(`=u'b'):
    return True
=> (defn func [&key {~ "b"}] true) ; this is pointless
def func(~=u'b'):
    return True
=> (defn func [&key {+ "b"}] ((setv f +) 1 1)) ; this may not end very well
from hy.core.shadow import +

def func(+=u'b'):
    f = +
    return f(1L, 1L)
=> (defn func [&key {= "b"}] nil) ; and this looks stupid
def func(==u'b'):
    return None
=> 
ryan@DevPC-LX:/media/ryan/stuff/hy$ 
```

**Comment by timmartin** [comment]
I agree about arguments that aren't identifiers. This isn't specific to `&key`, it applies to `&optional` as well. I've written a simple patch that seems to deal with this, and doesn't regress anything.

I'm not sure if I've got the terminology right, though. My code allows `HyString` and subclasses thereof, which includes `HySymbol`. This seems like the correct behaviour, but it means that the error message mentions strings, which makes it sound like they keyword name needs to be a quoted string literal.

**Comment by timmartin** [comment]
Is there anything left to be done for this issue?

**Comment by berkerpeksag** [comment]
I think we can close this now.
