### ISSUE TITLE
Consider making collections "callable"

### ISSUE THREAD

**Issue by gilch** [hylang/hy#963]
Clojure does this for its basic collections. I'm proposing Hy do this for anything with a `__getitem__` method that isn't already a Python callable, like we already do for keywords. This way it will also work for custom types that support the getitem interface. In the rare case that your collection is also a Python callable, you still have to use the `(get)` special form explicitly.

``` Hy
=> ([1 2 3 4] 1)
2
=> ({1 2 3 4} 1)
2
=> ("1234" (slice 2))
'12'
```

That last one would be especially nice with the slice literals I proposed in #541:

``` Hy
=> ("1234" :[1 3])
'23'
```

**Comment by zackmdavis** [comment]
I'm in favor of this.

**Comment by kirbyfan64** [comment]
Wouldn't this require wrapping every single function call to test for `__getitem__`? That would likely be a *major* speed issue for little gain.

I think a better solution would be to have *curried operators*. Basically, for `get`, there would be a curried version `getc` or something like that. That way, you could do `(getc [1 2 3])` to create an indexing callable.

**Comment by gilch** [comment]
There's really no need for `getc` since you can pass around `_getitem__` itself, so you could do `(. [1 2 3] __getitem__)` for the same effect. Because the dot access is on an instance, not the class, the implicit `self` argument is automatically curried.

Is the speed issue really that bad? Somehow we've got "callable" keywords, even though they're just strings to Python. How does that work?

You don't have to do the check first. Assume that it's a callable if it starts a Hy expression. If the call fails, catch the exception and retry with `__getitem__`.

**Comment by kirbyfan64** [comment]
@gilch 

> You don't have to do the check first.

That would mean `(any 1)` would be compiled to something like:

```python
try:
    _hy_anon_var_1 = any(1)
except TypeError:
    _hy_anon_var_1 = any[1]
```

which prints:

```
Traceback (most recent call last):
  File "call.py", line 4, in <module>
    _hy_anon_var_1 = any[1]
TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'
```

which would likely be the most confusing error message on earth.

Of course, you could do things like error message checks, but that still would fail in weird ways:

```python
def f(n):
    l = []
    l() # oops

try:
    _hy_anon_var_1 = f(1)
except TypeError as ex:
    if str(ex).endswith('is not callable'):
        _hy_anon_var_1 = f[1]
    else:
        raise
```

```
Traceback (most recent call last):
  File "call.py", line 9, in <module>
    _hy_anon_var_1 = f[1]
TypeError: 'function' object has no attribute '__getitem__'
```

The best thing I can think of would be:

```python
def f(n):
    l = []
    l() # oops

try:
    _hy_anon_var_1 = f(1)
except TypeError as ex:
    if callable(f):
        raise
    else:
        _hy_anon_var_1 = f[1]
```

But watch the results of the following speed test:

```python
from __future__ import print_function
import timeit

print('Base version:', timeit.repeat('f()' , '''
def f():
    return any([1, 1, 1])
'''))

print('Exceptions with direct return', timeit.repeat('f()' , '''
def f():
    try:
        return any([1, 1, 1])
    except TypeError:
        if callable(any):
            raise
        else:
            return any[[1, 1, 1]]
'''))

print('Exceptions with indirect return', timeit.repeat('f()' , '''
def f():
    try:
        _hy_anon_var_1 = any([1, 1, 1])
    except TypeError:
        if callable(any):
            raise
        else:
            _hy_anon_var_1 = any[[1, 1, 1]]
    return _hy_anon_var_1
'''))
```

Python 2:

```
Base version: [0.28238892555236816, 0.2855241298675537, 0.2818140983581543]
Exceptions with direct return [0.29772210121154785, 0.29675912857055664, 0.2970468997955322]
Exceptions with indirect return [0.31590700149536133, 0.3146848678588867, 0.31568408012390137]
```

Python 3:

```
Base version: [0.40082355300000927, 0.4072187689999964, 0.40149685299991233]
Exceptions with direct return [0.41813028399997165, 0.4186033580000412, 0.423580343000026]
Exceptions with indirect return [0.43899454200004584, 0.43792077899991, 0.4359661139999389]
```

Not bad...until you realize a major chunk of the average Hy program consists of function calls.

**Comment by gilch** [comment]
No, I didn't mean to put the try check in at run time, but at compile time like the `:keywords`. But I guess with Python's duck typing this information isn't available yet. An arbitrary symbol could be anything at compile time (but then how do macros work?).

The best we could do at compile time is detect if the literal syntax `[]` or `{}` is in the function position, which still seems worth doing, since "callable" collections are commonly used that way anyway. If you need to pass a callable collection to `map` or something, you can still use the `__getitem__` trick.

**Comment by algernon** [comment]
The keyword implementation is - as far as I remember - is a very ugly, slightly flaky hack. Might be worth extending to vector/map/etc literals, mind you. I'll have a try at remembering how the heck the keyword magic works, and see if it can be extended to other stuff too.

**Comment by kirbyfan64** [comment]
@gilch But I'm confused. What's the point of callable collections if they're literals? Is there a reason to do:

```hy
([1 2 3 4] 1)
```

instead of just:

```
1
```

?

**Comment by paultag** [comment]
Yeah, I want to avoid doing more of what we did with keywords -- basically,
I want to change it to be the (perhaps slower) method of using the object
and implementing `.__call__`.

Currently, stuff like `(map :foo ...)` won't work, and that kinda sucks.

On Wed, Oct 14, 2015 at 4:48 PM, Gergely Nagy <notifications@github.com>
wrote:

> The keyword implementation is - as far as I remember - is a very ugly,
> slightly flaky hack. Might be worth extending to vector/map/etc literals,
> mind you. I'll have a try at remembering how the heck the keyword magic
> works, and see if it can be extended to other stuff too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/963#issuecomment-148194139>.
>



-- 
:wq

**Comment by kirbyfan64** [comment]
Is there a reason standalone `:x` is compiled to have some weird Unicode character in front anyway? I crashed the Hy repl:

```
ryan@DevPC-LX:~/stuff/hy$ hy
hy 0.11.0 using CPython(default) 2.7.6 on Linux
=> (:f)
Traceback (most recent call last):
  File "/usr/local/bin/hy", line 9, in <module>
    load_entry_point('hy==0.11.0', 'console_scripts', 'hy')()
  File "/usr/local/lib/python2.7/dist-packages/hy-0.11.0-py2.7.egg/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/hy-0.11.0-py2.7.egg/hy/cmdline.py", line 342, in cmdline_handler
    return run_repl(spy=options.spy)
  File "/usr/local/lib/python2.7/dist-packages/hy-0.11.0-py2.7.egg/hy/cmdline.py", line 240, in run_repl
    os=platform.system()
  File "/usr/lib/python2.7/code.py", line 243, in interact
    more = self.push(line)
  File "/usr/lib/python2.7/code.py", line 265, in push
    more = self.runsource(source, self.filename)
  File "/usr/local/lib/python2.7/dist-packages/hy-0.11.0-py2.7.egg/hy/cmdline.py", line 113, in runsource
    sys.stderr.write(str(e))
  File "/usr/local/lib/python2.7/dist-packages/hy-0.11.0-py2.7.egg/hy/errors.py", line 104, in __str__
    self.message))
  File "build/bdist.linux-x86_64/egg/clint/textui/colored.py", line 108, in __radd__
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufdd0' in position 24: ordinal not in range(128)
ryan@DevPC-LX:~/stuff/hy$ 
```

**Comment by kirbyfan64** [comment]
(and I have no clue what keywords you guys are talking about...)

**Comment by paultag** [comment]
Yeah, :foo keywords

``
=> (:foo {:foo 1})
1
```

And no, I want to change that to be a Hy object. That comes from the old
days when I thought we could live without the .pyc depending on `hy` :)

On Wed, Oct 14, 2015 at 4:53 PM, Ryan Gonzalez <notifications@github.com>
wrote:

> (and I have no clue what keywords you guys are talking about...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hylang/hy/issues/963#issuecomment-148196735>.
>



-- 
:wq

**Comment by gilch** [comment]
> What's the point of callable collections if they're literals?

@kirbyfan64 just because the collection is a literal doesn't mean the argument to it has to be:
```Hy
;;  contrived example just to show how it works, I wouldn't actually use it this way.
 ({:January 1 :February 2 <etc.>} (get-current-month-name))
```
Easy inline lookup tables with minimal ceremony. In some circumstances this is a simpler alternative to `cond`.

Also note, only the fact that it's a collection literal must be known at compile time, not what's in it. Elements can be computed at run time:
```Hy
=> [(+ 2 3) (* 2 3)]
[(2 + 3), (2 * 3)]
[5, 6]
```

**Comment by gilch** [comment]
I think the tuple special form `(,)` should also support this. It could also be detected at compile time.

**Comment by paultag** [comment]
I remain -1 on compile time hacks :)

**Comment by kirbyfan64** [comment]
I *still* feel like it's an ugly effort (as @paultag said) for little gain. It only saves 4 bytes: `get `.

**Comment by kirbyfan64** [comment]
FWIW can this be closed now? I doubt this is ever really going to happen...

**Comment by Kodiologist** [comment]
Yeah, I don't like it, either. Let's close it.
