### ISSUE TITLE
Move xi to its own file

### ISSUE THREAD

**Issue by gilch** [hylang/hy#968]
Ref. #965

I wasn't sure where to put `xi` to begin with, but now I'm thinking about moving `xi` to its own file, so you could import it as `(require hy.contrib.xi)`. I'm not certain if it should count as anaphoric. If everybody likes it better where it is, that's fine, I can close this issue. Thoughts?

**Comment by Kodiologist** [comment]
It seems at home there to me. Namespace pollution isn't an issue now that we have selective macro import.

**Comment by Ealhad** [comment]
Seems anaphoric enough to me.

**Comment by Kodiologist** [comment]
Yeah, I think we can close this.
