### ISSUE TITLE
add option to hy2py that converts symbols to valid python identifiers

### ISSUE THREAD

**Issue by gilch** [hylang/hy#970]
Hy would be more useful if it could compile to Python, and not just ast, see #923.

`hy2py` can translate ast back into Python source. It's very useful as a debugging tool, but the result is not always executable. The main issue seems to be that Hy identifiers are a superset of valid Python identifiers. The ast doesn't care, but when importing Hy from Python we have a system to resolve this problem using Punycode and a few other rules (`-` to `_` etc.)

I'm proposing we add an option to `hy2py` that converts all invalid symbols using the same system. This way the Python code will be still be executable. I'm not sure if there are other problems with the output, but it's a step in the right direction.

This might also be more useful as the default for `hy --spy`.

**Comment by kirbyfan64** [comment]
I would argue against that being the default for `hy --spy`, since my own main goal of using that is to see *exactly* what Python code is generated.

This is a great idea; I've had it on my mind for a year or so. Do note that it's more complicated than it seems. You can't just mangle every name you see:

```
(defn $ [a b]) ; this can be mangled to whatever
(reduce + [1 2]) ; this would add an extra import from `hy.shadow`, and mindlessly mangling that will give an ImportError
(import x [$$]) ; same here
```

Basically, in particular, imports need extra attention.

**Comment by koji-kojiro** [comment]
I propose that use `foo = getattr(bar, "foo")` instead of  `from bar import foo`. 

The second case, `(reduce + [1 2]) ` becomes:
```python
import hy.core.shadow
+ = getattr(hy.core.shadow, "+") 
# equivelent to `from hy.core.shadow import +`

reduce(+, [1L, 2L])
# we can replace '+' with any valid identifier
```

**Comment by kirbyfan64** [comment]
Only problem is that that breaks any usage of `globals` and `locals`:

```python
(setv + 123)
(print (get (globals) "+"))  ; BOOM!!
```

Though I guess we already mangle `!` and `?`...

**Comment by koji-kojiro** [comment]
That might be solved as follows:
```python
globals().update({'+': 123})
+ = globals().get('+')
# equivalent to `+ = 123`
```
