### ISSUE TITLE
PyPy now handles reverse ASTs

### ISSUE THREAD

**Issue by kirbyfan64** [hylang/hy#977]
Basically, I tried removing the code in `hy/compiler.py` that sets the line and column numbers of all the AST nodes on PyPy to 1. And...guess what?

It works.

The tests pass for me. Even more interesting, the issue in #742 where lines go crazy doesn't happen, so PyPy actually works *better* with Hy than CPython! (This is leading me to believe that the line issue is a CPython bug!)

My idea is to figure out which version of PyPy it is that fixed this and not clear the position data on the newer versions. Thoughts?

**Comment by berkerpeksag** [comment]
I wouldn't bother to support multiple PyPy versions. If it's working on the latest PyPy, I'd say just drop the PyPy specific code.

**Comment by rcarmo** [comment]
+1 for going with the latest.
