### ISSUE TITLE
The new defclass removed the braces from the wrong place!

### ISSUE THREAD

**Issue by kirbyfan64** [hylang/hy#979]
Before, `defclass`'s syntax was:

```hy
(defclass X [Y] [
  [a 1]
  [b 2]])
```

So I could use macros like:

```hy
(defmacro defmethod [name &rest rest]
  `[~name (fn ~@rest)])

(defclass X [] [
  (defmethod --str-- [self] "123")])
```

HOWEVER, this no longer works. IMO, instead of removing the inner braces, the outer ones should have been removed, like:

```hy
(defclass X []
  [a 1]
  [b 2])
```

**Comment by gilch** [comment]
```Hy
(defmacro defmethod [name &rest rest]
  `(def ~name (fn ~@rest)))
```

**Comment by gilch** [comment]
In the new version you can just use `defn` directly in the class body, so there's no need for `defmethod`.

**Comment by gilch** [comment]
Using you example:
`hy --spy`
```Hy
=> (defclass X []
... (defn --str-- [self] "123"))
class X:

    def __str__(self):
        return '123'
```

**Comment by algernon** [comment]
Closing this, the solution provided by @gilch should be sufficient.
