### ISSUE TITLE
How can I do df.loc[df.sepal_length > 4.5] in hy?

### ISSUE THREAD

**Issue by endrebak** [hylang/hy#984]
See q at http://stackoverflow.com/questions/33656372/using-pandas-loc-in-hy

**Comment by kirbyfan64** [comment]
http://stackoverflow.com/a/33678354/2097780

**Comment by Foxboron** [comment]
For future notice i'd advice to use the mailinglist. It's better suited for these kinds of things the github issues.
https://groups.google.com/forum/#!forum/hylang-discuss

We should maybe promote it more?
