### ISSUE TITLE
Gitter chat for hy?

### ISSUE THREAD

**Issue by endrebak** [hylang/hy#985]
How about setting up a github gitter chat? See https://gitter.im

Much lower threshold for joining than irc, but gitter can be accessed with irc IIRC.

https://github.com/hylang/hy/issues/984 was my motivation for asking; I had nowhere appropriate to ask except IRC, which I have never used.

**Comment by paultag** [comment]
@endrebak I'm not opposed to it, but I've never used it, is there a way to tell it to use the hy channel on irc?

**Comment by endrebak** [comment]
https://irc.gitter.im/ claims that the IRC support is beta, so perhaps changing is not the best option (I cannot remember seeing that page when I asked.)

I know many projects use it successfully, like spacemacs: https://gitter.im/syl20bnr/spacemacs and I'm sure it lowers the bar for participation (whether that is a good thing depends on whether you are Linus Torvalds vs. for example Sylvain Benner.)

Best discussion of tradeoffs/benefits/IRC integration I have seen: https://github.com/w3c/modern-tooling/issues/16

Feel free to close btw. If someone else is interested, they'll surely reopen.

**Comment by kirbyfan64** [comment]
I like Gitter a lot. It's like IRC, but any messages you miss get emailed to you, and there's always a persistent log, which I find to be two major deficiencies of IRC (missing messages).

**Comment by agentultra** [comment]
I dislike special snowflake hosted communications services.

An irc bouncer like bitlbee is perfectly serviceable if you truly need to be always present.

Most of the time you don’t though… any important discussion should happen in ML or issue tracker, etc.

We can also host a bot to log our chat room…

**Comment by paultag** [comment]
OK. Well, perhaps we'll stick with IRC for now, and look at it again later - I don't super love nonfree communications systems (lawl I'm on github right now), and I flat out won't pay for a nonfree service (paid free: yeah, perhaps) -- we've got a full IRC room right now, so, perhaps we'll stick on IRC :)

Thanks for the suggestion, though!

**Comment by kirbyfan64** [comment]
@paultag 

> and I flat out won't pay for a nonfree service

FYI, Gitter is free for public GitHub organizations...

You can also do things like reference GitHub issues from within Gitter and use syntax highlighting.

**Comment by paultag** [comment]
@kirbyfan64 not at the number of people we have on IRC :)
